import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { aiBusinessCases, aiBusinessLessons, aiBusinessPath, aiBusinessResources } from "../src/aiBusinessContent.js";
import { buildAdoption, calculateEconomics, chooseApproach, designGovernance, designPilot, evaluateAgent, evaluateOpportunity, evaluateScale, selectPattern } from "../src/aiBusinessTools.js";
import { tools, topicGroups } from "../src/contentData.js";

test("publica hub, once módulos y un caso integrador",()=>{assert.equal(aiBusinessPath.title,"IA generativa para negocios");assert.equal(aiBusinessLessons.length,11);assert.equal(aiBusinessLessons.at(-1).slug,"caso-integrador");assert.ok(aiBusinessLessons.every((item)=>item.status==="published"&&item.sections.length>=2&&item.outcomes.length>=3));});
test("enseña marcos y decisiones críticas",()=>{const text=JSON.stringify(aiBusinessLessons);["VALORA","AUTORIZA","GUARDA","recuperación","ajuste fino","Configurar","Integrar","Construir","Diferir","costo total","Detener","Ajustar","Ampliar","Escalar","revisión humana"].forEach((term)=>assert.match(text,new RegExp(term,"i")));assert.doesNotMatch(text,/garantiza productividad|siempre reduce|reemplazar empleados/i);});
test("incluye casos y recursos originales completos",()=>{assert.equal(aiBusinessCases.length,18);assert.equal(new Set(aiBusinessCases.map((item)=>item.slug)).size,18);assert.ok(aiBusinessCases.every((item)=>item.fictional&&item.baseline&&item.risk&&item.humanRole&&item.metric&&item.stopCondition));assert.equal(aiBusinessResources.length,17);const ids=new Set(aiBusinessResources.map((item)=>item.id));assert.ok(aiBusinessLessons.every((item)=>item.relatedResources.every((id)=>ids.has(id))));});
test("Learn y nueve herramientas están publicados",()=>{const topic=topicGroups.flatMap((group)=>group.topics).find((item)=>item.slug==="ia-generativa-para-negocios");assert.equal(topic.status,"published");const slugs=["evaluar-oportunidad-ia","seleccionar-enfoque-ia","elegir-solucion-ia","evaluar-agente-negocio","calculadora-economia-ia","disenar-gobernanza-ia","disenar-piloto-ia","crear-plan-adopcion-ia","evaluar-escala-ia"];assert.ok(slugs.every((slug)=>tools.some((item)=>item.slug===slug&&item.status==="published")));});
test("oportunidad y patrón validan y son neutrales",()=>{assert.ok(evaluateOpportunity({}).errors.problem);const opportunity=evaluateOpportunity({problem:"demora",users:"equipo",baseline:"8 horas",metric:"tiempo",alternative:"simplificar",consequence:"baja",process:"manual",owner:"operaciones",data:"guías",stop:"no mejora"});assert.match(opportunity.output,/VALORA/);const pattern=selectPattern({task:"responder",input:"Solo texto",output:"borrador",sensitivity:"Baja",current:"Alta",consistency:"Alta",integration:"Media",evaluation:"Alta"});assert.match(pattern.output,/recuperación/i);assert.match(pattern.output,/No se recomienda un producto/i);});
test("selector puede diferir y agente limita autonomía",()=>{const approach=chooseApproach({useCase:"decisión",importance:"Alta",sensitivity:"Alta",customization:"Alta",integration:"Alta",capability:"Baja",time:"Alta",dependence:"Baja"});assert.match(approach.output,/Diferir/);const agent=evaluateAgent({goal:"reembolsar",users:"supervisor",data:"cuenta",tools:"pagos",actions:"emitir",financial:"Sí",external:"Sí",reversible:"No",approval:"No",logging:"No",stop:"incidente",impact:"Alto"});assert.match(agent.output,/No automatices la ejecución final/);assert.ok(agent.warnings.length);});
test("economía incluye escenarios y cautelas",()=>{const value=calculateEconomics({users:"10",frequency:"20",subscription:"0",usage:"500",development:"10000",integration:"5000",governance:"3000",training:"2000",support:"4000",timeSaved:"0.25",adoption:"60",hourValue:"20",errorReduction:"0",otherBenefit:"1000",horizon:"2"});["Conservador","Esperado","Optimista","No se convierte automáticamente","aproximaciones simples"].forEach((term)=>assert.match(value.output,new RegExp(term)));});
test("gobierno, piloto, adopción y escala son cautos",()=>{const governance=designGovernance({useCase:"borrador",users:"equipo",classification:"Confidencial",audience:"Externa",consequence:"Alta",review:"especialista",action:"Sí",logging:"eventos",retention:"30 días",incident:"detener",stakeholders:"clientes"});assert.match(governance.output,/GUARDA/);assert.match(governance.output,/No certifica cumplimiento/);const pilot=designPilot({problem:"demora",users:"5",baseline:"20 min",hypothesis:"reducir",scope:"un canal",exclusions:"pagos",solution:"borrador",data:"guías",oversight:"agente",businessMetric:"tiempo",qualityMetric:"correcciones",riskMetric:"incidentes",adoptionMetric:"uso",costMetric:"por salida",duration:"4 semanas",stop:"error grave",decision:"comparar"});assert.match(pilot.output,/BRIEF DE PILOTO/);assert.match(buildAdoption({change:"revisión",roles:"agentes",concerns:"carga",skills:"verificar",training:"casos",support:"clínica",incentives:"calidad",experiment:"dos semanas",signals:"uso pertinente",owner:"operaciones",review:"viernes"}).output,/PLAN DE ADOPCIÓN/);assert.match(evaluateScale({value:"No",quality:"Parcial",risk:"No",adoption:"Parcial",economics:"No",ownership:"Parcial",monitoring:"No",support:"Parcial",change:"No",exit:"Parcial",rollback:"No",gaps:"propiedad"}).output,/Detener o ajustar/);});
test("rutas, SEO, privacidad y accesibilidad están integrados",()=>{const app=readFileSync(new URL("../src/App.jsx",import.meta.url),"utf8");const sitemap=readFileSync(new URL("../public/sitemap.xml",import.meta.url),"utf8");const toolPage=readFileSync(new URL("../src/AIBusinessToolsPage.jsx",import.meta.url),"utf8");const pages=readFileSync(new URL("../src/AIBusinessPages.jsx",import.meta.url),"utf8");assert.match(app,/AIBusinessHubPage/);aiBusinessLessons.forEach((item)=>assert.match(sitemap,new RegExp(item.href)));assert.match(toolPage,/aria-live/);assert.match(toolPage,/aria-describedby/);assert.match(toolPage,/WebApplication/);assert.doesNotMatch(toolPage+readFileSync(new URL("../src/aiBusinessTools.js",import.meta.url),"utf8"),/fetch\(|XMLHttpRequest|localStorage|sessionStorage|sendBeacon/);assert.match(pages,/LearningResource/);assert.doesNotMatch(pages,/Microsoft 365|Azure|Copilot Studio|GitHub Copilot/);});

