import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{computationalLessons,computationalResources}from"../src/computationalContent.js";import{calculateInterval,compareOptimization,simulateMonteCarlo}from"../src/computationalTools.js";
test("publica ocho modulos y siete recursos",()=>{assert.equal(computationalLessons.length,8);assert.equal(computationalResources.length,7);assert.ok(computationalLessons.every(x=>x.status==="published"));});
test("cubre formulacion grafos estadistica validacion y metricas",()=>{const t=JSON.stringify(computationalLessons);["objetivo","restricciones","programación dinámica","grafo no ponderado","seudorrandom","error estándar","95%","Sobreajuste","fuga de datos","supervisado","Precisión","AUC"].forEach(x=>assert.match(t,new RegExp(x,"i")));});
test("optimizacion exacta dinamica y contraejemplo voraz",()=>{const r=compareOptimization({capacity:10,criterion:"value",items:[{label:"A",cost:6,value:12},{label:"B",cost:5,value:10},{label:"C",cost:5,value:10}]});assert.equal(r.exact.value,20);assert.equal(r.dynamic.value,20);assert.equal(r.greedy.value,12);assert.equal(r.heuristicMatched,false);});
test("optimizacion valida limites y desempata estable",()=>{assert.ok(compareOptimization({capacity:0,items:[]}).errors.capacity);const r=compareOptimization({capacity:4,items:[{label:"A",cost:2,value:3},{label:"B",cost:2,value:3},{label:"C",cost:4,value:6}]});assert.equal(r.exact.cost,4);assert.equal(r.exact.value,6);});
test("Monte Carlo es reproducible y acotado",()=>{const v={tasks:3,available:15,min:4,max:6,trials:1000,seed:42,mode:"uniform"},a=simulateMonteCarlo(v),b=simulateMonteCarlo(v),c=simulateMonteCarlo({...v,seed:43});assert.deepEqual(a,b);assert.notEqual(a.mean,c.mean);assert.ok(a.probability>=0&&a.probability<=1);assert.ok(simulateMonteCarlo({...v,trials:10}).errors.trials);});
test("intervalo calcula estadisticos muestrales con t",()=>{const r=calculateInterval({values:[1,2,3,4,5],confidence:95});assert.equal(r.n,5);assert.equal(r.mean,3);assert.equal(r.sd,1.5811);assert.equal(r.se,0.7071);assert.equal(r.t,2.776);assert.ok(r.lower<3&&r.upper>3);});
test("intervalo valida y advierte muestras pequenas",()=>{assert.ok(calculateInterval({values:"a 2",confidence:95}).errors.values);const r=calculateInterval({values:"2 3 4",confidence:90});assert.ok(r.warnings.some(x=>/pequeña/i.test(x)));});
test("rutas SEO privacidad y accesibilidad estan integrados",()=>{const app=readFileSync(new URL("../src/App.jsx",import.meta.url),"utf8"),site=readFileSync(new URL("../public/sitemap.xml",import.meta.url),"utf8"),page=readFileSync(new URL("../src/ComputationalPages.jsx",import.meta.url),"utf8"),tool=readFileSync(new URL("../src/ComputationalToolsPage.jsx",import.meta.url),"utf8"),logic=readFileSync(new URL("../src/computationalTools.js",import.meta.url),"utf8");assert.match(app,/ComputationalHubPage/);computationalLessons.forEach(x=>assert.match(site,new RegExp(x.href)));assert.match(page,/LearningResource/);assert.match(tool,/WebApplication/);assert.match(tool,/aria-live/);assert.match(tool,/role="alert"/);assert.doesNotMatch(tool+logic,/fetch\(|XMLHttpRequest|localStorage|sessionStorage|sendBeacon/);});
