import { useEffect, useMemo, useState } from "react";
import { Printer, RotateCcw, Sparkles } from "lucide-react";
import { trackEvent } from "./analytics";
import { buildAdaptabilityPlan, buildHabitPlan, buildJournalEntry, buildLearningIntention, buildReframe } from "./adaptabilityTools";
import { Breadcrumbs, CopyToClipboard, PageShell } from "./LearningComponents";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const configs = {
  intention: { title: "Constructor de intenciones de aprendizaje", description: "Convierte una capacidad por desarrollar en una intención, una primera práctica y preguntas de revisión.", path: "/herramientas/constructor-intenciones-aprendizaje", event: "learning_intention_generated", build: buildLearningIntention, fields: [["skill","Habilidad o capacidad *"],["situation","Situación concreta *"],["meaning","Por qué importa *"],["practice","Primera conducta de práctica *"],["frequency","Frecuencia"],["feedback","Fuente de feedback"],["review","Fecha de revisión"]] },
  reframe: { title: "Reencuadrar un desafío", description: "Aplica OPA para separar hechos, interpretación, acción, apoyo y límites.", path: "/herramientas/reencuadrar-desafio", event: "reframing_completed", build: buildReframe, fields: [["happened","¿Qué ocurrió? *"],["interpretation","¿Qué interpretaste? *"],["response","¿Qué sentiste o quisiste hacer?"],["facts","¿Qué hechos conoces? *"],["missing","¿Qué información falta?"],["influence","¿Qué puedes influir?"],["alternative","¿Qué interpretación alternativa existe?"],["next","¿Cuál es tu siguiente acción? *"],["boundary","¿Qué apoyo o límite necesitas?"]] },
  habit: { title: "Planificador de hábitos de aprendizaje", description: "Diseña una rutina pequeña con disparador, refuerzo, obstáculos y recuperación.", path: "/herramientas/planificador-habitos-aprendizaje", event: "habit_plan_generated", build: buildHabitPlan, fields: [["habit","Hábito a construir *"],["meaning","Por qué importa *"],["trigger","Disparador *"],["action","Acción más pequeña *"],["frequency","Frecuencia"],["reinforcement","Refuerzo inmediato"],["obstacle","Obstáculo probable"],["recovery","Plan de recuperación *"],["reduce","Hábito a reducir"],["review","Fecha de revisión"]] },
  plan: { title: "Plan de adaptabilidad de cuatro semanas", description: "Integra intención, práctica, feedback, ajuste, evidencia y límites en un ciclo personal.", path: "/herramientas/plan-adaptabilidad", event: "adaptability_plan_created", build: buildAdaptabilityPlan, fields: [["context","Contexto elegido *"],["challenge","Desafío concreto *"],["boundary","Límite que debes proteger"],["intention","Intención de aprendizaje *"],["support","Apoyo disponible *"],["practice","Subhabilidad o práctica *"],["feedback","Pregunta y fuente de feedback"],["alternative","Alternativa para probar"],["evidence","Evidencia de avance"],["maintain","Hábito a mantener"],["reduce","Hábito a reducir"]] },
  journal: { title: "Diario de aprendizaje", description: "Procesa una experiencia con hechos, explicación, consecuencia, aprendizaje y próximo experimento.", path: "/herramientas/diario-aprendizaje", event: "learning_journal_created", build: buildJournalEntry, fields: [["situation","Situación *"],["fact","Hecho observable *"],["interpretation","Interpretación inicial"],["action","Acción realizada *"],["result","Resultado o consecuencia *"],["feedback","Feedback recibido"],["lesson","Lección *"],["next","Próximo experimento *"]] },
};

export default function AdaptabilityToolsPage({ kind }) {
  const config = configs[kind];
  const initial = useMemo(() => Object.fromEntries(config.fields.map(([name]) => [name, ""])), [kind]);
  const [values, setValues] = useState(initial); const [result, setResult] = useState({ errors: {}, output: "" });
  const breadcrumbs = [{ label: "Inicio", href: "/" }, { label: "Herramientas", href: "/herramientas" }, { label: config.title, href: config.path }];
  const schema = useMemo(() => ({ "@context": "https://schema.org", "@graph": [{ "@type": "BreadcrumbList", itemListElement: breadcrumbSchema(breadcrumbs).itemListElement }, { "@type": "WebApplication", name: config.title, description: config.description, applicationCategory: "EducationalApplication", operatingSystem: "Web", url: `https://masanes.cl${config.path}` }] }), [kind]);
  usePageMetadata({ title: config.title, description: config.description, path: config.path, schema });
  useEffect(() => trackEvent("adaptability_tool_opened", { tool: kind }), [kind]);
  const reset = () => { setValues(initial); setResult({ errors: {}, output: "" }); };
  const submit = (event) => { event.preventDefault(); const next = config.build(values); setResult(next); if (next.output) trackEvent(config.event, { tool: kind }); };
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs} /><header className="page-hero"><div><p className="eyebrow">Herramienta local</p><h1>{config.title}</h1><p className="page-hero__lead">{config.description}</p><p>Evita información sensible. El contenido no se guarda, no se envía y desaparece al recargar.</p></div></header><section className="generator-layout"><form className="generator-form" noValidate onSubmit={submit}>{config.fields.map(([name, label]) => <label className="field" key={name} htmlFor={`adapt-${name}`}><span>{label}</span><textarea id={`adapt-${name}`} rows="3" value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name] ? `adapt-error-${name}` : undefined} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} />{result.errors[name] && <small className="field-error" id={`adapt-error-${name}`}>{result.errors[name]}</small>}</label>)}<div className="form-actions"><button className="button button--primary" type="submit"><Sparkles size={16} />Crear resultado</button><button className="button button--secondary" type="button" onClick={reset}><RotateCcw size={16} />Limpiar</button></div></form><aside className="generator-output" aria-live="polite"><h2>Resultado</h2>{result.output ? <><pre className="template-preview">{result.output}</pre><div className="form-actions"><CopyToClipboard text={result.output} label="Copiar resultado" onCopy={() => trackEvent("adaptability_resource_copied", { tool: kind })} /><button className="button button--secondary" type="button" onClick={() => { trackEvent("adaptability_resource_printed", { tool: kind }); window.print(); }}><Printer size={16} />Imprimir</button></div><p className="output-reminder">Revisa que el plan reconozca restricciones, límites y apoyo. No es un diagnóstico ni una recomendación médica.</p></> : <p>Completa los campos obligatorios para generar un resumen estructurado.</p>}</aside></section></main></PageShell>;
}
