const updatedAt = "2026-07-15";
const base = "/aprende/adaptabilidad-resiliencia";

export const adaptabilityScenarios = [
  { id: "feedback-ines", title: "Inés recibe feedback inesperado", person: "Inés", organization: "Estudio Nómada", situation: "Una revisión señala que su presentación fue precisa, pero difícil de seguir para el cliente.", question: "¿Qué parte es un hecho y qué interpretación podría aparecer?", action: "Pedir un ejemplo concreto y probar una apertura orientada a la decisión.", constraint: "El plazo de la siguiente presentación es corto; debe elegir un cambio pequeño." },
  { id: "jefatura-mateo", title: "Mateo lidera a antiguos pares", person: "Mateo", organization: "Logística Faro", situation: "Después de una promoción, evita conversaciones difíciles para no afectar relaciones previas.", question: "¿Qué necesita aprender antes de exigir desempeño inmediato?", action: "Acordar expectativas de rol y practicar una conversación con feedback estructurado.", constraint: "Las relaciones y la autoridad formal cambiaron al mismo tiempo." },
  { id: "software-samira", title: "Samira aprende una herramienta analítica", person: "Samira", organization: "Datos Cauce", situation: "Intenta dominar todo el software antes de aplicarlo y posterga un análisis útil.", question: "¿Cuál es la subhabilidad mínima que desbloquea el trabajo actual?", action: "Completar un ejercicio guiado y aplicarlo a una tabla pequeña.", constraint: "Necesita entregar un análisis básico esta semana." },
  { id: "alcance-diego", title: "Diego enfrenta un cambio de alcance", person: "Diego", organization: "Obras Litoral", situation: "El cliente agrega una región, pero mantiene fecha y presupuesto.", question: "¿Qué objetivo debe conservarse y qué debe renegociarse?", action: "Mostrar alternativas de alcance, impacto y riesgo antes de comprometer una nueva fecha.", constraint: "Adaptarse no significa aceptar una carga imposible." },
  { id: "propuesta-noelia", title: "La propuesta de Noelia es rechazada", person: "Noelia", organization: "Servicios Trama", situation: "Un comité no aprueba su propuesta y ella interpreta que perdió credibilidad.", question: "¿Qué evidencia existe sobre las razones del rechazo?", action: "Separar objeciones económicas, operativas y políticas y solicitar criterios de revisión.", constraint: "La decisión puede no revertirse, pero todavía puede generar aprendizaje." },
  { id: "industria-leon", title: "León entra a una industria nueva", person: "León", organization: "Salud Brújula", situation: "Conoce operaciones, pero no el vocabulario ni la regulación del sector.", question: "¿Qué conocimiento es transferible y qué brecha requiere apoyo experto?", action: "Crear un glosario de decisiones y validar supuestos con una especialista.", constraint: "No debe opinar sobre temas regulatorios que aún no comprende." },
  { id: "stakeholder-elena", title: "Elena trabaja con un stakeholder resistente", person: "Elena", organization: "Cooperativa Umbral", situation: "Un líder local rechaza un nuevo proceso porque aumentaría tareas de su equipo.", question: "¿La resistencia revela una barrera, un incentivo o un riesgo real?", action: "Mapear impacto operativo y diseñar un piloto que reduzca carga.", constraint: "La participación no elimina el desacuerdo ni la necesidad de decidir." },
  { id: "equipo-raul", title: "Raúl coordina un equipo distribuido", person: "Raúl", organization: "Red Boreal", situation: "Las reuniones remotas se alargan y las decisiones quedan implícitas.", question: "¿Qué parte necesita sincronía y qué puede documentarse?", action: "Probar agenda de decisiones, responsables y resumen asíncrono.", constraint: "Los husos horarios limitan reuniones adicionales." },
  { id: "carga-amalia", title: "Amalia equilibra aprendizaje y carga", person: "Amalia", organization: "Finanzas Prado", situation: "Quiere aprender visualización de datos, pero trabaja con cierres exigentes.", question: "¿Qué ritmo es sostenible durante este periodo?", action: "Reservar dos bloques breves y reducir el alcance a una técnica por semana.", constraint: "Descanso y obligaciones existentes también forman parte del plan." },
  { id: "piloto-omar", title: "El piloto de Omar no funciona", person: "Omar", organization: "Mercado Senda", situation: "Un nuevo onboarding no cambia activación y el equipo quiere abandonarlo todo.", question: "¿Falló la hipótesis, la ejecución, la medición o el segmento?", action: "Revisar fidelidad del test y elegir una sola hipótesis alternativa.", constraint: "No conviene prolongar un experimento sin valor solo para evitar reconocer el resultado." },
  { id: "ayuda-pilar", title: "Pilar pide ayuda antes del plazo", person: "Pilar", organization: "Energía Ronda", situation: "Detecta que una dependencia externa puede retrasar el entregable.", question: "¿Qué información necesita comunicar para pedir apoyo útil?", action: "Explicar riesgo, impacto, opciones y decisión requerida antes de la fecha límite.", constraint: "Pedir ayuda no transfiere automáticamente la responsabilidad." },
  { id: "ultima-hora-bruno", title: "Bruno cambia la preparación de última hora", person: "Bruno", organization: "Academia Delta", situation: "Estudia intensamente antes de cada evaluación, pero no retiene ni revisa errores.", question: "¿Qué disparador y acción pequeña podrían reemplazar ese ciclo?", action: "Después de cada clase, resolver una pregunta y registrar un error.", constraint: "El nuevo hábito debe caber en su horario real." },
];

const scenario = (...ids) => ids.map((id) => adaptabilityScenarios.find((item) => item.id === id));
const makeLesson = (order, slug, title, description, readingTime, outcomes, sections, relatedResources = [], relatedTools = []) => ({ order, slug, title, description, readingTime, outcomes, sections, relatedResources, relatedTools, href: `${base}/${slug}`, status: "published", level: "Introductorio", updatedAt });

export const adaptabilityLessons = [
  makeLesson(1, "que-es-adaptabilidad", "Qué significa adaptarse en el trabajo", "Distingue adaptación, resiliencia y aceptación pasiva para responder al cambio con aprendizaje, límites y apoyo.", "11 minutos", ["Diferenciar adaptabilidad y resiliencia", "Usar el modelo Aprender, Ajustar y Sostener", "Reconocer límites y necesidades de apoyo"], [
    { title: "Adaptarse no es aceptar pasivamente", paragraphs: ["Adaptabilidad es la capacidad de ajustar la manera de pensar y actuar cuando cambian el contexto, la información o las necesidades. Puede implicar aprender, preguntar, probar otro método, reducir alcance, buscar apoyo, repriorizar, negociar un plazo o abandonar un plan ineficaz.", "No exige cumplir toda demanda. Reconocer que una situación no es sostenible también puede ser una respuesta adaptativa."] },
    { title: "Adaptabilidad y resiliencia", comparison: { leftTitle: "Adaptabilidad", leftItems: ["ajustar el enfoque", "aprender del contexto", "cambiar una respuesta", "explorar alternativas", "actuar con nueva información"], rightTitle: "Resiliencia", rightItems: ["recuperar capacidad", "sostenerse durante la dificultad", "procesar una experiencia", "reconstruir estabilidad", "continuar o reorganizarse"] }, paragraphs: ["Una misma situación puede requerir las dos. Resiliencia no significa estar bien todo el tiempo; adaptabilidad no significa cambiar sin criterio."] },
    { title: "Aprendizaje intencional", paragraphs: ["Es el proceso de elegir deliberadamente qué quieres aprender, cómo practicarás y con qué evidencia revisarás el avance. Se superpone con la adaptación, pero no toda adaptación exige una nueva habilidad."] },
    { title: "Modelo práctico: Aprender, Ajustar y Sostener", framework: [{ title: "Aprender", text: "Adquirir información, habilidad o perspectiva." }, { title: "Ajustar", text: "Modificar plan, conducta o interpretación." }, { title: "Sostener", text: "Proteger energía, relaciones y funcionamiento en el tiempo." }], callout: { title: "Un modelo para esta guía", text: "Estas dimensiones organizan la reflexión; no pretenden ser universales ni diagnosticar una personalidad." } },
    { title: "Caso: Valentina coordina una región", caseStudy: { title: "Del control individual a la coordinación", paragraphs: ["Valentina asume un proyecto regional en una empresa ficticia de servicios técnicos. Conoce el contenido, pero tiene poca experiencia facilitando equipos. Intenta responder todo, oculta dudas, acumula tareas e interpreta desacuerdos como una amenaza.", "Define como aprendizaje conducir reuniones orientadas a decisiones, pide feedback sobre una sesión, distribuye responsables y prueba una agenda nueva. También limita reuniones fuera de horario y renegocia dos entregables. Los resultados del piloto, no una idea de perfección, orientan el siguiente ajuste."] } },
    { title: "Escenarios para aplicar el modelo", scenarios: scenario("jefatura-mateo", "alcance-diego") },
    { title: "Límites profesionales", callout: { title: "Adaptarse también puede ser poner un límite", text: "La adaptabilidad no consiste en aceptar cualquier condición ni en ignorar límites personales. También puede implicar pedir ayuda, renegociar expectativas, cambiar de enfoque o salir de una situación que no es sostenible." } },
  ], ["adaptability-assessment"]),

  makeLesson(2, "aprendizaje-intencional", "Cómo aprender con intención", "Convierte una necesidad de desarrollo en una intención significativa, observable y compatible con objetivos de desempeño.", "12 minutos", ["Separar aprendizaje y desempeño", "Redactar una intención significativa", "Definir práctica, feedback y evidencia"], [
    { title: "Aprender y rendir no son lo mismo", comparison: { leftTitle: "Intención de aprendizaje", leftItems: ["qué necesito comprender", "qué debo practicar", "qué incertidumbre reducir", "qué conducta mejorar"], rightTitle: "Objetivo de desempeño", rightItems: ["qué resultado alcanzar", "para cuándo", "con qué estándar", "bajo qué restricciones"] }, paragraphs: ["Ambos pueden coexistir. Cuando la capacidad todavía se desarrolla, medir solo el resultado puede ocultar el aprendizaje necesario."] },
    { title: "Cuatro contextos", examples: [{ title: "Nueva jefatura", text: "Aprender: conducir feedback que termine en acuerdos. Desempeño: completar evaluaciones antes del viernes." }, { title: "Analista", text: "Aprender: explicar un modelo a una audiencia no técnica. Desempeño: presentar una recomendación al comité." }, { title: "Búsqueda laboral", text: "Aprender: sintetizar en una entrevista de caso. Desempeño: completar tres entrevistas este mes." }, { title: "Emprendimiento", text: "Aprender: descubrir el problema más valioso del segmento. Desempeño: conseguir veinte clientes." }] },
    { title: "Conecta con una razón relevante", paragraphs: ["Puede resultar más fácil sostener el esfuerzo cuando se conecta con ayudar a un equipo, ganar autonomía, servir mejor, apoyar una meta familiar, cambiar de profesión, contribuir a una comunidad o reducir una fricción repetida. El significado no garantiza motivación ni elimina restricciones."] },
    { title: "Verbo + Capacidad + Contexto + Motivo", callout: { title: "Plantilla", text: "Quiero [explorar/practicar/comprender/desarrollar] [capacidad] en [situación concreta] porque [razón significativa]." }, example: { title: "Ejemplo", text: "Quiero practicar cómo estructurar conversaciones difíciles con mi equipo porque necesito abordar problemas antes de que escalen." } },
    { title: "Hazla accionable", paragraphs: ["Añade primer comportamiento, frecuencia, fuente de feedback, evidencia y fecha de revisión."], callout: { title: "Plan extendido", text: "Durante las próximas [periodo], practicaré [conducta] en [contexto]. Pediré feedback a [fuente] y revisaré mi avance usando [evidencia]." } },
    { title: "Clasifica diez objetivos", classification: [
      ["Comprender por qué falla el onboarding de clientes", "Intención de aprendizaje", "Busca reducir una incertidumbre."], ["Aumentar conversión en cinco puntos", "Objetivo de desempeño", "Define un resultado, no la capacidad."], ["Practicar recomendaciones de menos de dos minutos", "Intención de aprendizaje", "Define una conducta practicable."], ["Ser mejor líder", "Intención vaga", "Falta comportamiento y contexto."], ["Aprender tres formas de reducir conflicto en reuniones", "Intención de aprendizaje", "Define conocimiento aplicable."], ["Entregar el proyecto antes de fin de mes", "Objetivo de desempeño", "Prioriza resultado y fecha."], ["Aprender a delegar y reducir atrasos del equipo", "Objetivo mixto", "Combina capacidad y resultado."], ["Mejorar mi comunicación", "Intención vaga", "No especifica audiencia ni conducta."], ["Probar dos aperturas y elevar respuesta", "Objetivo mixto", "Incluye práctica y resultado."], ["Entender una función nueva antes de automatizarla", "Intención de aprendizaje", "Prioriza comprensión antes de ejecución."]
    ].map(([statement, answer, explanation]) => ({ statement, answer, explanation })) },
    { title: "Escenarios", scenarios: scenario("software-samira", "carga-amalia") },
    { title: "Construye tu intención", links: [{ label: "Abrir el constructor de intenciones", href: "/herramientas/constructor-intenciones-aprendizaje" }, { label: "Practicar síntesis en casos", href: "/aprende/consultoria/entrevistas-de-caso/practica-y-feedback" }] },
  ], ["learning-intention-worksheet"], ["learning-intention-builder"]),

  makeLesson(3, "reencuadrar-desafios", "Cómo responder con mayor flexibilidad ante un desafío", "Separa hechos e interpretaciones, crea una pausa útil y elige un ajuste sin negar restricciones reales.", "13 minutos", ["Aplicar OPA", "Distinguir hecho e interpretación", "Elegir una acción y un límite"], [
    { title: "OPA: Observar, Pausar, Ajustar", paragraphs: ["OPA es una herramienta práctica creada para esta ruta. No busca forzar optimismo: ayuda a reducir una reacción automática y ampliar las alternativas disponibles."], framework: [{ title: "Observar", text: "Qué ocurrió, qué interpreté y qué hechos conozco." }, { title: "Pausar", text: "Crear una distancia breve antes de responder." }, { title: "Ajustar", text: "Elegir interpretación, acción, apoyo o límite." }] },
    { title: "Observar", paragraphs: ["Pregunta qué pasó, qué interpretación apareció, qué sentiste o quisiste hacer, qué supuestos haces y qué hechos están confirmados."], comparison: { leftTitle: "Hecho", leftItems: ["La propuesta recibió tres objeciones"], rightTitle: "Interpretación", rightItems: ["No confían en mi capacidad"] } },
    { title: "Pausar", bullets: ["tomar una respiración lenta", "escribir la situación", "pedir unos minutos", "demorar un correo", "reformular lo escuchado", "solicitar claridad", "revisar carga y urgencia", "hablar con alguien de confianza", "nombrar la decisión"], paragraphs: ["Estas acciones no son tratamiento. Su utilidad depende del contexto y de la urgencia real."] },
    { title: "Ajustar", questionGroups: [{ title: "Influencia", items: ["¿Qué está bajo mi control?", "¿Qué está fuera?", "¿Qué información falta?"] }, { title: "Acción", items: ["¿Cuál es el paso útil más pequeño?", "¿Qué experimento reduce incertidumbre?", "¿Qué ayuda puedo pedir?"] }, { title: "Límite", items: ["¿Qué condición necesita renegociarse?", "¿Qué riesgo no es aceptable?", "¿Debo detenerme o salir?"] }] },
    { title: "Interpretaciones que pueden abrir opciones", examples: [{ title: "Debo saberlo todo", text: "Puedo investigar y hacer preguntas precisas." }, { title: "Un error prueba que no puedo", text: "Un error ofrece información sobre qué practicar." }, { title: "El plan debe mantenerse", text: "El objetivo puede seguir aunque cambie el camino." }, { title: "Todo depende de mí", text: "Puedo distribuir responsabilidad y coordinar apoyo." }] },
    { title: "Preguntas de reencuadre", questionGroups: [{ title: "Cuando falta experiencia", items: ["¿Qué parte específica no sé?", "¿Qué experiencia puedo transferir?", "¿Quién reduce esta brecha?"] }, { title: "Cuando cambia el plan", items: ["¿Qué objetivo sigue?", "¿Qué supuesto dejó de cumplirse?", "¿Qué decisión es reversible?"] }, { title: "Cuando hay pocos recursos", items: ["¿Qué es prioritario?", "¿Qué puede reducirse?", "¿Qué mínimo genera aprendizaje?"] }, { title: "Después de un error", items: ["¿Qué señal ignoré?", "¿Qué control añadiría?", "¿Qué debo comunicar?"] }] },
    { title: "Cuatro casos para aplicar OPA", scenarios: scenario("stakeholder-elena", "feedback-ines", "industria-leon", "piloto-omar") },
    { title: "Crea una reflexión estructurada", links: [{ label: "Abrir la herramienta OPA", href: "/herramientas/reencuadrar-desafio" }, { label: "Trabajar barreras de networking", href: "/aprende/networking/barreras" }] },
  ], ["opa-card", "facts-interpretations", "reframing-library"], ["challenge-reframer"]),

  makeLesson(4, "habitos-de-aprendizaje", "Cómo construir hábitos de aprendizaje sostenibles", "Diseña una rutina pequeña de preparación, práctica y procesamiento que pueda recuperarse después de una interrupción.", "14 minutos", ["Convertir una intención en rutina", "Planificar obstáculos y recuperación", "Reemplazar un hábito que interfiere"], [
    { title: "Motivación variable, decisiones repetibles", paragraphs: ["Los hábitos pueden reducir la necesidad de decidir de nuevo cada vez. El tiempo para consolidarlos varía según persona, conducta y contexto; no existe una duración universal."] },
    { title: "Preparar, Practicar y Procesar", framework: [{ title: "Preparar", text: "Define intención, reduce tarea, agenda, prepara materiales y anticipa obstáculos." }, { title: "Practicar", text: "Aplica una subhabilidad con dificultad manejable, criterios y feedback." }, { title: "Procesar", text: "Revisa patrones, supuestos, lecciones y próximo ajuste." }] },
    { title: "Empieza más pequeño", paragraphs: ["‘Aprender análisis de datos’ es demasiado amplio para una primera acción. Puedes completar un ejercicio, explicar un concepto, aplicarlo a un dataset, pedir feedback y revisar un error."] },
    { title: "Práctica deliberada", bullets: ["subhabilidad específica", "feedback", "criterio visible", "reto manejable", "repetición", "ajuste según errores"], paragraphs: ["Explicar una idea también puede revelar vacíos. Prueba comunicarla a un compañero, a un cliente y a un estudiante."] },
    { title: "Anticipa obstáculos", questionGroups: [{ title: "Capacidad", items: ["¿Sé cómo hacerlo?", "¿Qué instrucción falta?"] }, { title: "Motivación", items: ["¿Veo suficiente valor?", "¿La acción es demasiado grande?"] }, { title: "Contexto", items: ["¿Tengo tiempo, herramientas, acceso y apoyo?", "¿Qué restricción no puedo ignorar?"] }] },
    { title: "Disparador, Acción y Refuerzo", paragraphs: ["Usa un evento concreto como recordatorio, una conducta pequeña y un beneficio inmediato que facilite repetir. No es una ley universal, sino una manera simple de diseñar la rutina."], examples: [{ title: "Después de una reunión", text: "Registrar una lección y marcarla en el tracker." }, { title: "Antes de enviar", text: "Pedir feedback a una persona y guardar la mejora." }, { title: "Viernes", text: "Revisar un error y elegir la práctica siguiente." }] },
    { title: "Hábitos que pueden interferir", questionGroups: [{ title: "Antes", items: ["esperar hasta el final", "no definir habilidad", "sobrecargar agenda", "ignorar capacidad"] }, { title: "Durante", items: ["parecer competente en vez de experimentar", "solo practicar lo cómodo", "consumir sin aplicar", "multitarea", "evitar preguntas"] }, { title: "Después", items: ["no revisar errores", "rechazar feedback", "explicar todo por causas externas", "trabajar solo", "no extraer lecciones"] }] },
    { title: "Reemplaza sin castigarte", ordered: ["Identifica conducta", "Reconoce disparador", "Comprende recompensa inmediata", "Rediseña disparador", "Define reemplazo", "Hazlo más fácil", "Revisa sin autocastigo"] },
    { title: "Escenarios de hábito", scenarios: scenario("ultima-hora-bruno", "equipo-raul", "ayuda-pilar") },
    { title: "Diseña tu hábito", links: [{ label: "Abrir el planificador de hábitos", href: "/herramientas/planificador-habitos-aprendizaje" }, { label: "Revisar el plan de preparación de Consultoría", href: "/aprende/consultoria/plan-de-preparacion" }] },
  ], ["habit-planner", "habits-to-reduce"], ["habit-planner"]),

  makeLesson(5, "reflexion-y-feedback", "Cómo convertir la experiencia en aprendizaje", "Procesa una experiencia, solicita feedback observable y transforma una lección en un experimento siguiente.", "12 minutos", ["Aplicar HECA", "Pedir y recibir feedback útil", "Realizar una revisión periódica"], [
    { title: "La experiencia no aprende por sí sola", paragraphs: ["Repetir una situación no garantiza mejorar. Hace falta examinar qué ocurrió, qué supuesto guio la acción, qué resultado apareció, qué evidencia contradice la visión inicial y qué cambiarás."] },
    { title: "HECA: Hecho, Explicación, Consecuencia, Ajuste", paragraphs: ["HECA es un modelo práctico creado para esta guía."], framework: [{ title: "Hecho", text: "Qué ocurrió sin interpretación." }, { title: "Explicación", text: "Cómo explicas el resultado." }, { title: "Consecuencia", text: "Qué efecto produjo la acción." }, { title: "Ajuste", text: "Qué probarás o cambiarás." }] },
    { title: "Revisa explicaciones cómodas", paragraphs: ["A veces atribuimos el éxito completamente a nuestra acción, el fracaso solo al contexto, ignoramos feedback que afecta nuestra identidad o notamos evidencia que confirma lo que ya pensábamos. Son posibilidades para revisar, no diagnósticos."] },
    { title: "Pide feedback observable", bullets: ["¿Qué parte fue más clara?", "¿Dónde perdiste el hilo?", "¿Qué decisión expliqué insuficientemente?", "¿Qué debería mantener?", "¿Qué conducta debería cambiar?", "¿Qué evidencia observaste?"] },
    { title: "Recibe feedback con criterio", ordered: ["Escucha", "Pide un ejemplo", "Separa intención e impacto", "Evita defenderte inmediatamente", "Decide qué es útil", "Elige una conducta", "Haz seguimiento"], paragraphs: ["No todo feedback es preciso, respetuoso o apropiado. Considera evidencia, contexto, relación y límites."] },
    { title: "Entrega observación, impacto, pregunta y sugerencia", example: { title: "Ejemplo original", text: "En la revisión cambiaste de tema antes de cerrar dos decisiones. El equipo salió con responsables distintos. ¿Qué buscabas resolver? En la próxima sesión podrías confirmar decisión y responsable antes de avanzar." } },
    { title: "Revisión mensual de aprendizaje", questionGroups: [{ title: "Progreso", items: ["¿Qué generó avance?", "¿Qué debería continuar?"] }, { title: "Fricción", items: ["¿Qué creó fricción?", "¿Qué debería detener?"] }, { title: "Ajuste", items: ["¿Qué supuesto cambió?", "¿Qué experimento sigue?"] }] },
    { title: "Escenarios de feedback", scenarios: scenario("propuesta-noelia", "feedback-ines") },
    { title: "Registra una experiencia", links: [{ label: "Abrir el diario de aprendizaje", href: "/herramientas/diario-aprendizaje" }, { label: "Usar el tracker de casos", href: "/herramientas/seguimiento-practica-casos" }] },
  ], ["feedback-templates", "heca-worksheet"], ["learning-journal"]),

  makeLesson(6, "plan-personal", "Diseña tu plan personal de adaptabilidad", "Integra intención, reencuadre, hábitos, feedback y límites en un ciclo práctico de cuatro semanas.", "11 minutos", ["Elegir un contexto", "Construir un plan de cuatro semanas", "Definir evidencia, apoyo y límites"], [
    { title: "Diagnostica sin etiquetarte", bullets: ["intenciones", "respuesta a incertidumbre", "solicitud de ayuda", "feedback", "reflexión", "consistencia", "energía y límites", "experimentación", "cambio de plan", "recuperación"] },
    { title: "Elige un contexto", bullets: ["rol o equipo nuevo", "transformación digital", "cambio de carrera", "entrevistas", "software nuevo", "liderazgo", "programa académico", "emprendimiento", "reestructuración"] },
    { title: "Cuatro semanas", timeline: [{ time: "Semana 1", text: "Clarifica desafío, hechos, intención y apoyo." }, { time: "Semana 2", text: "Practica una subhabilidad, pide feedback y registra fricción." }, { time: "Semana 3", text: "Aplica OPA, prueba alternativa y revisa carga y límites." }, { time: "Semana 4", text: "Revisa evidencia, consolida un hábito y define el ciclo siguiente." }] },
    { title: "Caso integrador: Andrés cambia de función", caseStudy: { title: "Una transición con restricciones reales", paragraphs: ["Andrés pasa de operaciones a un equipo ficticio de transformación digital. Encuentra vocabulario nuevo, responsabilidades ambiguas, colegas remotos y expectativas incompatibles. Su primera presentación no conduce a una decisión.", "El ejercicio consiste en redactar una intención, aplicar OPA, elegir un hábito, solicitar feedback, completar HECA y construir cuatro semanas de práctica."] } },
    { title: "Respuesta modelo", modelAnswers: [{ title: "Una ruta posible", text: "Intención: practicar síntesis de decisiones en reuniones remotas porque necesita reducir ambigüedad. OPA: observa que la presentación terminó sin decisión; pausa y pide dos ejemplos; ajusta con un resumen previo. Hábito: antes de cada reunión escribe decisión, evidencia y pregunta. HECA: separa el hecho de la idea ‘no pertenezco’. Durante cuatro semanas prueba, pide feedback, revisa carga y conserva solo la conducta que muestre evidencia útil." }] },
    { title: "Crea tu plan", links: [{ label: "Crear mi plan de cuatro semanas", href: "/herramientas/plan-adaptabilidad" }, { label: "Explorar coaching profesional", href: "/#services" }] },
  ], ["four-week-plan", "team-discussion-guide"], ["adaptability-planner"]),
];

export const adaptabilityPath = { title: "Adaptabilidad y resiliencia", description: "Desarrolla una forma más consciente de aprender, responder al cambio y construir hábitos que te ayuden a avanzar en contextos inciertos.", audience: "Estudiantes, profesionales, líderes, emprendedores y equipos que enfrentan cambios o nuevas responsabilidades", readingTime: "Aproximadamente 73 minutos", level: "Introductorio", updatedAt, status: "published", format: "Ruta práctica", lessons: adaptabilityLessons, outcomes: ["Distinguir aprendizaje y desempeño", "Crear una intención significativa", "Aplicar OPA sin negar restricciones", "Diseñar hábitos sostenibles", "Usar HECA y feedback", "Construir un plan de cuatro semanas"] };
export const getAdaptabilityLesson = (slug) => adaptabilityLessons.find((item) => item.slug === slug);

export const adaptabilityResources = [
  { id: "adaptability-assessment", title: "Autodiagnóstico de adaptabilidad", contentType: "diagnostic", status: "published", description: "Identifica qué dimensión conviene observar en tu próxima situación de cambio.", reminder: "El resultado es descriptivo; no es un perfil psicológico ni un diagnóstico.", question: "Cuando enfrentas un cambio, ¿qué dimensión necesita más evidencia?", options: [{ label: "Claridad", action: "Separa hechos, decisión, alcance e información pendiente." }, { label: "Experimentación", action: "Convierte una incertidumbre en una prueba pequeña y reversible." }, { label: "Apoyo", action: "Identifica a quién pedir contexto, feedback o una decisión." }, { label: "Reflexión", action: "Reserva diez minutos después de una experiencia para completar HECA." }, { label: "Sostenibilidad", action: "Revisa carga, energía, límites y una expectativa que debas renegociar." }] },
  { id: "learning-intention-worksheet", title: "Hoja de intención de aprendizaje", contentType: "worksheet", status: "published", description: "Conecta capacidad, contexto, sentido y evidencia.", reminder: "La información es temporal y no se envía.", fields: ["Capacidad", "Contexto", "Motivo", "Primera práctica", "Feedback", "Evidencia", "Fecha de revisión"] },
  { id: "opa-card", title: "Tarjeta OPA", contentType: "template", status: "published", description: "Una pausa breve para separar reacción y decisión.", reminder: "OPA es una herramienta de reflexión profesional, no una intervención clínica.", template: "OBSERVAR\n¿Qué ocurrió? ¿Qué interpreté? ¿Qué hechos conozco?\n\nPAUSAR\n¿Qué acción breve puede crear distancia sin ignorar urgencia?\n\nAJUSTAR\n¿Qué alternativa, acción, apoyo o límite resulta útil ahora?" },
  { id: "facts-interpretations", title: "Hechos e interpretaciones", contentType: "worksheet", status: "published", description: "Separa lo observado de la explicación inicial.", reminder: "Una interpretación alternativa tampoco se convierte automáticamente en hecho.", fields: ["Hechos observables", "Interpretación inicial", "Supuestos", "Información faltante", "Interpretación alternativa", "Acción"] },
  { id: "reframing-library", title: "Preguntas para ampliar alternativas", contentType: "template", status: "published", description: "Preguntas organizadas por tipo de desafío.", reminder: "No uses reencuadre para minimizar riesgos o condiciones dañinas.", template: "INCERTIDUMBRE: ¿Qué información reduciría la duda?\nERROR: ¿Qué señal o control cambiaría?\nFEEDBACK: ¿Qué ejemplo observable puedo pedir?\nCARGA: ¿Qué debe reducirse o renegociarse?\nCONFLICTO: ¿Qué objetivo compartimos?\nAPRENDIZAJE: ¿Qué subhabilidad practicar primero?\nCAMBIO DE PLAN: ¿Qué objetivo sigue vigente?\nRECURSOS: ¿Qué mínimo genera valor o aprendizaje?" },
  { id: "habit-planner", title: "Hoja para diseñar un hábito", contentType: "worksheet", status: "published", description: "Planifica disparador, acción, refuerzo y recuperación.", reminder: "No existe un plazo universal para consolidar hábitos.", fields: ["Disparador", "Acción mínima", "Refuerzo", "Obstáculo probable", "Señal temprana", "Prevención", "Recuperación", "Revisión"] },
  { id: "habits-to-reduce", title: "Checklist de hábitos que interfieren", contentType: "checklist", status: "published", description: "Elige una conducta para reducir o reemplazar.", reminder: "Trabaja una conducta observable, no una etiqueta personal.", groups: [{ title: "Antes", items: ["Esperar hasta la urgencia", "Empezar sin definir habilidad", "Sobrecargar la agenda", "Ignorar capacidad"] }, { title: "Durante", items: ["Consumir sin aplicar", "Practicar solo lo cómodo", "Evitar preguntas", "Hacer multitarea"] }, { title: "Después", items: ["No revisar errores", "Rechazar feedback de inmediato", "No extraer una lección", "Trabajar solo sin necesidad"] }] },
  { id: "feedback-templates", title: "Plantillas para pedir feedback", contentType: "template", status: "published", description: "Solicitudes específicas para distintas relaciones.", reminder: "Adapta la pregunta a la responsabilidad y al contexto de la persona.", template: "JEFATURA: ¿Qué conducta debería mantener y cuál cambiar en la próxima entrega?\nPAR: ¿Dónde perdiste el hilo y qué ejemplo lo haría más claro?\nCLIENTE: ¿Qué decisión quedó insuficientemente explicada?\nDOCENTE: ¿Qué criterio todavía no estoy demostrando?\nEQUIPO: ¿Qué hice que facilitó o dificultó la participación?\nCOMPAÑERO DE PRÁCTICA: ¿Qué error dominante debería entrenar primero?" },
  { id: "heca-worksheet", title: "Hoja HECA", contentType: "worksheet", status: "published", description: "Convierte una experiencia en un ajuste comprobable.", reminder: "HECA no determina una causa; ayuda a examinar explicaciones.", fields: ["Hecho", "Explicación", "Consecuencia", "Evidencia que contradice", "Ajuste", "Próximo experimento"] },
  { id: "four-week-plan", title: "Plan de adaptabilidad de cuatro semanas", contentType: "tool", status: "published", description: "Construye un ciclo con intención, práctica, ajuste y consolidación.", reminder: "La herramienta funciona localmente y no almacena el plan.", href: "/herramientas/plan-adaptabilidad" },
  { id: "team-discussion-guide", title: "Guía de conversación para equipos", contentType: "template", status: "published", description: "Preguntas para coordinar aprendizaje, estabilidad y límites.", reminder: "Es una conversación de trabajo; no sustituye apoyo profesional de salud.", template: "¿Qué cambió?\n¿Qué necesita aprender el equipo?\n¿Qué supuestos dejaron de sostenerse?\n¿Qué debería permanecer estable?\n¿Qué experimento pequeño podemos ejecutar?\n¿Qué apoyo falta?\n¿Qué límite de carga necesitamos?\n¿Qué revisaremos la próxima semana?" },
];

export const getAdaptabilityResource = (id) => adaptabilityResources.find((item) => item.id === id);
