import { useEffect, useMemo } from "react";
import { ArrowRight, BookOpen, Clock, Gauge, Layers3, ShieldCheck, Target } from "lucide-react";
import { trackEvent } from "./analytics";
import { aiBusinessCases, aiBusinessLessons, aiBusinessPath, aiBusinessResources, getAIBusinessLesson, getAIBusinessResource } from "./aiBusinessContent";
import { Breadcrumbs, LessonContent, LessonMetadata, LessonNavigation, PageShell, RelatedContent, StatusBadge, WorksheetResource } from "./LearningComponents";
import { NotFoundPage } from "./LearningPages";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const base = "/aprende/ia-generativa-para-negocios";
const toolLinks = {
  "evaluar-oportunidad-ia": {title:"Evaluar una oportunidad",href:"/herramientas/evaluar-oportunidad-ia"},
  "seleccionar-enfoque-ia": {title:"Seleccionar un patrón",href:"/herramientas/seleccionar-enfoque-ia"},
  "elegir-solucion-ia": {title:"Elegir un enfoque",href:"/herramientas/elegir-solucion-ia"},
  "evaluar-agente-negocio": {title:"Evaluar un agente",href:"/herramientas/evaluar-agente-negocio"},
  "calculadora-economia-ia": {title:"Calcular economía",href:"/herramientas/calculadora-economia-ia"},
  "disenar-gobernanza-ia": {title:"Diseñar gobernanza",href:"/herramientas/disenar-gobernanza-ia"},
  "disenar-piloto-ia": {title:"Diseñar un piloto",href:"/herramientas/disenar-piloto-ia"},
  "crear-plan-adopcion-ia": {title:"Crear un plan de adopción",href:"/herramientas/crear-plan-adopcion-ia"},
  "evaluar-escala-ia": {title:"Evaluar preparación para escalar",href:"/herramientas/evaluar-escala-ia"},
};
const graphNode = ({"@context": _context, ...node}) => node;

function ScopeNotice() { return <aside className="lesson-callout safety-notice"><h2><ShieldCheck size={20}/> Alcance responsable</h2><p>Este contenido ayuda a estructurar decisiones, no certifica cumplimiento ni sustituye evaluación técnica, financiera, legal, laboral, de privacidad o seguridad. No todas las tareas son adecuadas para IA y los resultados deben verificarse.</p></aside>; }

export function AIBusinessHubPage() {
  const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"IA generativa para negocios",href:base}];
  const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:aiBusinessPath.title,description:aiBusinessPath.description,url:`https://masanes.cl${base}`,learningResourceType:"Ruta de aprendizaje",educationalLevel:aiBusinessPath.level,dateModified:aiBusinessPath.updatedAt,inLanguage:"es"}]}),[]);
  usePageMetadata({title:"IA generativa para negocios",description:aiBusinessPath.description,path:base,schema});
  useEffect(()=>{trackEvent("ai_business_hub_viewed");if(window.location.hash)requestAnimationFrame(()=>document.querySelector(window.location.hash)?.scrollIntoView());},[]);
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--networking"><div><p className="eyebrow">Ruta de aprendizaje</p><h1>IA generativa para negocios</h1><p className="page-hero__lead">{aiBusinessPath.description}</p><p>La IA generativa no es una estrategia. Una iniciativa útil comienza con un problema relevante, resultados medibles y una línea base. La tecnología viene después; el costo incluye operación y gobierno; y el piloto debe producir evidencia, no solo una demostración atractiva.</p><div className="hero-actions"><a className="button button--primary" href={aiBusinessLessons[0].href}>Comenzar la ruta <ArrowRight size={17}/></a><a className="button button--secondary" href="/herramientas/evaluar-oportunidad-ia">Evaluar un caso de uso</a><a className="button button--secondary" href="/herramientas/disenar-piloto-ia">Diseñar un piloto</a></div></div><aside className="summary-panel"><StatusBadge status="published"/><dl><div><dt><Target size={18}/>Dirigido a</dt><dd>{aiBusinessPath.audience}</dd></div><div><dt><BookOpen size={18}/>Tipo</dt><dd>{aiBusinessPath.format}</dd></div><div><dt><Clock size={18}/>Tiempo</dt><dd>{aiBusinessPath.readingTime}</dd></div><div><dt><Gauge size={18}/>Nivel</dt><dd>{aiBusinessPath.level}</dd></div><div><dt><Layers3 size={18}/>Módulos</dt><dd>11 módulos</dd></div></dl></aside></header><ScopeNotice/>
  <section className="guide-intro"><div><p className="eyebrow">Definición de trabajo</p><h2>Adoptar es construir capacidad para decidir y operar</h2><p>En esta ruta, la adopción organizacional de IA generativa es el proceso de seleccionar problemas adecuados, diseñar soluciones, medir resultados y gestionar los riesgos y capacidades necesarios para operar la tecnología de forma responsable. Es una definición práctica, no universal.</p></div><ul>{aiBusinessPath.outcomes.map((item)=><li key={item}>{item}</li>)}</ul></section>
  <section className="content-section content-section--soft" aria-labelledby="ai-lessons"><div className="section-title"><p className="eyebrow">Once módulos</p><h2 id="ai-lessons">Del problema a una operación responsable</h2><p>Puedes recorrerlos en orden o entrar por la decisión que necesitas preparar.</p></div><div className="case-chapter-grid">{aiBusinessLessons.map((item)=><a className="content-card content-card--link" href={item.href} key={item.slug}><span className="resource-type">Módulo {item.order}</span><h3>{item.title}</h3><p>{item.description}</p><span className="card-link">Abrir módulo <ArrowRight size={16}/></span></a>)}</div></section>
  <section className="content-section" aria-labelledby="ai-tools"><div className="section-title"><p className="eyebrow">Decisiones asistidas</p><h2 id="ai-tools">Herramientas locales y deterministas</h2><p>No usan una API de IA, no guardan entradas y no envían texto, nombres ni cifras a analítica.</p></div><div className="case-tool-links">{Object.values(toolLinks).map((tool)=><a href={tool.href} key={tool.href}>{tool.title}<ArrowRight size={16}/></a>)}</div></section>
  <section className="content-section content-section--soft"><div className="section-title"><p className="eyebrow">Ruta avanzada relacionada</p><h2>Sistemas de IA confiables</h2><p>Profundiza en especificaciones de prompts, fuentes, RAG, datos, seguridad, evaluación y operación técnica.</p></div><a className="button button--secondary" href="/aprende/sistemas-ia-confiables">Explorar sistemas de IA confiables <ArrowRight size={16}/></a></section>
  <section className="content-section"><div className="section-title"><p className="eyebrow">Escala organizacional</p><h2>Preparación organizacional para la IA</h2><p>Coordina estrategia, portafolio, capacidades compartidas, gobierno y una hoja de ruta entre varias iniciativas.</p></div><a className="button button--secondary" href="/aprende/preparacion-organizacional-para-ia">Explorar preparación organizacional <ArrowRight size={16}/></a></section>
  <section className="content-section content-section--soft" id="casos-ia" aria-labelledby="ai-cases"><div className="section-title"><p className="eyebrow">Biblioteca de práctica</p><h2 id="ai-cases">Dieciocho casos ficticios</h2><p>Las cifras y organizaciones son ficticias. Cada caso obliga a definir evidencia, riesgo, propiedad y una condición para detenerse.</p></div><div className="scenario-grid">{aiBusinessCases.map((item)=><article id={`caso-${item.slug}`} key={item.slug}><p className="resource-type">Caso ficticio · {item.category}</p><h3>{item.title}</h3><p><strong>Línea base:</strong> {item.baseline}.</p><p><strong>Uso propuesto:</strong> {item.proposedUse}.</p><details onToggle={(event)=>event.currentTarget.open&&trackEvent("ai_case_started",{category:item.category})}><summary>Revisar decisión</summary><p><strong>Valor:</strong> {item.expectedValue}</p><p><strong>Riesgo:</strong> {item.risk}.</p><p><strong>Rol humano:</strong> {item.humanRole}.</p><p><strong>Métrica:</strong> {item.metric}.</p><p><strong>Detener si:</strong> {item.stopCondition}.</p></details></article>)}</div></section>
  <section className="content-section" id="recursos" aria-labelledby="ai-resources"><div className="section-title"><p className="eyebrow">Recursos imprimibles</p><h2 id="ai-resources">Diecisiete plantillas para preparar decisiones</h2><p>Escribe solo información no confidencial. Los campos desaparecen al recargar la página.</p></div><div className="resource-grid">{aiBusinessResources.map((resource)=><article className="resource-card" id={`recurso-${resource.id}`} key={resource.id}><span className="resource-type">{resource.type}</span><h3>{resource.title}</h3><p>{resource.description}</p><details><summary>Completar recurso</summary><WorksheetResource title={resource.title} fields={resource.fields}/></details></article>)}</div></section>
  <aside className="contextual-cta"><div><h2>¿Estás evaluando una iniciativa de inteligencia artificial?</h2><p>Puedo ayudarte a definir el problema, estructurar el caso de negocio y diseñar un piloto con métricas, riesgos y responsabilidades claras.</p></div><a className="button button--primary" href="/#services" onClick={()=>trackEvent("ai_consulting_cta_clicked",{destination:"services"})}>Conocer los servicios de consultoría</a></aside></main></PageShell>;
}

export function AIBusinessLessonPage({ slug }) { const item=getAIBusinessLesson(slug); return item?<AIBusinessLessonContent item={item}/>:<NotFoundPage/>; }
function AIBusinessLessonContent({item}) {
  const index=aiBusinessLessons.indexOf(item); const resources=item.relatedResources.map(getAIBusinessResource).filter(Boolean); const tools=item.relatedTools.map((slug)=>toolLinks[slug]).filter(Boolean);
  const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"IA generativa para negocios",href:base},{label:item.title,href:item.href}];
  const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:item.title,description:item.description,url:`https://masanes.cl${item.href}`,learningResourceType:"Lección",educationalLevel:item.level,dateModified:item.updatedAt,inLanguage:"es",isPartOf:{"@type":"LearningResource",name:aiBusinessPath.title,url:`https://masanes.cl${base}`}}]}),[item.slug]);
  usePageMetadata({title:item.title,description:item.description,path:item.href,schema}); useEffect(()=>trackEvent("ai_business_lesson_opened",{module:item.slug}),[item.slug]);
  return <PageShell><main id="main-content" className="content-page lesson-page"><Breadcrumbs items={breadcrumbs}/><article><header className="lesson-header"><div><p className="eyebrow">Módulo {item.order} de 11</p><h1>{item.title}</h1><p>{item.description}</p></div><StatusBadge status="published"/></header><ScopeNotice/><LessonMetadata module={item} total={11}/><aside className="lesson-outcomes"><h2>Al terminar podrás</h2><ul>{item.outcomes.map((outcome)=><li key={outcome}>{outcome}</li>)}</ul></aside><LessonContent content={item}/><RelatedContent resources={resources} tools={tools} basePath={base}/><div className="lesson-hub-link"><a className="button button--secondary" href={base}>Volver a IA generativa para negocios</a></div><LessonNavigation previous={aiBusinessLessons[index-1]} next={aiBusinessLessons[index+1]}/></article></main></PageShell>;
}
