import { useEffect, useMemo, useState } from "react";
import { Printer, RotateCcw, Sparkles } from "lucide-react";
import { trackEvent } from "./analytics";
import { Breadcrumbs, CopyToClipboard, PageShell } from "./LearningComponents";
import { breadcrumbSchema, usePageMetadata } from "./seo";
import { buildAdoption, calculateEconomics, chooseApproach, designGovernance, designPilot, evaluateAgent, evaluateOpportunity, evaluateScale, selectPattern } from "./aiBusinessTools";

const configs = {
  opportunity: { title: "Evaluador de oportunidad de IA", description: "Ordena una oportunidad con VALORA antes de seleccionar tecnología.", path: "/herramientas/evaluar-oportunidad-ia", event: "ai_opportunity_evaluated", build: evaluateOpportunity, fields: [["problem","Problema de negocio *"],["users","Personas afectadas *"],["process","Proceso actual"],["baseline","Línea base medible *"],["metric","Resultado que podría mejorar *"],["alternative","Alternativa sin IA *"],["data","Datos o fuentes disponibles"],["consequence","Consecuencia de un error *"],["owner","Responsable operativo"],["stop","Condición de parada"]] },
  pattern: { title: "Selector de patrón de solución de IA", description: "Compara modalidad, recuperación e integración sin recomendar proveedores.", path: "/herramientas/seleccionar-enfoque-ia", event: "ai_solution_pattern_selected", build: selectPattern, fields: [["task","Tarea *"],["input","Tipo de entrada *","input"],["output","Salida esperada *"],["sensitivity","Sensibilidad de datos *","level"],["current","Necesidad de información vigente *","level"],["consistency","Consistencia requerida *","level"],["latency","Latencia"],["volume","Volumen"],["customization","Personalización"],["integration","Integración *","level"],["evaluation","Capacidad de evaluación *","level"]] },
  approach: { title: "Selector de enfoque para una solución de IA", description: "Orienta entre configurar, integrar, construir o diferir.", path: "/herramientas/elegir-solucion-ia", event: "ai_approach_selected", build: chooseApproach, fields: [["useCase","Caso de uso *"],["importance","Importancia estratégica *","level"],["platform","Plataforma aprobada existente"],["sensitivity","Sensibilidad *","level"],["customization","Personalización *","level"],["integration","Integración *","level"],["time","Urgencia *","level"],["capability","Capacidad interna *","level"],["budget","Perfil presupuestario"],["dependence","Tolerancia a dependencia *","level"]] },
  agent: { title: "Evaluador de agentes para negocios", description: "Revisa permisos y salvaguardas con AUTORIZA.", path: "/herramientas/evaluar-agente-negocio", event: "ai_agent_reviewed", build: evaluateAgent, fields: [["goal","Objetivo *"],["users","Responsable del resultado *"],["data","Datos accesibles *"],["tools","Herramientas conectadas *"],["actions","Acciones permitidas *"],["financial","Autoridad financiera *","yesno"],["external","Comunicación externa *","yesno"],["reversible","¿Las acciones son reversibles? *","yesno"],["approval","¿Existe aprobación humana? *","yesno"],["logging","¿Existe registro? *","yesno"],["stop","Condición de interrupción *"],["impact","Impacto de una falla *","impact"]] },
  economics: { title: "Calculadora de economía de IA", description: "Compara costo total y beneficios bajo tres escenarios.", path: "/herramientas/calculadora-economia-ia", event: "ai_economics_calculated", build: calculateEconomics, numeric: true, fields: [["users","Personas usuarias *"],["frequency","Usos mensuales por persona *"],["subscription","Suscripción mensual por persona"],["usage","Consumo mensual estimado"],["development","Desarrollo inicial *"],["integration","Integración inicial *"],["governance","Gobierno anual *"],["training","Formación inicial *"],["support","Soporte anual *"],["timeSaved","Horas liberadas por uso *"],["adoption","Adopción esperada, 0 a 100 *"],["hourValue","Valor por hora *"],["errorReduction","Valor anual de menor error"],["otherBenefit","Otro beneficio anual"],["horizon","Horizonte en años *"]] },
  governance: { title: "Planificador de gobernanza de IA", description: "Organiza responsabilidades y controles con GUARDA sin certificar cumplimiento.", path: "/herramientas/disenar-gobernanza-ia", event: "ai_governance_plan_generated", build: designGovernance, fields: [["useCase","Caso de uso *"],["users","Personas usuarias *"],["classification","Clasificación de datos *","classification"],["audience","Audiencia de la salida *","audience"],["consequence","Consecuencia del error *","consequence"],["review","Revisión humana *"],["action","¿Ejecuta una acción externa? *","yesno"],["vendor","Categoría de proveedor"],["logging","Registros disponibles *"],["retention","Retención y borrado *"],["incident","Proceso de incidentes *"],["stakeholders","Personas afectadas *"]] },
  pilot: { title: "Diseñador de pilotos de IA", description: "Crea un experimento limitado con métricas y condiciones de parada.", path: "/herramientas/disenar-piloto-ia", event: "ai_pilot_designed", build: designPilot, fields: [["problem","Problema *"],["users","Grupo de usuarios *"],["baseline","Línea base *"],["hypothesis","Hipótesis de valor *"],["scope","Alcance *"],["exclusions","Exclusiones *"],["solution","Solución candidata *"],["data","Datos *"],["oversight","Revisión humana *"],["businessMetric","Métrica de negocio *"],["qualityMetric","Métrica de calidad *"],["riskMetric","Métrica de riesgo *"],["adoptionMetric","Métrica de adopción *"],["costMetric","Métrica de costo *"],["duration","Duración *"],["stop","Condiciones de parada *"],["decision","Regla de decisión final *"]] },
  adoption: { title: "Constructor de plan de adopción de IA", description: "Alinea cambios de trabajo, capacidades, soporte y aprendizaje.", path: "/herramientas/crear-plan-adopcion-ia", event: "ai_adoption_plan_generated", build: buildAdoption, fields: [["change","Cambio en el trabajo *"],["roles","Roles afectados *"],["concerns","Preocupaciones *"],["skills","Habilidades necesarias *"],["training","Formación en tareas reales *"],["support","Soporte *"],["incentives","Incentivos a revisar *"],["experiment","Experimento de adopción *"],["signals","Señales de adopción responsable *"],["owner","Responsable *"],["review","Fecha o cadencia de revisión *"]] },
  scale: { title: "Evaluador de preparación para escalar IA", description: "Revisa evidencia, operación y reversibilidad antes de ampliar.", path: "/herramientas/evaluar-escala-ia", event: "ai_scale_readiness_evaluated", build: evaluateScale, fields: [["value","Valor demostrado *","evidence"],["quality","Calidad estable *","evidence"],["risk","Controles de riesgo *","evidence"],["adoption","Adopción responsable *","evidence"],["economics","Economía sostenible *","evidence"],["ownership","Propiedad operativa *","evidence"],["monitoring","Monitoreo *","evidence"],["support","Soporte *","evidence"],["change","Gestión de cambios *","evidence"],["exit","Plan de salida *","evidence"],["rollback","Reversión probada *","evidence"],["gaps","Brechas principales *"]] },
};
const options = { input: ["Solo texto","Texto e imagen","Audio u otra modalidad"], level: ["Baja","Media","Alta"], yesno: ["Sí","No"], impact: ["Bajo","Medio","Alto"], classification: ["Pública","Interna","Confidencial"], audience: ["Interna","Externa"], consequence: ["Baja","Media","Alta"], evidence: ["Sí","Parcial","No"] };

export default function AIBusinessToolsPage({ kind }) {
  const config = configs[kind];
  const initial = useMemo(() => Object.fromEntries(config.fields.map(([name]) => [name, ""])), [kind]);
  const [values, setValues] = useState(initial);
  const [result, setResult] = useState({ errors: {}, output: "", warnings: [] });
  const breadcrumbs = [{label:"Inicio",href:"/"},{label:"Herramientas",href:"/herramientas"},{label:config.title,href:config.path}];
  const schema = useMemo(() => ({"@context":"https://schema.org","@graph":[breadcrumbSchema(breadcrumbs),{"@type":"WebApplication",name:config.title,description:config.description,applicationCategory:"BusinessApplication",operatingSystem:"Web",url:`https://masanes.cl${config.path}`,dateModified:"2026-07-16"}]}), [kind]);
  usePageMetadata({ title: config.title, description: config.description, path: config.path, schema });
  useEffect(() => trackEvent("ai_business_tool_opened", { tool: kind }), [kind]);
  const reset = () => { setValues(initial); setResult({errors:{},output:"",warnings:[]}); };
  const submit = (event) => { event.preventDefault(); const next = config.build(values); setResult(next); if (next.output) trackEvent(config.event, { tool: kind }); };
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero"><div><p className="eyebrow">Herramienta local y determinista</p><h1>{config.title}</h1><p className="page-hero__lead">{config.description}</p><p>No ingreses nombres, datos personales, secretos, contratos ni información confidencial. Tus entradas no se guardan ni se envían. El resultado es una guía de análisis, no una aprobación técnica, financiera, legal o regulatoria.</p></div></header><section className="generator-layout"><form className="generator-form" noValidate onSubmit={submit}>{config.fields.map(([name,label,type]) => <label className="field" key={name} htmlFor={`ai-${kind}-${name}`}><span>{label}</span>{type ? <select id={`ai-${kind}-${name}`} value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name]?`ai-error-${kind}-${name}`:undefined} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}><option value="">Selecciona una opción</option>{options[type].map((option)=><option key={option}>{option}</option>)}</select> : config.numeric ? <input id={`ai-${kind}-${name}`} type="number" min="0" step="any" value={values[name]} aria-invalid={Boolean(result.errors[name])} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}/> : <textarea id={`ai-${kind}-${name}`} rows="3" value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name]?`ai-error-${kind}-${name}`:undefined} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}/>} {result.errors[name]&&<small className="field-error" id={`ai-error-${kind}-${name}`}>{result.errors[name]}</small>}</label>)}<div className="form-actions"><button className="button button--primary" type="submit"><Sparkles size={16}/>Generar revisión</button><button className="button button--secondary" type="button" onClick={reset}><RotateCcw size={16}/>Limpiar</button></div></form><aside className="generator-output" aria-live="polite"><h2>Resultado</h2>{result.output?<><pre className="template-preview">{result.output}</pre>{result.warnings.length>0&&<div className="tool-warnings"><h3>Atención</h3><ul>{result.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></div>}<div className="form-actions"><CopyToClipboard text={result.output} label="Copiar resultado" onCopy={()=>trackEvent("ai_resource_copied",{tool:kind})}/><button className="button button--secondary" type="button" onClick={()=>{trackEvent("ai_resource_printed",{tool:kind});window.print();}}><Printer size={16}/>Imprimir</button></div></>:<p>Completa los campos obligatorios para generar una revisión. No se transmitirá el contenido.</p>}</aside></section></main></PageShell>;
}

