const updatedAt = "2026-07-14";
const base = "/aprende/consultoria/entrevistas-de-caso";

const lesson = (order, slug, title, description, readingTime, outcomes, sections, relatedResources = []) => ({
  order, slug, title, description, readingTime, outcomes, sections, relatedResources,
  href: `${base}/${slug}`, level: "Introductorio a intermedio", updatedAt, status: "published",
});

export const caseLessons = [
  lesson(1, "como-funciona", "Cómo funciona una entrevista de caso", "Comprende qué evalúa una entrevista de caso, cómo puede avanzar y qué cambia entre formatos.", "9 minutos", ["Reconocer las etapas flexibles de una entrevista", "Distinguir formatos guiados y abiertos", "Entender las dimensiones evaluadas"], [
    { title: "Una simulación condensada", paragraphs: ["Una entrevista de caso es una simulación simplificada de un problema de negocio. La persona candidata debe aclarar la decisión, ordenar la ambigüedad, identificar información relevante, analizar evidencia y recomendar una acción.", "La conversación es colaborativa. El entrevistador puede entregar información, desafiar un supuesto, redirigir el análisis, introducir una restricción o pedir una síntesis. El proceso importa tanto como la respuesta final."] },
    { title: "Qué puede evaluarse", questionGroups: [{ title: "Resolución de problemas", items: ["descomponer y priorizar", "identificar impulsores causales", "conectar evidencia y conclusión"] }, { title: "Comunicación", items: ["explicar el plan", "separar hechos, supuestos y conclusiones", "sintetizar periódicamente"] }, { title: "Razonamiento cuantitativo", items: ["elegir fórmula", "conservar unidades", "interpretar el resultado"] }, { title: "Adaptabilidad", items: ["escuchar", "incorporar nueva evidencia", "recuperarse de un error"] }] },
    { title: "Presencia profesional", paragraphs: ["Se busca claridad, curiosidad, energía apropiada y confianza calibrada. No existe una regla universal de contacto visual o lenguaje corporal.", "En virtual, prueba audio, cámara y pantalla compartida; ordena papel y calculadora; mira periódicamente a cámara sin abandonar notas útiles."] },
    { title: "Una secuencia posible", timeline: [{ time: "Inicio", text: "Saludo, motivación o experiencia." }, { time: "Apertura", text: "Escuchar, reformular, alinear objetivo y aclarar." }, { time: "Estructura", text: "Construir el mapa y proponer un inicio." }, { time: "Análisis", text: "Usar exhibits, cálculos, ideas e hipótesis." }, { time: "Cierre", text: "Recomendar con evidencia, riesgo y siguiente paso." }] },
    { title: "Más o menos dirección", comparison: { leftTitle: "Caso con mayor iniciativa del candidato", leftItems: ["decide qué analizar", "solicita información", "prioriza ramas"], rightTitle: "Caso más guiado", rightItems: ["recibe preguntas específicas", "avanza por bloques", "integra cada respuesta"] }, paragraphs: ["Ambos requieren estructura, interpretación y síntesis. El formato varía por proceso, rol, oficina, nivel e entrevistador; verifica información vigente."] },
    { title: "Mapa del razonamiento", framework: [{ title: "Problema", text: "¿Qué ocurre?" }, { title: "Objetivo", text: "¿Qué decisión y métrica importan?" }, { title: "Hipótesis", text: "¿Qué explicación probar primero?" }, { title: "Estructura", text: "¿Cómo dividir el análisis?" }, { title: "Evidencia", text: "¿Qué muestran datos y cálculos?" }, { title: "Insight", text: "¿Qué implica?" }, { title: "Recomendación", text: "¿Qué debe hacer el cliente?" }] },
  ], ["case-cheat-sheet", "case-readiness"]),

  lesson(2, "entender-el-problema", "Cómo entender y definir el problema", "Aprende a tomar notas útiles, reformular el encargo y hacer pocas preguntas que cambien el análisis.", "10 minutos", ["Reformular un caso con precisión", "Definir una métrica de éxito", "Elegir preguntas aclaratorias de alto valor"], [
    { title: "Escucha para construir un mapa", paragraphs: ["Registra cliente, situación actual, problema u oportunidad, métrica, geografía, producto, horizonte, restricciones y decisión. Las notas deben capturar relaciones, no transcribir cada palabra."] },
    { title: "Reformula sin repetir", callout: { title: "Estructura de reformulación", text: "Para confirmar que entendí: [cliente] enfrenta o evalúa [situación] y necesita decidir [decisión] para lograr [métrica], dentro de [alcance o plazo]." }, paragraphs: ["Una buena reformulación revela quién decide, qué cambió, qué significa éxito y qué alcance importa."] },
    { title: "Convierte aspiraciones en objetivos", paragraphs: ["Crecer puede significar ingresos, margen, clientes o uso. Adopción puede ser registro, activación, primera transacción, repetición o retención. Rentabilidad puede significar utilidad absoluta, margen, retorno, equilibrio o caja."], exercise: { title: "Define el éxito", prompt: "Para ‘mejorar adopción’, elige comportamiento, segmento, horizonte y restricción.", help: "Ejemplo: aumentar usuarios que completan una primera transacción dentro de 30 días, sin elevar el costo por activación sobre el límite acordado." } },
    { title: "Sistema de preguntas aclaratorias", questionGroups: [{ title: "Cliente y decisión", items: ["¿Quién decide?", "¿Qué cambió y desde cuándo?", "¿Qué acción está sobre la mesa?"] }, { title: "Métrica y alcance", items: ["¿Cómo se medirá éxito?", "¿Qué segmento, canal o geografía incluye?", "¿Cuál es el plazo?"] }, { title: "Restricciones y economía", items: ["¿Hay límites regulatorios, de inversión o capacidad?", "¿Cómo se generan ingresos?", "¿Qué costos dominan?"] }] },
    { title: "Preguntas útiles y preguntas débiles", comparison: { leftTitle: "Cambian el análisis", leftItems: ["definen éxito", "resuelven ambigüedad esencial", "aclaran una restricción"], rightTitle: "Añaden ruido", rightItems: ["repiten el prompt", "piden todos los números", "buscan ganar tiempo", "preguntan continuamente si está bien"] } },
    { title: "Tres prompts ambiguos", examples: [{ title: "LinguaNube", text: "Las renovaciones de una suscripción para aprender idiomas disminuyeron. Define cliente, cohorte, métrica y plazo." }, { title: "Clínica Horizonte", text: "Una red regional evalúa consultas virtuales. Define objetivo, pacientes incluidos y restricción clínica." }, { title: "CampoClaro", text: "Una empresa de alimentos considera una línea baja en azúcar. Define decisión, segmento y umbral económico." }] },
    { title: "Respuestas modelo", modelAnswers: [{ title: "LinguaNube", text: "Objetivo: recuperar la renovación anual de usuarios nuevos. Preguntas: ¿en qué cohortes comenzó la caída? ¿cambió precio, uso u onboarding? Métrica: porcentaje que renueva al cierre del primer año." }, { title: "Clínica Horizonte", text: "Objetivo: decidir un piloto que mejore acceso sin deteriorar calidad. Preguntas: ¿qué especialidades son elegibles? ¿qué capacidad tecnológica existe? Métrica: consultas resueltas y tiempo de espera, con calidad como guardrail." }, { title: "CampoClaro", text: "Objetivo: decidir lanzamiento para un segmento definido. Preguntas: ¿qué necesidad no satisfecha existe? ¿qué margen mínimo se requiere? Métrica: contribución incremental después de canibalización." }] },
  ], ["clarifying-checklist", "structure-worksheet"]),

  lesson(3, "hipotesis-y-estructura", "Cómo formular hipótesis y estructurar un caso", "Construye hipótesis provisionales e issue trees adaptados a la decisión, no plantillas rígidas.", "12 minutos", ["Formular una hipótesis comprobable", "Descomponer métricas", "Presentar y priorizar una estructura"], [
    { title: "Una hipótesis orienta, no sentencia", paragraphs: ["Una hipótesis inicial es una explicación provisional conectada al objetivo. Sugiere qué probar primero y debe cambiar cuando la evidencia la contradice. No es una adivinanza presentada como hecho ni una respuesta que haya que defender."] },
    { title: "Ejemplos comprobables", examples: [{ title: "Rentabilidad", text: "La caída podría concentrarse en costos variables; compararía costo unitario y mix antes de revisar gastos fijos." }, { title: "Retención", text: "La baja podría estar en usuarios nuevos que no alcanzan el primer momento de valor; segmentaría por cohorte y activación." }, { title: "Experimento", text: "El aumento observado podría incluir estacionalidad; estimaría efecto incremental frente a un grupo comparable." }] },
    { title: "La estructura es el mapa", bullets: ["específica al caso", "con ramas suficientemente distintas", "amplia sin perder foco", "priorizada", "conectada a la decisión", "fácil de explicar"], callout: { title: "MECE como aspiración", text: "Busca minimizar solapamientos y vacíos, pero no sacrifiques relevancia por etiquetas perfectas." } },
    { title: "Árboles de métricas", formulas: [{ label: "Utilidad", formula: "Ingresos − Costos" }, { label: "Ingresos", formula: "Precio × Volumen" }, { label: "Volumen", formula: "Clientes × Frecuencia × Unidades" }, { label: "Valor de mercado", formula: "Compradores × Compras anuales × Ticket" }, { label: "Capacidad efectiva", formula: "Capacidad disponible × Utilización × Productividad" }] },
    { title: "Construye en siete pasos", ordered: ["Declara la decisión", "Identifica la métrica", "Descompón el resultado o la decisión", "Añade factibilidad no financiera", "Añade riesgos", "Prioriza una rama", "Explica por qué empieza allí"] },
    { title: "Presenta con dirección", example: { title: "Guion", text: "Organizaría el análisis en cuatro áreas. Primero evaluaría [A] porque determina [razón]; luego [B] y [C]; finalmente validaría [D] y sus riesgos. Empezaría por [A] y ajustaría la estructura con nueva información." } },
    { title: "Práctica de estructura", examples: ["Caída de utilidad en una lavandería industrial", "Entrada de un servicio de teleasistencia a una región", "Reducción de costos en distribución de libros", "Adopción de una aplicación de mantenimiento"].map((text, i) => ({ title: `Prompt ${i + 1}`, text: `${text}. Escribe la decisión, métrica, tres a cinco ramas, hipótesis y primer análisis.` })) },
    { title: "Estructuras posibles", modelAnswers: [{ title: "Criterio de revisión", text: "Comprueba que las ramas respondan a la decisión, que la métrica pueda descomponerse, que factibilidad y riesgos aparezcan cuando importan, y que exista una prioridad. Puede haber más de una respuesta válida." }] },
  ], ["structure-worksheet", "case-cheat-sheet"]),

  lesson(4, "frameworks-y-lentes", "Frameworks y lentes para estructurar casos", "Combina pocos lentes analíticos útiles y personalízalos según el cliente, la métrica y la decisión.", "13 minutos", ["Elegir lentes con intención", "Adaptar categorías al caso", "Evitar frameworks memorizados"], [
    { title: "No memorices decenas de plantillas", paragraphs: ["Aprende a combinar un conjunto pequeño de lentes. Empieza por la decisión y la métrica; incluye una categoría solo si puede cambiar la recomendación."] },
    { title: "Mapa analítico general", questionGroups: [{ title: "Finanzas", items: ["precio, volumen e ingresos", "costos y margen", "inversión, retorno, payback y equilibrio"] }, { title: "Mercado y competencia", items: ["tamaño y crecimiento", "segmentos y barreras", "posición, sustitutos y respuesta rival"] }, { title: "Cliente", items: ["necesidad y disposición a pagar", "journey, adopción y churn", "confianza y valor de vida"] }, { title: "Operaciones", items: ["capacidad y cuellos de botella", "personas, procesos y tecnología", "calidad, proveedores y logística"] }, { title: "Riesgo", items: ["estratégico, regulatorio y reputacional", "operativo, tecnológico y financiero", "ejecución, adopción y canibalización"] }] },
    { title: "Lentes prácticos", bullets: ["stakeholders y segmentos", "financiero frente a no financiero", "ecuación causal", "alternativas: construir, comprar, asociar o pilotear", "prevención, detección y mitigación", "cadena de valor", "crecimiento orgánico e inorgánico", "corto, medio y largo plazo", "cliente, competencia y compañía", "journey del cliente", "árbol de costos"] },
    { title: "Usa macro y fuerzas sectoriales con criterio", paragraphs: ["Factores económicos, regulatorios, tecnológicos, sociales o ambientales sirven cuando afectan la decisión. Un análisis macro completo rara vez aporta si el problema depende de una cohorte, un proceso o una economía unitaria."] },
    { title: "Elige en siete movimientos", ordered: ["Parte de la decisión", "Define la métrica", "Elige dos o tres lentes", "Descarta categorías memorizadas sin utilidad", "Renombra ramas para el cliente", "Prioriza", "Revisa con nueva evidencia"] },
    { title: "Practica en el constructor", links: [{ label: "Abrir el constructor de estructuras", href: "/herramientas/constructor-estructuras-caso" }] },
  ], ["structure-worksheet", "case-taxonomy"]),

  lesson(5, "exhibits-y-calculos", "Cómo analizar exhibits y resolver cálculos", "Interpreta gráficos y tablas, calcula con unidades visibles y transforma resultados en implicaciones de negocio.", "15 minutos", ["Leer un exhibit con método", "Aplicar fórmulas esenciales", "Detectar errores de unidades", "Interpretar cada cálculo"], [
    { title: "Del gráfico a la decisión", framework: [{ title: "Orientar", text: "Título, ejes, unidades, periodo, segmentos y notas." }, { title: "Describir", text: "Qué contiene, sin narrar cada etiqueta." }, { title: "Comparar", text: "Extremos, tendencias, quiebres, diferencias y outliers." }, { title: "Interpretar", text: "Qué hipótesis apoya o debilita." }, { title: "Conectar", text: "Implicación y siguiente análisis." }] },
    { title: "Síntesis de exhibit", callout: { title: "Guion", text: "El gráfico muestra [hallazgo]. Esto sugiere [interpretación]. Para el cliente implica [consecuencia], por lo que analizaría [siguiente paso]." } },
    { title: "Exhibits comunes", bullets: ["estado de resultados", "tendencias de ingresos", "costos", "participación", "segmentos", "funnel y cohortes", "capacidad", "benchmark", "curva de precios", "journey", "resultados experimentales", "mix y waterfall"] },
    { title: "Calcula de forma auditable", ordered: ["Define la pregunta", "Declara la fórmula", "Revisa datos", "Explicita supuestos", "Mantén unidades", "Calcula por pasos", "Verifica", "Prueba plausibilidad", "Interpreta", "Conecta a la decisión"] },
    { title: "Fórmulas esenciales", formulas: [{ label: "Ingresos", formula: "Precio × Volumen" }, { label: "Costos", formula: "Fijos + Variable unitario × Volumen" }, { label: "Utilidad", formula: "Ingresos − Costos" }, { label: "Margen", formula: "Utilidad ÷ Ingresos" }, { label: "Crecimiento", formula: "(Nuevo − Anterior) ÷ Anterior" }, { label: "Participación", formula: "Ventas propias ÷ Mercado" }, { label: "Equilibrio", formula: "Costos fijos ÷ (Precio − Costo variable unitario)" }, { label: "ROI simple", formula: "Beneficio neto incremental ÷ Inversión" }, { label: "Payback simple", formula: "Inversión inicial ÷ Flujo anual esperado" }, { label: "Impacto incremental", formula: "Resultado tratado − Contrafactual estimado" }] },
    { title: "Unidades que cambian respuestas", paragraphs: ["Distingue miles, millones y escalas lingüísticas; porcentaje y puntos porcentuales; moneda; mes y año; valor unitario y total; puntos base. Pasar de 10% a 12% suma 2 puntos porcentuales y equivale a 20% de crecimiento relativo."] },
    { title: "Errores frecuentes", bullets: ["perder ceros", "mezclar meses y años", "confundir porcentaje y puntos", "aplicar una tasa a la base incorrecta", "doble conteo", "olvidar costos fijos", "confundir ingresos con utilidad", "no interpretar"] },
    { title: "Diez drills", calculationDrills: [
      ["Ingresos", "800 unidades a $25", "$20.000", "Precio × volumen", "Cuantifica la escala de ventas."], ["Margen", "$36.000 de utilidad sobre $120.000", "30%", "36.000 ÷ 120.000", "Permite comparar rentabilidad relativa."], ["Crecimiento", "Ventas suben de 50 a 62 millones", "24%", "12 ÷ 50", "Separa aumento absoluto y relativo."], ["Equilibrio", "$90.000 fijos; precio $50; variable $20", "3.000 unidades", "90.000 ÷ 30", "Volumen mínimo antes de utilidad."], ["Participación", "$18 millones de $120 millones", "15%", "18 ÷ 120", "Ubica la posición en el mercado."], ["Promedio ponderado", "60% compra $20 y 40% compra $35", "$26", "0,6×20 + 0,4×35", "El mix explica el ticket."], ["Capacidad", "12 equipos × 8 turnos × 75%", "72 turnos efectivos", "12×8×0,75", "Mide capacidad utilizable."], ["ROI", "$45.000 beneficio neto sobre $150.000", "30%", "45.000 ÷ 150.000", "Debe revisarse definición y horizonte."], ["Precio-volumen", "Precio baja 10%; volumen sube 15%", "+3,5% ingresos", "0,9×1,15−1", "El volumen compensa la reducción de precio."], ["Incrementalidad", "Tratado +12 puntos; control +5", "+7 puntos incrementales", "12−5", "El control aproxima lo ocurrido sin intervención."]
    ].map(([title,prompt,answer,hint,interpretation]) => ({ title,prompt,answer,hint,explanation: hint,interpretation })) },
  ], ["formula-sheet", "exhibit-checklist"]),
  lesson(6, "market-sizing", "Market sizing: cómo estimar un mercado", "Estima demanda o ingresos con supuestos transparentes, unidades consistentes y controles de plausibilidad.", "12 minutos", ["Definir el resultado antes de calcular", "Elegir un enfoque", "Explicitar y comprobar supuestos"], [
    { title: "No busca una cifra perfecta", paragraphs: ["Un market sizing estima usuarios, unidades, transacciones, ingresos, capacidad o demanda potencial. Permite observar lógica, transparencia, control numérico, juicio práctico y comunicación."] },
    { title: "Define la salida", bullets: ["unidades o dinero", "día, mes o año", "mercado total o segmento accesible", "ciudad, país o región", "situación actual o potencial", "consumidor o empresa"] },
    { title: "Cuatro enfoques", questionGroups: [{ title: "Top-down", items: ["Población × elegibilidad × adopción × frecuencia × unidades × precio", "útil para demanda de consumidores"] }, { title: "Bottom-up", items: ["puntos de operación × clientes × días × ticket", "útil cuando se observan unidades productivas"] }, { title: "Oferta", items: ["instalaciones × capacidad × utilización", "útil cuando la demanda es difícil de observar"] }, { title: "Reposición", items: ["base instalada ÷ vida útil + demanda de crecimiento", "útil para bienes durables"] }] },
    { title: "Supuestos que se pueden defender", paragraphs: ["Hazlos explícitos, simples, plausibles, coherentes y relevantes. Usa cifras redondeadas y aclara su carácter hipotético. Evita memorizar tablas demográficas como si fueran exactas."] },
    { title: "Pruebas de plausibilidad", bullets: ["método alternativo", "valor por habitante", "capacidad máxima", "benchmark de ingresos", "mercado adyacente", "límite superior e inferior"] },
    { title: "Ocho ejercicios originales", examples: ["Reparaciones anuales de bicicletas en Santiago", "Demanda mensual de escritorios flexibles en una ciudad regional", "Ingresos anuales de peluquería para mascotas en Chile", "Compras de café en un aeropuerto principal", "Reposición de refrigeradores comerciales", "Transacciones de billetera digital entre estudiantes", "Ingresos de tutorías en línea en una zona metropolitana", "Sesiones de carga pública para vehículos eléctricos"].map((text, i) => ({ title: `Ejercicio ${i + 1}`, text: `${text}. Define salida, ecuación, supuestos, rango y una prueba alternativa.` })) },
    { title: "Tres soluciones ilustrativas", modelAnswers: [{ title: "Bicicletas", text: "Supuestos: 600.000 bicicletas activas; 45% requiere una reparación pagada anual; ticket medio hipotético $24.000. Resultado: 600.000×45%×$24.000 = $6.480 millones anuales. Alternativa: talleres×servicios diarios×días×ticket. Es una estimación, no un dato de mercado." }, { title: "Cowork", text: "Supuestos: 18 centros, 90 escritorios promedio y 72% de ocupación. Demanda estimada: 1.166 escritorios ocupados. Alternativa: trabajadores elegibles×preferencia por modalidad flexible." }, { title: "Carga pública", text: "Supuestos: 32.000 vehículos eléctricos en alcance, 30% usa carga pública, 3 sesiones mensuales. Resultado: 28.800 sesiones al mes. Contrasta con estaciones×conectores×sesiones posibles." }] },
    { title: "Practica con un prompt nuevo", links: [{ label: "Abrir práctica de market sizing", href: "/herramientas/practica-market-sizing" }] },
  ], ["market-sizing-sheet", "formula-sheet"]),

  lesson(7, "brainstorming", "Cómo hacer brainstorming estructurado", "Genera alternativas amplias pero organizadas, relevantes y priorizadas para el objetivo del caso.", "8 minutos", ["Elegir categorías útiles", "Generar ideas sin duplicarlas", "Priorizar con criterios explícitos"], [
    { title: "No es solo producir muchas ideas", paragraphs: ["El brainstorming permite observar amplitud, organización, relevancia, creatividad, priorización y juicio. La calidad aumenta cuando cada idea vive dentro de una lógica."] },
    { title: "Proceso en siete pasos", ordered: ["Reformula la pregunta", "Elige dos a cuatro categorías", "Genera dentro de cada categoría", "Elimina duplicados", "Prioriza", "Explica las ideas más fuertes", "Conecta con el objetivo"] },
    { title: "Lentes frecuentes", questionGroups: [{ title: "Crecimiento", items: ["clientes", "frecuencia", "ticket", "productos", "canales", "geografías", "conversión", "retención"] }, { title: "Costos", items: ["personas", "compras", "tecnología", "instalaciones", "logística", "procesos", "capacidad"] }, { title: "Adopción", items: ["awareness", "valor", "onboarding", "confianza", "conveniencia", "hábito"] }, { title: "Riesgo", items: ["prevención", "detección", "respuesta", "contingencia", "monitoreo"] }] },
    { title: "Lista frente a estructura", comparison: { leftTitle: "Débil", leftItems: ["marketing", "precio", "redes sociales", "alianzas", "productos"], rightTitle: "Más útil", rightItems: ["adquisición: canal y mensaje", "activación: onboarding y primer valor", "retención: hábito y servicio"] } },
    { title: "Prioriza sin falsa precisión", bullets: ["impacto", "confianza", "esfuerzo", "velocidad", "encaje estratégico", "reversibilidad", "riesgo"], paragraphs: ["No hay una fórmula universal. Explica por qué un criterio importa en este caso."] },
    { title: "Seis drills", examples: ["Mejorar adopción digital", "Reducir churn", "Bajar costo de entrega", "Responder a un competidor", "Reducir ausencias a citas médicas", "Aumentar uso de crédito para empresas"].map((text, i) => ({ title: `Drill ${i + 1}`, text: `${text}: crea tres categorías, tres ideas por categoría y prioriza una.` })) },
    { title: "Respuesta modelo", modelAnswers: [{ title: "Ausencias a citas", text: "Categorías: prevención, facilidad de reprogramación y gestión de capacidad. Prioridad: recordatorios que permitan confirmar o liberar el cupo, porque puede probarse rápido; medir asistencia y vigilar sobrecarga del canal." }] },
  ], ["brainstorming-sheet"]),

  lesson(8, "recomendacion-final", "Cómo cerrar un caso con una recomendación ejecutiva", "Sintetiza hallazgos durante el caso y responde la decisión con evidencia, riesgo y siguiente paso.", "9 minutos", ["Hacer síntesis intermedias", "Dar una respuesta directa", "Incluir incertidumbre sin esconderse en ella"], [
    { title: "Sintetiza antes del final", ordered: ["Declara el hallazgo", "Explica la implicación", "Di qué cambia", "Propón el siguiente paso"] },
    { title: "Modelo de cierre", framework: [{ title: "Decisión", text: "Qué debe hacer el cliente." }, { title: "Razones", text: "Dos o tres evidencias prioritarias." }, { title: "Riesgo", text: "Qué podría debilitar la recomendación." }, { title: "Próximo paso", text: "Qué validar o ejecutar ahora." }, { title: "Condición", text: "Cuándo cambiaría la respuesta." }] },
    { title: "Características", bullets: ["directa", "basada en evidencia", "priorizada", "breve", "accionable", "equilibrada", "conectada al objetivo", "consciente de incertidumbre"] },
    { title: "Errores comunes", bullets: ["repetir todo el caso", "no decidir", "listar cada hallazgo", "introducir ideas sin respaldo", "olvidar riesgo", "ignorar economía negativa", "decir ‘depende’ sin condiciones"] },
    { title: "Cinco ejercicios de 60–90 segundos", examples: [{ title: "Piloto de teleconsulta", text: "Demanda alta, capacidad clínica limitada y calidad aún no medida." }, { title: "Nueva tarifa", text: "Sube ingreso por cliente, pero aumenta churn en el segmento sensible." }, { title: "Centro de distribución", text: "Reduce costo unitario si alcanza 70% de utilización." }, { title: "Producto bajo en azúcar", text: "Interés alto, margen bajo y posible canibalización." }, { title: "Campaña de cashback", text: "Ventas suben, pero la utilidad incremental es negativa." }] },
    { title: "Respuesta modelo y rúbrica", modelAnswers: [{ title: "Piloto de teleconsulta", text: "Recomiendo un piloto acotado en especialidades elegibles. La demanda valida el problema y el alcance protege capacidad. El riesgo es deteriorar calidad; mediría resolución y reconsulta. Escalaría solo si esos guardrails se mantienen." }], checklist: ["Respondí primero", "Usé dos evidencias", "Nombré un riesgo", "Propuse un próximo paso", "Volví al objetivo"] },
  ], ["recommendation-template"]),

  lesson(9, "tipos-de-casos", "Tipos de casos de negocio", "Reconoce familias de problemas sin convertir sus etiquetas en respuestas memorizadas.", "10 minutos", ["Identificar la decisión central", "Combinar categorías", "Elegir una lógica inicial"], [
    { title: "Las categorías se mezclan", paragraphs: ["Un caso de entrada puede incluir precios, capacidad y experimentación. La etiqueta orienta una primera pregunta; no reemplaza el análisis específico."] },
    { title: "Diagnóstico y crecimiento", comparison: { leftTitle: "¿Qué causa el resultado?", leftItems: ["define la métrica", "descompone", "segmenta", "compara", "localiza la desviación"], rightTitle: "¿Cómo crecer o mejorar?", rightItems: ["clientes", "frecuencia", "ticket", "producto", "canal", "retención"] } },
    { title: "Expansión e inversión", questionGroups: [{ title: "¿Vale la pena entrar?", items: ["atractivo", "capacidad para competir", "economía", "modo de entrada", "riesgos"] }, { title: "¿Asignar recursos?", items: ["valor esperado", "inversión", "alternativas", "encaje", "momento", "reversibilidad"] }] },
    { title: "Operaciones y comercial", questionGroups: [{ title: "Operaciones", items: ["personas", "proceso", "tecnología", "capacidad", "calidad", "cadena de suministro"] }, { title: "Comercial", items: ["precio", "ventas", "distribución", "mix", "posicionamiento", "go-to-market"] }] },
    { title: "Cliente, digital y tecnología", paragraphs: ["Los casos de cliente exploran segmento, necesidad, journey, valor, barrera y retención. En digital, conecta objetivo de negocio, usuario, factibilidad, datos, integración, costo, adopción y cambio organizacional. La tecnología es un medio, no la recomendación por sí sola."] },
    { title: "Experimentación", paragraphs: ["Pregunta si una iniciativa causó valor incremental. Define decisión, hipótesis, tratamiento, comparación, KPI, economía, segmento, escala y factibilidad."] },
    { title: "Cuatro preguntas fundacionales", ordered: ["¿Qué causa el resultado?", "¿Cómo crecer o mejorar?", "¿Conviene invertir o entrar?", "¿Cómo operar con mayor efectividad?"] },
  ], ["case-taxonomy"]),

  lesson(10, "experimentacion", "Casos de experimentación e incrementalidad", "Diseña análisis que separen crecimiento observado de impacto incremental y conecten resultados con economía y escala.", "16 minutos", ["Definir decisión, tratamiento y comparación", "Distinguir KPI y guardrails", "Evaluar incrementalidad y economía"], [
    { title: "Empieza por la decisión", paragraphs: ["Antes del test, define qué resultado llevaría a escalar, detener, modificar, segmentar o extender una iniciativa. Sin decisión, un experimento produce datos pero no necesariamente aprendizaje accionable."] },
    { title: "Lógica de experimentación", ordered: ["Define decisión", "Formula hipótesis", "Describe tratamiento", "Construye comparación", "Elige KPI principal", "Añade guardrails", "Estima impacto incremental", "Calcula economía", "Revisa factibilidad", "Recomienda escala, iteración o término"] },
    { title: "Incrementalidad con cautela", paragraphs: ["Un antes y después no aísla causalidad. Estacionalidad, tendencias, selección, contaminación o adelanto de compras pueden explicar parte del cambio. Cuando sea viable, usa asignación aleatoria; si no, busca grupos comparables y revisa balance previo."] },
    { title: "Cuatro clases de métricas", questionGroups: [{ title: "Resultado principal", items: ["conducta o resultado que decide"] }, { title: "Diagnóstico", items: ["explica dónde cambió"] }, { title: "Guardrail", items: ["no debe deteriorarse"] }, { title: "Economía", items: ["ingreso y utilidad incremental", "costo por resultado", "retorno y payback"] }] },
    { title: "Framework de experimento", framework: [{ title: "Decisión", text: "Acción dependiente del resultado." }, { title: "Población", text: "Personas o unidades elegibles." }, { title: "Hipótesis", text: "Conducta que debería cambiar." }, { title: "Intervención", text: "Cambio para el grupo tratado." }, { title: "Comparación", text: "Contrafactual razonable." }, { title: "Métrica", text: "Resultado y guardrails." }, { title: "Economía", text: "Valor incremental frente a costo." }, { title: "Escala", text: "Capacidad para operar." }, { title: "Riesgo", text: "Sesgo o amenaza." }] },
    { title: "Cuatro casos originales", cases: ["billetera-lumina", "pagos-mercavia", "ingresos-nexoempresas", "cashback-mercadalia"] },
    { title: "Diseña un experimento", links: [{ label: "Abrir el diseñador de experimentos", href: "/herramientas/disenador-experimentos-negocio" }] },
  ], ["experiment-template", "formula-sheet"]),

  lesson(11, "fit-y-conductuales", "Fit, motivación y entrevistas conductuales", "Prepara una presentación, motivaciones y experiencias verificables sin memorizar un libreto personal.", "12 minutos", ["Explicar una trayectoria con foco", "Construir motivaciones basadas en evidencia", "Preparar historias y preguntas de seguimiento"], [
    { title: "El proceso puede combinar componentes", paragraphs: ["Es común encontrar presentación, motivación, revisión de CV, preguntas conductuales, caso y preguntas del candidato. Los nombres y el orden varían."] },
    { title: "Preséntate con una secuencia", ordered: ["Identidad profesional actual", "Trayectoria relevante", "Una o dos evidencias", "Por qué el rol es el siguiente paso lógico"], callout: { title: "Ejemplo ficticio", text: "Valentina es ingeniera de operaciones, ha liderado mejoras de capacidad y quiere trasladar ese razonamiento a problemas diversos con clientes. Sustenta la transición con dos proyectos verificables." } },
    { title: "Motivación investigada", bullets: ["por qué consultoría", "por qué esta firma", "por qué esta oficina", "por qué esta práctica", "por qué ahora", "por qué no un rol interno"], paragraphs: ["Conecta evidencia personal, características reales del cargo, una meta futura e investigación específica. El prestigio por sí solo no explica encaje."] },
    { title: "Una historia orientada a decisiones", framework: [{ title: "Contexto", text: "Qué ocurría." }, { title: "Responsabilidad", text: "Qué debías lograr." }, { title: "Decisión", text: "Qué opciones enfrentaste." }, { title: "Acción", text: "Qué hiciste personalmente." }, { title: "Resultado", text: "Qué cambió." }, { title: "Aprendizaje", text: "Qué harías diferente." }] },
    { title: "Banco de historias", bullets: ["alineamiento", "conflicto", "ética", "fracaso", "comunicación", "storytelling", "oportunidad", "influencia", "resistencia", "priorización", "liderazgo", "feedback", "ambigüedad", "equipo", "adaptabilidad"] },
    { title: "Principios en situaciones ficticias", examples: [{ title: "Stakeholders", text: "Convertir un mandato amplio en una agenda con decisión y responsables." }, { title: "Conflicto", text: "Resolver desacuerdo volviendo al objetivo compartido y a la evidencia." }, { title: "Ética", text: "Proteger confianza cuando los controles son limitados." }, { title: "Fracaso", text: "Reconocer que un alcance ambiguo debilitó la ejecución y cambiar el proceso." }, { title: "Influencia", text: "Construir una coalición alrededor del problema, no de una solución favorita." }] },
    { title: "Prepárate para profundizar", bullets: ["¿Qué hiciste tú?", "¿Qué alternativas consideraste?", "¿Qué fue difícil?", "¿Quién discrepó?", "¿Qué cambiarías?", "¿Cómo atribuyes el resultado?"] },
    { title: "Banco interactivo de preguntas", behavioralQuestions: { "Liderazgo": ["Cuéntame sobre una ocasión en que diste dirección sin autoridad formal."], "Conflicto": ["Describe un desacuerdo importante y cómo cambió la conversación."], "Fracaso": ["Háblame de un resultado que no cumplió tus expectativas."], "Ética": ["Describe una decisión en que proteger confianza tuvo un costo."], "Influencia": ["¿Cómo lograste apoyo para una idea inicialmente resistida?"], "Comunicación": ["¿Cuándo adaptaste un mensaje para una audiencia difícil?"], "Priorización": ["Describe cómo elegiste entre objetivos incompatibles."], "Innovación": ["¿Cómo convertiste una observación en una prueba?"], "Cliente": ["Describe cómo aclaraste una necesidad ambigua de un cliente."] }, links: [{ label: "Ir al módulo conductual completo", href: "/aprende/consultoria/entrevistas-conductuales" }] },
  ], ["case-behavioral-bank", "candidate-question-bank"]),

  lesson(12, "practica-y-feedback", "Cómo practicar entrevistas de caso", "Progresa desde habilidades aisladas hacia simulaciones completas y convierte feedback cualitativo en ejercicios correctivos.", "12 minutos", ["Diseñar una progresión", "Dar feedback específico", "Diagnosticar la siguiente práctica"], [
    { title: "Seis etapas", timeline: [{ time: "1. Componentes", text: "Problema, estructura, cálculo, exhibits, ideas y síntesis." }, { time: "2. Drills", text: "Estructuras, matemática, gráficos y recomendaciones." }, { time: "3. Sin tiempo", text: "Prioriza calidad de razonamiento." }, { time: "4. Secciones", text: "Añade presión moderada." }, { time: "5. Simulación", text: "Fit, caso, cierre y preguntas." }, { time: "6. Corrección", text: "Vuelve a la habilidad más débil." }] },
    { title: "Compañeros de práctica", paragraphs: ["Puedes practicar con candidatos, estudiantes, exalumnos, antiguos consultores, coaches o comunidades. Alternen roles, usen material propio o autorizado, protejan la privacidad y eviten casos confidenciales."], links: [{ label: "Aprender a construir una red", href: "/aprende/networking" }, { label: "Preparar un mensaje", href: "/herramientas/generador-mensajes-networking" }] },
    { title: "Acuerdos útiles", checklist: ["Definir dificultad y duración", "Acordar dimensiones de feedback", "No compartir información confidencial", "Dar ejemplos observables", "Cerrar con un drill", "Variar compañeros"] },
    { title: "Rúbrica cualitativa", rubric: ["Alineamiento del objetivo", "Preguntas", "Estructura", "Priorización", "Hipótesis", "Exactitud cuantitativa", "Exhibits", "Juicio", "Brainstorming", "Síntesis", "Recomendación", "Comunicación", "Colaboración", "Presencia"] },
    { title: "Clasifica errores", bullets: ["conocimiento", "estructura", "cálculo", "comunicación", "priorización", "interpretación", "proceso", "ritmo o nervios", "configuración de herramientas", "brecha de preparación"] },
    { title: "Diagnóstico de preparación", diagnostic: ["Reformular", "Definir éxito", "Estructura propia", "Calcular hablando", "Interpretar gráfico", "Sintetizar", "Recomendar", "Incorporar feedback", "Historias", "Categorías variadas", "Compañeros variados", "Recuperarse de un error"].map((barrier) => ({ barrier, action: `Practica un ejercicio breve de ${barrier.toLowerCase()} y solicita feedback observable.` })) },
    { title: "Registra y mejora", links: [{ label: "Abrir seguimiento de práctica", href: "/herramientas/seguimiento-practica-casos" }, { label: "Volver al plan de preparación", href: "/aprende/consultoria/plan-de-preparacion" }] },
  ], ["case-practice-rubric", "case-readiness", "case-practice-log"]),
];

export const caseInterviewPath = {
  title: "Entrevistas de caso",
  description: "Una guía práctica para estructurar problemas, analizar datos y construir recomendaciones en procesos de consultoría y estrategia.",
  audience: "Estudiantes, profesionales y candidatos que preparan roles de consultoría, estrategia, analytics o experimentación",
  level: "Introductorio a intermedio", readingTime: "Aproximadamente 138 minutos", updatedAt, status: "published", lessons: caseLessons,
  outcomes: ["Identificar la decisión real", "Reformular y aclarar", "Construir una estructura propia", "Formular y actualizar hipótesis", "Interpretar datos y calcular", "Generar alternativas", "Recomendar con evidencia", "Diagnosticar brechas y practicar"],
};

export const getCaseLesson = (slug) => caseLessons.find((item) => item.slug === slug);

const practiceCase = ({ slug, title, category, difficulty, client, objective, prompt, facts, structure, exhibit, calculation, brainstorm, recommendation, insights, skills }) => ({
  slug, title, category, difficulty, client, objective, prompt,
  fictional: true,
  clarifyingFacts: facts,
  suggestedQuestions: ["¿Cómo se define el objetivo?", "¿Qué segmento y horizonte están incluidos?", "¿Qué restricción puede cambiar la decisión?"],
  possibleStructures: [structure],
  exhibits: [{ title: exhibit.title, columns: exhibit.columns, rows: exhibit.rows, summary: exhibit.summary }],
  calculations: [{ prompt: calculation.prompt, answer: calculation.answer, explanation: calculation.explanation }],
  brainstormingPrompts: [brainstorm], recommendationPrompt: recommendation,
  interviewerGuide: "Entrega los hechos solo cuando se soliciten. Acepta estructuras alternativas si conectan objetivo, evidencia, economía y riesgo.",
  modelInsights: insights, skills,
});

export const practiceCases = [
  practiceCase({ slug: "margen-brisa", title: "El margen de Brisa Verde", category: "Rentabilidad", difficulty: "introductorio", client: "Brisa Verde", objective: "Recuperar margen sin deteriorar la propuesta de valor.", prompt: "Una cadena ficticia de cafeterías saludables aumentó ventas, pero su utilidad cayó.", facts: ["La caída comenzó hace seis meses.", "El número de locales no cambió.", "Los insumos importados afectan solo una categoría."], structure: ["Ingresos por precio, volumen y mix", "Costos fijos y variables", "Segmentos y causas", "Acciones y riesgos"], exhibit: { title: "Economía por categoría", columns: ["Categoría", "Ventas", "Margen"], rows: [["Bebidas", "$120 M", "55%"], ["Bowls", "$90 M", "28%"], ["Snacks", "$40 M", "45%"]], summary: "Bowls combina volumen relevante y menor margen." }, calculation: { prompt: "Calcula utilidad bruta total.", answer: "$109,2 millones", explanation: "120×55% + 90×28% + 40×45%." }, brainstorm: "¿Cómo recuperar margen en bowls sin una subida general de precios?", recommendation: "Recomienda una acción, riesgo y validación.", insights: ["Segmentar antes de recortar.", "El mix puede explicar la divergencia entre ventas y utilidad."], skills: ["Rentabilidad", "Mix", "Cálculo"] }),
  practiceCase({ slug: "crecimiento-aulavia", title: "El crecimiento de AulaVía", category: "Crecimiento", difficulty: "intermedio", client: "AulaVía", objective: "Aumentar alumnos activos con economía sostenible.", prompt: "Una plataforma ficticia de tutorías quiere crecer en una ciudad donde ya opera.", facts: ["El tráfico crece, pero la activación está estable.", "La oferta de tutores es suficiente."], structure: ["Funnel", "Segmentos y necesidad", "Canales", "Retención y economía"], exhibit: { title: "Funnel mensual", columns: ["Etapa", "Usuarios"], rows: [["Visitas", "50.000"], ["Registro", "10.000"], ["Primera clase", "2.000"], ["Segunda clase", "1.100"]], summary: "La mayor caída proporcional ocurre antes de la primera clase." }, calculation: { prompt: "Calcula conversión visita a primera clase.", answer: "4%", explanation: "2.000 ÷ 50.000." }, brainstorm: "Genera ideas de activación y retención.", recommendation: "Elige un punto del funnel para pilotear.", insights: ["Priorizar activación sobre adquisición adicional.", "Vigilar calidad y costo por alumno incremental."], skills: ["Funnel", "Crecimiento", "Priorización"] }),
  practiceCase({ slug: "entrada-nutrilago", title: "NutriLago entra a una nueva región", category: "Entrada a mercado", difficulty: "intermedio", client: "NutriLago", objective: "Decidir si lanzar bebidas vegetales en una región vecina.", prompt: "Un productor ficticio evalúa una expansión geográfica.", facts: ["Puede usar capacidad ociosa.", "Necesita un distribuidor local."], structure: ["Atractivo del mercado", "Capacidad para competir", "Economía", "Modo de entrada y riesgos"], exhibit: { title: "Tres segmentos", columns: ["Segmento", "Tamaño", "Crecimiento"], rows: [["Masivo", "$80 M", "2%"], ["Salud", "$35 M", "9%"], ["Profesional", "$15 M", "12%"]], summary: "Salud ofrece escala y crecimiento; profesional crece desde una base menor." }, calculation: { prompt: "Estima ventas si captura 6% de Salud.", answer: "$2,1 millones", explanation: "35×6%." }, brainstorm: "Compara entrada directa, distribuidor y piloto digital.", recommendation: "Decide si entrar y mediante qué modalidad.", insights: ["Tamaño no basta sin margen y distribución.", "Un piloto reduce irreversibilidad."], skills: ["Mercado", "Entrada", "Riesgo"] }),
  practiceCase({ slug: "inversion-frioazul", title: "La inversión de FríoAzul", category: "Inversión", difficulty: "intermedio", client: "FríoAzul", objective: "Decidir una nueva planta de almacenamiento refrigerado.", prompt: "Una empresa ficticia enfrenta demanda estacional y evalúa ampliar capacidad.", facts: ["La inversión es reversible solo parcialmente.", "Existe una alternativa de arriendo."], structure: ["Demanda y capacidad", "Economía", "Alternativas", "Riesgos y ejecución"], exhibit: { title: "Demanda y capacidad", columns: ["Periodo", "Demanda", "Capacidad"], rows: [["Bajo", "6.000", "8.000"], ["Medio", "8.500", "8.000"], ["Alto", "11.000", "8.000"]], summary: "El déficit se concentra en periodos medio y alto." }, calculation: { prompt: "Calcula déficit en periodo alto.", answer: "3.000 posiciones", explanation: "11.000−8.000." }, brainstorm: "¿Qué alternativas existen a construir toda la capacidad?", recommendation: "Compara construir, arrendar o combinar.", insights: ["La estacionalidad importa para utilización.", "Una solución flexible puede superar a una inversión completa."], skills: ["Capacidad", "Inversión", "Alternativas"] }),
  practiceCase({ slug: "operacion-rutaclara", title: "Las entregas de RutaClara", category: "Operaciones", difficulty: "introductorio", client: "RutaClara", objective: "Reducir atrasos sin elevar el costo total.", prompt: "Una distribuidora ficticia de libros tiene más entregas fuera de plazo.", facts: ["El volumen total creció 8%.", "Una zona concentra reclamos."], structure: ["Demanda", "Proceso", "Capacidad", "Rutas y proveedores", "Calidad y costo"], exhibit: { title: "Entrega por zona", columns: ["Zona", "A tiempo", "Costo/entrega"], rows: [["Norte", "91%", "$5,2"], ["Centro", "72%", "$6,8"], ["Sur", "89%", "$5,6"]], summary: "Centro tiene menor puntualidad y mayor costo." }, calculation: { prompt: "¿Cuántos atrasos hay en 2.000 entregas de Centro?", answer: "560", explanation: "2.000×(1−72%)." }, brainstorm: "Genera causas y soluciones para Centro.", recommendation: "Prioriza un diagnóstico y una intervención.", insights: ["La segmentación evita rediseñar toda la red.", "Costo y servicio deben analizarse juntos."], skills: ["Operaciones", "Segmentación", "Causa raíz"] }),
  practiceCase({ slug: "precio-nubecuenta", title: "El precio de NubeCuenta", category: "Pricing", difficulty: "avanzado", client: "NubeCuenta", objective: "Rediseñar precios manteniendo valor y retención.", prompt: "Un software ficticio para pymes evalúa subir su tarifa.", facts: ["Hay tres segmentos de uso.", "El costo marginal es bajo."], structure: ["Disposición a pagar", "Valor y uso", "Competencia", "Economía y churn", "Implementación"], exhibit: { title: "Respuesta esperada", columns: ["Segmento", "Alza", "Churn estimado"], rows: [["Básico", "10%", "12%"], ["Creciente", "10%", "4%"], ["Avanzado", "10%", "2%"]], summary: "La sensibilidad difiere materialmente por segmento." }, calculation: { prompt: "Con 1.000 clientes Básico a $20, calcula ingresos tras alza y churn.", answer: "$19.360", explanation: "1.000×88%×$22; antes eran $20.000." }, brainstorm: "Propón alternativas a un alza uniforme.", recommendation: "Diseña una estrategia segmentada.", insights: ["Una subida puede reducir ingresos en un segmento.", "Paquetes y migración pueden proteger valor."], skills: ["Pricing", "Elasticidad", "Segmentación"] }),
  practiceCase({ slug: "retencion-linguanube", title: "Las renovaciones de LinguaNube", category: "Retención", difficulty: "intermedio", client: "LinguaNube", objective: "Recuperar renovación anual de usuarios nuevos.", prompt: "Una aplicación ficticia para idiomas observa una baja de renovaciones.", facts: ["El precio no cambió.", "La caída afecta cohortes recientes."], structure: ["Calidad de adquisición", "Activación y uso", "Producto y servicio", "Competencia", "Renovación"], exhibit: { title: "Renovación por activación", columns: ["Funciones usadas", "Renovación"], rows: [["0–1", "42%"], ["2", "63%"], ["3+", "81%"]], summary: "La renovación aumenta con activación más profunda, sin probar causalidad." }, calculation: { prompt: "Diferencia entre 3+ y 0–1.", answer: "39 puntos porcentuales", explanation: "81%−42%." }, brainstorm: "Diseña acciones para el primer mes.", recommendation: "Propón un piloto y sus guardrails.", insights: ["Priorizar onboarding de cohortes nuevas.", "Probar causalidad antes de escalar."], skills: ["Retención", "Cohortes", "Hipótesis"] }),
  practiceCase({ slug: "tecnologia-civitas", title: "La plataforma de Civitas", category: "Tecnología", difficulty: "intermedio", client: "Civitas", objective: "Decidir si digitalizar un trámite ciudadano.", prompt: "Una institución ficticia evalúa una plataforma para permisos comerciales.", facts: ["Parte de la población tiene acceso digital limitado.", "La regulación exige revisión humana."], structure: ["Objetivo y usuarios", "Proceso actual", "Solución y factibilidad", "Adopción", "Economía, riesgo e implementación"], exhibit: { title: "Tiempo por etapa", columns: ["Etapa", "Días"], rows: [["Ingreso", "2"], ["Revisión", "14"], ["Corrección", "9"], ["Aprobación", "3"]], summary: "Revisión y corrección explican la mayor parte del plazo." }, calculation: { prompt: "Participación de revisión+corrección en el tiempo total.", answer: "82,1%", explanation: "23÷28." }, brainstorm: "¿Qué soluciones atacan la causa sin excluir usuarios?", recommendation: "Recomienda un alcance inicial.", insights: ["Digitalizar ingreso no resuelve el cuello principal.", "Mantener un canal asistido puede ser necesario."], skills: ["Tecnología", "Proceso", "Inclusión"] }),
  practiceCase({ slug: "billetera-lumina", title: "La activación de Billetera Lúmina", category: "Experimentación", difficulty: "avanzado", client: "Banco Lúmina", objective: "Aumentar primera transacción rentable dentro de 30 días.", prompt: "Un banco ficticio prueba un incentivo de activación para su billetera digital.", facts: ["Usuarios elegibles fueron asignados aleatoriamente.", "El guardrail de fraude se mantuvo estable."], structure: ["Funnel", "Diseño del test", "Incrementalidad", "Economía", "Escalabilidad"], exhibit: { title: "Resultado del test", columns: ["Grupo", "Usuarios", "Activación", "Utilidad por activado"], rows: [["Control", "10.000", "20%", "$18"], ["Incentivo", "10.000", "27%", "$9"]], summary: "La activación sube, pero el incentivo reduce utilidad por usuario activado." }, calculation: { prompt: "Calcula activaciones incrementales y utilidad incremental aproximada.", answer: "700 activaciones; la economía requiere comparar $24.300 tratados con $36.000 del control, por lo que es negativa en este horizonte.", explanation: "27%−20%=7 puntos; utilidad total 2.700×9 frente a 2.000×18." }, brainstorm: "Rediseña el incentivo por segmento o umbral.", recommendation: "Decide escalar, iterar o detener.", insights: ["Adopción bruta no basta.", "Iterar monto o targeting antes de escalar."], skills: ["Experimento", "Incrementalidad", "Economía"] }),
  practiceCase({ slug: "turnos-puente", title: "Los turnos de Puente Salud", category: "Sector público/social", difficulty: "introductorio", client: "Puente Salud", objective: "Reducir ausencias manteniendo acceso equitativo.", prompt: "Una red ficticia de atención primaria tiene horas perdidas por inasistencia.", facts: ["No todas las personas usan smartphone.", "La capacidad clínica es fija."], structure: ["Segmentos y causas", "Journey de la cita", "Intervenciones", "Capacidad", "Equidad y guardrails"], exhibit: { title: "Ausencia por canal", columns: ["Canal", "Citas", "Ausencia"], rows: [["Web", "4.000", "12%"], ["Teléfono", "3.000", "21%"], ["Presencial", "3.000", "18%"]], summary: "El canal telefónico tiene mayor tasa, pero no demuestra que el canal sea la causa." }, calculation: { prompt: "Calcula ausencias totales.", answer: "1.650", explanation: "480+630+540." }, brainstorm: "Diseña prevención, reprogramación y lista de espera.", recommendation: "Propón un piloto inclusivo.", insights: ["Investigar causas dentro de canal.", "Medir acceso además de asistencia."], skills: ["Impacto social", "Segmentación", "Guardrails"] }),
  practiceCase({ slug: "capacidad-talleruno", title: "La capacidad de TallerUno", category: "Capacidad", difficulty: "intermedio", client: "TallerUno", objective: "Atender más equipos sin ampliar instalaciones.", prompt: "Un servicio técnico ficticio enfrenta una lista de espera creciente.", facts: ["La demanda supera capacidad tres días a la semana.", "La calidad no puede caer."], structure: ["Demanda", "Capacidad teórica", "Utilización y productividad", "Cuello de botella", "Opciones y calidad"], exhibit: { title: "Proceso diario", columns: ["Etapa", "Capacidad"], rows: [["Diagnóstico", "48"], ["Reparación", "30"], ["Prueba", "42"]], summary: "Reparación limita el flujo a 30 equipos diarios." }, calculation: { prompt: "Con 20% más productividad en reparación, ¿cuál es el nuevo flujo máximo?", answer: "36 equipos diarios", explanation: "30×1,2; sigue bajo las otras etapas." }, brainstorm: "Genera opciones para el cuello de botella.", recommendation: "Elige un piloto con métrica de calidad.", insights: ["Mejorar etapas no limitantes no aumenta throughput.", "Revisar demanda y variabilidad además del promedio."], skills: ["Capacidad", "Cuello de botella", "Operaciones"] }),
  practiceCase({ slug: "alianza-sendasur", title: "La alianza de SendaSur", category: "M&A o alianza", difficulty: "avanzado", client: "SendaSur", objective: "Decidir una alianza con una red de puntos de retiro.", prompt: "Un comercio electrónico ficticio evalúa asociarse para ampliar cobertura.", facts: ["La adquisición completa no está disponible.", "El socio atiende otras plataformas."], structure: ["Valor estratégico", "Demanda y cliente", "Economía", "Capacidades y gobernanza", "Riesgo y alternativa"], exhibit: { title: "Economía por entrega", columns: ["Modalidad", "Costo", "Entrega exitosa"], rows: [["Domicilio", "$7,0", "88%"], ["Punto de retiro", "$4,2", "95%"]], summary: "El punto reduce costo y aumenta éxito, sujeto a adopción del cliente." }, calculation: { prompt: "Ahorro en 80.000 entregas migradas.", answer: "$224.000", explanation: "80.000×($7−$4,2)." }, brainstorm: "Define términos, gobernanza y riesgos de dependencia.", recommendation: "Recomienda alianza, piloto o no avanzar.", insights: ["El ahorro depende de migración real.", "La gobernanza y experiencia del cliente son parte de la decisión."], skills: ["Alianza", "Economía", "Gobernanza"] }),
];

practiceCases.push(
  practiceCase({ slug: "pagos-mercavia", title: "El checkout de Mercavía", category: "Experimentación", difficulty: "avanzado", client: "Pagos Prisma y Mercavía", objective: "Aumentar compras aprobadas con economía positiva.", prompt: "Una empresa ficticia de pagos y un marketplace ficticio evalúan rediseñar checkout.", facts: ["La regulación y la integración cambian por país.", "El piloto cubre compradores recurrentes."], structure: ["Mercado y dolor", "Funnel y aprobación", "Test y control", "Fraude y economía", "Integración y escala"], exhibit: { title: "Piloto de checkout", columns: ["Grupo", "Conversión", "Fraude", "Margen/orden"], rows: [["Control", "62%", "0,8%", "$4,8"], ["Nuevo", "66%", "1,1%", "$4,5"]], summary: "La conversión mejora y también aumenta fraude; la decisión requiere utilidad incremental." }, calculation: { prompt: "En 50.000 intentos, ¿cuántas órdenes adicionales produce el nuevo flujo?", answer: "2.000", explanation: "50.000×(66%−62%)." }, brainstorm: "Diseña pruebas de credenciales tokenizadas, herramientas para vendedores y prevención de fraude.", recommendation: "Propón diagnóstico, piloto y condición de escala.", insights: ["La conversión no debe separarse de fraude y margen.", "Una entrada por fases reduce riesgo de integración."], skills: ["Pagos", "Experimentación", "Riesgo"] }),
  practiceCase({ slug: "ingresos-nexoempresas", title: "Los ingresos de NexoEmpresas", category: "Experimentación", difficulty: "intermedio", client: "NexoEmpresas", objective: "Explicar la caída de ingresos y probar una recuperación focalizada.", prompt: "Un emisor corporativo ficticio observa menor ingreso por pagos empresariales.", facts: ["No hubo cambio contable.", "Dos industrias concentran la caída."], structure: ["Volumen de pagos", "Take rate neto", "Segmentos", "Causas y sustitución", "Pruebas"], exhibit: { title: "Árbol de ingreso", columns: ["Métrica", "Antes", "Ahora"], rows: [["Clientes activos", "2.000", "1.900"], ["Transacciones/cliente", "50", "46"], ["Ticket", "$180", "$175"], ["Take rate", "1,2%", "1,1%"]], summary: "Todos los impulsores se deterioran; hace falta cuantificar contribuciones y segmentar." }, calculation: { prompt: "Calcula ingreso actual mensual aproximado.", answer: "$168.245", explanation: "1.900×46×$175×1,1%." }, brainstorm: "Propón pruebas para recuperar frecuencia sin incentivos generalizados.", recommendation: "Elige el driver prioritario y un test.", insights: ["Revenue = volumen×take rate.", "La recomendación depende del driver por segmento."], skills: ["Driver tree", "Segmentación", "Experimentos"] }),
  practiceCase({ slug: "cashback-mercadalia", title: "El cashback de Mercadalia", category: "Experimentación", difficulty: "avanzado", client: "Mercadalia", objective: "Decidir si escalar una promoción de cashback.", prompt: "Un retailer ficticio y su socio de pagos observan mayor venta durante una promoción.", facts: ["La asignación fue por zonas comparables.", "Existe posible adelanto de compras."], structure: ["Diseño y comparabilidad", "Incrementalidad", "Margen e incentivo", "Segmentos y repetición", "Rediseño"], exhibit: { title: "Resultado por 10.000 clientes", columns: ["Grupo", "Ventas", "Margen bruto", "Incentivo"], rows: [["Control", "$1,00 M", "$300.000", "$0"], ["Cashback", "$1,16 M", "$348.000", "$70.000"]], summary: "El margen bruto incremental es $48.000, menor al incentivo de $70.000." }, calculation: { prompt: "Calcula utilidad incremental antes de otros costos.", answer: "−$22.000", explanation: "$348.000−$300.000−$70.000." }, brainstorm: "Rediseña monto, umbral, categorías, segmentos y horizonte.", recommendation: "Decide escalar, iterar o detener.", insights: ["Crecimiento de ventas puede destruir utilidad incremental.", "Targeting y seguimiento de repetición pueden cambiar la economía."], skills: ["Cashback", "Incrementalidad", "Utilidad"] }),
);

export const getPracticeCase = (slug) => practiceCases.find((item) => item.slug === slug);

export const caseResources = [
  { id: "case-cheat-sheet", title: "Cheat sheet de entrevista de caso", contentType: "template", status: "published", description: "Secuencia compacta desde apertura hasta recomendación.", reminder: "Adáptala al formato y no la leas como un guion.", template: "APERTURA\nReformula y alinea objetivo.\n\nACLARAR\nPregunta solo lo que cambia el análisis.\n\nHIPÓTESIS\nDeclara una dirección provisional.\n\nESTRUCTURA\nExplica ramas y prioridad.\n\nANÁLISIS\nFórmula, unidades, evidencia e implicación.\n\nSÍNTESIS\nHallazgo → implicación → siguiente paso.\n\nRECOMENDACIÓN\nDecisión → razones → riesgo → próximo paso." },
  { id: "clarifying-checklist", title: "Checklist de preguntas aclaratorias", contentType: "checklist", status: "published", description: "Comprueba si entendiste la decisión antes de estructurar.", reminder: "No necesitas formular todas las preguntas.", groups: [{ title: "Información esencial", items: ["Cliente y decisor", "Decisión", "Métrica de éxito", "Alcance", "Plazo", "Restricciones", "Economía", "Términos ambiguos"] }] },
  { id: "structure-worksheet", title: "Hoja para estructurar un caso", contentType: "worksheet", status: "published", description: "Ordena objetivo, hipótesis, ramas y prioridad.", reminder: "La hoja no guarda ni envía lo que escribes.", fields: ["Objetivo", "Métrica", "Hipótesis", "Ramas", "Prioridad", "Datos necesarios", "Riesgos"] },
  { id: "formula-sheet", title: "Hoja de fórmulas", contentType: "template", status: "published", description: "Fórmulas esenciales con recordatorios de interpretación.", reminder: "Confirma definición, horizonte y unidades antes de usar una fórmula.", template: "INGRESOS = Precio × Volumen\nCOSTOS = Fijos + Variable unitario × Volumen\nUTILIDAD = Ingresos − Costos\nMARGEN = Utilidad ÷ Ingresos\nCRECIMIENTO = (Nuevo − Anterior) ÷ Anterior\nPARTICIPACIÓN = Ventas propias ÷ Mercado\nEQUILIBRIO = Fijos ÷ (Precio − Variable unitario)\nROI SIMPLE = Beneficio neto incremental ÷ Inversión\nPAYBACK SIMPLE = Inversión ÷ Flujo anual\nPROMEDIO PONDERADO = Σ(valor × peso)\nIMPACTO INCREMENTAL = Tratado − Contrafactual estimado\n\nLimitaciones: ROI y payback pueden definirse de otra forma; un antes/después no prueba causalidad." },
  { id: "exhibit-checklist", title: "Checklist para analizar exhibits", contentType: "checklist", status: "published", description: "Pasa de etiquetas a insight y siguiente pregunta.", reminder: "Incluye siempre la implicación para la decisión.", groups: [{ title: "Lectura", items: ["Título", "Ejes", "Unidades", "Periodo", "Segmentos", "Patrón", "Insight", "Implicación", "Siguiente pregunta"] }] },
  { id: "brainstorming-sheet", title: "Prompts de brainstorming", contentType: "template", status: "published", description: "Lentes para generar alternativas sin producir una lista plana.", reminder: "Elige pocas categorías y prioriza.", template: "INGRESOS: clientes, frecuencia, ticket, mix\nCOSTOS: personas, compras, tecnología, logística\nCRECIMIENTO: producto, canal, geografía, retención\nCLIENTE: awareness, valor, onboarding, confianza\nOPERACIONES: proceso, capacidad, calidad, gobernanza\nRIESGO: prevención, detección, respuesta\nTECNOLOGÍA: usuario, datos, integración, adopción\nIMPLEMENTACIÓN: piloto, responsables, secuencia, métricas" },
  { id: "recommendation-template", title: "Plantilla de recomendación", contentType: "worksheet", status: "published", description: "Construye un cierre ejecutivo breve.", reminder: "Responde primero y evita introducir hechos nuevos.", fields: ["Decisión", "Dos o tres evidencias", "Riesgo principal", "Próximo paso", "Condición que cambiaría la respuesta"] },
  { id: "case-taxonomy", title: "Referencia de tipos de casos", contentType: "template", status: "published", description: "Mapa flexible de categorías y preguntas centrales.", reminder: "Los casos pueden combinar varias categorías.", template: "DIAGNÓSTICO: ¿qué causa el resultado?\nCRECIMIENTO: ¿cómo crecer o mejorar?\nENTRADA: ¿conviene entrar?\nINVERSIÓN: ¿conviene asignar recursos?\nOPERACIONES: ¿cómo mejorar capacidad o eficiencia?\nCOMERCIAL: ¿cómo capturar valor?\nCLIENTE: ¿qué necesita y cómo se comporta?\nTECNOLOGÍA: ¿cómo crear valor de negocio?\nEXPERIMENTACIÓN: ¿qué valor fue incremental?" },
  { id: "experiment-template", title: "Plantilla de experimentación", contentType: "worksheet", status: "published", description: "Conecta decisión, diseño, incrementalidad y economía.", reminder: "No demuestra validez estadística.", fields: ["Decisión", "Población", "Hipótesis", "Tratamiento", "Control", "KPI", "Guardrails", "Incrementalidad", "Economía", "Decisión de escala"] },
  { id: "case-practice-log", title: "Tracker de práctica", contentType: "tool", status: "published", description: "Registra prácticas y convierte feedback en un drill.", reminder: "Funciona durante la sesión del navegador y no envía datos.", href: "/herramientas/seguimiento-practica-casos" },
  { id: "case-behavioral-bank", title: "Banco de historias conductuales", contentType: "worksheet", status: "published", description: "Mapea decisiones y evidencia a competencias.", reminder: "No copies datos confidenciales ni memorices texto completo.", fields: ["Competencia", "Contexto", "Responsabilidad", "Decisión", "Acción personal", "Resultado", "Aprendizaje", "Preguntas de seguimiento"] },
  { id: "candidate-question-bank", title: "Preguntas del candidato", contentType: "template", status: "published", description: "Preguntas para investigar trabajo, equipo y desarrollo.", reminder: "Elige preguntas que no estén resueltas en información pública.", template: "TRABAJO: ¿Qué decisiones ocupa más tiempo al inicio?\nEQUIPO: ¿Cómo se comparte feedback durante un proyecto?\nOFICINA: ¿Qué distingue la colaboración local?\nDESARROLLO: ¿Cómo evoluciona la responsabilidad el primer año?\nCLIENTE: ¿Cómo cambia la exposición según el rol?\nCASOS: ¿Qué tipos de problemas son frecuentes en esta práctica?\nÉXITO: ¿Qué conducta distingue un buen primer año?\nESPECIALIZACIÓN: ¿Cómo se exploran áreas?\nEXPERIMENTACIÓN: ¿Cómo conviven asesoría y pruebas en terreno?" },
  { id: "case-practice-rubric", title: "Rúbrica cualitativa de práctica", contentType: "checklist", status: "published", description: "Evalúa dimensiones sin convertirlas en probabilidad de contratación.", reminder: "Usa niveles: fundamentos, desarrollo, consistente y listo en esta dimensión.", groups: [{ title: "Dimensiones", items: ["Objetivo", "Preguntas", "Estructura", "Priorización", "Hipótesis", "Cálculo", "Exhibits", "Juicio", "Ideas", "Síntesis", "Recomendación", "Comunicación", "Colaboración", "Presencia"] }] },
  { id: "case-readiness", title: "Diagnóstico de preparación para casos", contentType: "diagnostic", status: "published", description: "Selecciona la dimensión que hoy limita tu desempeño.", reminder: "No calcula probabilidad de éxito.", question: "¿Qué dimensión necesita una evidencia nueva?", options: ["Reformulación", "Objetivo", "Estructura", "Cálculo", "Exhibits", "Síntesis", "Recomendación", "Feedback", "Historias", "Variedad de casos"].map((label) => ({ label, action: `Realiza un drill de ${label.toLowerCase()}, registra el error dominante y solicita feedback específico.` })) },
  { id: "market-sizing-sheet", title: "Hoja de market sizing", contentType: "worksheet", status: "published", description: "Documenta salida, ecuación, supuestos y controles.", reminder: "Los supuestos son ilustrativos, no datos de mercado.", fields: ["Pregunta", "Unidad y horizonte", "Enfoque", "Ecuación", "Supuestos", "Cálculo", "Rango", "Sanity check", "Implicación"] },
];

export const getCaseResource = (id) => caseResources.find((item) => item.id === id);
