import { useEffect, useMemo, useState } from "react";
import { ArrowRight, Play, Printer, RotateCcw, Sparkles } from "lucide-react";
import { trackEvent } from "./analytics";
import { Breadcrumbs, CopyToClipboard, PageShell } from "./LearningComponents";
import { buildCaseStructure, buildExperiment, nextSizingPrompt, sizingPrompts } from "./caseTools";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const configs = {
  sizing: { title: "Práctica de market sizing", description: "Genera prompts originales, documenta supuestos y compara tu lógica con una estructura modelo.", path: "/herramientas/practica-market-sizing" },
  experiment: { title: "Diseñador de experimentos de negocio", description: "Convierte una decisión en un brief de experimento con comparación, métricas, economía y alertas.", path: "/herramientas/disenador-experimentos-negocio" },
  structure: { title: "Constructor de estructuras de caso", description: "Crea una plantilla editable y preguntas analíticas sin tratar un framework como respuesta correcta.", path: "/herramientas/constructor-estructuras-caso" },
  tracker: { title: "Seguimiento de práctica de casos", description: "Registra feedback durante esta sesión y define el próximo ejercicio correctivo.", path: "/herramientas/seguimiento-practica-casos" },
};

export default function CaseToolsPage({ kind }) {
  const config = configs[kind];
  const breadcrumbs = [{ label: "Inicio", href: "/" }, { label: "Herramientas", href: "/herramientas" }, { label: config.title, href: config.path }];
  const schema = useMemo(() => ({ "@context": "https://schema.org", "@graph": [{ "@type": "BreadcrumbList", itemListElement: breadcrumbSchema(breadcrumbs).itemListElement }, { "@type": "WebApplication", name: config.title, description: config.description, applicationCategory: "EducationalApplication", operatingSystem: "Web", url: `https://masanes.cl${config.path}` }] }), [kind]);
  usePageMetadata({ title: config.title, description: config.description, path: config.path, schema });
  useEffect(() => trackEvent("case_tool_opened", { tool: kind }), [kind]);
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs} /><header className="page-hero"><div><p className="eyebrow">Herramienta local</p><h1>{config.title}</h1><p className="page-hero__lead">{config.description}</p><p>No requiere cuenta, API externa ni envío de respuestas personales.</p></div></header>{kind === "sizing" && <SizingTool />}{kind === "experiment" && <ExperimentTool />}{kind === "structure" && <StructureTool />}{kind === "tracker" && <TrackerTool />}<aside className="contextual-cta"><div><h2>Continúa aprendiendo</h2><p>Revisa la explicación, ejemplos y recursos antes de convertir velocidad en tu objetivo principal.</p></div><a className="button button--primary" href="/aprende/consultoria/entrevistas-de-caso">Volver a Entrevistas de caso <ArrowRight size={16} /></a></aside></main></PageShell>;
}

function Field({ name, label, values, setValues, errors = {}, rows = 2 }) {
  return <label className="field" htmlFor={`field-${name}`}><span>{label}</span><textarea id={`field-${name}`} rows={rows} value={values[name] || ""} aria-invalid={Boolean(errors[name])} aria-describedby={errors[name] ? `error-${name}` : undefined} onChange={(event) => setValues((current) => ({ ...current, [name]: event.target.value }))} />{errors[name] && <small className="field-error" id={`error-${name}`}>{errors[name]}</small>}</label>;
}

function ToolActions({ onReset, children }) { return <div className="form-actions">{children}<button type="button" className="button button--secondary" onClick={onReset}><RotateCcw size={16} />Limpiar</button></div>; }

function SizingTool() {
  const categories = ["Todas", ...new Set(sizingPrompts.map((item) => item.category))];
  const [category, setCategory] = useState("Todas"); const [version, setVersion] = useState(0); const [prompt, setPrompt] = useState(() => nextSizingPrompt("Todas"));
  const [values, setValues] = useState({ assumptions: "", equation: "", calculation: "", implication: "" }); const [revealed, setRevealed] = useState(false); const [timerOn, setTimerOn] = useState(false); const [seconds, setSeconds] = useState(0);
  useEffect(() => { if (!timerOn) return; const id = setInterval(() => setSeconds((value) => value + 1), 1000); return () => clearInterval(id); }, [timerOn]);
  const another = () => { const next = version + 1; setVersion(next); setPrompt(nextSizingPrompt(category, next)); setRevealed(false); setSeconds(0); trackEvent("market_sizing_used", { tool: "sizing" }); };
  return <section className="generator-layout"><div className="generator-form"><label className="field">Categoría<select value={category} onChange={(event) => { setCategory(event.target.value); setPrompt(nextSizingPrompt(event.target.value, 0)); }}>{categories.map((item) => <option key={item}>{item}</option>)}</select></label><article className="tool-prompt"><p className="eyebrow">Prompt</p><h2>{prompt.prompt}</h2></article><div className="timer-controls"><button type="button" className="button button--secondary" onClick={() => setTimerOn((value) => !value)}><Play size={16} />{timerOn ? "Pausar" : "Iniciar"} timer</button><span aria-live="polite">{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, "0")}</span></div><Field name="assumptions" label="Supuestos" values={values} setValues={setValues} rows={4} /><Field name="equation" label="Ecuación" values={values} setValues={setValues} /><Field name="calculation" label="Cálculo con unidades" values={values} setValues={setValues} rows={4} /><Field name="implication" label="Interpretación" values={values} setValues={setValues} /><ToolActions onReset={() => { setValues({ assumptions: "", equation: "", calculation: "", implication: "" }); setSeconds(0); setTimerOn(false); }}><button className="button button--primary" type="button" onClick={another}><Sparkles size={16} />Otro prompt</button></ToolActions></div><aside className="generator-output"><h2>Autoevaluación</h2><label className="check-row"><input type="checkbox" />Definí unidad, geografía y horizonte</label><label className="check-row"><input type="checkbox" />Explicité supuestos</label><label className="check-row"><input type="checkbox" />Mantuve unidades</label><label className="check-row"><input type="checkbox" />Hice sanity check</label><button className="button button--secondary" type="button" onClick={() => setRevealed(true)}>Revelar estructura modelo</button>{revealed && <div className="lesson-callout" aria-live="polite"><h3>Una estructura posible</h3><p>{prompt.structure}</p><p>Puede haber otros enfoques válidos.</p></div>}</aside></section>;
}

const experimentInitial = { decision: "", population: "", hypothesis: "", treatment: "", control: "", kpi: "", guardrails: "", duration: "", cost: "", benefit: "", constraints: "" };
function ExperimentTool() {
  const [values, setValues] = useState(experimentInitial); const [result, setResult] = useState({ errors: {}, output: "", warnings: [] });
  const labels = { decision: "Decisión de negocio *", population: "Población objetivo *", hypothesis: "Hipótesis *", treatment: "Tratamiento *", control: "Control o comparación *", kpi: "KPI principal *", guardrails: "Guardrails", duration: "Duración", cost: "Costo esperado", benefit: "Beneficio esperado", constraints: "Restricciones operativas" };
  return <section className="generator-layout"><form className="generator-form" onSubmit={(event) => { event.preventDefault(); const next = buildExperiment(values); setResult(next); if (next.output) trackEvent("experiment_tool_used", { tool: "experiment" }); }}>{Object.keys(labels).map((name) => <Field key={name} name={name} label={labels[name]} values={values} setValues={setValues} errors={result.errors} />)}<ToolActions onReset={() => { setValues(experimentInitial); setResult({ errors: {}, output: "", warnings: [] }); }}><button className="button button--primary" type="submit"><Sparkles size={16} />Construir brief</button></ToolActions></form><aside className="generator-output" aria-live="polite"><h2>Brief del experimento</h2>{result.output ? <><pre className="template-preview">{result.output}</pre><CopyToClipboard text={result.output} label="Copiar brief" /><button type="button" className="button button--secondary" onClick={() => window.print()}><Printer size={16} />Imprimir</button>{result.warnings.length > 0 && <div className="lesson-callout"><h3>Información pendiente</h3><ul>{result.warnings.map((warning) => <li key={warning}>{warning}</li>)}</ul></div>}<p className="output-reminder">Revisa selección, contaminación, estacionalidad, spillover, comparabilidad y capacidad de muestra. Esto no valida significancia estadística.</p></> : <p>Completa los campos esenciales para construir un brief local.</p>}</aside></section>;
}

const structureInitial = { type: "Rentabilidad", client: "", objective: "", metric: "", industry: "", geography: "", horizon: "", constraints: "", facts: "" };
function StructureTool() {
  const [values, setValues] = useState(structureInitial); const [result, setResult] = useState({ errors: {}, branches: [], questions: [] }); const [editedBranches, setEditedBranches] = useState([]);
  const text = editedBranches.length ? `OBJETIVO\n${values.objective}\nMÉTRICA\n${values.metric}\n\nRAMAS EDITABLES\n${editedBranches.map((item, i) => `${i + 1}. ${item}`).join("\n")}\n\nPREGUNTAS\n${result.questions.map((item) => `- ${item}`).join("\n")}` : "";
  return <section className="generator-layout"><form className="generator-form" onSubmit={(event) => { event.preventDefault(); const next = buildCaseStructure(values); setResult(next); setEditedBranches(next.branches); if (next.branches.length) trackEvent("structure_builder_used", { tool: "structure" }); }}><label className="field">Tipo de caso *<select value={values.type} onChange={(event) => setValues((current) => ({ ...current, type: event.target.value }))}>{["Rentabilidad", "Crecimiento", "Entrada a mercado", "Operaciones", "Experimentación"].map((item) => <option key={item}>{item}</option>)}</select></label>{[["client","Cliente *"],["objective","Objetivo *"],["metric","Métrica de éxito *"],["industry","Industria"],["geography","Geografía"],["horizon","Horizonte"],["constraints","Restricciones"],["facts","Hechos conocidos"]].map(([name,label]) => <Field key={name} name={name} label={label} values={values} setValues={setValues} errors={result.errors} />)}<ToolActions onReset={() => { setValues(structureInitial); setResult({ errors: {}, branches: [], questions: [] }); setEditedBranches([]); }}><button className="button button--primary" type="submit"><Sparkles size={16} />Crear plantilla</button></ToolActions></form><aside className="generator-output" aria-live="polite"><h2>Estructura editable</h2>{text ? <><div className="worksheet-grid">{editedBranches.map((branch, index) => <label key={index}>Rama {index + 1}<textarea value={branch} rows="2" onChange={(event) => setEditedBranches((current) => current.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} /></label>)}</div><h3>Preguntas sugeridas</h3><ul>{result.questions.map((question) => <li key={question}>{question}</li>)}</ul><CopyToClipboard text={text} label="Copiar estructura" /><button type="button" className="button button--secondary" onClick={() => window.print()}><Printer size={16} />Imprimir</button><p className="output-reminder">La estructura debe adaptarse al caso. No utilices todas las categorías ni la trates como una respuesta correcta.</p></> : <p>Describe el caso para obtener una plantilla inicial, no una solución.</p>}</aside></section>;
}

const trackerInitial = { date: "", title: "", category: "", partner: "", format: "", duration: "", strength: "", weakness: "", arithmetic: "", missed: "", feedback: "", drill: "", next: "", confidence: "" };
function TrackerTool() {
  const [values, setValues] = useState(trackerInitial); const [entries, setEntries] = useState([]); const required = !values.date || !values.title || !values.drill;
  const labels = { date: "Fecha *", title: "Título del caso *", category: "Categoría", partner: "Compañero o entrevistador", format: "Formato", duration: "Duración", strength: "Fortaleza principal", weakness: "Debilidad principal", arithmetic: "Errores aritméticos", missed: "Insight omitido", feedback: "Feedback", drill: "Drill correctivo *", next: "Próxima práctica", confidence: "Confianza cualitativa" };
  const summary = entries.map((entry, i) => `PRÁCTICA ${i + 1}\n${Object.entries(labels).map(([key,label]) => `${label.replace(" *", "")}: ${entry[key] || "—"}`).join("\n")}`).join("\n\n");
  return <section className="generator-layout"><form className="generator-form" onSubmit={(event) => { event.preventDefault(); if (required) return; setEntries((current) => [...current, values]); setValues(trackerInitial); trackEvent("case_practice_completed", { tool: "tracker" }); }}>{Object.entries(labels).map(([name,label]) => <Field key={name} name={name} label={label} values={values} setValues={setValues} />)}{required && <p className="output-reminder">Fecha, título y drill correctivo son obligatorios.</p>}<ToolActions onReset={() => setValues(trackerInitial)}><button className="button button--primary" type="submit" disabled={required}>Agregar práctica</button></ToolActions></form><aside className="generator-output" aria-live="polite"><h2>Prácticas de esta sesión</h2><p className="output-reminder">La información vive solo en el estado temporal de esta página. No se guarda, no se envía y desaparecerá al recargar.</p>{entries.length ? <><ol>{entries.map((entry, index) => <li key={`${entry.date}-${index}`}><strong>{entry.title}</strong><p>{entry.date} · {entry.category || "Sin categoría"}</p><p>Próximo drill: {entry.drill}</p></li>)}</ol><CopyToClipboard text={summary} label="Copiar registro" /><button type="button" className="button button--secondary" onClick={() => window.print()}><Printer size={16} />Imprimir</button><button type="button" className="text-button" onClick={() => setEntries([])}>Borrar sesión</button></> : <p>Añade una práctica para ver el registro.</p>}</aside></section>;
}
