const updatedAt = "2026-07-15";
const base = "/aprende/comunicacion-profesional";

const audienceCases = [
  ["Demora de producto","Una responsable de producto debe explicar una demora al equipo comercial.","Ventas necesita anticipar conversaciones con clientes; producto conoce dependencias técnicas todavía inciertas."],
  ["Nueva evaluación","Un profesor presenta una evaluación distinta al curso.","El grupo necesita comprender criterios, propósito y vías para resolver dudas."],
  ["Recomendación al cliente","Una consultora expone una recomendación ante dirección y equipo operativo.","Quien decide quiere impacto; quien implementa necesita capacidad, secuencia y riesgos."],
  ["Cambio de carga","Una jefatura redistribuye trabajo durante un mes.","Las personas afectadas necesitan límites, prioridades y un espacio para corregir supuestos."],
  ["Solicitud de datos","Un analista pide a otra área mejorar un registro.","El área receptora conoce el proceso y soportará el costo del cambio."],
].map(([title,text,detail])=>({title,text:`${text} ${detail} Identifica audiencia, hechos, supuestos, intereses, preguntas, canal y qué verificar.`}));

const listeningDialogues = [
  ["Alcance cambiante","“Cada semana aparece una solicitud nueva.”","¿Qué solicitudes cambiaron el resultado o la fecha?"],
  ["Sobrecarga","“No puedo asumir otra tarea ahora.”","¿Qué compromisos actuales limitan la capacidad y qué podría repriorizarse?"],
  ["Dato dudoso","“El tablero nunca coincide con mi reporte.”","¿En qué indicador y período observas la diferencia?"],
  ["Cliente incómodo","“La propuesta no responde a lo que pedimos.”","¿Qué necesidad quedó fuera o recibió una respuesta insuficiente?"],
  ["Decisión lenta","“Seguimos conversando y nadie decide.”","¿Quién tiene autoridad y qué evidencia le falta?"],
  ["Reunión virtual","“Creo que estamos mezclando dos problemas.”","¿Cuáles serían esos dos problemas y cuál debemos resolver hoy?"],
  ["Feedback ambiguo","“La presentación debe ser más ejecutiva.”","¿Qué decisión o nivel de detalle debería priorizar la próxima versión?"],
  ["Desacuerdo técnico","“Esa alternativa es demasiado riesgosa.”","¿Qué riesgo consideras dominante y qué evidencia permitiría compararlo?"],
].map(([title,quote,response])=>({title,text:`Situación ficticia: ${quote} Una respuesta posible es: “${response}”. Distingue lo oído, lo supuesto, lo que falta aclarar y una siguiente pregunta.`}));

const purposeExercises = ["Iniciar el proyecto","Actualizar ventas","Dar feedback","Pedir presupuesto","Realizar un taller con cliente","Coordinar un trabajo universitario","Conversar sobre contratación","Revisar un lanzamiento"].map((title)=>({title,text:`Objetivo débil: “Hablar sobre ${title.toLowerCase()}”. Reescríbelo con Finalidad, Interés compartido y Next step; delimita lo que no se resolverá.`}));

const insightExercises = ["Renovaciones de clientes","Incorporación de personal","Citas hospitalarias","Finalización de cursos","Errores de inventario","Embudo comercial","Uso de billetera digital","Demora de proyecto","Participación en servicio público","Postulaciones universitarias"].map((title,index)=>({title,text:`Datos ficticios ${index+1}: el indicador cambia, pero la variación se concentra en un segmento y existe una posible diferencia de medición. Identifica hallazgo, insight, consecuencia, recomendación y evidencia faltante.`}));

const structureExercises = ["Correo extenso","Actualización ejecutiva","Notas de reunión","Estado de proyecto","Explicación técnica","Presentación universitaria","Mensaje de feedback","Recomendación de producto","Solicitud de fondos","Escalamiento de riesgo"].map((title)=>({title,text:`Reestructura “${title}” con un mensaje principal, dos razones comparables, evidencia, objeción y llamado. Prueba una versión directa y otra con contexto mínimo primero.`}));

const narrativeExercises = ["Explicar una demora","Recomendar un piloto tecnológico","Presentar un problema de retención","Comunicar un cambio organizacional","Solicitar recursos","Explicar un modelo analítico"].map((title)=>({title,text:`${title}: define audiencia, crea una narrativa CAMBIO, elige un trabajo visual, escribe un título conclusivo y termina con una acción proporcionada a la evidencia.`}));

const meetingExercises = ["Inicio de proyecto","Priorización presupuestaria","Taller con cliente","Retrospectiva","Decisión de producto","Conflicto entre áreas","Reunión universitaria","Sesión sobre un cambio"].map((title)=>({title,text:`${title}: escribe propósito, apertura, dos preguntas de foco, método de participación, cierre y respuesta ante una dinámica difícil.`}));

export const communicationScenarios = [
  ["actualizacion-ejecutiva","Un riesgo que requiere decisión","Actualización ejecutiva","intermedio","La fecha crítica depende de elegir qué entregable posponer."],
  ["correo-dificil","Rechazo de una solicitud urgente","Correo difícil","intermedio","Explicar un límite y ofrecer una alternativa viable."],
  ["recomendacion-cliente","Piloto para Red Alba","Recomendación a cliente","avanzado","Recomendar un piloto acotado con condiciones."],
  ["feedback","Conversación sobre coordinación","Conversación de feedback","intermedio","Acordar una conducta observable sin atribuir intención."],
  ["anuncio-cambio","Nuevo proceso de turnos","Anuncio de cambio","intermedio","Informar qué cambia, por qué y cómo resolver dudas."],
  ["escalamiento","Dependencia bloqueada","Escalamiento de proyecto","avanzado","Solicitar una decisión sin dramatizar el riesgo."],
  ["datos","Uso móvil en Aula Litoral","Presentación de datos","intermedio","Convertir tres indicadores en una implicación."],
  ["presupuesto","Capacidad para atención","Solicitud de presupuesto","avanzado","Pedir recursos mostrando alternativas y consecuencias."],
  ["facilitacion","Prioridades de trimestre","Facilitación de reunión","avanzado","Cerrar una prioridad entre tres áreas."],
  ["virtual","Demostración remota","Presentación virtual","introductorio","Explicar una función y recoger preguntas en línea."],
  ["conflicto","Ventas y operaciones","Conflicto entre departamentos","avanzado","Reformular posiciones como criterios y evidencia."],
  ["apoyo","Solicitud de revisión","Solicitud de apoyo","introductorio","Pedir una revisión delimitada con fecha y contexto."],
  ["ensenanza","Explicar una correlación","Enseñar un concepto complejo","intermedio","Diferenciar relación estadística y causalidad."],
  ["memo","Elegir proveedor","Memo de decisión","avanzado","Comparar opciones, condiciones y recomendación."],
  ["tiempo","Recomendación en tres minutos","Presentación con tiempo limitado","intermedio","Priorizar mensaje, evidencia y solicitud."],
].map(([slug,title,category,difficulty,purpose],index)=>({
  slug,title,category,difficulty,fictional:true,context:`Escenario ficticio ${index+1}: un equipo debe comunicar una decisión con información incompleta.`,audience:["Persona que decide","Persona que implementa","Persona afectada"],purpose,channel:index%3===0?"Reunión":index%3===1?"Correo":"Presentación",constraints:["Tiempo limitado","Incertidumbre visible"],evidence:["Registro interno","Perspectiva de usuarios","Supuesto todavía no verificado"],draftMessage:"Hay varios temas que revisar y necesitamos conversar.",learnerTask:["Mapear audiencia","Definir FIN","Sintetizar con DICA","Estructurar con NÚCLEO","Cerrar con acción"],modelResponse:`La recomendación es avanzar solo con el siguiente paso verificable. La evidencia disponible orienta esta opción, pero la incertidumbre declarada exige una revisión antes de ampliarla.`,explanation:["Abre con la decisión o el propósito.","Separa evidencia de interpretación.","Adapta detalle y participación a la audiencia."],skills:["Audiencia","Síntesis","Estructura","Cierre"]
}));

export const communicationResources = [
  {id:"marea",title:"Tarjeta MAREA",description:"Prepara audiencia, propósito, estructura, interacción y acuerdos.",contentType:"worksheet",status:"published",fields:["Mirar a la audiencia","Acordar el propósito","Reducir y estructurar","Expresar e interactuar","Aterrizar acuerdos"],reminder:"Úsala como orientación adaptable, no como guion rígido."},
  {id:"audience-map",title:"Mapa de audiencia",description:"Separa conocimiento, posición, interés, autoridad y supuestos.",contentType:"worksheet",status:"published",fields:["Rol","Conocimiento","Posición","Intereses","Qué está en juego","Inquietudes","Autoridad","Supuestos por verificar"],reminder:"No uses el rol para inferir personalidad o emociones."},
  {id:"capta",title:"Checklist CAPTA",description:"Revisa conductas observables de escucha.",contentType:"checklist",status:"published",groups:[{title:"Escucha activa",items:["Concentré mi atención","Aclaré términos","Parafraseé el significado","Tensioné con respeto","Acordé lo entendido"]}],reminder:"No mide empatía ni personalidad."},
  {id:"fin",title:"Hoja FIN",description:"Define finalidad, interés compartido y siguiente paso.",contentType:"worksheet",status:"published",fields:["Finalidad","Interés compartido","Next step","Tiempo","Fuera de alcance"],reminder:"Un propósito compartido no exige intereses idénticos."},
  {id:"data-insight",title:"De datos a insight",description:"Distingue observación, patrón, significado y acción.",contentType:"worksheet",status:"published",fields:["Dato","Información","Hallazgo","Insight","Recomendación","Incertidumbre"],reminder:"Etiqueta la interpretación como tal."},
  {id:"dica",title:"Tarjeta DICA",description:"Conecta hallazgo, interpretación, consecuencia y acción.",contentType:"worksheet",status:"published",fields:["Dato o hallazgo","Interpretación","Consecuencia","Acción o pregunta"],reminder:"La acción debe ser proporcional a la evidencia."},
  {id:"nucleo",title:"Hoja NÚCLEO",description:"Ordena mensaje, relevancia, razones, evidencia y llamado.",contentType:"worksheet",status:"published",fields:["Núcleo","Utilidad","Cimientos","Evidencia","Llamado","Objeciones"],reminder:"No ocultes riesgos importantes para simplificar."},
  {id:"cambio",title:"Hoja CAMBIO",description:"Construye una narrativa profesional sin fabricar dramatismo.",contentType:"worksheet",status:"published",fields:["Contexto","Alteración","Motivo","Insight","Giro","Outcome"],reminder:"No presentes ficción o expectativa como hecho."},
  {id:"visual-guide",title:"Guía de selección visual",description:"Elige una representación por el trabajo que debe realizar.",contentType:"template",status:"published",template:"OBJETIVO\n\n¿COMPARAR? Barras o tabla\n¿MOSTRAR CAMBIO? Línea o antes/después\n¿MOSTRAR DISTRIBUCIÓN? Histograma o puntos\n¿MOSTRAR PROCESO? Diagrama o timeline\n¿MOSTRAR RELACIÓN? Dispersión o matriz\n\nTÍTULO CONCLUSIVO\n\nRESUMEN TEXTUAL Y UNIDADES\n\nRIESGO DE INTERPRETACIÓN",reminder:"Incluye un resumen textual y no dependas solo del color."},
  {id:"viva",title:"Checklist VIVA",description:"Prepara voz, intención, visibilidad y atención.",contentType:"checklist",status:"published",groups:[{title:"Presentación",items:["Voz audible y natural","Intención clara","Presencia accesible y no distractora","Atención a preguntas y contexto"]}],reminder:"No existe una postura, acento o gesto universalmente correcto."},
  {id:"afo",title:"Guía AFO",description:"Abre, focaliza y operacionaliza una reunión.",contentType:"worksheet",status:"published",fields:["Abrir: propósito y condiciones","Focalizar: preguntas y participación","Operacionalizar: decisión, responsable y fecha"],reminder:"Facilitar no significa dominar ni forzar consenso."},
  {id:"executive-email",title:"Correo ejecutivo",description:"Plantilla breve con solicitud visible.",contentType:"template",status:"published",template:"ASUNTO: [decisión o acción]\n\nMENSAJE PRINCIPAL\n\nCONTEXTO ESENCIAL\n\nEVIDENCIA\n• \n• \n\nSOLICITUD Y FECHA\n\nRIESGO O CONDICIÓN",reminder:"Adapta tono y detalle a la relación y al canal."},
  {id:"decision-update",title:"Actualización de decisión",description:"Documenta decisión, evidencia, riesgo y responsable.",contentType:"worksheet",status:"published",fields:["Decisión","Evidencia","Riesgo","Responsable","Fecha","Revisión"],reminder:"Haz visible lo que sigue abierto."},
  {id:"question-prep",title:"Preparación de preguntas",description:"Anticipa respuestas sin fingir certeza.",contentType:"worksheet",status:"published",fields:["Pregunta probable","Respuesta breve","Evidencia","Incertidumbre","Seguimiento"],reminder:"Si no sabes, registra cómo y cuándo responderás."},
  {id:"action-log",title:"Registro de acciones",description:"Cierra reuniones con responsabilidades explícitas.",contentType:"worksheet",status:"published",fields:["Decisión","Acción","Responsable","Fecha","Dependencia","Seguimiento"],reminder:"Comparte el registro con quienes deban ejecutar o estar informados."},
];

const lessons = [
 {slug:"comprender-audiencia",title:"Comprender a la audiencia",description:"Prepara preguntas informadas sin convertir roles o señales en estereotipos.",outcomes:["Separar hechos y supuestos","Mapear intereses y autoridad","Adaptar canal y nivel de detalle"],sections:[
  {title:"Comprender no es adivinar",paragraphs:["Analizar una audiencia no significa leer emociones, evitar desacuerdo ni decir solo lo que alguien quiere oír. Significa preparar preguntas sobre conocimiento, decisiones, restricciones, riesgos e información necesaria."],bullets:["No trates la demografía como destino","No supongas que un rol determina una opinión","Observa reacciones con cautela y permite corrección"]},
  {title:"Diez dimensiones útiles",questionGroups:[{title:"Persona y decisión",items:["Rol y responsabilidad","Conocimiento","Posición actual","Interés","Qué está en juego","Inquietudes","Autoridad"]},{title:"Situación",items:["Contexto y presión","Canal","Historia de la relación"]}]},
  {title:"Hechos, supuestos y verificación",paragraphs:["Registra qué sabes, qué infieres, qué debes preguntar y qué puede cambiar durante la conversación."],example:{title:"Regla práctica",text:"Escribe cada aspecto en cuatro columnas: sé, supongo, verificaré y actualizaré."}},
  {title:"Empatía con límites",callout:{title:"Una definición cauta",text:"La empatía profesional es el esfuerzo por comprender una perspectiva sin asumir que la conocemos por completo. No exige acuerdo, aprobación, resolver emociones ni abandonar el propio objetivo."}},
  {title:"Varias audiencias, un núcleo",paragraphs:["Quien decide, implementa, aporta experiencia o recibe el impacto puede necesitar distinto detalle. Conserva un mensaje central y adapta ejemplos, anexos o seguimientos, en vez de sobrecargar una sola pieza."],bullets:["¿Qué información tiene esta persona?","¿Qué resultado necesita?","¿Qué debo preguntar en vez de asumir?","¿Qué puede decidir realmente?"]},
  {title:"Cinco prácticas ficticias",examples:audienceCases,links:[{label:"Crear un mapa de audiencia",href:"/herramientas/mapa-audiencia"}]}
 ],relatedResources:["marea","audience-map"],relatedTools:["mapa-audiencia"]},
 {slug:"escucha-activa",title:"Escuchar y preguntar mejor",description:"Comprueba lo entendido, explora diferencias y evita resolver antes de comprender.",outcomes:["Aplicar CAPTA","Secuenciar preguntas","Responder ante situaciones difíciles"],sections:[
  {title:"Escuchar es una tarea activa",paragraphs:["Escuchar requiere atención, interpretación cauta, preguntas, pausas y comprobación. Preparar toda la respuesta mientras otra persona habla suele desplazar aquello que todavía no entendemos."]},
  {title:"CAPTA",framework:[{title:"Concentrar",text:"Reduce distracciones y atiende a la interacción."},{title:"Aclarar",text:"Pregunta por términos o contexto ambiguos."},{title:"Parafrasear",text:"Devuelve el significado esencial con tus palabras."},{title:"Tensionar con respeto",text:"Examina una inconsistencia sin atacar."},{title:"Acordar lo entendido",text:"Confirma comprensión antes de avanzar."}],callout:{title:"Modelo práctico",text:"CAPTA fue creado para esta ruta; no mide empatía ni calidad personal."}},
  {title:"Respuestas y preguntas útiles",questionGroups:[{title:"Explorar y aclarar",items:["¿En qué etapa ocurre?","¿Qué cambió?","¿Qué alternativa intentaron?","¿Qué información falta?"]},{title:"Reconocer sin asumir",items:["Veo que este tema importa. ¿Qué está en juego?","¿Prefieres pensar opciones o que primero siga escuchando?"]}]},
  {title:"Errores frecuentes",bullets:["Interrumpir o solucionar demasiado pronto","Atribuir una emoción","Llevar la conversación hacia uno mismo","Hacer varias preguntas a la vez","Aceptar solo para reducir tensión","Tratar el silencio como fracaso"]},
  {title:"Secuencia adaptable",ordered:["Abre el tema.","Aclara hechos.","Explora consecuencias.","Examina supuestos.","Confirma lo entendido.","Avanza a una decisión o siguiente acción."],paragraphs:["No es un guion obligatorio. Ajusta ante emoción, exceso de detalle, poder desigual, desacuerdo, virtualidad o poco tiempo; no ofrece consejo de salud mental."]},
  {title:"Ocho diálogos ficticios",examples:listeningDialogues,links:[{label:"Practicar escucha activa",href:"/herramientas/practica-escucha-activa"},{label:"Preparar conversaciones de networking",href:"/aprende/networking/conversaciones-informales"}]}
 ],relatedResources:["capta","question-prep"],relatedTools:["practica-escucha-activa"]},
 {slug:"definir-proposito",title:"Definir el propósito",description:"Convierte un tema amplio en un resultado realista para la interacción.",outcomes:["Distinguir tema y propósito","Aplicar FIN","Construir una agenda orientada a resultados"],sections:[
  {title:"El tema no dice para qué conversar",examples:[{title:"Tema",text:"Actualizar el estado del proyecto."},{title:"Propósito",text:"Acordar qué entregable posponer para proteger la fecha crítica."},{title:"Otro propósito",text:"Resolver dudas y asignar responsables para un piloto; no aprobar hoy el despliegue completo."}]},
  {title:"Doce finalidades posibles",bullets:["Informar, explorar o comprender","Alinear, decidir o solicitar","Recomendar, enseñar o coordinar","Resolver, negociar, obtener feedback o construir compromiso"],paragraphs:["Elige una finalidad primaria. Los resultados secundarios no deberían ocultarla."]},
  {title:"Un propósito compartido no exige acuerdo total",paragraphs:["La interacción necesita un resultado suficientemente relevante para participar. Considera tu necesidad, la de la audiencia, el tiempo, la acción posible y aquello que no cabe hoy."]},
  {title:"FIN",framework:[{title:"Finalidad",text:"Qué debe lograr la interacción."},{title:"Interés compartido",text:"Por qué vale la pena participar."},{title:"Next step",text:"Qué cambia al terminar."}],callout:{title:"Modelo práctico",text:"FIN fue creado para esta guía; puede combinarse con otras formas de preparación."}},
  {title:"Propósito, alcance y agenda",checklist:["Seleccioné un resultado principal","Separé información de decisión","Creé un espacio para temas fuera de alcance","Definí seguimiento solo si aporta valor","Cada punto de agenda produce una salida"]},
  {title:"Ocho objetivos para reescribir",examples:purposeExercises,links:[{label:"Definir propósito y agenda",href:"/herramientas/definir-proposito-comunicacion"}]}
 ],relatedResources:["fin","marea"],relatedTools:["definir-proposito-comunicacion"]},
 {slug:"insights-y-sintesis",title:"Convertir información en mensajes",description:"Distingue evidencia, hallazgos, interpretaciones e implicaciones relevantes.",outcomes:["Diferenciar cinco niveles","Sintetizar con DICA","Seleccionar evidencia útil"],sections:[
  {title:"Cinco niveles de significado",framework:[{title:"Dato",text:"Observación o valor sin elaborar."},{title:"Información",text:"Dato organizado en un contexto."},{title:"Hallazgo",text:"Patrón relevante observado."},{title:"Insight",text:"Interpretación que importa para una decisión."},{title:"Recomendación",text:"Acción propuesta a partir del insight."}]},
  {title:"Un insight no necesita sorprender",paragraphs:["Debe conectarse al propósito, apoyarse en evidencia, ser relevante, explicar por qué importa y reconocer incertidumbre. Su valor está en cambiar comprensión o acción, no en parecer ingenioso."]},
  {title:"Resumen y síntesis",comparison:{leftTitle:"Resumen",leftItems:["Condensa evidencia","Describe piezas","Puede dejar la decisión abierta"],rightTitle:"Síntesis",rightItems:["Conecta patrones","Explica significado conjunto","Orienta una pregunta o acción"]}},
  {title:"DICA",framework:[{title:"Dato o hallazgo",text:"Qué muestra la evidencia."},{title:"Interpretación",text:"Qué explicación sostiene."},{title:"Consecuencia",text:"Por qué importa."},{title:"Acción o pregunta",text:"Qué debería ocurrir después."}],callout:{title:"Modelo práctico",text:"DICA fue creado para esta ruta y no convierte una interpretación en hecho."}},
  {title:"Selecciona con criterio",checklist:["Apoya el propósito","Puede cambiar la conclusión","La audiencia lo necesita ahora","No duplica otro punto","La fuente es suficiente","La incertidumbre está calificada"],paragraphs:["Etiqueta hecho, estimación, supuesto, interpretación, recomendación e incógnita."]},
  {title:"Diez ejercicios de síntesis",examples:insightExercises,links:[{label:"Convertir datos en insight",href:"/herramientas/convertir-datos-en-insight"},{label:"Profundizar en síntesis y recomendaciones",href:"/aprende/resolucion-de-problemas/sintesis-y-recomendaciones"}]}
 ],relatedResources:["data-insight","dica"],relatedTools:["convertir-datos-en-insight"]},
 {slug:"estructurar-mensaje",title:"Estructurar una comunicación",description:"Organiza la conclusión, las razones, la evidencia y la acción según el canal.",outcomes:["Aplicar NÚCLEO","Agrupar argumentos","Adaptar longitud y encabezados"],sections:[
  {title:"Empieza por el punto principal cuando corresponda",paragraphs:["En muchos contextos conviene abrir con respuesta, recomendación, decisión, actualización o riesgo. Un mínimo de contexto puede ir primero si la audiencia no lo tiene, el asunto es sensible, existen obligaciones legales o de seguridad, o el propósito es explorar en conjunto."]},
  {title:"NÚCLEO",framework:[{title:"Núcleo",text:"Mensaje o respuesta principal."},{title:"Utilidad",text:"Por qué importa a la audiencia."},{title:"Cimientos",text:"Razones de apoyo comparables."},{title:"Evidencia",text:"Hechos o análisis que sostienen cada razón."},{title:"Llamado",text:"Decisión, solicitud o acción."},{title:"Objeciones",text:"Riesgos, condiciones y preguntas probables."}],callout:{title:"Arquitectura práctica",text:"NÚCLEO fue creado para masanes.cl y debe adaptarse al canal."}},
  {title:"Construye hacia arriba, comunica hacia abajo",paragraphs:["El análisis suele avanzar desde evidencia hasta conclusión; el mensaje suele presentarse desde conclusión hacia razones. Cada apoyo debe responder por qué o cómo, y los elementos de un nivel deben ser comparables."]},
  {title:"Formas de agrupar",bullets:["Causas o acciones","Tiempo o proceso","Geografía o segmento","Beneficios o riesgos","Opciones o prioridades","Interno o externo","Financiero o no financiero"],paragraphs:["Reduce solapamientos y omisiones importantes sin convertir la estructura en un ejercicio formalista."]},
  {title:"Canal, longitud y encabezados",questionGroups:[{title:"Formatos",items:["Una frase: mensaje, implicación, acción","Correo: contexto esencial, dos apoyos, solicitud","Actualización: estado, evidencia, riesgo, acción","Presentación: narrativa, evidencia, interacción, cierre","Mensaje instantáneo: contexto, solicitud, fecha y enlace"]},{title:"Encabezados",items:["Evita etiquetas como “Resultados”","Escribe el significado: “La demora se concentra en dos dependencias”","No afirmes más de lo que muestran los datos"]}]},
  {title:"Diez reestructuraciones",examples:structureExercises,links:[{label:"Estructurar un mensaje",href:"/herramientas/estructurar-mensaje"},{label:"Practicar una recomendación de caso",href:"/aprende/consultoria/entrevistas-de-caso/recomendacion-final"}]}
 ],relatedResources:["nucleo","executive-email","decision-update"],relatedTools:["estructurar-mensaje"]},
 {slug:"narrativa-y-visuales",title:"Construir una narrativa y elegir apoyos visuales",description:"Explica qué cambió, por qué importa y qué debería ocurrir sin fabricar dramatismo.",outcomes:["Aplicar CAMBIO","Elegir el trabajo de un visual","Escribir títulos y resúmenes accesibles"],sections:[
  {title:"Narrativa no es decoración",paragraphs:["Una narrativa profesional ordena cambio, tensión, evidencia y respuesta. No necesita suspenso artificial, emoción fabricada, historias personales ni un final motivacional."]},
  {title:"CAMBIO",framework:[{title:"Contexto",text:"Situación inicial necesaria."},{title:"Alteración",text:"Cambio o tensión."},{title:"Motivo",text:"Por qué importa."},{title:"Insight",text:"Qué revela el análisis."},{title:"Giro",text:"Qué respuesta se propone."},{title:"Outcome",text:"Qué resultado o paso se espera."}],callout:{title:"Modelo práctico",text:"CAMBIO fue creado para esta ruta. Una expectativa no es un resultado garantizado."}},
  {title:"Ejemplos y analogías con honestidad",bullets:["Vuelven concreto un concepto","Muestran experiencia o consecuencia","Ayudan a explicar escala o proceso"],paragraphs:["Evita anécdotas inventadas como verdaderas, analogías engañosas, estereotipos o emoción desconectada de la evidencia."]},
  {title:"Cada visual necesita un trabajo",bullets:["Comparar, mostrar cambio o composición","Mostrar distribución, relación o proceso","Representar geografía, secuencia, lógica o ejemplo"],paragraphs:["Barras, líneas, puntos, tablas, cascadas, embudos, timelines y diagramas sirven a trabajos distintos. Si el visual no aclara el mensaje, puede ser mejor una frase o un número destacado."]},
  {title:"Título, simplicidad y acceso",checklist:["Una idea principal","Título conclusivo respaldado","Etiquetas y unidades visibles","Escala honesta","Resumen textual","Contraste y etiquetas además de color","Alternativa tabular cuando aporta","Nada esencial depende de animación"]},
  {title:"Seis narrativas para practicar",examples:narrativeExercises,links:[{label:"Construir una narrativa",href:"/herramientas/constructor-narrativa-profesional"}]}
 ],relatedResources:["cambio","visual-guide"],relatedTools:["constructor-narrativa-profesional"]},
 {slug:"presentacion-oral",title:"Presentar con claridad",description:"Ensaya voz, intención y participación sin convertir la presencia en una fórmula corporal.",outcomes:["Aplicar VIVA","Preparar una presentación virtual","Usar feedback cualitativo"],sections:[
  {title:"La entrega apoya; no repara una lógica débil",paragraphs:["Una presencia clara puede hacer el mensaje audible y fácil de seguir, pero no compensa evidencia insuficiente, propósito confuso o afirmaciones engañosas."]},
  {title:"VIVA",framework:[{title:"Voz",text:"Volumen, ritmo, articulación, pausa y énfasis."},{title:"Intención",text:"Qué debe comprender o hacer la audiencia."},{title:"Visibilidad",text:"Presencia física o en pantalla que no distrae."},{title:"Atención",text:"Observación cauta y ajuste durante la interacción."}],callout:{title:"Modelo práctico",text:"VIVA no prescribe un acento, postura o gesto universal."}},
  {title:"Voz y presencia accesibles",bullets:["Habla con volumen suficiente y ritmo natural","Usa pausas y énfasis sin actuar un personaje","Adopta una postura cómoda y gestos funcionales","Ajusta cámara, audio, iluminación y notas a tus necesidades","Sentarse, estar de pie o no usar cámara puede depender del contexto y la accesibilidad"]},
  {title:"Conexión y nervios",paragraphs:["La conexión puede surgir de relevancia, respeto, ejemplos honestos, incertidumbre visible y participación. Para preparar nervios, ensaya apertura, verifica tecnología, usa notas simples, ralentiza las primeras frases y prepara preguntas. Son sugerencias prácticas, no tratamiento médico."]},
  {title:"Virtualidad y ensayo",ordered:["Prueba audio, cámara si se usará y pantalla.","Explica cómo participar.","Planifica una falla técnica.","Ensaya en silencio y luego en voz alta.","Cronometra y registra solo si resulta accesible.","Identifica una fortaleza y una prioridad.","Prueba apertura, cierre y preguntas.","Ajusta sin memorizar cada palabra."]},
  {title:"Rúbrica cualitativa",rubric:["Claridad del mensaje","Estructura y relevancia","Voz, ritmo y pausas","Apoyo visual","Conexión y preguntas","Confianza sin exageración","Llamado a la acción"],links:[{label:"Preparar una presentación",href:"/herramientas/preparar-presentacion"},{label:"Revisar feedback y práctica",href:"/aprende/adaptabilidad-resiliencia/reflexion-y-feedback"}]}
 ],relatedResources:["viva","question-prep"],relatedTools:["preparar-presentacion"]},
 {slug:"facilitacion",title:"Facilitar reuniones y conversaciones",description:"Abre, focaliza y convierte el diálogo en decisiones, responsables y seguimiento.",outcomes:["Aplicar AFO","Diseñar participación inclusiva","Cerrar con acuerdos verificables"],sections:[
  {title:"Facilitar no es dominar",paragraphs:["Quien facilita ayuda a comprender el propósito, participar, explorar perspectivas, decidir y registrar. No necesita hablar más, ser la mayor persona experta, eliminar desacuerdo ni forzar consenso."]},
  {title:"AFO",framework:[{title:"Abrir",text:"Contexto, propósito, alcance, tiempo y condiciones de participación."},{title:"Focalizar",text:"Preguntas, resúmenes, diferencias, evidencia y tiempo."},{title:"Operacionalizar",text:"Decisiones, responsables, fechas y seguimiento."}],callout:{title:"Modelo práctico",text:"AFO fue creado para masanes.cl y no elimina las dinámicas de poder."}},
  {title:"Una apertura suficiente",bullets:["Por qué existe la reunión","Resultado y alcance","Tiempo y forma de participar","Preparación asumida","Autoridad disponible","Tratamiento de temas abiertos"]},
  {title:"Foco y participación",questionGroups:[{title:"Facilitar",items:["Una pregunta clara a la vez","Separar hechos y opiniones","Nombrar diferencias con neutralidad","Detener repetición y estacionar desvíos","Preguntar qué evidencia resolvería la diferencia"]},{title:"Incluir",items:["Reflexión silenciosa","Ronda o parejas cuando aporte","Chat o entrada anónima según el riesgo","Invitar sin forzar","Pedir a la jerarquía que hable después"]}]},
  {title:"Dinámicas difíciles y cierre",bullets:["Dominio: resume e invita otras perspectivas","Silencio: aclara y da tiempo","Conflicto: vuelve a criterios e intereses","Desvío: conecta con propósito o estaciona","Sin autoridad: define recomendación y decisor","Sin datos: pausa, condiciona o asigna análisis"],paragraphs:["Cierra con decisión, asuntos abiertos, supuestos, acciones, responsables, fechas, revisión y comunicación a personas ausentes. No improvises una respuesta que no sabes."]},
  {title:"Ocho reuniones ficticias",examples:meetingExercises,links:[{label:"Planificar una reunión",href:"/herramientas/planificar-reunion"},{label:"Revisar colaboración y sesgos",href:"/aprende/resolucion-de-problemas/colaboracion-y-sesgos"}]}
 ],relatedResources:["afo","action-log","decision-update"],relatedTools:["planificar-reunion"]},
 {slug:"caso-integrador",title:"Aplicar el método completo",description:"Convierte un análisis mixto en una decisión comunicable, una reunión y un seguimiento.",outcomes:["Integrar MAREA","Preparar una decisión con evidencia contradictoria","Cerrar y documentar la acción"],sections:[
  {title:"Caso ficticio: Aprendo Sur",paragraphs:["Caso ficticio creado con fines educativos.","Una empresa regional de tecnología educativa probó una nueva incorporación para participantes corporativos. Hay datos de uso, entrevistas mixtas, una demora de proyecto, capacidad limitada y una reunión de decisión en una semana."]},
  {title:"Audiencias y tensiones",bullets:["Dirección general quiere velocidad","Producto busca aprendizaje válido","Ventas teme una promesa débil","Éxito de clientes pide personalización","Tecnología advierte capacidad","El cliente necesita una experiencia clara"],paragraphs:["La reunión dura cuarenta y cinco minutos y la evidencia sostiene un piloto limitado, no un despliegue completo."]},
  {title:"Evidencia ficticia",questionGroups:[{title:"Uso y operación",items:["Más personas completan el primer paso, pero no el segundo.","La variante exige apoyo manual que no escala con la capacidad actual.","La medición de éxito difiere entre producto y ventas."]},{title:"Entrevistas",items:["Clientes valoran la orientación inicial.","Participantes piden menos pasos y recordatorios más claros.","Operaciones anticipa más consultas durante el despliegue."]}]},
  {title:"Recorrido MAREA",ordered:["Mapea audiencia y supuestos.","Define el propósito FIN y la decisión.","Convierte evidencia en DICA.","Estructura NÚCLEO.","Crea CAMBIO y dos visuales con resumen textual.","Prepara apertura, objeciones y respuestas honestas.","Facilita con AFO.","Cierra con decisión, responsable, fecha y correo."]},
  {title:"Mensaje modelo",modelAnswers:[{title:"Piloto condicionado",text:"Recomendamos ampliar el piloto solo a dos cuentas comparables durante cuatro semanas. La nueva orientación mejora el primer paso, pero el efecto posterior y la capacidad de soporte siguen inciertos. Producto será responsable; tecnología y éxito de clientes definirán el límite operativo; la revisión usará finalización, demanda de soporte y feedback cualitativo."},{title:"Camino alternativo",text:"Si la capacidad manual supera el límite acordado, puede ser válido pausar la expansión y simplificar primero el segundo paso. La respuesta depende de la restricción dominante y de cómo se defina éxito."}]},
  {title:"Guía y rúbrica",bullets:["Entrega evidencia por etapas","Pide separar hechos y supuestos","Acepta distintas estructuras si responden a la decisión","Exige incertidumbre y objeciones visibles","Evalúa claridad, relevancia, evidencia, interacción y cierre"],links:[{label:"Usar la tarjeta MAREA",href:`${base}#resource-marea`},{label:"Explorar escenarios de práctica",href:"#biblioteca-comunicacion"}]}
 ],relatedResources:["marea","audience-map","dica","nucleo","cambio","afo","action-log"],relatedTools:["mapa-audiencia","definir-proposito-comunicacion","convertir-datos-en-insight","estructurar-mensaje","planificar-reunion"]},
];

export const communicationLessons = lessons.map((item,index)=>({...item,order:index+1,href:`${base}/${item.slug}`,status:"published",level:index<3?"Introductorio":index===8?"Avanzado":"Intermedio",readingTime:`${9+index} minutos`,updatedAt,contentType:"lesson"}));
export const communicationPath = {title:"Comunicación profesional",description:"Aprende a comprender a tu audiencia, estructurar ideas complejas y conducir conversaciones hacia decisiones y acciones claras.",audience:"Estudiantes, profesionales, líderes, docentes, consultores y equipos",format:"Ruta práctica",readingTime:"Aproximadamente 120 minutos",level:"Progresivo",updatedAt,status:"published",outcomes:["Preparar audiencia y propósito","Escuchar y preguntar","Convertir evidencia en síntesis","Estructurar mensajes y narrativas","Presentar, facilitar y cerrar acuerdos"]};
export const getCommunicationLesson=(slug)=>communicationLessons.find((item)=>item.slug===slug);
export const getCommunicationResource=(id)=>communicationResources.find((item)=>item.id===id);
