import { useEffect, useMemo } from "react";
import { ArrowRight, BookOpen, Clock, Gauge, Layers3, Target } from "lucide-react";
import { trackEvent } from "./analytics";
import { communicationLessons, communicationPath, communicationResources, communicationScenarios, getCommunicationLesson, getCommunicationResource } from "./communicationContent";
import { Breadcrumbs, LessonContent, LessonMetadata, LessonNavigation, PageShell, RelatedContent, ResourceCard, StatusBadge } from "./LearningComponents";
import { NotFoundPage } from "./LearningPages";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const base="/aprende/comunicacion-profesional";
const graphNode=({"@context":_context,...node})=>node;
const toolLinks={
 "mapa-audiencia":{title:"Mapa de audiencia",href:"/herramientas/mapa-audiencia"},
 "practica-escucha-activa":{title:"Práctica de escucha activa",href:"/herramientas/practica-escucha-activa"},
 "definir-proposito-comunicacion":{title:"Constructor de propósito",href:"/herramientas/definir-proposito-comunicacion"},
 "convertir-datos-en-insight":{title:"Constructor de insights",href:"/herramientas/convertir-datos-en-insight"},
 "estructurar-mensaje":{title:"Estructurador de mensajes",href:"/herramientas/estructurar-mensaje"},
 "constructor-narrativa-profesional":{title:"Constructor de narrativa",href:"/herramientas/constructor-narrativa-profesional"},
 "preparar-presentacion":{title:"Preparador de presentaciones",href:"/herramientas/preparar-presentacion"},
 "planificar-reunion":{title:"Planificador de reuniones",href:"/herramientas/planificar-reunion"},
};

export function CommunicationHubPage(){
 const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"Comunicación profesional",href:base}];
 const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:communicationPath.title,description:communicationPath.description,url:`https://masanes.cl${base}`,learningResourceType:"Ruta de aprendizaje",educationalLevel:communicationPath.level,dateModified:communicationPath.updatedAt}]}),[]);
 usePageMetadata({title:"Comunicación profesional: guía práctica",description:communicationPath.description,path:base,schema});
 useEffect(()=>{trackEvent("communication_hub_viewed");if(window.location.hash)requestAnimationFrame(()=>document.querySelector(window.location.hash)?.scrollIntoView());},[]);
 return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--networking"><div><p className="eyebrow">Ruta de aprendizaje</p><h1>Comunicación profesional</h1><p className="page-hero__lead">{communicationPath.description}</p><p>Comunicar no es solo transmitir. Una idea bien analizada puede fallar si ignora a la audiencia, y una entrega segura no repara un propósito confuso. Esta ruta comienza antes del correo o la reunión y termina con acuerdos verificables.</p><div className="hero-actions"><a className="button button--primary" href={communicationLessons[0].href}>Comenzar la ruta <ArrowRight size={17}/></a><a className="button button--secondary" href="/herramientas/definir-proposito-comunicacion">Preparar una comunicación</a><a className="button button--secondary" href="/herramientas/estructurar-mensaje">Evaluar mi mensaje</a></div></div><aside className="summary-panel"><StatusBadge status="published"/><dl><div><dt><Target size={18}/>Dirigido a</dt><dd>{communicationPath.audience}</dd></div><div><dt><BookOpen size={18}/>Tipo</dt><dd>{communicationPath.format}</dd></div><div><dt><Clock size={18}/>Tiempo</dt><dd>{communicationPath.readingTime}</dd></div><div><dt><Gauge size={18}/>Nivel</dt><dd>{communicationPath.level}</dd></div><div><dt><Layers3 size={18}/>Módulos</dt><dd>9 módulos</dd></div></dl></aside></header>
 <section className="guide-intro"><div><p className="eyebrow">MAREA</p><h2>Una preparación que termina en acuerdos</h2><p>Mirar a la audiencia, Acordar el propósito, Reducir y estructurar, Expresar e interactuar y Aterrizar acuerdos. MAREA es un modelo práctico creado para esta ruta, no una secuencia rígida ni un estándar científico.</p></div><ul>{communicationPath.outcomes.map((item)=><li key={item}>{item}</li>)}</ul></section>
 <section className="content-section content-section--soft" aria-labelledby="communication-lessons"><div className="section-title"><p className="eyebrow">Nueve módulos</p><h2 id="communication-lessons">De preparar la audiencia a cerrar la acción</h2></div><div className="case-chapter-grid">{communicationLessons.map((item)=><a className="content-card content-card--link" href={item.href} key={item.slug}><span className="resource-type">Módulo {item.order}</span><h3>{item.title}</h3><p>{item.description}</p><span className="card-link">Abrir módulo <ArrowRight size={16}/></span></a>)}</div></section>
 <section className="content-section" aria-labelledby="communication-tools"><div className="section-title"><p className="eyebrow">Herramientas locales</p><h2 id="communication-tools">Prepara sin enviar tu contenido</h2><p>Los resultados se generan en tu navegador y desaparecen al recargar.</p></div><div className="case-tool-links">{Object.values(toolLinks).map((tool)=><a href={tool.href} key={tool.href}>{tool.title}<ArrowRight size={16}/></a>)}</div></section>
 <section className="content-section content-section--soft" id="biblioteca-comunicacion" aria-labelledby="communication-practice"><div className="section-title"><p className="eyebrow">Biblioteca de práctica</p><h2 id="communication-practice">Quince escenarios ficticios</h2><p>Practica el criterio, no una frase universal.</p></div><div className="scenario-grid">{communicationScenarios.map((item)=><article id={`escenario-${item.slug}`} key={item.slug}><p className="resource-type">Caso ficticio · {item.difficulty}</p><h3>{item.title}</h3><p>{item.context}</p><p><strong>Propósito:</strong> {item.purpose}</p><details><summary>Abrir práctica y modelo</summary><p><strong>Audiencia:</strong> {item.audience.join("; ")}</p><p><strong>Canal:</strong> {item.channel}</p><p><strong>Evidencia:</strong> {item.evidence.join("; ")}</p><p><strong>Restricciones:</strong> {item.constraints.join("; ")}</p><p><strong>Borrador débil:</strong> {item.draftMessage}</p><p><strong>Tarea:</strong> {item.learnerTask.join("; ")}</p><p><strong>Respuesta modelo:</strong> {item.modelResponse}</p><p><strong>Por qué:</strong> {item.explanation.join(" ")}</p><p><strong>Habilidades:</strong> {item.skills.join("; ")}</p></details></article>)}</div></section>
 <section className="content-section" id="recursos" aria-labelledby="communication-resources"><div className="section-title"><p className="eyebrow">Recursos</p><h2 id="communication-resources">Quince plantillas y checklists</h2><p>Los campos son efímeros. Copia lo que quieras conservar.</p></div><div className="resource-grid">{communicationResources.map((resource)=><ResourceCard key={resource.id} resource={resource}/>)}</div></section>
 <aside className="contextual-cta"><div><h2>¿Necesitas preparar una comunicación importante?</h2><p>Puedo ayudarte a ordenar el mensaje, anticipar preguntas y convertir una idea compleja en una conversación clara y accionable.</p></div><a className="button button--primary" href="/#services" onClick={()=>trackEvent("communication_service_clicked",{destination:"coaching"})}>Conocer los servicios de coaching</a></aside></main></PageShell>;
}

export function CommunicationLessonPage({slug}){const item=getCommunicationLesson(slug);return item?<CommunicationLessonContent item={item}/>:<NotFoundPage/>;}
function CommunicationLessonContent({item}){
 const index=communicationLessons.indexOf(item);const resources=item.relatedResources.map(getCommunicationResource).filter(Boolean);const tools=item.relatedTools.map((slug)=>toolLinks[slug]).filter(Boolean);const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"Comunicación profesional",href:base},{label:item.title,href:item.href}];
 const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:item.title,description:item.description,url:`https://masanes.cl${item.href}`,learningResourceType:"Lección",educationalLevel:item.level,dateModified:item.updatedAt,isPartOf:{"@type":"LearningResource",name:communicationPath.title,url:`https://masanes.cl${base}`}}]}),[item.slug]);
 usePageMetadata({title:item.title,description:item.description,path:item.href,schema});useEffect(()=>trackEvent("communication_lesson_opened",{module:item.slug}),[item.slug]);
 return <PageShell><main id="main-content" className="content-page lesson-page"><Breadcrumbs items={breadcrumbs}/><article><header className="lesson-header"><div><p className="eyebrow">Módulo {item.order} de 9</p><h1>{item.title}</h1><p>{item.description}</p></div><StatusBadge status="published"/></header><LessonMetadata module={item} total={9}/><aside className="lesson-outcomes"><h2>Al terminar podrás</h2><ul>{item.outcomes.map((outcome)=><li key={outcome}>{outcome}</li>)}</ul></aside><LessonContent content={item}/><RelatedContent resources={resources} tools={tools} basePath={base}/><div className="lesson-hub-link"><a className="button button--secondary" href={base}>Volver a Comunicación profesional</a></div><LessonNavigation previous={communicationLessons[index-1]} next={communicationLessons[index+1]}/></article></main></PageShell>;
}
