import { useEffect, useMemo, useState } from "react";
import { Printer, RotateCcw, Sparkles } from "lucide-react";
import { trackEvent } from "./analytics";
import { buildAudienceMap, buildCommunicationPurpose, buildInsight, buildListeningPractice, buildMeetingPlan, buildMessageStructure, buildNarrative, buildPresentationPlan } from "./communicationTools";
import { Breadcrumbs, CopyToClipboard, PageShell } from "./LearningComponents";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const configs={
 audience:{title:"Mapa de audiencia",description:"Prepara preguntas sobre conocimiento, posición, intereses y autoridad sin perfilar personas.",path:"/herramientas/mapa-audiencia",event:"audience_map_completed",build:buildAudienceMap,fields:[["topic","Tema *"],["role","Rol de la audiencia *"],["knowledge","Conocimiento actual *","level"],["position","Posición actual *"],["interests","Intereses *"],["concerns","Inquietudes"],["stakes","Qué está en juego"],["authority","Autoridad o influencia *"],["context","Contexto"],["channel","Canal *","channel"],["assumptions","Supuestos por verificar"]]},
 listening:{title:"Práctica de escucha activa",description:"Ensaya una respuesta y contrástala con CAPTA sin recibir una puntuación de empatía.",path:"/herramientas/practica-escucha-activa",event:"listening_practice_completed",build:buildListeningPractice,fields:[["scenario","Escenario *","scenario"],["response","¿Qué responderías? *"]]},
 purpose:{title:"Definir el propósito de una comunicación",description:"Convierte un tema amplio en una finalidad, una relevancia compartida y un siguiente paso.",path:"/herramientas/definir-proposito-comunicacion",event:"communication_purpose_generated",build:buildCommunicationPurpose,fields:[["topic","Tema *"],["audience","Audiencia *"],["time","Tiempo disponible *"],["objective","Objetivo de quien comunica *"],["audienceNeed","Necesidad de la audiencia *"],["action","Decisión o acción deseada *"],["outOfScope","Fuera de alcance"],["followUp","Seguimiento"]]},
 insight:{title:"Convertir datos en insight",description:"Separa hechos, patrón, interpretación, consecuencia y acción mediante DICA.",path:"/herramientas/convertir-datos-en-insight",event:"communication_insight_generated",build:buildInsight,fields:[["purpose","Propósito *"],["audience","Audiencia *"],["facts","Hechos clave *"],["pattern","Patrón o hallazgo *"],["comparison","Comparación"],["explanation","Explicación posible *"],["consequence","Consecuencia profesional *"],["uncertainty","Incertidumbre"],["action","Acción posible"]]},
 message:{title:"Estructurar un mensaje",description:"Crea una versión breve y otra ampliada con la arquitectura NÚCLEO.",path:"/herramientas/estructurar-mensaje",event:"communication_outline_generated",build:buildMessageStructure,fields:[["channel","Canal *","channel"],["audience","Audiencia *"],["purpose","Propósito o relevancia *"],["message","Mensaje principal *"],["reasons","Razones de apoyo *"],["evidence","Evidencia *"],["risks","Riesgos u objeciones"],["action","Acción solicitada *"],["deadline","Fecha o plazo"]]},
 narrative:{title:"Constructor de narrativa profesional",description:"Organiza contexto, cambio, evidencia y respuesta con CAMBIO.",path:"/herramientas/constructor-narrativa-profesional",event:"professional_narrative_generated",build:buildNarrative,fields:[["audience","Audiencia *"],["context","Contexto actual *"],["change","Cambio o tensión *"],["importance","Por qué importa *"],["insight","Insight principal *"],["response","Respuesta propuesta *"],["outcome","Resultado esperado *"],["evidence","Evidencia disponible"],["channel","Canal *","channel"]]},
 presentation:{title:"Preparar una presentación",description:"Diseña un ensayo, una revisión VIVA y preguntas probables sin subir audio o video.",path:"/herramientas/preparar-presentacion",event:"presentation_plan_generated",build:buildPresentationPlan,fields:[["audience","Audiencia *"],["purpose","Propósito *"],["duration","Duración *"],["message","Mensaje principal *"],["points","Puntos de apoyo *"],["opening","Apertura *"],["closing","Cierre *"],["questions","Preguntas probables"],["priority","Prioridad de práctica"],["channel","Canal *","channel"]]},
 meeting:{title:"Planificar una reunión",description:"Crea una agenda AFO, participación, apertura y registro de acciones.",path:"/herramientas/planificar-reunion",event:"meeting_agenda_generated",build:buildMeetingPlan,fields:[["topic","Tema *"],["participants","Participantes *"],["time","Tiempo disponible *"],["outcome","Resultado deseado *"],["owner","Responsable de la decisión *"],["scope","Alcance *"],["inputs","Insumos requeridos"],["questions","Preguntas principales *"],["risks","Riesgos de dinámica"],["actions","Acciones esperadas *"]]},
};
const options={level:["Bajo","Medio","Alto"],channel:["Presencial","Videollamada","Correo","Presentación","Mensaje asincrónico"],scenario:["Cambio de alcance","Demasiado detalle","Desacuerdo entre áreas"]};

export default function CommunicationToolsPage({kind}){
 const config=configs[kind];const initial=useMemo(()=>Object.fromEntries(config.fields.map(([name])=>[name,""])),[kind]);const[values,setValues]=useState(initial);const[result,setResult]=useState({errors:{},output:"",warnings:[]});const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Herramientas",href:"/herramientas"},{label:config.title,href:config.path}];
 const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList",itemListElement:breadcrumbSchema(breadcrumbs).itemListElement},{"@type":"WebApplication",name:config.title,description:config.description,applicationCategory:"EducationalApplication",operatingSystem:"Web",url:`https://masanes.cl${config.path}`,dateModified:"2026-07-15"}]}),[kind]);
 usePageMetadata({title:config.title,description:config.description,path:config.path,schema});useEffect(()=>trackEvent("communication_tool_opened",{tool:kind}),[kind]);const reset=()=>{setValues(initial);setResult({errors:{},output:"",warnings:[]});};const submit=(event)=>{event.preventDefault();const next=config.build(values);setResult(next);if(next.output)trackEvent(config.event,{tool:kind});};
 return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero"><div><p className="eyebrow">Herramienta local</p><h1>{config.title}</h1><p className="page-hero__lead">{config.description}</p><p>Evita datos confidenciales. Tus entradas no se guardan, no se envían y desaparecen al recargar.</p></div></header><section className="generator-layout"><form className="generator-form" noValidate onSubmit={submit}>{config.fields.map(([name,label,type])=><label className="field" key={name} htmlFor={`communication-${kind}-${name}`}><span>{label}</span>{type?<select id={`communication-${kind}-${name}`} value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name]?`communication-error-${kind}-${name}`:undefined} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}><option value="">Selecciona una opción</option>{options[type].map((option)=><option key={option}>{option}</option>)}</select>:<textarea id={`communication-${kind}-${name}`} rows="3" value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name]?`communication-error-${kind}-${name}`:undefined} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}/>} {result.errors[name]&&<small className="field-error" id={`communication-error-${kind}-${name}`}>{result.errors[name]}</small>}</label>)}<div className="form-actions"><button className="button button--primary" type="submit"><Sparkles size={16}/>Generar resultado</button><button className="button button--secondary" type="button" onClick={reset}><RotateCcw size={16}/>Limpiar</button></div></form><aside className="generator-output" aria-live="polite"><h2>Resultado</h2>{result.output?<><pre className="template-preview">{result.output}</pre>{result.warnings?.length>0&&<div className="tool-warnings"><h3>Revisiones sugeridas</h3><ul>{result.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></div>}<div className="form-actions"><CopyToClipboard text={result.output} label="Copiar resultado" onCopy={()=>trackEvent("communication_resource_copied",{tool:kind})}/><button className="button button--secondary" type="button" onClick={()=>{trackEvent("communication_resource_printed",{tool:kind});window.print();}}><Printer size={16}/>Imprimir</button></div></>:<p>Completa los campos obligatorios para crear una primera versión revisable.</p>}</aside></section></main></PageShell>;
}
