export const CONTENT_TYPES = [
  "guide",
  "lesson",
  "framework",
  "template",
  "checklist",
  "case",
  "exercise",
  "tool",
  "glossary-entry",
  "learning-path",
];

export const topicGroups = [
  {
    title: "Carrera y habilidades profesionales",
    topics: [
      { title: "Networking", slug: "networking", status: "published", href: "/aprende/networking" },
      { title: "Comunicación profesional", slug: "comunicacion-profesional", status: "published", href: "/aprende/comunicacion-profesional", description: "Aprende a comprender a tu audiencia, sintetizar información y conducir reuniones y presentaciones hacia acciones claras." },
      { title: "Entrevistas informativas", slug: "entrevistas-informativas", status: "published", href: "/aprende/entrevistas-informativas", description: "Aprende a explorar trayectorias, contrastar decisiones de carrera y conducir conversaciones profesionales con respeto." },
      { title: "Marca profesional", slug: "marca-profesional", status: "published", href: "/aprende/marca-profesional", description: "Ordena evidencia, narrativa y señales profesionales para comunicar tu contribución con claridad y coherencia." },
      { title: "Escucha, curiosidad y feedback", slug: "escucha-curiosidad-feedback", status: "published", href: "/aprende/escucha-curiosidad-feedback", description: "Aprende a comprender, aclarar, evaluar feedback y reparar conversaciones sin perder criterio ni límites." },
      { title: "Investigación de empresas", slug: "investigacion-de-empresas", status: "published", href: "/aprende/investigacion-de-empresas", description: "Analiza organizaciones, contrasta evidencia y decide dónde concentrar una búsqueda profesional sin rankings ni investigación invasiva." },
      { title: "Trabajo en equipo", slug: "trabajo-en-equipo", status: "published", href: "/aprende/trabajo-en-equipo", description: "Coordina propósito, roles, decisiones, desacuerdos, seguimiento y aprendizaje sin clasificar personas." },
      { title: "Búsqueda de trabajo", status: "planned" },
      { title: "Cambio de carrera", status: "planned" },
      { title: "Negociación", status: "planned" },
      { title: "Comunicación ejecutiva", status: "planned" },
    ],
  },
  {
    title: "Estrategia y negocios",
    topics: [
      { title: "Prospección B2B", slug: "prospeccion-b2b", status: "published", href: "/aprende/prospeccion-b2b", description: "Aprende a identificar prospectos relevantes, comunicar valor y convertir contactos iniciales en conversaciones comerciales útiles." },
      { title: "Marketing digital", slug: "marketing-digital", status: "published", href: "/aprende/marketing-digital", description: "Aprende a entender a tus clientes, elegir canales, crear contenido y medir resultados con una estrategia conectada al negocio." },
      { title: "Preparación organizacional para la IA", slug: "preparacion-organizacional-para-ia", status: "published", href: "/aprende/preparacion-organizacional-para-ia", description: "Evalúa estrategia, portafolio, capacidades, gobierno y hoja de ruta para adoptar IA." },
      { title: "IA generativa para negocios", slug: "ia-generativa-para-negocios", status: "published", href: "/aprende/ia-generativa-para-negocios", description: "Aprende a evaluar oportunidades, costos, riesgos y decisiones de adopción antes de implementar inteligencia artificial en una organización." },
      { title: "Consultoría", slug: "consultoria", status: "published", href: "/aprende/consultoria", description: "Explora la carrera, prepara tu candidatura y practica entrevistas de caso con recursos aplicables." },
      { title: "Resolución de problemas", slug: "resolucion-de-problemas", status: "published", href: "/aprende/resolucion-de-problemas", description: "Aprende a definir problemas ambiguos, priorizar análisis y transformar evidencia en decisiones accionables." },
      ...["Diseño de estrategia", "Modelos de negocio", "Entrada a mercados", "Priorización", "Toma de decisiones"].map((title) => ({ title, status: "planned" })),
    ],
  },
  {
    title: "Datos e inteligencia artificial",
    topics: [
      { title: "IA responsable y gobernanza", slug: "ia-responsable-y-gobernanza", status: "published", href: "/aprende/ia-responsable-y-gobernanza", description: "Evalúa impactos, usos sensibles, equidad, supervisión, reparación y gobierno operativo." },
      { title: "Escalamiento y adopción de IA", slug: "escalamiento-y-adopcion-de-ia", status: "published", href: "/aprende/escalamiento-y-adopcion-de-ia", description: "Convierte experimentos en capacidades operables con evidencia, participación y control." },
      { title: "Pensamiento computacional y decisiones con datos", slug: "pensamiento-computacional-y-datos", status: "published", href: "/aprende/pensamiento-computacional-y-datos", description: "Formula problemas, modela incertidumbre y evalúa evidencia y algoritmos con criterio." },
      { title: "Inteligencia artificial y deep learning", slug: "inteligencia-artificial-y-deep-learning", status: "published", href: "/aprende/inteligencia-artificial-y-deep-learning", description: "Comprende redes neuronales, transformers, modelos generativos y decisiones de adaptación." },
      { title: "Preparación organizacional para la IA", slug: "preparacion-organizacional-para-ia", status: "published", href: "/aprende/preparacion-organizacional-para-ia", description: "Evalúa si la organización cuenta con estrategia, datos, capacidades y controles suficientes." },
      { title: "Sistemas de IA confiables", slug: "sistemas-ia-confiables", status: "published", href: "/aprende/sistemas-ia-confiables", description: "Comprende cómo prompts, fuentes, RAG, datos, seguridad y monitoreo se combinan en una solución de inteligencia artificial." },
      { title: "IA generativa para negocios", slug: "ia-generativa-para-negocios", status: "published", href: "/aprende/ia-generativa-para-negocios", description: "Evalúa valor, soluciones, costos, gobierno, pilotos y escala con criterios de negocio." },
      ...["Fundamentos de inteligencia artificial", "Selección de modelos de IA", "Diseño de prompts", "Automatización", "Análisis de datos", "Agentes de IA"].map((title) => ({ title, status: "planned" })),
    ],
  },
  {
    title: "Liderazgo y ejecución",
    topics: [
      { title: "Adaptabilidad y resiliencia", slug: "adaptabilidad-resiliencia", status: "published", href: "/aprende/adaptabilidad-resiliencia", description: "Aprende a responder al cambio, desarrollar nuevas capacidades y construir hábitos de aprendizaje sostenibles." },
      { title: "Relaciones y bienestar", slug: "relaciones-y-bienestar", status: "published", href: "/aprende/relaciones-y-bienestar", description: "Aprende a cuidar tu capacidad, fortalecer relaciones profesionales y contribuir a equipos donde sea posible hablar, aprender y trabajar con responsabilidad." },
      ...["Gestión de equipos", "Definición de objetivos", "OKR", "Reuniones efectivas", "Gestión del cambio", "Coaching profesional"].map((title) => ({ title, status: "planned" })),
    ],
  },
];

export const networkingModules = [
  {
    order: 1,
    title: "Por qué importa el networking",
    slug: "por-que-importa",
    description: "Estructura prevista para los fundamentos y el valor de las conexiones profesionales.",
    topics: ["Qué es el networking", "Por qué importan las conexiones profesionales", "Acceso a información y oportunidades", "Mercado laboral oculto", "Dinámicas de las redes profesionales"],
  },
  {
    order: 2,
    title: "Cómo construir una red",
    slug: "como-construir-una-red",
    description: "Estructura prevista para preparar y comenzar a desarrollar una red profesional.",
    topics: ["Definir un objetivo", "Revisar la red existente", "Mejorar el perfil profesional", "Participar en comunidades", "Identificar personas relevantes", "Contactar de manera estratégica"],
  },
  {
    order: 3,
    title: "Entrevistas informativas",
    slug: "entrevistas-informativas",
    description: "Estructura prevista para solicitar, preparar y cerrar conversaciones informativas.",
    topics: ["Qué son", "Para qué sirven", "Cómo solicitar una conversación", "Cómo investigar a la persona", "Cómo preparar preguntas", "Cómo cerrar y hacer seguimiento"],
  },
  {
    order: 4,
    title: "Conversaciones informales",
    slug: "conversaciones-informales",
    description: "Estructura prevista para iniciar conversaciones y mantener vínculos profesionales.",
    topics: ["Diferencias con una entrevista informativa", "Cómo iniciar la conversación", "Cómo demostrar interés genuino", "Cómo escuchar activamente", "Cuándo pedir ayuda", "Cómo mantener el vínculo"],
  },
  {
    order: 5,
    title: "Qué nos impide hacer networking",
    slug: "barreras",
    description: "Estructura prevista para reconocer barreras y definir primeros pasos pequeños.",
    topics: ["Miedo al rechazo", "Sensación de estar molestando", "Incomodidad social", "Falta de claridad", "Síndrome del impostor", "Acciones pequeñas para comenzar"],
  },
].map((module) => ({
  ...module,
  description: networkingLessonContent[module.slug].description,
  href: `/aprende/networking/${module.slug}`,
  contentType: "lesson",
  topic: "networking",
  level: "Introductorio",
  readingTime: networkingLessonContent[module.slug].readingTime,
  updatedAt: "2026-07-14",
  status: "published",
  relatedResources: networkingLessonContent[module.slug].relatedResources,
  relatedTools: ["generador-mensajes-networking"],
}));

export const networkingPath = {
  title: "Networking",
  slug: "networking",
  description: "Aprende a construir relaciones profesionales valiosas, incluso si hoy no tienes una red sólida.",
  contentType: "learning-path",
  topic: "networking",
  status: "published",
  audience: "Estudiantes, profesionales y personas en transición laboral",
  outcomes: ["Definir un objetivo concreto", "Identificar personas relevantes", "Escribir un primer mensaje", "Preparar y conducir conversaciones", "Dar seguimiento con respeto", "Reconocer barreras y comenzar con acciones pequeñas"],
  readingTime: "Aproximadamente 39 minutos",
  level: "Introductorio",
  updatedAt: "2026-07-14",
  format: "Guía práctica",
  modules: networkingModules,
};

export const networkingResources = networkingResourceContent;

export const tools = [
  ...[
    ["clarificar-proposito-equipo","Clarificador de propósito colectivo","Ordena resultado, beneficiario, entregables, límites y evidencia."],
    ["mapear-dependencias-equipo","Mapa de dependencias","Detecta elementos sin dueño, ciclos y puntos únicos de fallo."],
    ["disenar-decision-equipo","Diseñador de derechos de decisión","Aclara autoridad, consulta, evidencia y reversibilidad."],
    ["crear-acuerdos-equipo","Constructor de acuerdos de trabajo","Convierte preferencias y necesidades en acuerdos revisables."],
    ["preparar-desacuerdo-equipo","Preparador de desacuerdo","Separa tema, evidencia, tensión, alternativas, poder y canal."],
    ["registrar-decision-equipo","Registro de decisiones","Documenta opciones, razón, objeciones y condición de reapertura."],
    ["revisar-compromisos-equipo","Revisor de compromisos","Revisa dueño, capacidad, dependencia y evidencia de cierre."],
    ["revisar-ciclo-equipo","Facilitador de revisión de ciclo","Separa hechos, interpretación, condiciones y experimentos."],
    ["observar-dinamica-equipo","Detector de dinámica situacional","Orienta entre conversar, cambiar proceso, documentar o escalar."],
    ["crear-experimento-equipo","Plan de experimento de equipo","Diseña un cambio acotado con señal, revisión e interrupción."],
  ].map(([slug,title,description],index)=>({title,slug,description,contentType:"tool",topic:"Carrera y habilidades profesionales",level:"Introductorio",readingTime:"10–15 minutos",updatedAt:"2026-07-16",featured:index<2,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[
    ["crear-pregunta-investigacion-empresa","Constructor de pregunta de investigación","Delimita una decisión, evidencia mínima y condición de cierre."],
    ["generar-universo-organizaciones","Generador de universo organizacional","Propone categorías y rutas de descubrimiento sin recomendar empresas."],
    ["evaluar-fuente-empresarial","Evaluador de fuentes empresariales","Revisa autoría, fecha, propósito, evidencia y corroboración."],
    ["mapa-evidencia-empresarial","Mapa de evidencia empresarial","Ordena actividad, modelo, contexto, capacidades, movimiento e implicaciones."],
    ["analizar-rol-contexto","Analizador de rol en contexto","Relaciona un puesto con equipo, entregables, dependencias y estrategia."],
    ["comparar-organizaciones","Comparador de organizaciones","Contrasta criterios, evidencia y sensibilidad sin elegir un ganador."],
    ["detectar-contradicciones-empresa","Detector de contradicciones","Expone conflictos entre fuentes y preguntas de verificación."],
    ["planificar-investigacion-empresa","Planificador de próximos pasos","Distingue investigar, conversar, postular, observar, comparar o detener."],
    ["registro-investigacion-empresa","Registro de investigación","Crea un registro local, fechado y copiable sin almacenamiento."],
    ["revisar-privacidad-investigacion","Revisor de privacidad","Identifica datos innecesarios y propone minimización sin asesoría legal."],
  ].map(([slug,title,description],index)=>({title,slug,description,contentType:"tool",topic:"Carrera y habilidades profesionales",level:"Introductorio",readingTime:"10–15 minutos",updatedAt:"2026-07-16",featured:index<2,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[
    ["observador-atencion-conversaciones","Observador de atención","Revisa un cambio de atención en una conversación concreta."],
    ["separar-observacion-interpretacion","Separador de observación e interpretación","Distingue hechos, significados, motivos inferidos y evidencia faltante."],
    ["constructor-preguntas-curiosidad","Constructor de preguntas de curiosidad","Prepara preguntas acotadas y no invasivas."],
    ["preparar-escucha-conversacion","Preparador de escucha","Organiza propósito, apoyos, distracciones y límites."],
    ["filtro-feedback-util","Filtro de feedback útil","Examina evidencia, contexto y decisión sin puntuación."],
    ["revisar-feedback-profesional","Revisor de feedback","Detecta etiquetas, absolutos y motivos supuestos."],
    ["planificar-respuesta-feedback","Planificador de respuesta","Ordena pausa, aclaración, prueba, límite o escalamiento."],
    ["simular-clarificacion-conversacion","Simulador de clarificación","Practica alternativas en escenarios ficticios."],
    ["plan-reparacion-conversacion","Plan de reparación","Decide entre reparar, documentar, escalar o salir."],
    ["plan-practica-escucha-feedback","Plan de práctica deliberada","Diseña un experimento de conducta observable."],
  ].map(([slug,title,description],index)=>({title,slug,description,contentType:"tool",topic:"Carrera y habilidades profesionales",level:"Introductorio",readingTime:"10–15 minutos",updatedAt:"2026-07-16",featured:index<2,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[
    ["diagnostico-senales-profesionales", "Diagnóstico de señales profesionales", "Ordena dirección, evidencia, narrativa, coherencia y evolución."],
    ["inventario-evidencia-profesional", "Inventario de evidencia", "Convierte experiencias anónimas en fichas verificables."],
    ["constructor-contribuciones-profesionales", "Constructor de contribuciones", "Distingue responsabilidad, aporte, contexto y efecto."],
    ["constructor-narrativa-marca-profesional", "Constructor de narrativa profesional", "Prepara versiones sin fabricar contenido."],
    ["revisor-lenguaje-profesional", "Revisor de lenguaje genérico", "Señala afirmaciones que necesitan evidencia."],
    ["mapa-coherencia-profesional", "Mapa de coherencia", "Compara afirmaciones, fechas y pruebas entre canales."],
    ["revisor-perfil-profesional", "Revisor de perfil público", "Revisa propósito, evidencia y privacidad sin puntuación."],
    ["preparar-revision-marca-profesional", "Preparador de revisión por pares", "Crea un encargo de retroalimentación estructurada."],
    ["plan-actualizacion-marca-profesional", "Plan de actualización", "Organiza mantenimiento a partir de cambios reales."],
    ["comparar-canales-profesionales", "Comparador CV–perfil–presentación", "Detecta coincidencias y contradicciones justificables."],
  ].map(([slug,title,description],index)=>({title,slug,description,contentType:"tool",topic:"Carrera y habilidades profesionales",level:"Introductorio",readingTime:"10–15 minutos",updatedAt:"2026-07-16",featured:index<2,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[
    ["diagnostico-marketing-digital", "Diagnóstico de marketing digital", "Identifica fundamentos y brechas con CONECTA."],
    ["crear-estrategia-marketing-digital", "Crear estrategia de marketing digital", "Construye un brief estratégico con objetivos, evidencia y límites."],
    ["mapa-recorrido-cliente", "Mapa del recorrido del cliente", "Organiza preguntas, puntos de contacto y fricciones."],
    ["auditoria-presencia-digital", "Auditoría de presencia digital", "Prioriza observaciones de claridad, acceso y medición."],
    ["seleccionar-canales-marketing", "Selector de canales de marketing", "Compara funciones, recursos, medición y dependencias."],
    ["plan-contenidos-marketing", "Plan de contenidos de marketing", "Diseña un sistema sostenible conectado a preguntas reales."],
    ["plan-medicion-marketing", "Plan de medición de marketing", "Conecta métricas, fuentes y umbrales con decisiones."],
    ["calculadora-metricas-marketing", "Calculadora de métricas de marketing", "Calcula fórmulas locales y explica sus limitaciones."],
  ].map(([slug, title, description]) => ({ title, slug, description, contentType: "tool", topic: "Estrategia y negocios", level: "Introductorio", readingTime: "10 minutos", updatedAt: "2026-07-16", status: "published", href: `/herramientas/${slug}` })),
  ...[["explorador-red-neuronal","Explorador de red neuronal"],["interpretar-curvas-entrenamiento","Intérprete de curvas de entrenamiento"],["elegir-estrategia-ia","Planificador de estrategia de IA"]].map(([slug,title],index)=>({title,slug,description:"Herramienta educativa local, determinista y sin modelos externos.",contentType:"tool",topic:"Datos e inteligencia artificial",level:"Intermedio",readingTime:"10 minutos",updatedAt:"2026-07-16",featured:index===0,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[["comparador-estrategias-optimizacion","Comparador de estrategias de optimización"],["explorador-monte-carlo","Explorador Monte Carlo"],["muestreo-e-intervalos","Muestreo e intervalos"]].map(([slug,title],index)=>({title,slug,description:"Herramienta determinista para aprender con ejemplos locales.",contentType:"tool",topic:"Datos e inteligencia artificial",level:"Intermedio",readingTime:"10 minutos",updatedAt:"2026-07-16",featured:index===0,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[["revision-escalamiento-ia","Revisión de escalamiento"],["alineamiento-escalamiento-ia","Alineamiento de liderazgo"],["disenar-modelo-operativo-ia","Modelo operativo de IA"],["gestionar-portafolio-escalamiento-ia","Portafolio de escalamiento"],["evaluar-componente-reutilizable-ia","Componente reutilizable"],["plan-colaboracion-dominio-ia","Colaboración de dominio"],["plan-democratizacion-ia","Democratización responsable"],["plan-aprendizaje-roles-ia","Aprendizaje por roles"],["tablero-adopcion-ia","Tablero de adopción"],["revisar-portafolio-agentes-ia","Portafolio de agentes"],["crear-hoja-ruta-escalamiento-ia","Hoja de ruta de escalamiento"]].map(([slug,title],index)=>({title,slug,description:"Herramienta local para estructurar evidencia y una próxima decisión.",contentType:"tool",topic:"Datos e inteligencia artificial",level:"Avanzado",readingTime:"10 minutos",updatedAt:"2026-07-16",featured:index<3,order:index+1,status:"published",href:`/herramientas/${slug}`})),
  ...[["mapa-impacto-ia","Mapa de impacto de IA"],["evaluar-uso-sensible-ia","Evaluador de uso sensible"],["revision-equidad-ia","Revisión de equidad"],["plan-proteccion-ia","Plan de protección"],["evaluacion-impacto-ia","Evaluación de impacto"],["disenar-supervision-humana-ia","Supervisión humana"],["disenar-modelo-gobernanza-ia","Modelo de gobernanza"],["inventario-gobernanza-ia","Inventario de IA"],["revision-inclusion-ia","Revisión de inclusión"],["crear-nota-transparencia-ia","Nota de transparencia"],["evaluar-proveedor-ia","Evaluador de proveedor"]].map(([slug,title])=>({title,slug,description:"Herramienta local de IA responsable y gobernanza.",contentType:"tool",status:"published",href:`/herramientas/${slug}`})),
  { title: "Preparación organizacional para IA", slug: "evaluar-preparacion-organizacional-ia", description: "Describe brechas PREPARA sin puntaje.", contentType: "tool", status: "published", href: "/herramientas/evaluar-preparacion-organizacional-ia" },
  { title: "Alineación estratégica de IA", slug: "alinear-iniciativa-ia-estrategia", description: "Crea una hipótesis NORTE.", contentType: "tool", status: "published", href: "/herramientas/alinear-iniciativa-ia-estrategia" },
  { title: "Portafolio de iniciativas de IA", slug: "portafolio-iniciativas-ia", description: "Organiza una iniciativa con IMPULSO.", contentType: "tool", status: "published", href: "/herramientas/portafolio-iniciativas-ia" },
  { title: "Fundamentos de tecnología y datos", slug: "evaluar-base-tecnologia-datos-ia", description: "Identifica capacidades compartidas.", contentType: "tool", status: "published", href: "/herramientas/evaluar-base-tecnologia-datos-ia" },
  { title: "Capacidades organizacionales de IA", slug: "mapa-capacidades-organizacionales-ia", description: "Aclara roles y decisiones.", contentType: "tool", status: "published", href: "/herramientas/mapa-capacidades-organizacionales-ia" },
  { title: "Gobierno organizacional de IA", slug: "disenar-gobierno-organizacional-ia", description: "Crea un plan CUSTODIA.", contentType: "tool", status: "published", href: "/herramientas/disenar-gobierno-organizacional-ia" },
  { title: "Hoja de ruta organizacional de IA", slug: "crear-hoja-ruta-organizacional-ia", description: "Ordena brechas y dependencias.", contentType: "tool", status: "published", href: "/herramientas/crear-hoja-ruta-organizacional-ia" },
  { title: "Proceso de entrega de IA", slug: "disenar-proceso-entrega-ia", description: "Diseña un proceso repetible.", contentType: "tool", status: "published", href: "/herramientas/disenar-proceso-entrega-ia" },
  { title: "Adopción organizacional de IA", slug: "plan-adopcion-organizacional-ia", description: "Conecta cambio y aprendizaje.", contentType: "tool", status: "published", href: "/herramientas/plan-adopcion-organizacional-ia" },
  { title: "Monitor de portafolio de IA", slug: "monitorear-portafolio-ia", description: "Prepara decisiones de continuidad y retiro.", contentType: "tool", status: "published", href: "/herramientas/monitorear-portafolio-ia" },
  { title: "Mapa de confiabilidad de IA", slug: "mapa-confiabilidad-ia", description: "Representa la cadena completa y sus controles críticos.", contentType: "tool", status: "published", href: "/herramientas/mapa-confiabilidad-ia" },
  { title: "Diseñador de plantilla de prompt", slug: "disenar-plantilla-prompt", description: "Crea una especificación NORMA versionada.", contentType: "tool", status: "published", href: "/herramientas/disenar-plantilla-prompt" },
  { title: "Evaluador de fuentes para IA", slug: "evaluar-fuentes-ia", description: "Revisa autoridad, vigencia y acceso con VIGENTE.", contentType: "tool", status: "published", href: "/herramientas/evaluar-fuentes-ia" },
  { title: "Diseñador de flujo RAG", slug: "disenar-flujo-rag", description: "Mapea fuentes, permisos, recuperación y generación.", contentType: "tool", status: "published", href: "/herramientas/disenar-flujo-rag" },
  { title: "Evaluador de preparación de datos", slug: "evaluar-preparacion-datos-ia", description: "Organiza una revisión PREPARA sin puntuaciones.", contentType: "tool", status: "published", href: "/herramientas/evaluar-preparacion-datos-ia" },
  { title: "Revisión de seguridad para IA", slug: "revision-seguridad-ia", description: "Identifica preguntas de control sin auditar.", contentType: "tool", status: "published", href: "/herramientas/revision-seguridad-ia" },
  { title: "Selector de método de IA", slug: "elegir-metodo-ia", description: "Compara generación, predicción, búsqueda y reglas.", contentType: "tool", status: "published", href: "/herramientas/elegir-metodo-ia" },
  { title: "Plan de evaluación de IA", slug: "plan-evaluacion-ia", description: "Separa componentes, sistema, negocio y riesgo.", contentType: "tool", status: "published", href: "/herramientas/plan-evaluacion-ia" },
  { title: "Planificador del ciclo de vida", slug: "plan-ciclo-vida-modelo", description: "Conecta versiones, monitoreo, cambios y retiro.", contentType: "tool", status: "published", href: "/herramientas/plan-ciclo-vida-modelo" },
  { title: "Diseñador de operación de IA", slug: "disenar-operacion-ia", description: "Asigna responsabilidades con RESPONDE.", contentType: "tool", status: "published", href: "/herramientas/disenar-operacion-ia" },
  { title: "Evaluador de oportunidad de IA", slug: "evaluar-oportunidad-ia", description: "Ordena una oportunidad con VALORA antes de elegir tecnología.", contentType: "tool", status: "published", href: "/herramientas/evaluar-oportunidad-ia" },
  { title: "Selector de patrón de IA", slug: "seleccionar-enfoque-ia", description: "Compara modalidad, recuperación e integración sin recomendar proveedores.", contentType: "tool", status: "published", href: "/herramientas/seleccionar-enfoque-ia" },
  { title: "Selector de solución de IA", slug: "elegir-solucion-ia", description: "Orienta entre configurar, integrar, construir o diferir.", contentType: "tool", status: "published", href: "/herramientas/elegir-solucion-ia" },
  { title: "Evaluador de agentes", slug: "evaluar-agente-negocio", description: "Revisa autonomía, permisos y salvaguardas con AUTORIZA.", contentType: "tool", status: "published", href: "/herramientas/evaluar-agente-negocio" },
  { title: "Calculadora de economía de IA", slug: "calculadora-economia-ia", description: "Compara costo total y beneficios bajo tres escenarios.", contentType: "tool", status: "published", href: "/herramientas/calculadora-economia-ia" },
  { title: "Planificador de gobernanza de IA", slug: "disenar-gobernanza-ia", description: "Organiza controles y responsables con GUARDA.", contentType: "tool", status: "published", href: "/herramientas/disenar-gobernanza-ia" },
  { title: "Diseñador de pilotos de IA", slug: "disenar-piloto-ia", description: "Crea un piloto limitado con métricas y condiciones de parada.", contentType: "tool", status: "published", href: "/herramientas/disenar-piloto-ia" },
  { title: "Plan de adopción de IA", slug: "crear-plan-adopcion-ia", description: "Alinea roles, formación, soporte y aprendizaje.", contentType: "tool", status: "published", href: "/herramientas/crear-plan-adopcion-ia" },
  { title: "Evaluador de escala de IA", slug: "evaluar-escala-ia", description: "Revisa evidencia, operación y reversibilidad antes de ampliar.", contentType: "tool", status: "published", href: "/herramientas/evaluar-escala-ia" },
  {
    title: "Generador de mensajes de networking",
    slug: "generador-mensajes-networking",
    description: "Prepara un primer mensaje profesional, breve y adaptado al canal y tono que elijas.",
    contentType: "tool",
    status: "published",
    href: "/herramientas/generador-mensajes-networking",
  },
  {
    title: "Constructor de bullets para consultoría",
    slug: "constructor-bullets-consultoria",
    description: "Convierte acciones y resultados verificables en variaciones claras para tu CV, sin inventar métricas.",
    contentType: "tool",
    status: "published",
    href: "/herramientas/constructor-bullets-consultoria",
  },
  {
    title: "Práctica de market sizing", slug: "practica-market-sizing", description: "Genera prompts originales y contrasta tu lógica con una estructura modelo.", contentType: "tool", status: "published", href: "/herramientas/practica-market-sizing",
  },
  {
    title: "Diseñador de experimentos de negocio", slug: "disenador-experimentos-negocio", description: "Construye un brief con tratamiento, comparación, métricas, economía y riesgos.", contentType: "tool", status: "published", href: "/herramientas/disenador-experimentos-negocio",
  },
  {
    title: "Constructor de estructuras de caso", slug: "constructor-estructuras-caso", description: "Crea una plantilla inicial adaptable a la decisión y la métrica del caso.", contentType: "tool", status: "published", href: "/herramientas/constructor-estructuras-caso",
  },
  {
    title: "Seguimiento de práctica de casos", slug: "seguimiento-practica-casos", description: "Registra feedback temporal y define el siguiente drill correctivo.", contentType: "tool", status: "published", href: "/herramientas/seguimiento-practica-casos",
  },
  { title: "Constructor de intenciones de aprendizaje", slug: "constructor-intenciones-aprendizaje", description: "Convierte una capacidad en una intención y una primera práctica.", contentType: "tool", status: "published", href: "/herramientas/constructor-intenciones-aprendizaje" },
  { title: "Reencuadrar un desafío", slug: "reencuadrar-desafio", description: "Separa hechos, interpretación, acción, apoyo y límites con OPA.", contentType: "tool", status: "published", href: "/herramientas/reencuadrar-desafio" },
  { title: "Planificador de hábitos de aprendizaje", slug: "planificador-habitos-aprendizaje", description: "Diseña una rutina pequeña con prevención y recuperación.", contentType: "tool", status: "published", href: "/herramientas/planificador-habitos-aprendizaje" },
  { title: "Plan de adaptabilidad", slug: "plan-adaptabilidad", description: "Construye un ciclo personal de cuatro semanas.", contentType: "tool", status: "published", href: "/herramientas/plan-adaptabilidad" },
  { title: "Diario de aprendizaje", slug: "diario-aprendizaje", description: "Procesa una experiencia y define el próximo experimento.", contentType: "tool", status: "published", href: "/herramientas/diario-aprendizaje" },
  { title: "Diagnóstico de profundidad del problema", slug: "diagnostico-tipo-problema", description: "Orienta la profundidad según urgencia, incertidumbre y consecuencia.", contentType: "tool", status: "published", href: "/herramientas/diagnostico-tipo-problema" },
  { title: "Constructor de definición del problema", slug: "definir-problema", description: "Crea una pregunta CLARO y un lienzo revisable.", contentType: "tool", status: "published", href: "/herramientas/definir-problema" },
  { title: "Constructor de árbol lógico", slug: "constructor-arbol-problemas", description: "Organiza ramas, hipótesis y evidencia con controles accesibles.", contentType: "tool", status: "published", href: "/herramientas/constructor-arbol-problemas" },
  { title: "Priorizador de análisis", slug: "priorizar-analisis", description: "Ordena preguntas mediante VERA, esfuerzo y dependencias.", contentType: "tool", status: "published", href: "/herramientas/priorizar-analisis" },
  { title: "Constructor de plan de trabajo", slug: "plan-trabajo-problema", description: "Conecta pregunta, análisis, fuente, responsable y regla de parada.", contentType: "tool", status: "published", href: "/herramientas/plan-trabajo-problema" },
  { title: "Constructor de recomendaciones", slug: "constructor-recomendaciones", description: "Convierte hallazgos en HIA y una recomendación DECIR.", contentType: "tool", status: "published", href: "/herramientas/constructor-recomendaciones" },
  { title: "Revisión de sesgos y decisión", slug: "revision-sesgos-decision", description: "Busca evidencia contraria, perspectivas y supuestos antes de cerrar.", contentType: "tool", status: "published", href: "/herramientas/revision-sesgos-decision" },
  { title: "Mapa de audiencia", slug: "mapa-audiencia", description: "Prepara preguntas sobre conocimiento, intereses, inquietudes y autoridad.", contentType: "tool", status: "published", href: "/herramientas/mapa-audiencia" },
  { title: "Práctica de escucha activa", slug: "practica-escucha-activa", description: "Ensaya una respuesta y revísala con CAPTA sin puntuaciones de empatía.", contentType: "tool", status: "published", href: "/herramientas/practica-escucha-activa" },
  { title: "Propósito de comunicación", slug: "definir-proposito-comunicacion", description: "Convierte un tema en una finalidad, relevancia y siguiente paso.", contentType: "tool", status: "published", href: "/herramientas/definir-proposito-comunicacion" },
  { title: "Constructor de insights", slug: "convertir-datos-en-insight", description: "Separa evidencia, interpretación, consecuencia y acción con DICA.", contentType: "tool", status: "published", href: "/herramientas/convertir-datos-en-insight" },
  { title: "Estructurador de mensajes", slug: "estructurar-mensaje", description: "Crea versiones breves y ampliadas con NÚCLEO.", contentType: "tool", status: "published", href: "/herramientas/estructurar-mensaje" },
  { title: "Constructor de narrativa profesional", slug: "constructor-narrativa-profesional", description: "Organiza cambio, evidencia y respuesta mediante CAMBIO.", contentType: "tool", status: "published", href: "/herramientas/constructor-narrativa-profesional" },
  { title: "Preparador de presentaciones", slug: "preparar-presentacion", description: "Diseña ensayo, revisión VIVA y preparación de preguntas.", contentType: "tool", status: "published", href: "/herramientas/preparar-presentacion" },
  { title: "Planificador de reuniones", slug: "planificar-reunion", description: "Crea agenda AFO, participación y registro de acciones.", contentType: "tool", status: "published", href: "/herramientas/planificar-reunion" },
  { title: "Mapa de bienestar en contexto", slug: "mapa-bienestar-contexto", description: "Separa acciones personales, conversaciones y condiciones organizacionales.", contentType: "tool", status: "published", href: "/herramientas/mapa-bienestar-contexto" },
  { title: "Mapa de energía y recuperación", slug: "mapa-energia-recuperacion", description: "Describe efectos temporales y posibles ventanas de recuperación.", contentType: "tool", status: "published", href: "/herramientas/mapa-energia-recuperacion" },
  { title: "Plan de práctica sostenible", slug: "plan-practica-sostenible", description: "Diseña una práctica PASO pequeña y reiniciable.", contentType: "tool", status: "published", href: "/herramientas/plan-practica-sostenible" },
  { title: "Preparar un límite profesional", slug: "preparar-limite-profesional", description: "Organiza necesidad, margen, alternativa y escalamiento.", contentType: "tool", status: "published", href: "/herramientas/preparar-limite-profesional" },
  { title: "Conversación de relación", slug: "preparar-conversacion-relacion", description: "Prepara claridad, perspectiva, petición y reparación con CERCA.", contentType: "tool", status: "published", href: "/herramientas/preparar-conversacion-relacion" },
  { title: "Conversación difícil", slug: "preparar-conversacion-dificil", description: "Construye un plan HABLAR y revisa seguridad y poder.", contentType: "tool", status: "published", href: "/herramientas/preparar-conversacion-dificil" },
  { title: "Reflexión sobre seguridad de equipo", slug: "reflexion-seguridad-equipo", description: "Observa patrones con VOCES sin emitir puntuaciones o diagnósticos.", contentType: "tool", status: "published", href: "/herramientas/reflexion-seguridad-equipo" },
  { title: "Diseñar prácticas de equipo", slug: "disenar-practicas-equipo", description: "Crea una norma y un experimento EQUIPO revisable.", contentType: "tool", status: "published", href: "/herramientas/disenar-practicas-equipo" },
  { title: "Plan de relaciones y bienestar", slug: "plan-relaciones-bienestar", description: "Integra acciones personales, relacionales, de equipo y organizacionales.", contentType: "tool", status: "published", href: "/herramientas/plan-relaciones-bienestar" },
  { title: "Diagnóstico de prospección B2B", slug: "diagnostico-prospeccion-b2b", description: "Detecta fundamentos ausentes y decide por dónde comenzar.", contentType: "tool", status: "published", href: "/herramientas/diagnostico-prospeccion-b2b" },
  { title: "Definir cliente ideal B2B", slug: "definir-cliente-ideal-b2b", description: "Construye un ICP, exclusiones y roles de compra sin falsa precisión.", contentType: "tool", status: "published", href: "/herramientas/definir-cliente-ideal-b2b" },
  { title: "Crear propuesta de valor B2B", slug: "crear-propuesta-valor-b2b", description: "Formula una hipótesis de cambio con evidencia e incertidumbre.", contentType: "tool", status: "published", href: "/herramientas/crear-propuesta-valor-b2b" },
  { title: "Crear mensaje de prospección B2B", slug: "crear-mensaje-prospeccion-b2b", description: "Prepara un primer contacto claro, verificable y respetuoso.", contentType: "tool", status: "published", href: "/herramientas/crear-mensaje-prospeccion-b2b" },
  { title: "Crear secuencia de prospección", slug: "crear-secuencia-prospeccion", description: "Coordina canales, aportes, tiempos y una regla de salida.", contentType: "tool", status: "published", href: "/herramientas/crear-secuencia-prospeccion" },
  { title: "Preparar respuestas a objeciones", slug: "preparar-respuestas-objeciones", description: "Decide cuándo aclarar, aportar, pausar, derivar o cerrar.", contentType: "tool", status: "published", href: "/herramientas/preparar-respuestas-objeciones" },
  { title: "Calculadora de prospección B2B", slug: "calculadora-prospeccion-b2b", description: "Estima actividad con tasas, sensibilidad y advertencias explícitas.", contentType: "tool", status: "published", href: "/herramientas/calculadora-prospeccion-b2b" },
  { title: "Tablero de prospección B2B", slug: "tablero-prospeccion-b2b", description: "Interpreta el embudo con tasas y denominadores claros.", contentType: "tool", status: "published", href: "/herramientas/tablero-prospeccion-b2b" },
  { title: "Clarificador de objetivo", slug: "clarificador-entrevista-informativa", description: "Convierte una incertidumbre amplia en una pregunta de aprendizaje.", contentType: "tool", status: "published", href: "/herramientas/clarificador-entrevista-informativa" },
  { title: "Mapa de perspectivas", slug: "mapa-perspectivas-profesionales", description: "Identifica perspectivas directas, adyacentes y contrastantes.", contentType: "tool", status: "published", href: "/herramientas/mapa-perspectivas-profesionales" },
  { title: "Clasificador de preguntas", slug: "clasificador-preguntas-entrevista", description: "Distingue preguntas públicas, contextuales, experienciales y reflexivas.", contentType: "tool", status: "published", href: "/herramientas/clasificador-preguntas-entrevista" },
  { title: "Constructor de solicitud informativa", slug: "constructor-solicitud-entrevista-informativa", description: "Prepara una invitación transparente y fácil de rechazar.", contentType: "tool", status: "published", href: "/herramientas/constructor-solicitud-entrevista-informativa" },
  { title: "Revisor de presión y claridad", slug: "revisor-solicitud-entrevista", description: "Detecta riesgos de presión con reglas locales explícitas.", contentType: "tool", status: "published", href: "/herramientas/revisor-solicitud-entrevista" },
  { title: "Planificador de conversación informativa", slug: "planificador-conversacion-informativa", description: "Crea una tarjeta flexible de preguntas, límites y cierre.", contentType: "tool", status: "published", href: "/herramientas/planificador-conversacion-informativa" },
  { title: "Preparador de evento profesional", slug: "preparador-evento-profesional", description: "Organiza atención, descansos y conversaciones en grupo.", contentType: "tool", status: "published", href: "/herramientas/preparador-evento-profesional" },
  { title: "Registro de aprendizajes", slug: "registro-aprendizajes-conversacion", description: "Separa observaciones, interpretaciones y asuntos por verificar.", contentType: "tool", status: "published", href: "/herramientas/registro-aprendizajes-conversacion" },
  { title: "Comparador de perspectivas", slug: "comparador-perspectivas-profesionales", description: "Contrasta acuerdos, diferencias y límites contextuales.", contentType: "tool", status: "published", href: "/herramientas/comparador-perspectivas-profesionales" },
  { title: "Decisor de seguimiento", slug: "decisor-seguimiento-profesional", description: "Orienta entre agradecer, actualizar, esperar, preguntar o cerrar.", contentType: "tool", status: "published", href: "/herramientas/decisor-seguimiento-profesional" },
  ...["Matriz de priorización", "Evaluador de mensajes", "Mapa de networking", "Herramientas de estrategia", "Herramientas de inteligencia artificial"].map((title) => ({ title, contentType: "tool", status: "planned" })),
];

export const getNetworkingModule = (slug) => networkingModules.find((module) => module.slug === slug);
import { networkingLessonContent, networkingResourceContent } from "./networkingContent.js";
