export const informationalBase = "/aprende/entrevistas-informativas";
export const informationalLastReviewed = "2026-07-16";

const framework = (...items) => items.map(([title, text]) => ({ title, text }));
const exercise = (title, prompt, help) => ({ title, prompt, help });
const lesson = (order, slug, title, description, outcomes, sections, relatedTools = []) => ({
  order, slug, title, description, outcomes, sections, relatedTools,
  href: `${informationalBase}/${slug}`, level: order < 4 ? "Inicial" : order < 9 ? "Intermedio" : "Aplicado",
  readingTime: `${10 + (order % 5)}–${15 + (order % 5)} minutos`, updatedAt: informationalLastReviewed,
  lastReviewed: informationalLastReviewed, status: "published",
});

export const informationalToolLinks = {
  objective: { title: "Clarificador de objetivo", href: "/herramientas/clarificador-entrevista-informativa", description: "Convierte una incertidumbre amplia en una pregunta de aprendizaje." },
  perspectives: { title: "Mapa de perspectivas", href: "/herramientas/mapa-perspectivas-profesionales", description: "Identifica perspectivas directas, adyacentes y contrastantes." },
  questions: { title: "Clasificador de preguntas", href: "/herramientas/clasificador-preguntas-entrevista", description: "Distingue preguntas públicas, contextuales, experienciales y reflexivas." },
  request: { title: "Constructor de solicitud", href: "/herramientas/constructor-solicitud-entrevista-informativa", description: "Prepara una invitación transparente y fácil de rechazar." },
  pressure: { title: "Revisor de presión y claridad", href: "/herramientas/revisor-solicitud-entrevista", description: "Detecta riesgos de presión mediante reglas locales explícitas." },
  conversation: { title: "Planificador de conversación", href: "/herramientas/planificador-conversacion-informativa", description: "Crea una tarjeta flexible de preguntas, límites y cierre." },
  event: { title: "Preparador de evento profesional", href: "/herramientas/preparador-evento-profesional", description: "Organiza atención, descansos y conversaciones en grupo." },
  record: { title: "Registro de aprendizajes", href: "/herramientas/registro-aprendizajes-conversacion", description: "Separa observaciones, interpretaciones y asuntos por verificar." },
  compare: { title: "Comparador de perspectivas", href: "/herramientas/comparador-perspectivas-profesionales", description: "Contrasta acuerdos, diferencias y límites contextuales." },
  followup: { title: "Decisor de seguimiento", href: "/herramientas/decisor-seguimiento-profesional", description: "Orienta entre agradecer, actualizar, esperar, preguntar o cerrar." },
};

export const informationalPath = {
  title: "Entrevistas informativas",
  description: "Aprende de otras trayectorias, contrasta decisiones de carrera y construye relaciones profesionales con respeto.",
  definition: "Una entrevista informativa es una conversación acotada para comprender una experiencia profesional, contrastar una hipótesis y decidir qué investigar o probar después. No es una entrevista de selección ni una solicitud indirecta de empleo.",
  audience: "Estudiantes, profesionales en transición y personas que exploran funciones, sectores o mercados",
  format: "Ruta práctica con casos, recursos y herramientas",
  effort: "Entre 2 y 4 horas de lectura y práctica, según el punto de partida",
  outcomes: ["Convertir incertidumbre en preguntas", "Elegir perspectivas con límites claros", "Invitar y conversar sin presión", "Comparar evidencia sin sobregeneralizar"],
};

const purposeMap = framework(
  ["Aprendizaje buscado", "Incertidumbre, supuesto o decisión que necesita mejor evidencia."],
  ["Perspectiva adecuada", "Experiencia que puede iluminar la pregunta y límites de esa mirada."],
  ["Preparación suficiente", "Información pública que conviene revisar antes de pedir tiempo."],
  ["Conversación útil", "Escucha, preguntas y aclaraciones que producen contexto sin interrogar."],
  ["Próximo paso razonado", "Investigación, comparación, experimento o decisión posterior."],
);
const depthScale = framework(
  ["Público", "Dato verificable en fuentes fiables antes de la conversación."],
  ["Contextual", "Forma en que ese dato se manifiesta en un entorno concreto."],
  ["Experiencial", "Situaciones, aprendizajes y dificultades que la persona ha observado."],
  ["Reflexivo", "Interpretación de cambios, tensiones y caminos posibles."],
);

const focusedQuestions = [
  "Conocer personas de tecnología", "Entender cómo es marketing", "Explorar otra industria", "Saber si necesito estudiar", "Hablar con alguien senior", "Conseguir orientación profesional",
].map((title, index) => ({ id: `objetivo-${index + 1}`, title, situation: `Una persona declara: “${title}”.`, question: "¿Qué decisión o supuesto necesita evidencia?", action: "Define una incertidumbre, evidencia faltante y qué cambiaría después de conversar.", constraint: "No pidas a la otra persona decidir tu carrera ni resolver todos los temas." }));

export const informationalLessons = [
  lesson(1, "definir-aprendizaje", "Decidir qué necesitas aprender", "Comienza con una decisión o incertidumbre, no con una lista de contactos.", ["Separar curiosidad, supuesto y decisión", "Formular un objetivo acotado", "Definir evidencia y límites"], [
    { title: "De la curiosidad a una decisión", paragraphs: ["Una entrevista informativa es una conversación para aprender. No es una entrevista de selección ni una solicitud indirecta de empleo, referencia o acceso privilegiado.", "La conversación aporta evidencia y contexto, pero no delega la decisión profesional en la persona entrevistada.", "La curiosidad abre un tema; la incertidumbre identifica lo desconocido; un supuesto propone una explicación provisional; una decisión exige escoger un siguiente paso. Una conversación resulta más útil cuando sabes cuál de estas tareas estás realizando.", "“Cuéntame tu carrera” deja todo el trabajo a la otra persona. Una pregunta enfocada nombra el rol o transición, el supuesto que quieres contrastar y qué harás con lo aprendido."] },
    { title: "Mapa de conversación con propósito", framework: purposeMap, callout: { title: "Modelo práctico", text: "Este modelo fue creado para organizar esta ruta. No es un estándar, una certificación ni una garantía de resultados." } },
    { title: "Lienzo de decisión", questionGroups: [{ title: "Pregunta", items: ["¿Qué decisión o incertidumbre tengo?", "¿Qué supuesto estoy usando?", "¿Qué evidencia ya existe y cuál falta?"] }, { title: "Límite", items: ["¿Qué perspectiva podría ayudar?", "¿Qué resultado sería útil?", "¿Qué no corresponde preguntar?"] }], exercise: exercise("Seis metas vagas", "Convierte cada objetivo del taller en una pregunta que pueda orientar una conversación.", "Una conversación no necesita responder todas tus dudas.") },
    { title: "Taller de enfoque", scenarios: focusedQuestions, callout: { title: "Errores frecuentes", text: "Empezar por nombres, buscar validación, confundir prestigio con relevancia o pedir a otra persona que tome la decisión." }, links: [{ label: "Ver fundamentos de networking", href: "/aprende/networking/por-que-importa" }] },
  ], ["objective"]),

  lesson(2, "elegir-perspectivas", "Elegir perspectivas relevantes", "Construye una combinación manejable de experiencias directas, adyacentes y contrastantes.", ["Priorizar relevancia sobre jerarquía", "Reconocer límites de cada perspectiva", "Evitar investigación intrusiva"], [
    { title: "La mejor perspectiva depende de la pregunta", paragraphs: ["Un cargo famoso no garantiza conocimiento pertinente. Compara función, etapa, entorno, transición y actualidad de la experiencia. Una persona cercana al trabajo cotidiano puede describir tensiones que una mirada directiva no observa, y viceversa."], comparison: { leftTitle: "Perspectiva directa", leftItems: ["Realiza hoy el trabajo", "Conoce rutinas y tensiones", "Puede reflejar un solo entorno"], rightTitle: "Perspectiva contrastante", rightItems: ["Vivió otra etapa o función", "Cuestiona supuestos", "Puede basarse en un contexto diferente"] } },
    { title: "Matriz cualitativa", bullets: ["Relevancia para la pregunta", "Actualidad de la experiencia", "Diversidad de contexto", "Accesibilidad respetuosa", "Puntos ciegos probables", "Relación existente", "Proporción de la solicitud"], callout: { title: "No es un puntaje de personas", text: "La matriz organiza decisiones; no mide valor profesional ni predice quién responderá." } },
    { title: "Portafolio pequeño y equilibrado", exercise: exercise("Elegir cuatro perspectivas", "Para una transición ficticia, elige cuatro de diez perfiles genéricos y justifica las exclusiones.", "Incluye experiencia directa, adyacente y contrastante sin pedir todo a una sola persona."), example: { title: "Caso ficticio", text: "Inés explora logística sostenible. Prefiere conversar con una analista operativa, una responsable de compras, una persona que dejó el área y un especialista regulatorio, no solo con gerentes." } },
    { title: "Privacidad y límites", bullets: ["Usa información profesional pública y pertinente.", "No infieras rasgos personales.", "No extraigas perfiles ni construyas listas automatizadas.", "Una relación cálida no crea obligación.", "Una solicitud fría puede ser legítima si es transparente y acotada."], links: [{ label: "Construir una red con respeto", href: "/aprende/networking/como-construir-una-red" }] },
  ], ["perspectives"]),

  lesson(3, "investigar-antes", "Investigar antes de contactar", "Prepárate lo suficiente para evitar preguntas obvias sin convertir la búsqueda en vigilancia.", ["Separar investigación y experiencia", "Aplicar la escala de profundidad", "Definir una regla de suficiencia"], [
    { title: "Dos frentes de preparación", bullets: ["Sobre ti: contexto breve, exploración actual, experiencia relevante, conocimiento previo e incertidumbre.", "Sobre el tema: sitio oficial, descripción pública del rol, informes primarios, material auténticamente publicado por la persona y contexto sectorial."], paragraphs: ["Explicar incertidumbre no requiere disculparse. Describe qué sabes, qué no y por qué esta perspectiva podría ayudar."] },
    { title: "Escala de profundidad de preguntas", framework: depthScale, callout: { title: "Modelo práctico", text: "Esta escala fue creada para esta ruta. No es un estándar, una certificación ni una garantía de resultados. Investiga el nivel público para dedicar la conversación a contexto, experiencia y reflexión." } },
    { title: "Regla de preparación suficiente", paragraphs: ["Detén la investigación cuando puedas explicar por qué la persona es relevante, evitar preguntas evidentes y señalar tres asuntos donde su experiencia añade contexto. Investigar más no siempre mejora la conversación."], exercise: exercise("Clasificar preguntas", "Clasifica preguntas como públicas, contextuales, experienciales, reflexivas, especulativas o inapropiadas.", "Una pregunta confidencial no mejora por reformularla; debe eliminarse.") },
    { title: "Ejemplo y límites", example: { title: "Caso ficticio", text: "Tomás leyó una descripción oficial de producto. En vez de preguntar qué hace el rol, pregunta qué tensiones cambian entre lanzamiento y operación." }, bullets: ["No menciones detalles personales irrelevantes.", "No repitas promociones como hechos.", "No finjas haber leído material que no revisaste.", "Verifica fecha y procedencia de la información."], links: [{ label: "Mejorar la investigación de problemas", href: "/aprende/resolucion-de-problemas" }] },
  ], ["questions"]),

  lesson(4, "invitar-sin-presionar", "Invitar sin presionar", "Escribe solicitudes transparentes, acotadas y fáciles de rechazar.", ["Aplicar contexto, motivo y salida fácil", "Adaptar canal y relación", "Saber cuándo no insistir"], [
    { title: "Contexto, motivo y salida fácil", framework: framework(["Contexto verdadero", "Relación, evento o situación de exploración que existe."], ["Motivo específico", "Razón por la que esa perspectiva es pertinente."], ["Tema de aprendizaje", "Pregunta acotada que no disfraza una postulación."], ["Solicitud limitada", "Formato y rango de tiempo razonables."], ["Salida fácil", "Forma explícita de declinar o no responder."]), callout: { title: "Guía flexible", text: "No es una plantilla obligatoria. Ajusta extensión y tono sin inventar cercanía, urgencia ni detalles personales." } },
    { title: "Mostrar, no ocultar", comparison: { leftTitle: "Solicitud problemática", leftItems: ["Biografía extensa", "Propósito ambiguo", "Varios favores", "Urgencia artificial", "Pide empleo o referencia"], rightTitle: "Solicitud mejorada", rightItems: ["Contexto suficiente", "Pregunta concreta", "Un formato acotado", "Declinación cómoda", "Cierre respetuoso"] } },
    { title: "Una sola insistencia puede ser suficiente", paragraphs: ["Si no hay respuesta, un seguimiento breve puede confirmar recepción cuando el contexto lo justifica. Después, cierra. Una negativa se agradece sin pedir explicación; una oferta de otro formato se evalúa según el mismo objetivo y límites."], exercise: exercise("Revisar cinco solicitudes", "Detecta propósito oculto, exceso de contexto, elogio artificial, múltiples pedidos y ausencia de salida.", "Escribe una versión que la otra persona pueda responder en una frase.") },
    { title: "Nueve contextos", bullets: ["Estudiante que explora una función", "Transición a mitad de carrera", "Profesional independiente que estudia un sector", "Contacto de evento", "Presentación mutua", "Solicitud contextual sin conexión", "Conversación entre países", "Retomar después de tiempo", "Solicitud que no debe enviarse"], example: { title: "Caso ficticio", text: "Amara conoció brevemente a una ponente. Menciona el tema compartido, no afirma que se conocen, y pregunta si aceptaría responder dos preguntas por escrito." }, links: [{ label: "Practicar mensajes de networking", href: "/herramientas/generador-mensajes-networking" }] },
  ], ["request", "pressure"]),

  lesson(5, "disenar-conversacion", "Diseñar una conversación flexible", "Prepara una arquitectura adaptable sin memorizar un interrogatorio.", ["Acordar foco y tiempo", "Priorizar preguntas", "Cerrar con síntesis"], [
    { title: "Flujo adaptable", ordered: ["Acordar el foco y confirmar el tiempo disponible.", "Dar contexto suficiente sobre la exploración.", "Explorar experiencia, decisiones y realidad del trabajo.", "Profundizar con ejemplos, condiciones y excepciones.", "Cerrar con una síntesis y un siguiente paso apropiado."], callout: { title: "Sin cronómetro rígido", text: "El flujo orienta atención; no asigna minutos obligatorios. Pide permiso antes de exceder el tiempo acordado." } },
    { title: "Variantes de formato", bullets: ["Conversación de unos 10 minutos", "Conversación de 20–30 minutos", "Espacio de aproximadamente 45 minutos", "Intercambio escrito asincrónico", "Encuentro breve tras un evento", "Mesa grupal", "Reunión acortada", "Conversación que podría extenderse"], paragraphs: ["Expresa el tiempo como rango o disponibilidad, no como derecho. Si el encuentro se acorta, conserva una pregunta prioritaria y el cierre."] },
    { title: "Tarjeta de preparación", questionGroups: [{ title: "Núcleo", items: ["Pregunta principal", "Contexto breve", "Tres preguntas prioritarias"] }, { title: "Flexibilidad", items: ["Dos seguimientos opcionales", "Un límite", "Frase de cierre", "Plan de notas"] }], exercise: exercise("Recortar el plan", "Reduce una lista de doce preguntas a tres prioritarias y dos opcionales.", "Las preguntas no utilizadas pueden alimentar otra conversación.") },
    { title: "Ejemplo y errores", example: { title: "Caso ficticio", text: "Rafael tenía ocho preguntas sobre ciberseguridad. Al saber que la reunión duraría diez minutos, conserva una sobre el trabajo cotidiano, otra sobre barreras de entrada y una sobre qué verificar después." }, bullets: ["No recites un discurso.", "No cubras la lista ignorando respuestas.", "No conviertas el cierre en una petición automática de referencia."] },
  ], ["conversation"]),

  lesson(6, "escuchar-y-profundizar", "Escuchar, preguntar y profundizar", "Convierte respuestas generales en evidencia contextual sin invadir ni discutir.", ["Escuchar ejemplos y excepciones", "Separar observación e interpretación", "Reformular preguntas problemáticas"], [
    { title: "La calidad ocurre durante la respuesta", bullets: ["Toma notas breves sin dejar de escuchar.", "Pide un ejemplo cuando una afirmación sea general.", "Pregunta qué cambia según equipo o etapa.", "Explora tensiones y excepciones.", "Separa lo observado de la interpretación.", "Redirige si la conversación se vuelve una entrevista de selección."], paragraphs: ["Escuchar activamente no exige señales teatrales. Resume con tus palabras, pregunta si entendiste y acepta que un consejo puede no encajar contigo."] },
    { title: "Biblioteca por propósito", questionGroups: [{ title: "Trabajo y decisiones", items: ["¿Qué problemas ocupan más atención de la que imaginabas?", "¿Qué decisión se vuelve más difícil con la experiencia?", "¿Qué cambia entre organizaciones?"] }, { title: "Trayectoria y aprendizaje", items: ["¿Qué capacidad previa resultó transferible?", "¿Qué aprendiste solo al trabajar en el área?", "¿Qué idea sobre el rol tuviste que revisar?"] }, { title: "Condiciones y futuro", items: ["¿Qué condiciones permiten hacer bien el trabajo?", "¿Qué barreras suelen subestimarse?", "¿Qué fuente recomendarías contrastar después?"] }] },
    { title: "Preguntas que conviene reformular", comparison: { leftTitle: "Riesgo", leftItems: ["Demasiado amplia", "Disponible públicamente", "Pide información confidencial", "Presiona a evaluar al usuario", "Supone un camino único", "Pide predecir contratación"], rightTitle: "Reformulación", rightItems: ["Acota una situación", "Usa el dato como contexto", "Pregunta por criterios generales", "Pide experiencia, no evaluación", "Explora alternativas", "Pregunta qué evidencia falta"] } },
    { title: "Práctica de escucha", exercise: exercise("Leer un diálogo ficticio", "Marca dónde la persona pudo pedir un ejemplo, aclarar una excepción, sintetizar o cerrar un tema incómodo.", "Puede haber varias intervenciones razonables."), example: { title: "Caso ficticio", text: "Cuando Elena oye “aquí todos programan”, no concluye que sea una regla del sector: pregunta qué significa programar en ese equipo y qué tareas requieren mayor profundidad." }, links: [{ label: "Practicar escucha activa", href: "/herramientas/practica-escucha-activa" }] },
  ], ["questions", "conversation"]),

  lesson(7, "eventos-y-grupos", "Conversaciones breves y eventos profesionales", "Adapta el aprendizaje a mesas, paneles y encuentros con atención compartida.", ["Definir un propósito realista", "Participar sin monopolizar", "Planificar accesibilidad y energía"], [
    { title: "Un evento no es una colección de objetivos", paragraphs: ["Prioriza unas pocas conversaciones y sesiones sin tratar personas como blancos. Investiga temas y organizaciones, prepara varios ángulos y conserva espacio para lo inesperado."], bullets: ["Únete a grupos observando el momento.", "Construye sobre preguntas ajenas.", "Deja espacio para otras voces.", "Toma notas entre conversaciones.", "Sal con una frase sencilla cuando necesites terminar."] },
    { title: "Tres categorías de atención", framework: framework(["Necesito aprender", "Preguntas centrales para la decisión."], ["Conviene comparar", "Perspectivas que pueden desafiar patrones."], ["Valor inesperado", "Espacio para conversaciones y temas emergentes."]), callout: { title: "No clasifica personas", text: "Las categorías distribuyen atención; no establecen jerarquías humanas ni obligan a conversar." } },
    { title: "Plan para un entorno real", exercise: exercise("Evento ficticio de dos horas", "Elige entre seis sesiones, descansos y conversaciones posibles para responder dos objetivos sin saturarte.", "Incluye una alternativa si el ambiente es ruidoso, inaccesible o agotador."), example: { title: "Caso ficticio", text: "Noah cambia una mesa concurrida por una sesión tranquila y una conversación escrita posterior. La adaptación protege su objetivo y su energía." } },
    { title: "Apariencia, seguridad y cultura", bullets: ["Sigue instrucciones del evento.", "Prioriza comodidad, clima, accesibilidad y seguridad.", "Evita normas de vestimenta basadas en género.", "No presupongas contacto físico.", "Respeta variaciones culturales y lingüísticas.", "Una interacción breve no equivale a una entrevista completa."], links: [{ label: "Preparar conversaciones profesionales", href: "/aprende/comunicacion-profesional" }] },
  ], ["event"]),

  lesson(8, "registrar-y-seguir", "Registrar, contrastar y dar seguimiento", "Transforma conversaciones en aprendizaje sin convertir relaciones en un embudo.", ["Separar cita, observación e interpretación", "Comparar perspectivas", "Elegir un seguimiento legítimo"], [
    { title: "Registrar con mínima información necesaria", ordered: ["Resume hechos y ejemplos sin detalles personales innecesarios.", "Separa lo dicho de tu interpretación.", "Anota incertidumbre y posibles sesgos.", "Identifica qué verificar en otra fuente.", "Decide una acción pequeña.", "Minimiza o elimina notas cuando dejan de ser útiles."] },
    { title: "Ocho preguntas de reflexión", questionGroups: [{ title: "Evidencia", items: ["¿Qué esperaba?", "¿Qué escuché?", "¿Qué me sorprendió?", "¿Qué sigue incierto?"] }, { title: "Contexto y acción", items: ["¿Qué puede ser particular de esta persona?", "¿Qué debo verificar?", "¿Qué acción tomaré?", "¿Corresponde seguimiento?"] }] },
    { title: "Comparar sin contar votos", paragraphs: ["La repetición puede indicar un patrón que merece investigación, pero no prueba representatividad. Busca diferencias de función, momento, organización y definición antes de concluir."], exercise: exercise("Tres consejos en tensión", "Compara tres conversaciones ficticias sobre credenciales, experiencia y portafolio. Explica qué podría reconciliar sus diferencias.", "No elijas la opinión más frecuente como verdad automática.") },
    { title: "Seguimiento con razón", bullets: ["Agradece con una referencia específica sin citar extensamente.", "Actualiza solo cuando actuaste o existe información útil.", "Haz una pregunta acotada si fue invitada.", "Espera si no existe una razón nueva.", "No continúes después de una negativa."], example: { title: "Caso ficticio", text: "Sofía aplica un consejo, envía una actualización breve seis semanas después y cierra sin pedir otra reunión." }, links: [{ label: "Profundizar en seguimiento de networking", href: "/aprende/networking/conversaciones-informales" }] },
  ], ["record", "compare", "followup"]),

  lesson(9, "practica-integrada", "Práctica integrada", "Recorre el proceso completo con guía decreciente, ambigüedad y perspectivas en conflicto.", ["Integrar las cinco decisiones", "Justificar alternativas", "Evaluar la propia práctica"], [
    { title: "Caso ficticio creado con fines educativos", caseStudy: { title: "Proyecto Umbral: explorar trabajo de producto orientado a datos", paragraphs: ["Valentina trabaja en operaciones y considera una transición hacia producto con datos. Las descripciones públicas son atractivas, pero no aclaran profundidad técnica, balance entre estrategia y coordinación, evaluación del desempeño ni transferencia de capacidades.", "Su primer objetivo es demasiado amplio y su mensaje pide orientación, revisión de perfil y referencias. Dos perspectivas posteriores discrepan sobre credenciales y programación. Ninguna respuesta decide por ella."] } },
    { title: "Secuencia progresiva", ordered: ["Nombra la incertidumbre sobre profundidad técnica, decisiones y transferencia de capacidades.", "Transforma “saber si producto es para mí” en un objetivo que pueda contrastarse.", "Elige perspectivas directas, adyacentes, contrastantes y de transición.", "Revisa descripciones públicas y separa datos conocidos de preguntas experienciales.", "Detecta que el primer mensaje mezcla aprendizaje, revisión de perfil y referencias.", "Reescribe la invitación con contexto, motivo, tema acotado y salida fácil.", "Prepara tres preguntas prioritarias, dos seguimientos y un límite de confidencialidad.", "Practica una conversación que se acorta y conserva la pregunta principal.", "Registra una respuesta ambigua sin convertirla en conclusión.", "Separa lo dicho, la interpretación de Valentina y lo que todavía debe verificarse.", "Busca una segunda perspectiva con un contexto laboral distinto.", "Participa en un evento con un objetivo breve y sin monopolizar la conversación.", "Compara acuerdos, desacuerdos, condiciones y vigencia de las tres miradas.", "Diseña un experimento profesional pequeño para probar capacidades y preferencias.", "Envía un agradecimiento específico y cierra los seguimientos que no añaden valor.", "Reflexiona sobre qué cambió, qué sigue incierto y qué decisión provisional corresponde."] },
    { title: "Conversaciones y evidencia en conflicto", examples: [
      { title: "Primera perspectiva", text: "Valentina pregunta qué profundidad técnica exige el trabajo cotidiano. La profesional responde: “En mi equipo analizo datos y discuto criterios con ingeniería, pero no desarrollo sistemas”. Valentina aclara qué tareas realiza directamente y cuáles coordina." },
      { title: "Segunda perspectiva", text: "Otra profesional afirma que programar con soltura fue decisivo en su entorno. Valentina no elige una respuesta por prestigio: registra que ambas experiencias provienen de equipos, productos y etapas diferentes." },
      { title: "Conversación en evento", text: "En una mesa abierta, Valentina formula una sola pregunta sobre cómo cambia el rol según la madurez del producto, escucha dos respuestas y agradece sin solicitar reuniones adicionales." },
    ], callout: { title: "Nota para facilitar", text: "Pide al grupo identificar qué frases son observaciones, cuáles son interpretaciones y qué información contextual falta antes de comparar." } },
    { title: "Experimento y señales de aprendizaje", bullets: ["Durante cuatro semanas, Valentina define un problema operativo, acuerda criterios de calidad y prepara un análisis breve.", "Registra tareas completadas, criterios que pudo justificar, dudas que requirieron ayuda y retroalimentación recibida.", "Anota interés y energía como observaciones personales, no como prueba universal de encaje.", "Compara las brechas observadas con las tres perspectivas y decide si necesita práctica adicional o formación acotada.", "No usa respuestas, contactos, referencias ni ofertas laborales como métrica de éxito de la entrevista informativa."], exercise: exercise("Defender una decisión provisional", "Explica qué evidencia apoya el siguiente paso de Valentina y qué hallazgo podría cambiarlo.", "Una buena respuesta reconoce límites y propone una comprobación posterior.") },
    { title: "Tres niveles de práctica", questionGroups: [{ title: "Inicial", items: ["Usa preguntas guiadas", "Revisa un mensaje con criterios", "Compara dos perspectivas claras"] }, { title: "Intermedio", items: ["Trabaja con información incompleta", "Decide qué no preguntar", "Adapta una reunión acortada"] }, { title: "Avanzado", items: ["Integra consejos incompatibles", "Gestiona una pregunta inapropiada", "Defiende una decisión provisional"] }] },
    { title: "Razonamiento modelo", modelAnswers: [{ title: "Objetivo", text: "Cambiaría “saber si producto es para mí” por entender qué profundidad técnica y qué decisiones caracterizan tres contextos de producto distintos." }, { title: "Perspectivas", text: "Combinaría una persona en producto, una en datos, otra que hizo una transición desde operaciones y una que dejó el área." }, { title: "Experimento", text: "Probaría durante cuatro semanas una tarea de definición de problema y análisis con revisión de alguien del campo; observaría interés, dificultad, calidad del razonamiento y brechas concretas." }, { title: "Decisión", text: "No concluiría por mayoría. Registraría contexto, probaría una capacidad y decidiría qué formación acotada tiene valor después." }] },
    { title: "Rúbrica y facilitación", rubric: ["Claridad del aprendizaje", "Diversidad y límites de perspectivas", "Calidad de investigación", "Transparencia de la solicitud", "Escucha y adaptación", "Separación de evidencia e interpretación", "Próximo paso razonado", "Privacidad y respeto"], callout: { title: "Guía para facilitar", text: "Pide justificar elecciones, ofrecer una alternativa válida y nombrar qué evidencia podría cambiar la decisión. No busques una única respuesta correcta." } },
  ], ["objective", "conversation", "compare"]),

  lesson(10, "biblioteca", "Biblioteca de recursos y herramientas", "Elige una ayuda según la decisión actual, sin convertir la ruta en un proceso obligatorio.", ["Seleccionar un recurso pertinente", "Usar herramientas sin datos sensibles", "Imprimir o copiar un plan"], [
    { title: "Comienza por tu bloqueo", applications: [
      { title: "No sé qué preguntar", contacts: ["Clarificador de objetivo", "Guía de profundidad"], questions: ["¿Qué decisión tengo?", "¿Qué información falta?"], links: [{ label: "Abrir clarificador", href: informationalToolLinks.objective.href }] },
      { title: "No sé a quién escuchar", contacts: ["Mapa de perspectivas", "Matriz cualitativa"], questions: ["¿Qué mirada es directa?", "¿Qué punto ciego necesito contrastar?"], links: [{ label: "Abrir mapa", href: informationalToolLinks.perspectives.href }] },
      { title: "La conversación ya ocurrió", contacts: ["Registro", "Comparador", "Decisor de seguimiento"], questions: ["¿Qué fue hecho?", "¿Qué debo verificar?"], links: [{ label: "Abrir registro", href: informationalToolLinks.record.href }] },
    ] },
    { title: "Privacidad por diseño", bullets: ["Usa etiquetas genéricas, no nombres ni empleadores.", "No pegues mensajes o notas confidenciales.", "Copia el resultado antes de salir si deseas conservarlo.", "Las herramientas no guardan ni transmiten entradas.", "Elimina notas personales que ya no necesites."] },
    { title: "Ejemplo de elección", example: { title: "Caso ficticio", text: "Lina ya tiene una invitación y no necesita rehacer toda la ruta: usa el revisor de presión, imprime una tarjeta de conversación y luego registra solo aprendizajes anónimos." }, exercise: exercise("Crear tu combinación", "Elige un recurso antes, durante y después de una conversación.", "La combinación debe responder a una necesidad, no completar casillas.") },
    { title: "Rutas relacionadas", links: [{ label: "Networking", href: "/aprende/networking" }, { label: "Comunicación profesional", href: "/aprende/comunicacion-profesional" }, { label: "Adaptabilidad y transiciones", href: "/aprende/adaptabilidad-resiliencia" }, { label: "Decisiones con evidencia", href: "/aprende/resolucion-de-problemas" }] },
  ], ["objective", "request", "record", "followup"]),
];

const caseSeeds = [
  ["Primera conversación sin red", "Estudiante que no conoce profesionales del campo"], ["Experiencia transferible", "Persona que cambia de carrera con capacidades sólidas"], ["Trayectoria asesora", "Profesional senior que explora un rol consultivo"], ["Regreso gradual", "Persona que vuelve después de una pausa"], ["Nuevo mercado laboral", "Profesional que se muda a otro país"], ["Servicio público", "Persona que explora trabajo estatal"], ["Sector regulado", "Profesional que investiga una industria con controles"], ["Comprender al cliente", "Independiente que estudia un sector"], ["Después del seminario", "Solicitud tras una presentación virtual"], ["Presentación mutua", "Contacto ofrecido por una relación común"], ["Relevancia sin conexión", "Solicitud fría pero contextual"], ["Silencio", "No hubo respuesta al primer mensaje"], ["Declinación", "La persona rechaza con cortesía"], ["Diez minutos", "La conversación se acorta de improviso"], ["Poco espacio para preguntar", "La otra persona domina el diálogo"], ["¿Buscas empleo?", "El propósito se interpreta como postulación"], ["Mesa compartida", "Grupo con tiempo limitado"], ["Demasiadas opciones", "Evento con sesiones simultáneas"], ["Consejos opuestos", "Dos perspectivas discrepan"], ["Experiencia desactualizada", "Consejo basado en un mercado anterior"], ["Límite confidencial", "Una pregunta invade información no pública"], ["Seguimiento excesivo", "Ya se enviaron varios mensajes"], ["Cerrar una relación", "No existe motivo para continuar"], ["Descartar un camino", "La conversación reduce el interés por una carrera"],
];
export const informationalCases = caseSeeds.map(([title, context], index) => ({
  id: `caso-${String(index + 1).padStart(2, "0")}`, title, label: "Caso ficticio creado con fines educativos.",
  difficulty: index < 8 ? "inicial" : index < 17 ? "intermedia" : "avanzada",
  learningObjective: `Practicar una decisión sobre ${title.toLowerCase()}.`, context,
  decisionPoint: "¿Qué acción conserva el aprendizaje y respeta los límites?",
  actions: ["Investigar una pieza más", "Proponer un paso acotado", "Pausar o cerrar"],
  risks: ["Sobregeneralizar", "Presionar", "Confundir hipótesis con hecho"],
  feedback: index === 12 || index === 21 ? "La señal pide cerrar. Agradece o registra la preferencia sin otro intento." : "Compara el propósito, la evidencia y el costo para la otra persona; varias acciones pueden ser válidas.",
  relatedLesson: informationalLessons[index % informationalLessons.length].slug,
  relatedTool: Object.keys(informationalToolLinks)[index % 10], fictional: true,
}));

const resourceTitles = ["Lienzo de objetivo de aprendizaje", "Matriz de selección de perspectivas", "Checklist de investigación suficiente", "Hoja de planificación de invitación", "Tarjeta de preparación de conversación", "Guía de profundidad de preguntas", "Plan de evento grupal", "Plantilla de notas", "Tabla de comparación de evidencia", "Guía de decisión de seguimiento", "Rúbrica de autoevaluación", "Guía de facilitación"];
export const informationalResources = resourceTitles.map((title, index) => ({
  id: `entrevista-${index + 1}`, title, description: `Recurso editable para ${title.toLowerCase()} con información general o ficticia.`,
  contentType: index % 3 === 0 ? "template" : index % 3 === 1 ? "worksheet" : "checklist", status: "published",
  template: index % 3 === 0 ? `${title.toUpperCase()}\n\nPROPÓSITO\n\nEVIDENCIA\n\nLÍMITE\n\nSIGUIENTE PASO` : undefined,
  fields: index % 3 === 1 ? ["Pregunta de aprendizaje", "Evidencia disponible", "Perspectiva y límite", "Próximo paso"] : undefined,
  groups: index % 3 === 2 ? [{ title: "Revisión", items: ["Separé hechos e interpretación", "Evité datos personales", "Definí un límite", "Incluí una salida respetuosa"] }] : undefined,
  reminder: "No ingreses nombres, empleadores, contactos, mensajes privados ni información confidencial. Copia o imprime antes de cerrar si deseas conservarlo.",
}));

export const getInformationalLesson = (slug) => informationalLessons.find((item) => item.slug === slug);
