export const INVESTMENT_HELP = Object.freeze({
  initialMoney: {
    simple: "Es el dinero que debes tener disponible para concretar la compra.",
    technical: "Capital inicial requerido",
    formula: "Pie + gastos de compra + corretaje del comprador + preparación + muebles + reservas.",
    includes: "Incluye los desembolsos iniciales ingresados por ti.",
    excludes: "No incluye gastos futuros, impuestos personales ni costos que no hayas ingresado.",
    warning: "En una propiedad nueva, revisa también el máximo dinero acumulado antes del primer arriendo.",
  },
  firstYearCash: {
    simple: "Muestra si durante el primer año tendrás que poner dinero adicional o recibirás un excedente.",
    technical: "Flujo de caja antes de impuestos",
    formula: "Arriendo efectivo − gastos de operación − pagos del crédito − renovaciones importantes.",
    includes: "Incluye los ingresos y pagos modelados para ese año.",
    excludes: "No incluye impuestos personales ni gastos extraordinarios no ingresados.",
    warning: "Un valor positivo no es una ganancia garantizada ni necesariamente dinero disponible para retirar.",
  },
  presentValue: {
    simple: "Mide cuánto valor crea o destruye el proyecto después de exigirle la rentabilidad definida como costo de oportunidad. No simula por separado los depósitos, retiros o comisiones de otra inversión.",
    technical: "Valor presente neto (VPN)",
    formula: "− inversión inicial + cada flujo anual ÷ (1 + tasa de descuento)^año + resultado final ÷ (1 + tasa de descuento)^año. La tasa de descuento es el costo de oportunidad configurado. Si viene expresado en pesos, se convierte a una tasa real comparable: (1 + retorno nominal) ÷ (1 + inflación esperada) − 1.",
    includes: "Según el indicador abierto, incluye el dinero puesto al comienzo, los aportes o excedentes anuales y la venta neta al final del horizonte, la venta neta al terminar el crédito, o un valor de continuidad si mantienes la propiedad.",
    excludes: "No incluye flujos posteriores al año de venta. Si eliges “Nunca”, usa los flujos hasta el horizonte de inversión y agrega un valor de continuidad. Tampoco incluye impuestos personales ni hechos que no estén representados en los supuestos.",
    warning: "Una tasa de descuento más alta reduce el valor actual de los flujos futuros. Cerca de cero, pequeñas variaciones en arriendo, vacancia, tasa o precio pueden cambiar la conclusión.",
  },
  saleVsHoldValue: {
    simple: "Imagina que en el año elegido debes decidir entre vender o continuar. La herramienta calcula cuánto dinero estimado dejaría cada opción al final del horizonte para compararlas en la misma fecha.",
    technical: "Comparación de riqueza futura entre venta y continuidad",
    formula: "Si vendes: venta neta × (1 + rentabilidad alternativa)^(horizonte − año de decisión). Si continúas: flujos posteriores por arriendo reinvertidos + venta neta de la propiedad al final del horizonte.",
    includes: "La venta descuenta deuda, costos de salida y comisión de prepago. La continuidad incluye los pagos del crédito, los gastos e ingresos por arriendo posteriores, y una venta estimada al final para expresar la propiedad como dinero.",
    excludes: "No suma ambas opciones ni vuelve a contar los años anteriores a la decisión, porque son iguales para las dos estrategias. No incluye impuestos personales ni hechos no ingresados.",
    warning: "Los montos son estimaciones al final del horizonte, no dinero de hoy. Su resultado depende especialmente de la rentabilidad alternativa, los arriendos, el valor futuro de la propiedad y los costos de venta.",
  },
  adjustedPresentValue: {
    simple: "Compara desde hoy una propiedad nueva, incluyendo la espera y los pagos antes del primer arriendo.",
    technical: "VPN ajustado desde hoy",
    formula: "Valor de la operación al comenzar el arriendo, descontado hasta hoy, menos el valor presente de los pagos previos.",
    includes: "Incluye espera, bono modelado, pagos al desarrollador y pagos hipotecarios previos ingresados.",
    excludes: "No reconstruye mensualmente toda la operación después del primer arriendo.",
    warning: "Las fechas contractuales y las condiciones del bono deben confirmarse documentalmente.",
  },
  operatingIncome: {
    simple: "Es lo que deja el arriendo después de los gastos normales de mantenerlo, antes de pagar el crédito.",
    technical: "Ingreso operativo neto (NOI)",
    formula: "Ingreso efectivo por arriendo − gastos operativos.",
    includes: "Incluye vacancia, gastos comunes del propietario, mantención, administración, contribuciones, seguros y otros gastos ingresados.",
    excludes: "No descuenta crédito, renovaciones importantes ni impuestos personales.",
    warning: "No es dinero libre para el propietario.",
  },
  debtCoverage: {
    simple: "Indica cuánto de los pagos del crédito alcanza a cubrir el arriendo después de los gastos normales.",
    technical: "Cobertura del servicio de deuda (DSCR)",
    formula: "Ingreso operativo neto ÷ pagos del crédito.",
    includes: "Incluye el ingreso operativo y el calendario hipotecario usado por el modelo.",
    excludes: "No considera todos los gastos extraordinarios ni impuestos personales.",
    warning: "Menos de 1 significa que el arriendo no cubre completamente el crédito bajo estos supuestos.",
  },
  irr: {
    simple: "Resume el rendimiento anual implícito de los flujos calculados.",
    technical: "Tasa interna de retorno (TIR)",
    formula: "Tasa que hace que el valor presente neto de los flujos sea cero.",
    includes: "Incluye el aporte inicial, los flujos anuales y la alternativa final evaluada.",
    excludes: "No usa directamente el rendimiento de tu otra alternativa.",
    warning: "Puede no existir o puede haber más de una tasa cuando los flujos cambian de signo varias veces.",
  },
  mirr: {
    simple: "Muestra una tasa anual usando supuestos explícitos para financiar aportes y reinvertir excedentes.",
    technical: "Tasa interna de retorno modificada (MIRR)",
    formula: "Relaciona el valor presente de las salidas con el valor futuro de las entradas.",
    includes: "Incluye las tasas de financiamiento y reinversión usadas por el modelo.",
    excludes: "No garantiza que puedas financiar o reinvertir realmente a esas tasas.",
    warning: "Debe leerse junto con los montos y no como una recomendación aislada.",
  },
  cashReturn: {
    simple: "Compara el dinero que aporta o entrega el primer año con lo que pusiste al comienzo.",
    technical: "Retorno sobre efectivo invertido (cash-on-cash)",
    formula: "Flujo del primer año ÷ capital inicial.",
    includes: "Incluye deuda y gastos de operación del primer año.",
    excludes: "No incluye la valorización de la propiedad ni años posteriores.",
    warning: "Puede ser negativo si debes aportar dinero durante el año.",
  },
  operatingYield: {
    simple: "Compara lo que deja la operación antes del crédito con el precio de la propiedad.",
    technical: "Rentabilidad del ingreso operativo neto",
    formula: "Ingreso operativo neto del primer año ÷ precio de compra.",
    includes: "Incluye arriendo efectivo y gastos normales.",
    excludes: "No incluye financiamiento, valorización, venta ni impuestos personales.",
    warning: "No representa por sí sola el rendimiento total de tu inversión.",
  },
  opportunityRate: {
    simple: "Es el rendimiento que podrías exigirle a la propiedad porque renuncias a invertir ese dinero en otra opción.",
    technical: "Costo de oportunidad o tasa de descuento real",
    formula: "Si la alternativa está en pesos: (1 + retorno nominal) ÷ (1 + inflación esperada) − 1.",
    includes: "Incluye la alternativa y la inflación esperada seleccionadas.",
    excludes: "No ajusta diferencias de riesgo, liquidez, comisiones o impuestos entre inversiones.",
    warning: "Las referencias históricas o de mercado no aseguran rendimientos futuros.",
  },
  mortgageRate: {
    simple: "Es la tasa anual del crédito hipotecario. La referencia automática es solo un punto de partida y puedes reemplazarla por tu cotización.",
    technical: "Tasa hipotecaria anual efectiva en UF",
    formula: "El motor la convierte en una tasa mensual equivalente para construir el calendario del crédito.",
    includes: "Cuando está disponible, usa como referencia el promedio ponderado de créditos de vivienda en UF a más de tres años del Banco Central de Chile.",
    excludes: "No está ajustada al plazo elegido, a una segunda vivienda ni al perfil de quien solicita el crédito.",
    warning: "No es una oferta bancaria. Confirma siempre la tasa, seguros y condiciones en una cotización formal.",
  },
  occupancy: {
    simple: "Es la parte del año en que esperas recibir arriendo.",
    technical: "Tasa de ocupación anual",
    formula: "Meses equivalentes con arriendo ÷ 12.",
    includes: "Reduce el arriendo potencial para representar meses sin arrendatario.",
    excludes: "No determina en qué meses ocurre la vacancia.",
    warning: "100% supone arriendo durante todo el año; 0% supone que no recibes arriendo.",
  },
  appreciation: {
    simple: "Es cuánto supones que cambiará el valor de la propiedad por encima de la UF durante un período limitado. Puede deberse a un nuevo metro, mall, parques, servicios o mejoras del barrio; también puede ser negativa si la zona pierde atractivo.",
    technical: "Variación anual real del inmueble",
    formula: "Durante los años seleccionados: valor anterior × (1 + variación real). Fuera de ese tramo no se aplica plusvalía adicional.",
    includes: "Incluye la tasa y los años de inicio y término que ingresaste.",
    excludes: "No supone que la plusvalía continúe para siempre ni predice obras o cambios del mercado.",
    warning: "Un supuesto pequeño cambia de forma importante el valor de venta a muchos años.",
  },
  investmentHorizon: {
    simple: "Es la cantidad de años que quieres mirar hacia adelante para comparar ingresos, gastos, deuda y valor de la propiedad.",
    technical: "Horizonte de evaluación",
    formula: "Define cuántas filas anuales se proyectan y la fecha final en que se comparan las alternativas.",
    includes: "Afecta el tiempo de arriendo, el saldo del crédito, la plusvalía dentro de su tramo y el valor final.",
    excludes: "No significa que debas mantener la propiedad exactamente durante ese plazo.",
    warning: "Cambiar el horizonte puede modificar de forma importante los resultados porque mueve la fecha de comparación.",
  },
});
