import { useEffect, useMemo } from "react";
import { ArrowRight, BookOpen, CheckCircle2 } from "lucide-react";
import { Breadcrumbs, ContextualServiceCta, PageShell } from "./LearningComponents";
import { breadcrumbSchema, usePageMetadata } from "./seo";
import { trackEvent } from "./analytics";

const REVIEW_DATE = "2026-07-18";
const PATH = "/aprende/finanzas-personales/evaluar-inversion-inmobiliaria";
const chapters = [
  ["Separar las cuatro capas", "Adquisición responde cuánto capital necesitas; financiamiento describe la deuda; operación muestra el negocio de arriendo; salida o continuidad compara alternativas futuras. Mezclarlas oculta qué supuesto explica el resultado."],
  ["Capital inicial", "Suma pie, gastos de compra pagados por quien adquiere, corretaje del comprador, preparación, equipamiento y reservas. El corretaje del vendedor pertenece al año de salida, no al desembolso inicial."],
  ["Renta potencial e ingreso efectivo", "El arriendo contractual anual es una capacidad teórica. La ocupación y otros ingresos determinan el ingreso efectivo. Un comparable puede sugerir una relación precio/arriendo, pero no demuestra que una unidad específica logrará esa renta."],
  ["NOI y flujo de caja", "El ingreso operativo neto descuenta egresos necesarios para operar el arriendo. No descuenta dividendo ni gastos de capital. El flujo para el inversionista sí resta servicio de deuda y CAPEX."],
  ["Crédito y saldo", "La cuota anual debe sumar cada pago del calendario de amortización. Así se respetan seguros, término del crédito y saldo exacto al año de venta; multiplicar siempre la primera cuota por doce puede distorsionar el resultado."],
  ["Valor del inmueble", "La apreciación es un supuesto editable, no una promesa. Conviene probar también crecimiento nulo y caídas. La herramienta mantiene valores reales en UF y no proyecta el valor futuro de la UF en pesos."],
  ["Venta neta", "Al valor proyectado se restan costos variables y fijos de venta, saldo hipotecario y un costo de prepago solo cuando fue confirmado. Este valor aparece una vez en el flujo terminal."],
  ["Continuar arrendando", "La continuidad se aproxima con el valor presente de los NOI posteriores y no se suma a la venta. En una perpetuidad creciente, la tasa de descuento debe superar el crecimiento; de lo contrario el método no produce un valor finito."],
  ["VPN, TIR y MIRR", "El VPN descuenta los flujos al costo de oportunidad personal. La TIR incluye el capital inicial, pero puede no existir o tener más de una raíz. La MIRR usa tasas explícitas para financiar salidas y reinvertir entradas."],
  ["Puntos de equilibrio", "Un solucionador busca el arriendo, ocupación o precio que hace cercano a cero el VPN. Si el rango no contiene una raíz, el resultado correcto es informar que no hay solución válida, no mostrar NaN."],
  ["Sensibilidad e incertidumbre", "Una cifra central no representa toda la incertidumbre. Cambia vacancia, renta, tasa, gastos, apreciación y costo de oportunidad por separado y en escenarios coherentes; identifica qué variables alteran la conclusión."],
];

export default function InvestmentLearningPage() {
  const breadcrumbs = [{ label: "Inicio", href: "/" }, { label: "Aprende", href: "/aprende" }, { label: "Evaluar inversión inmobiliaria", href: PATH }];
  const schema = useMemo(() => ({ "@context": "https://schema.org", "@graph": [breadcrumbSchema(breadcrumbs), { "@type": "LearningResource", name: "Cómo evaluar una propiedad para arriendo sin confundir renta, deuda y salida", description: "Guía práctica para analizar una inversión residencial de arriendo en Chile mediante capital inicial, NOI, flujo, VPN y alternativas terminales.", url: `https://masanes.cl${PATH}`, learningResourceType: "Guía práctica", educationalLevel: "Intermedio", inLanguage: "es-CL", datePublished: REVIEW_DATE, dateModified: REVIEW_DATE }] }), []);
  usePageMetadata({ title: "Cómo evaluar una inversión inmobiliaria para arriendo", description: "Aprende a separar adquisición, deuda, arriendo, gastos, venta y continuidad al evaluar una propiedad residencial en Chile.", path: PATH, schema });
  useEffect(() => trackEvent("investment_learning_opened", { category: "investment" }), []);
  return <PageShell><main id="main-content" className="content-page mortgage-learning investment-learning"><Breadcrumbs items={breadcrumbs} />
    <header className="page-hero"><div><p className="eyebrow">Finanzas personales</p><h1>Cómo evaluar una propiedad para arriendo sin confundir renta, deuda y salida</h1><p className="page-hero__lead">Una guía para construir escenarios, interpretar flujos y reconocer los límites de un modelo antes de comprometer capital.</p><a className="button button--primary" href="/herramientas/evaluador-inversion-inmobiliaria">Abrir evaluador <ArrowRight size={17} /></a></div><aside className="summary-panel"><BookOpen size={24} /><dl><div><dt>Nivel</dt><dd>Intermedio</dd></div><div><dt>Formato</dt><dd>Guía práctica</dd></div><div><dt>Última revisión</dt><dd><time dateTime={REVIEW_DATE}>18 de julio de 2026</time></dd></div></dl></aside></header>
    <section className="learning-outcomes"><h2>Al terminar podrás</h2><ul><li>Separar capital, operación, deuda y alternativa terminal.</li><li>Interpretar NOI, cash-on-cash, DSCR, VPN, TIR y MIRR.</li><li>Comparar venta y continuidad sin sumarlas.</li><li>Diseñar escenarios y puntos de equilibrio sin falsa precisión.</li></ul></section>
    <section className="content-section" aria-labelledby="guide-chapters"><div className="section-title"><p className="eyebrow">Once decisiones</p><h2 id="guide-chapters">Una secuencia para construir el análisis</h2></div><div className="mortgage-learning-grid">{chapters.map(([title, body], index) => <article key={title}><span>{String(index + 1).padStart(2, "0")}</span><h3>{title}</h3><p>{body}</p></article>)}</div></section>
    <section className="integrative-case"><p className="case-label">Caso ficticio creado con fines educativos.</p><h2>Una unidad que exige aportes al comienzo</h2><p>Una persona evalúa un departamento usado de 3.600 UF con 75% de financiamiento a 25 años. Estima un arriendo de 15 UF, 90% de ocupación, gastos operativos equivalentes a 12% del ingreso efectivo y una renovación de 55 UF. Proyecta diez años, prueba una apreciación real entre −1% y 2% y usa 6% como costo de oportunidad.</p><h3>Preguntas de trabajo</h3><ol><li>Calcula el capital inicial incluyendo pie, compra y preparación.</li><li>Separa NOI del flujo después del crédito.</li><li>Observa cuánto saldo queda en el año diez.</li><li>Prueba una venta con costos de salida y una continuidad basada en NOI.</li><li>Identifica qué combinación de renta y ocupación acerca el VPN a cero.</li></ol><details><summary>Ver solución razonada</summary><div><p><CheckCircle2 size={18} /> El pie es solo una parte del capital. Los gastos y la renovación deben entrar en el periodo cero aunque no generen renta inmediata.</p><p>Una ocupación de 90% reduce la renta potencial antes de descontar operación. El NOI aún no considera el crédito; por eso puede ser positivo mientras el flujo para el inversionista es negativo.</p><p>La apreciación debe probarse como rango. En el año diez, la venta neta descuenta el saldo real y los costos de salida. La continuidad usa los NOI posteriores: elegir una alternativa excluye recibir la otra al mismo tiempo.</p><p>El punto de equilibrio no valida el supuesto de mercado; solo indica qué condición matemática necesitaría el escenario.</p></div></details></section>
    <section className="content-section"><div className="section-title"><p className="eyebrow">Fórmulas esenciales</p><h2>Definiciones sin ambigüedad</h2></div><dl className="formula-grid"><div><dt>Ingreso efectivo</dt><dd>Renta potencial × ocupación + otros ingresos.</dd></div><div><dt>NOI</dt><dd>Ingreso efectivo − egresos operativos.</dd></div><div><dt>Flujo antes de impuestos</dt><dd>NOI − servicio de deuda − gastos de capital.</dd></div><div><dt>Venta neta</dt><dd>Valor proyectado − costos de venta − saldo hipotecario − prepago confirmado.</dd></div><div><dt>Continuidad</dt><dd>NOI del año siguiente ÷ (costo de oportunidad − crecimiento perpetuo).</dd></div><div><dt>VPN</dt><dd>Capital inicial negativo más flujos y una sola alternativa terminal, descontados.</dd></div></dl></section>
    <section className="questions-section"><h2>Preguntas que el modelo no responde</h2><ul><li>Si una institución aprobará el crédito o la tasación.</li><li>Si el arriendo esperado es alcanzable para esa unidad.</li><li>Qué tratamiento tributario corresponde al inmueble o contribuyente.</li><li>Cuánto tardará una venta ni qué precio aceptará el mercado.</li><li>Qué reparaciones, conflictos o cambios regulatorios ocurrirán.</li><li>Cómo cambiará la UF futura expresada en pesos.</li></ul><p>Confirma contratos, condiciones de financiamiento, contribuciones, seguros, gastos y tratamiento tributario con fuentes oficiales o profesionales habilitados. Esta guía no es una recomendación, tasación ni opinión legal o tributaria.</p></section>
    <ContextualServiceCta />
  </main></PageShell>;
}
