export const listeningBase="/aprende/escucha-curiosidad-feedback";
export const listeningLastReviewed="2026-07-16";
const framework=(...items)=>items.map(([title,text])=>({title,text}));
const exercise=(title,prompt,help)=>({title,prompt,help});
const lesson=(order,slug,title,description,outcomes,sections,relatedTools=[])=>({order,slug,title,description,outcomes,sections,relatedTools,href:`${listeningBase}/${slug}`,level:order<4?"Inicial":order<9?"Intermedio":"Aplicado",readingTime:`${11+(order%4)}–${17+(order%4)} minutos`,updatedAt:listeningLastReviewed,lastReviewed:listeningLastReviewed,status:"published"});

export const listeningToolLinks={
 attention:{title:"Observador de atención",href:"/herramientas/observador-atencion-conversaciones",description:"Revisa hacia dónde se desplazó tu atención en una situación concreta."},
 separate:{title:"Separador de observación e interpretación",href:"/herramientas/separar-observacion-interpretacion",description:"Distingue hechos, significado atribuido, intención inferida y evidencia faltante."},
 curiosity:{title:"Constructor de preguntas de curiosidad",href:"/herramientas/constructor-preguntas-curiosidad",description:"Prepara preguntas abiertas, acotadas y fáciles de rechazar."},
 prepare:{title:"Preparador de escucha",href:"/herramientas/preparar-escucha-conversacion",description:"Organiza propósito, apoyos, distracciones y límites."},
 filter:{title:"Filtro de feedback útil",href:"/herramientas/filtro-feedback-util",description:"Examina observación, efecto, evidencia, contexto y decisión sin puntuar."},
 give:{title:"Revisor de feedback",href:"/herramientas/revisar-feedback-profesional",description:"Detecta etiquetas, motivos supuestos, absolutos y falta de ejemplos."},
 respond:{title:"Planificador de respuesta",href:"/herramientas/planificar-respuesta-feedback",description:"Ordena pausa, aclaración, investigación, prueba, límite o escalamiento."},
 clarify:{title:"Simulador de clarificación",href:"/herramientas/simular-clarificacion-conversacion",description:"Practica respuestas en escenarios ficticios sin calificación global."},
 repair:{title:"Plan de reparación",href:"/herramientas/plan-reparacion-conversacion",description:"Decide entre reparar, documentar, escalar, pausar o salir."},
 practice:{title:"Plan de práctica deliberada",href:"/herramientas/plan-practica-escucha-feedback",description:"Diseña un experimento pequeño para una conducta observable."},
};

export const listeningPath={title:"Escucha, curiosidad y feedback",description:"Comprende mejor, pregunta con intención y convierte observaciones en aprendizaje sin perder criterio propio.",definition:"Escuchar dirige atención y comprueba significado; la curiosidad explora incertidumbre sin invadir; el feedback ofrece una perspectiva situada que debe evaluarse. Ninguna de estas capacidades exige obediencia, supresión emocional ni tolerancia a conductas dañinas.",audience:"Profesionales, estudiantes, líderes, equipos y personas que preparan conversaciones difíciles",format:"Ruta práctica con casos, recursos y herramientas locales",effort:"Entre 3 y 5 horas de lectura y práctica, según el contexto",outcomes:["Distinguir observación, interpretación e inferencia","Clarificar antes de aconsejar o responder","Evaluar y dar feedback con contexto","Reparar o cerrar conversaciones con límites"]};

const comprehensionCycle=framework(["Atender","Dirigir atención al mensaje y notar demandas internas o externas."],["Distinguir","Separar lo dicho, lo observado y lo inferido."],["Explorar","Preguntar por significado, contexto, ejemplos e incertidumbre."],["Devolver","Resumir para que la otra persona pueda corregir."],["Elegir","Responder, preguntar, disentir, pausar, actuar o cerrar."]);
const usefulFilter=framework(["Qué se observó","Conducta, resultado o mensaje específico."],["Qué efecto se atribuye","Consecuencia observada, no intención asumida."],["Qué evidencia existe","Ejemplo, momento, patrón y cercanía de la fuente."],["Qué contexto falta","Restricciones, poder, estándar y evidencia contradictoria."],["Qué decisión corresponde","Aplicar, probar, investigar, descartar o escalar."]);
const attentionDestinations=framework(["Hacia mí","Defensa, emoción, comparación, límite o preparación de respuesta."],["Hacia el mensaje","Contenido explícito, instrucciones y detalles."],["Hacia la situación","Contexto, incertidumbre, restricciones y dinámica de interacción."]);

const listeningMoments=["Instrucción técnica ambigua","Colega que pide ser escuchada","Revisión de proyecto","Cliente molesto","Decisión con información incompleta","Mensaje escrito breve","Desacuerdo entre áreas","Conversación de apoyo","Feedback inesperado","Reunión con intérprete","Coordinación asincrónica","Plazo que cambia","Pregunta invasiva","Explicación extensa","Cierre de acuerdos"].map((title,index)=>({id:`momento-${index+1}`,title,situation:`Situación ficticia: ${title}.`,question:"¿Qué necesita la conversación: recepción, atención, comprensión, acuerdo o acción?",action:"Nombra el propósito y una comprobación de significado.",constraint:"No uses silencio, mirada o rapidez como prueba de escucha."}));

export const listeningLessons=[
 lesson(1,"escuchar-no-es-silencio","Escuchar no es solo permanecer en silencio","Distingue recepción, atención, comprensión, acuerdo y acción.",["Reconocer propósitos de escucha","Separar comprensión y acuerdo","Elegir apoyos de procesamiento"],[
  {title:"Nueve procesos diferentes",bullets:["Recibir una señal","Prestar atención","Comprender palabras","Comprender significado","Recordar","Sentir empatía","Estar de acuerdo","Cumplir","Actuar"],paragraphs:["Una persona puede comprender y disentir, guardar silencio sin atender o interrumpir para aclarar de manera colaborativa. Escuchar no obliga a obedecer, no es un rasgo fijo ni una actuación corporal."]},
  {title:"Ciclo de comprensión antes de respuesta",framework:comprehensionCycle,callout:{title:"Modelo práctico",text:"Este es un modelo práctico creado para organizar esta ruta. No es un estándar, una certificación ni una garantía de resultados."}},
  {title:"Propósito de la conversación",questionGroups:[{title:"Para qué escucho",items:["Aprender","Coordinar","Apoyar","Diagnosticar un problema","Decidir","Resolver ambigüedad"]},{title:"Qué debo confirmar",items:["Solicitud real","Alcance","Incertidumbre","Acuerdo","Próximo paso","Formato accesible"]}],exercise:exercise("Clasificar quince momentos","Decide qué tipo de escucha necesita cada escenario ficticio.","No existe una conducta corporal universal que demuestre atención.")},
  {title:"Quince momentos",scenarios:listeningMoments,callout:{title:"Accesibilidad",text:"Notas, subtítulos, repetición, agenda, pausas y seguimiento escrito pueden apoyar comprensión. No exijas mirada, quietud, expresividad o respuesta inmediata."},links:[{label:"Profundizar en comunicación profesional",href:"/aprende/comunicacion-profesional"}]},
 ],["attention","prepare"]),

 lesson(2,"reconocer-atencion","Reconocer dónde está tu atención","Observa desplazamientos de atención para elegir la respuesta que requiere la situación.",["Nombrar demandas internas y externas","Elegir un foco adecuado","Diseñar apoyos sin jerarquías"],[
  {title:"Tres destinos de la atención",framework:attentionDestinations,callout:{title:"Modelo situacional",text:"Ningún destino es siempre mejor. El objetivo es notar y elegir, no permanecer en un nivel considerado superior."}},
  {title:"Qué puede desplazarla",bullets:["Preparar una refutación","Comparar experiencias","Resolver demasiado pronto","Suponer el final","Palabras emocionalmente cargadas","Diferencia de estatus","Fatiga","Multitarea","Notificaciones","Presión de tiempo","Procesamiento lingüístico","Sobrecarga sensorial","Miedo a ser evaluado"]},
  {title:"Lectura de un diálogo",example:{title:"Caso ficticio",text:"Mientras Ada explica un retraso, Martín prepara una defensa. Al notar el cambio hacia sí mismo, registra su límite y vuelve al mensaje con una pregunta sobre dependencias. No elimina su reacción; decide cuándo atenderla."},exercise:exercise("Rastrear cambios","Marca cinco momentos de un diálogo ficticio donde la atención cambia y propone una elección posible.","Incluye una alternativa escrita o una pausa cuando ayude.")},
  {title:"Práctica sin actuación",bullets:["Nombra el propósito antes de reunirte","Reduce una distracción controlable","Pide agenda o información previa","Usa notas o subtítulos","Solicita una pausa","Confirma por escrito"],links:[{label:"Practicar conversaciones informativas",href:"/aprende/entrevistas-informativas"}]},
 ],["attention","prepare"]),

 lesson(3,"separar-hechos-inferencias","Separar hechos, interpretaciones e inferencias","Evita presentar significados y motivos supuestos como observaciones objetivas.",["Clasificar tipos de información","Detectar lenguaje absoluto","Nombrar evidencia faltante"],[
  {title:"Seis capas",framework:framework(["Observación","Algo visto, oído o registrado directamente."],["Interpretación","Significado asignado a la observación."],["Inferencia","Conclusión sobre causa, intención o futuro."],["Evaluación","Juicio respecto de un estándar."],["Sensación","Experiencia interna de quien habla."],["Solicitud","Acción propuesta."])},
  {title:"Un hecho no prueba un motivo",comparison:{leftTitle:"Observación acotada",leftItems:["Intervino antes del cierre tres veces","El documento llegó después del plazo","Dos preguntas quedaron sin respuesta"],rightTitle:"Conclusión que requiere evidencia",rightItems:["No quiere escuchar","No le importa el proyecto","Está ocultando información"]}},
  {title:"Reescribir sin fingir objetividad",exercise:exercise("Separar veinte frases","Identifica observación, interpretación, inferencia, evaluación, sensación y solicitud.","Sustituye siempre o nunca por el momento y alcance observables."),example:{title:"Caso ficticio",text:"Luz dice “nadie me escucha”. Al revisar, identifica dos interrupciones y un acuerdo no registrado. Conserva su impacto personal, pero no atribuye una intención colectiva sin evidencia."}},
  {title:"Errores y límites",bullets:["Describir motivos como hechos","Invocar consenso sin comprobarlo","Usar impacto como prueba de intención","Usar buena intención para cancelar impacto","Inferir verdad a partir de postura, tono o mirada"],links:[{label:"Tomar decisiones con evidencia",href:"/aprende/resolucion-de-problemas"}]},
 ],["separate"]),

 lesson(4,"curiosidad-sin-invadir","Practicar curiosidad sin invadir","Usa preguntas para comprobar supuestos, no para esconder críticas o exigir divulgación.",["Elegir un tipo de pregunta","Crear una salida fácil","Reconocer preguntas que cierran"],[
  {title:"Curiosidad que abre",bullets:["Admite incertidumbre","Invita corrección","Busca contexto pertinente","Permite no responder","Evita asumir motivo"]},
  {title:"Curiosidad que cierra",bullets:["Busca confirmación","Contiene un veredicto","Fuerza justificación","Se vuelve repetitiva","Ignora un límite","Exige revelar emociones"],callout:{title:"Una pregunta también puede ejercer presión",text:"La curiosidad no es una virtud automática. El poder, el propósito, la privacidad y el costo de responder cambian la conversación."}},
  {title:"Preguntas por función",questionGroups:[{title:"Comprender",items:["Ejemplo","Contexto","Criterio","Excepción","Impacto"]},{title:"Decidir",items:["Alternativa","Evidencia faltante","Límite","Próximo paso"]}],exercise:exercise("Reformular preguntas","Reescribe preguntas acusatorias, dirigidas o invasivas sin ocultar el desacuerdo.","A veces corresponde afirmar una diferencia, no formular otra pregunta.")},
  {title:"Ejemplo con salida",example:{title:"Caso ficticio",text:"En vez de preguntar por qué Nadia está tan molesta, Omar dice que no quiere asumir cómo se siente y pregunta qué parte del acuerdo necesita aclaración; añade que pueden retomarlo por escrito."},links:[{label:"Aplicar curiosidad en networking",href:"/aprende/networking"}]},
 ],["curiosity"]),

 lesson(5,"clarificar-resumir-comprobar","Clarificar, resumir y comprobar","Practica conductas concretas para verificar significado antes de aconsejar o decidir.",["Parafrasear sin añadir motivos","Comprobar alcance y solicitud","Cerrar acuerdos de forma accesible"],[
  {title:"Seis movimientos flexibles",bullets:["Parafrasear significado","Resumir temas","Reflejar incertidumbre","Comprobar alcance","Confirmar la solicitud","Pedir corrección"],paragraphs:["Frases como “lo que entiendo hasta ahora” sirven como andamiaje, no como guiones obligatorios. Adapta el lenguaje y acepta correcciones."]},
  {title:"Errores de paráfrasis",bullets:["Repetir palabras sin significado","Añadir interpretación","Exagerar","Usar el resumen para cerrar el desacuerdo","Afirmar emoción como certeza","Pedir confirmación de una versión distorsionada"]},
  {title:"Ocho decisiones",example:{title:"Caso ficticio",text:"Sam recibe una explicación extensa. Resume dos asuntos, pregunta si la otra persona busca escucha, análisis o propuesta, y confirma qué debe quedar por escrito. La respuesta corrige uno de sus supuestos."},exercise:exercise("Elegir una comprobación","Para ocho mensajes ficticios, selecciona una aclaración, un resumen o una pregunta de alcance.","Incluye opciones escritas y asincrónicas.")},
  {title:"Cerrar el circuito",ordered:["Resume lo comprendido.","Nombra lo que sigue incierto.","Confirma acuerdo, desacuerdo o pausa.","Registra responsable y próximo paso.","Ofrece formato escrito si ayuda."],links:[{label:"Mejorar reuniones y mensajes",href:"/aprende/comunicacion-profesional"}]},
 ],["clarify","prepare"]),

 lesson(6,"reaccion-al-feedback","Entender la reacción al feedback","Reconoce fricción emocional y contextual sin diagnosticar ni suprimir la reacción.",["Distinguir fuentes simultáneas","Crear una pausa útil","Reconocer poder y consecuencia"],[
  {title:"Fuentes de fricción al recibir feedback",framework:framework(["Contenido","El mensaje parece impreciso, vago o injusto."],["Vínculo","La historia o el poder cambian cómo se recibe."],["Autoconcepto","Contradice la forma en que la persona se entiende."],["Momento","Cansancio, estrés o exposición intensifican la reacción."],["Consecuencia","Puede afectar evaluación, oportunidad, estatus o seguridad."]),callout:{title:"Modelo práctico",text:"Varias fuentes pueden operar a la vez. No son un diagnóstico, una taxonomía clínica ni una medida estable."}},
  {title:"Opciones inmediatas",bullets:["Pausar","Pedir tiempo","Solicitar un ejemplo","Tomar notas sin responder todavía","Nombrar confusión","Cambiar de formato o lugar","Confirmar si el mensaje es evaluativo, correctivo o de desarrollo","Preguntar qué decisión está en curso","Establecer un límite"]},
  {title:"Seis situaciones",example:{title:"Caso ficticio",text:"Ariel recibe una crítica pública de su responsable. El contenido puede contener información útil, pero el momento y la consecuencia requieren separar revisión del trabajo, límite sobre exposición y documentación del proceso."},exercise:exercise("Localizar fricción","Analiza seis casos sin etiquetar personalidad ni estado mental.","Propón al menos dos respuestas compatibles con seguridad y accesibilidad.")},
  {title:"Lo que regulación no significa",bullets:["Ocultar emoción","Aceptar el mensaje","Responder de inmediato","Respirar de una forma específica","Mantener contacto visual","Continuar una conversación insegura"],links:[{label:"Revisar límites y bienestar",href:"/aprende/relaciones-y-bienestar"}]},
 ],["respond"]),

 lesson(7,"evaluar-feedback","Evaluar feedback con criterio","Procesa la información antes de aceptarla o descartarla por reflejo.",["Aplicar el filtro de feedback","Elegir entre aplicar, probar, investigar o descartar","Distinguir repetición de validez"],[
  {title:"Filtro de feedback útil",framework:usefulFilter,callout:{title:"Modelo práctico",text:"El filtro organiza preguntas; no certifica la verdad, no mide apertura y no obliga a aceptar feedback repetido o proveniente de autoridad."}},
  {title:"Cuatro decisiones provisionales",framework:framework(["Aplicar","La evidencia es suficiente y la acción resulta apropiada."],["Probar","Persiste incertidumbre, pero existe un experimento pequeño y reversible."],["Investigar","Faltan ejemplos, contexto o perspectivas pertinentes."],["Descartar","Es irrelevante, abusivo, discriminatorio o no tiene respaldo."])},
  {title:"Comparar sin votar",example:{title:"Caso ficticio",text:"Dos personas dicen que Eva domina las reuniones y otra valora su síntesis. Eva pide momentos específicos, compara formato y rol, y prueba rondas de participación en dos reuniones. No concluye por frecuencia."},exercise:exercise("Diseñar una prueba","Compara tres mensajes parcialmente incompatibles y diseña un experimento de bajo riesgo.","Incluye evidencia que llevaría a detener la prueba.")},
  {title:"Preguntas de criterio",bullets:["¿Qué conducta específica?","¿En qué situación?","¿Qué efecto se observó?","¿Qué estándar se usa?","¿Qué sería diferente?","¿Es patrón o evento?","¿Quién decide el cambio?"],links:[{label:"Contrastar perspectivas profesionales",href:"/aprende/entrevistas-informativas"}]},
 ],["filter","respond"]),

 lesson(8,"dar-feedback","Dar feedback útil y respetuoso","Aumenta la calidad de información sin convertir una observación en juicio de identidad.",["Describir conducta y efecto","Nombrar estándar y poder","Abrir una conversación real"],[
  {title:"Situación, conducta, efecto y conversación",framework:framework(["Situación","Contexto relevante y acotado."],["Conducta","Comportamiento o producto observable."],["Efecto","Consecuencia o riesgo observado."],["Conversación","Aclaración, perspectiva y próximo paso."]),callout:{title:"Estructura flexible",text:"No es universal ni propietaria. En procesos formales puede requerirse documentación, estándar explícito y procedimientos vigentes."}},
  {title:"Elección y poder",bullets:["Pregunta si es bienvenido cuando exista opción real","Distingue feedback gerencial requerido de consejo opcional","Habla en privado cuando corresponda","No uses etiquetas de identidad","No supongas motivos","Nombra el estándar","Da ejemplos","Ofrece elección solo si realmente existe"]},
  {title:"Diez contextos",bullets:["Entre pares","De responsable a colaborador","Hacia una autoridad","Cliente","Revisión de proyecto","Presentación","Trabajo escrito","Equipo remoto","Malentendido intercultural","Reconocimiento positivo"],exercise:exercise("Reescribir doce mensajes","Transforma críticas vagas, personales o acusatorias en observación, efecto y conversación.","No ocultes una exigencia formal bajo una falsa invitación.")},
  {title:"Ejemplo positivo específico",example:{title:"Caso ficticio",text:"En vez de “gran trabajo”, Leila señala que el resumen separó decisiones y dudas, lo que permitió cerrar responsables. Pregunta si pueden reutilizar esa estructura, sin convertirla en obligación universal."},links:[{label:"Conectar feedback y marca profesional",href:"/aprende/marca-profesional"}]},
 ],["give"]),

 lesson(9,"conversaciones-dificiles-reparacion","Conversaciones difíciles y reparación","Decide cuándo reparar, documentar, escalar, pausar o terminar una interacción.",["Nombrar un desajuste","Reconocer impacto sin asumir intención","Elegir un canal seguro"],[
  {title:"Secuencia de reparación",ordered:["Nombra el desajuste.","Explica qué entendiste.","Invita una corrección.","Reconoce el impacto observable.","Acuerda el siguiente paso de comunicación.","Documenta cuando corresponda."]},
  {title:"Explicación no equivale a excusa",paragraphs:["Puedes explicar contexto y reconocer impacto a la vez. Una disculpa útil no exige una confesión exagerada ni garantiza reconciliación. Algunas diferencias quedan abiertas."]},
  {title:"Cuándo la reparación directa no basta",bullets:["Abuso","Represalia","Amenaza","Discriminación persistente","Disciplina formal","Disputa legal","Riesgo de seguridad","Cliente abusivo"],callout:{title:"Límite de esta ruta",text:"Las técnicas conversacionales no sustituyen canales formales, recursos humanos, mediación calificada, asesoría legal, atención de salud o intervención de seguridad."}},
  {title:"Diez decisiones",example:{title:"Caso ficticio",text:"Después de un comentario discriminatorio repetido, Jo no programa otra conversación informal. Conserva registros, revisa políticas y busca apoyo apropiado. La salida segura tiene prioridad sobre practicar reparación."},exercise:exercise("Elegir el canal","Decide entre reparar, pausar, documentar, escalar o salir en diez escenarios.","Explica poder, riesgo y evidencia disponible."),links:[{label:"Revisar seguridad y relaciones",href:"/aprende/relaciones-y-bienestar"}]},
 ],["repair","respond"]),

 lesson(10,"practica-integrada","Práctica integrada y herramientas","Integra atención, distinción, curiosidad, feedback, reparación y práctica en un caso ambiguo.",["Resolver quince etapas","Comparar alternativas válidas","Crear una práctica observable"],[
  {title:"Caso ficticio creado con fines educativos",caseStudy:{title:"Proyecto Nexo: “necesitas escuchar más”",paragraphs:["Después de una reunión transversal remota, una responsable dice a Dani que necesita escuchar más. Dani cree que solo intentaba aclarar fechas; otras personas recuerdan interrupciones, demoras de audio y preguntas sin cierre.","El feedback inicial es vago, existe diferencia de poder, una participante usa subtítulos y el plazo presiona al equipo. El caso no busca declarar quién tiene razón, sino mejorar la calidad de observación y decidir qué cambiar, verificar o limitar."]}},
  {title:"Quince etapas",ordered:["Describe el contexto de reunión.","Compara relatos distintos.","Registra el feedback inicial.","Nombra la reacción sin diagnosticar.","Separa observación e interpretación.","Solicita ejemplos.","Examina poder y vínculo.","Añade perspectivas pertinentes.","Formula explicaciones competidoras.","Rediseña la conversación de feedback.","Elige un experimento pequeño.","Realiza una reunión de seguimiento.","Revisa evidencia observable.","Repara un malentendido.","Decide qué cambiar y qué conservar."]},
  {title:"Modos accesibles de práctica",bullets:["Individual","En pareja","Grupo facilitado","Escrito o asincrónico","Reunión remota","Situación de bajo riesgo","Situación de alto riesgo con límites","Autoobservación","Guía para observador"],callout:{title:"Sin grabación obligatoria",text:"La práctica puede usar notas ficticias o una guía escrita. No requiere audio, cámara, contacto visual, postura particular ni divulgación personal."}},
  {title:"Razonamiento y rúbrica",modelAnswers:[{title:"Observación",text:"Pediría momentos, turnos y acuerdos concretos; no usaría “escucha” como etiqueta global."},{title:"Accesibilidad",text:"Consideraría demora, subtítulos, turnos explícitos, agenda y seguimiento escrito como parte del contexto."},{title:"Experimento",text:"Probaría una pregunta prioritaria, resumen antes de responder y ronda final; observaría aclaraciones y acuerdos, no una puntuación personal."},{title:"Límite",text:"Si el feedback se vuelve humillante o disciplinario, separaría práctica informal del proceso formal y buscaría apoyo."}],rubric:["Atención elegida","Observación separada de inferencia","Curiosidad con límites","Resumen corregible","Criterio ante feedback","Poder y seguridad","Accesibilidad","Próximo experimento"],exercise:exercise("Resolver Proyecto Nexo","Crea análisis, pregunta, respuesta, experimento y plan de seguimiento.","Incluye dos resoluciones razonables y qué evidencia las distinguiría.")},
 ],["attention","separate","filter","practice"]),
];

const caseSeeds=[["Interrupciones en reunión","Tres personas se pisan al hablar"],["Refutación preparada","Una respuesta se forma antes de escuchar el final"],["Consejo inmediato","Alguien pide escucha y recibe soluciones"],["Mensaje escrito ambiguo","Un texto breve se interpreta como enfado"],["Feedback de responsable","El mensaje puede afectar una evaluación"],["Feedback entre pares","Una colega propone cambiar una práctica"],["Feedback ascendente","Una persona comenta a quien decide su trabajo"],["Cliente crítico","Un cliente mezcla observación con ataque"],["Crítica pública","El comentario debió ocurrir en privado"],["Elogio vago","No queda claro qué conviene repetir"],["Crítica vaga","Se pide mejorar la actitud"],["Dos mensajes opuestos","Dos fuentes describen la misma conducta de modo distinto"],["Preferencia de estilo","Se presenta una preferencia como norma"],["Sesgo repetido","Varias personas repiten la misma expectativa discriminatoria"],["Útil pero mal entregado","Existe evidencia dentro de un mensaje hostil"],["Amable sin respaldo","El mensaje positivo no ofrece ejemplos"],["Una palabra activa defensa","Un término concentra toda la atención"],["Lectura intercultural","Se atribuye intención a una convención diferente"],["Comunicación neurodivergente","Se confunde una forma de procesar con desinterés"],["Acceso auditivo o lingüístico","Falta apoyo para comprender en tiempo real"],["Demora remota","El retraso de audio parece interrupción"],["Cámara apagada","Se infiere falta de compromiso"],["Escucha antes que consejo","La solicitud real no fue comprobada"],["Feedback declinado","Una persona no acepta una conversación opcional"],["Escalamiento formal","El caso incluye represalia y requiere otro canal"],["Reparación posible","Dos personas corrigen una inferencia"],["Reparación que debe parar","Una amenaza hace inseguro continuar"],["Seguimiento escrito","La asincronía mejora precisión y acceso"]];
export const listeningCases=caseSeeds.map(([title,context],index)=>({id:`escucha-caso-${String(index+1).padStart(2,"0")}`,title,label:"Caso ficticio creado con fines educativos.",difficulty:index<10?"inicial":index<20?"intermedia":"avanzada",learningObjective:`Practicar una decisión contextual en “${title}”.`,context,observations:["Existe información observable pero incompleta","Las personas describen momentos diferentes"],interpretations:["Hay al menos dos significados plausibles"],missingInformation:["Ejemplo específico","Contexto, estándar o poder"],decisionPoint:"¿Conviene aclarar, probar, limitar, documentar, escalar o cerrar?",actions:["Pedir un ejemplo acotado","Proponer una comprobación o prueba","Elegir un límite o canal alternativo"],risks:["Convertir inferencia en hecho","Ignorar poder o acceso","Forzar una conversación insegura"],feedback:"Distingue observación, interpretación, contexto, accesibilidad y autoridad. Varias respuestas pueden ser defendibles.",relatedLesson:listeningLessons[index%10].slug,relatedTool:Object.keys(listeningToolLinks)[index%10],fictional:true}));

const resourceSeeds=[["observacion-atencion","Ficha de observación de atención"],["separar-capaz","Tabla de observación, interpretación e inferencia"],["plan-preguntas","Planificador de preguntas de curiosidad"],["tarjeta-clarificacion","Tarjeta de aclaraciones"],["resumen-conversacion","Plantilla de resumen de conversación"],["friccion-feedback","Mapa de fricción ante feedback"],["evidencia-feedback","Ficha de evidencia de feedback"],["preparar-feedback","Hoja para preparar feedback"],["respuesta-feedback","Planificador de respuesta"],["reparacion","Guía de reparación"],["limites-dificil","Guía de límites para conversaciones difíciles"],["observador-practica","Ficha para observar una práctica"],["facilitacion-escucha","Guía de facilitación"],["plan-personal","Plan personal de práctica"],["feedback-asincronico","Guía de feedback asincrónico"]];
export const listeningResources=resourceSeeds.map(([id,title])=>({id,title,description:"Recurso original para registrar hechos, contexto, límites y una decisión sin puntuar personas.",contentType:"worksheet",format:"HTML · editable · imprimible",status:"published",reminder:"Usa situaciones ficticias o anónimas. No ingreses nombres, transcripciones, datos de salud, RR. HH. o información confidencial.",fields:["Propósito y situación","Observación directa","Interpretación o reacción","Contexto y evidencia faltante","Accesibilidad, poder o seguridad","Próximo paso"]}));
export const getListeningLesson=(slug)=>listeningLessons.find((item)=>item.slug===slug);
