const updatedAt = "2026-07-15";
const base = "/aprende/resolucion-de-problemas";

const scenarios = [
  ["Centro de atención", "La espera subió de forma repentina tras un cambio de turnos.", "¿Hace falta contener la demanda, revisar capacidad o investigar una medición defectuosa?"],
  ["Programa vespertino", "Una universidad evalúa abrir un programa para personas que trabajan.", "¿Qué evidencia reduciría la incertidumbre sobre necesidad y viabilidad?"],
  ["Despachos incompletos", "Una fábrica acumula entregas parciales aunque la producción total no cayó.", "¿En qué etapa se origina el retraso y quién puede cambiarla?"],
  ["Reorganización del equipo", "Una persona clave dejó el área antes de cerrar un proyecto.", "¿Qué trabajo debe protegerse, redistribuirse o detenerse?"],
].map(([title, situation, question], index) => ({ id: `tipo-${index + 1}`, title, situation, question, action: "Clasifica urgencia, incertidumbre, reversibilidad, actores y profundidad necesaria.", constraint: "La clasificación orienta el esfuerzo; no sustituye protocolos de seguridad ni criterio especialista." }));

const ambiguousExercises = ["Cayó la finalización de cursos digitales.", "Las citas de atención se postergan.", "El equipo casi no usa el tablero interno.", "El costo de reparto aumentó.", "Bajó la asistencia a un programa comunitario.", "Los pronósticos comerciales varían demasiado."].map((text, index) => ({ title: `Enunciado ${index + 1}`, text: `${text} Distingue síntoma y decisión; luego escribe una pregunta CLARO, delimita alcance, dos restricciones y tres actores.` }));

const treeExercises = ["Margen en descenso", "Rotación de personal", "Entregas tardías", "Adopción baja", "Entrada a una región", "Reclamos recurrentes", "Participación ciudadana", "Implementación tecnológica"].map((title) => ({ title, text: `Construye una primera capa para “${title}”. Una vía posible es separar demanda, oferta/capacidad, proceso, medición y contexto; cambia las ramas si la decisión exige otra lógica.` }));

export const practiceProblems = [
  ["cuello-operativo","Turnos en el centro de distribución","Cuello de botella operativo","intermedio","¿Cómo recuperar puntualidad sin ampliar instalaciones?"],
  ["costos","Costo de atención en terreno","Aumento de costos","introductorio","¿Qué componente explica el aumento y qué acción conviene priorizar?"],
  ["retencion","Renovaciones del software NubeSur","Retención de clientes","intermedio","¿Cómo recuperar renovaciones sin descuentos generalizados?"],
  ["adopcion","Portal de beneficios Vecina","Adopción de producto","introductorio","¿Qué fricción impide completar el primer uso valioso?"],
  ["expansion","Academia Horizonte","Expansión de mercado","avanzado","¿Conviene abrir operaciones en una segunda región?"],
  ["dotacion","Cobertura del laboratorio","Problema de dotación","intermedio","¿Cómo sostener cobertura tras un cambio de turnos?"],
  ["pronostico","Demanda estacional de Brisa","Error de pronóstico","intermedio","¿Qué supuestos deben revisarse antes del próximo ciclo?"],
  ["calidad","Reprocesos en Taller Luma","Calidad de proceso","introductorio","¿Dónde se origina el reproceso y cómo comprobarlo?"],
  ["servicio-publico","Taller barrial Puente","Participación en servicio público","intermedio","¿Qué cambio puede mejorar la asistencia efectiva?"],
  ["tecnologia","Inventario digital en Red Norte","Implementación tecnológica","avanzado","¿Cómo recuperar la adopción sin paralizar la operación?"],
  ["inversion","Nueva línea de EcoEnvase","Decisión de inversión","avanzado","¿Qué condiciones deben cumplirse antes de invertir?"],
  ["colaboracion","Prioridades del equipo Prisma","Colaboración de equipo","intermedio","¿Cómo cerrar una prioridad con evidencia y disenso útil?"],
].map(([slug,title,category,difficulty,decision], index) => ({
  slug,title,category,difficulty,fictional:true,
  description:`Práctica breve sobre ${category.toLowerCase()}.`, prompt:`El equipo de ${title} dispone de dos semanas para presentar una decisión razonada.`, decision,
  context:["La evidencia disponible es incompleta.","Dos áreas ofrecen explicaciones distintas."], constraints:["Capacidad limitada para investigar.","La decisión no puede depender de una sola fuente."],
  stakeholders:["Responsable de la decisión","Equipo operativo","Personas usuarias"], knownFacts:[`Existe una variación observable en el indicador ${index + 1}.`,"La medición cambió recientemente y debe revisarse."], unknowns:["Causa dominante","Viabilidad de implementación"],
  possibleHypotheses:["La fricción principal está en el proceso.","Cambió la composición de la demanda.","Parte del efecto proviene de la medición."],
  possibleStructures:["Demanda / capacidad / proceso / medición / contexto"], evidence:["Serie temporal interna","Entrevistas breves","Muestra de casos"],
  prioritizationExercise:"Ordena tres pruebas con VERA y declara una regla de parada.", synthesisPrompt:"Redacta un HIA que conecte un hallazgo con la decisión.", recommendationPrompt:"Formula una recomendación DECIR con riesgo, responsable y revisión.",
  modelInsights:["Conviene validar primero medición y concentración del efecto antes de escalar una solución general."], skills:["Definición","Hipótesis","Priorización","Síntesis"]
}));

export const problemSolvingResources = [
  { id:"type-diagnostic",title:"Diagnóstico de profundidad",description:"Orienta cuánto proceso puede requerir una decisión.",contentType:"diagnostic",status:"published",href:"/herramientas/diagnostico-tipo-problema",reminder:"Es una orientación, no un diagnóstico especializado." },
  { id:"claro",title:"Checklist CLARO",description:"Revisa si la pregunta es concreta, ligada a una decisión, acotada, referida a un resultado y oportuna.",contentType:"checklist",status:"published",groups:[{title:"Pregunta del problema",items:["Nombra una decisión concreta","Delimita alcance","Explicita resultado","Incluye horizonte","Permite actuar"]}],reminder:"CLARO es un modelo práctico de esta guía." },
  { id:"problem-canvas",title:"Lienzo de definición",description:"Alinea decisión, contexto, objetivo, métrica y límites.",contentType:"worksheet",status:"published",fields:["Decisión","Situación actual","Resultado deseado","Métrica","Horizonte","Incluido","Excluido","Restricciones","Actores","Evidencia","Incógnitas"],reminder:"Revisa el lienzo cuando cambie la evidencia." },
  { id:"stakeholder-map",title:"Mapa de actores",description:"Distingue información, influencia y función en la ejecución.",contentType:"worksheet",status:"published",fields:["Actor","Interés","Influencia","Información que aporta","Papel en la decisión","Papel en la ejecución","Acción de participación"],reminder:"No todas las personas deben aprobar cada decisión." },
  { id:"hypothesis-register",title:"Registro de hipótesis",description:"Contrasta explicaciones sin convertirlas en hechos.",contentType:"worksheet",status:"published",fields:["Hipótesis","Evidencia a favor","Evidencia en contra","Prueba","Estado cualitativo","Siguiente acción"],reminder:"Mantén explicaciones alternativas abiertas." },
  { id:"logic-tree",title:"Hoja de árbol lógico",description:"Divide una pregunta en ramas investigables.",contentType:"worksheet",status:"published",fields:["Pregunta principal","Tipo de árbol","Ramas","Subpreguntas","Evidencia","Prioridad"],reminder:"Relevancia antes que elegancia formal." },
  { id:"vera",title:"Matriz VERA",description:"Compara valor, evidencia, riesgo y accesibilidad.",contentType:"worksheet",status:"published",fields:["Pregunta","Valor para la decisión","Evidencia disponible","Riesgo de ignorar","Accesibilidad","Decisión de prioridad"],reminder:"Usa niveles cualitativos y registra excepciones." },
  { id:"work-plan",title:"Plantilla de plan de trabajo",description:"Conecta pregunta, análisis, fuente, responsable y salida.",contentType:"worksheet",status:"published",fields:["Frente","Pregunta","Hipótesis","Análisis","Fuente","Responsable","Fecha","Resultado","Regla de parada"],reminder:"Etiqueta hechos, supuestos, estimaciones e incógnitas." },
  { id:"assumptions",title:"Registro de supuestos",description:"Hace visibles condiciones aún no verificadas.",contentType:"worksheet",status:"published",fields:["Supuesto","Importancia","Evidencia","Prueba","Responsable","Estado"],reminder:"Cambiar de opinión ante evidencia nueva es parte del proceso." },
  { id:"evidence",title:"Checklist de evidencia",description:"Revisa calidad antes de apoyar una decisión.",contentType:"checklist",status:"published",groups:[{title:"Calidad de la evidencia",items:["Fuente identificable","Relevante para la pregunta","Vigencia suficiente","Método comprensible","Muestra adecuada","Incentivos considerados","Conflictos visibles"]}],reminder:"Correlación no demuestra causalidad." },
  { id:"hia",title:"Plantilla HIA",description:"Convierte un dato en hallazgo, implicación y acción.",contentType:"worksheet",status:"published",fields:["Hallazgo","Implicación para la decisión","Acción"],reminder:"No agregues una acción que la evidencia no sostenga." },
  { id:"decir",title:"Plantilla DECIR",description:"Estructura una recomendación ejecutable.",contentType:"worksheet",status:"published",fields:["Decisión","Evidencia","Condiciones","Impacto","Riesgos","Responsable","Revisión"],reminder:"Explicita incertidumbre y condiciones." },
  { id:"decision-log",title:"Registro de decisiones",description:"Conserva el razonamiento y la fecha de revisión.",contentType:"worksheet",status:"published",fields:["Decisión","Fecha","Responsable","Evidencia","Supuestos","Alternativas","Incertidumbre","Fecha de revisión"],reminder:"Registra cambios y por qué ocurrieron." },
  { id:"meeting",title:"Guía de reunión de resolución",description:"Ayuda a cerrar una conversación con prioridades y responsables.",contentType:"template",status:"published",template:"DECISIÓN A TOMAR\n\nHECHOS CONFIRMADOS\n\nHIPÓTESIS EN COMPETENCIA\n\nDIFERENCIAS Y EVIDENCIA FALTANTE\n\nPRIORIDAD\n\nSIGUIENTES ACCIONES · RESPONSABLE · FECHA",reminder:"Invita primero perspectivas independientes y critica ideas, no personas." },
];

const lessons = [
  { slug:"comprender-el-problema",title:"Comprender el problema antes de resolverlo",description:"Clasifica el desafío y elige una profundidad proporcional a sus consecuencias.",outcomes:["Distinguir pensamiento divergente y convergente","Evaluar urgencia, incertidumbre y reversibilidad","Elegir entre resolución rápida, enfocada o extendida"],sections:[
    {title:"Un problema tiene varias dimensiones",paragraphs:["Antes de buscar una solución, observa tiempo disponible, naturaleza cuantitativa o cualitativa, incertidumbre, reversibilidad y complejidad de actores. Un mismo proyecto puede combinar varias clases de problema.","Ante una emergencia, reducir el daño y seguir protocolos aplicables puede tener prioridad mientras la investigación continúa."],bullets:["Decisión inmediata, investigación breve o proyecto extenso","Exploración divergente, selección convergente o ciclo entre ambas","Método conocido, causa incierta, objetivo ambiguo o datos débiles","Decisión reversible, costosa de revertir o crítica"]},
    {title:"Abrir y cerrar posibilidades",comparison:{leftTitle:"Pensamiento divergente",leftItems:["Explora causas","Genera opciones","Busca perspectivas","Cuestiona supuestos"],rightTitle:"Pensamiento convergente",rightItems:["Compara alternativas","Prioriza pruebas","Descarta explicaciones débiles","Elige una acción"]},paragraphs:["Cerrar demasiado pronto oculta alternativas; abrir indefinidamente evita decidir. Alterna ambos modos de acuerdo con la evidencia."]},
    {title:"Tres profundidades posibles",framework:[{title:"Rápida",text:"Para consecuencias limitadas y decisiones reversibles: decisión, restricción, información suficiente y siguiente acción segura."},{title:"Enfocada",text:"Para días o semanas: definición, hipótesis, prioridades, responsables y alineamiento."},{title:"Extendida",text:"Para dependencias y consecuencias relevantes: gobernanza, hitos, riesgos, síntesis iterativa e implementación."}]},
    {title:"Practica con cuatro contextos",scenarios},
    {title:"Decidir cuánto análisis basta",callout:{title:"Estructura no es burocracia",text:"Puede ser una pausa de cinco minutos o un proyecto formal. El esfuerzo debe ser proporcional y revisable."},links:[{label:"Usar el diagnóstico de profundidad",href:"/herramientas/diagnostico-tipo-problema"}]},
    {title:"Conexiones útiles",links:[{label:"Reencuadrar un desafío",href:"/aprende/adaptabilidad-resiliencia/reencuadrar-desafios"},{label:"Practicar bajo restricciones de entrevista",href:"/aprende/consultoria/entrevistas-de-caso"}]}
  ],relatedResources:["type-diagnostic"],relatedTools:["diagnostico-tipo-problema"]},
  { slug:"definir-el-problema",title:"Definir la decisión y el alcance",description:"Separa síntoma, causa posible, decisión y objetivo antes de diseñar análisis.",outcomes:["Escribir una pregunta CLARO","Delimitar alcance y restricciones","Mapear actores y evidencia"],sections:[
    {title:"Cuatro niveles que no conviene confundir",examples:[{title:"Síntoma",text:"Las renovaciones bajaron."},{title:"Causa posible",text:"Las personas nuevas podrían no completar la puesta en marcha."},{title:"Decisión",text:"¿Qué cambio del proceso debemos priorizar?"},{title:"Objetivo",text:"Mejorar la renovación del segmento pequeño durante dos trimestres sin elevar de forma relevante el costo de soporte."}]},
    {title:"CLARO: una pregunta que habilita acción",framework:[{title:"Concreta",text:"Nombra lo que realmente debe resolverse."},{title:"Ligada a una decisión",text:"Responderla permite actuar."},{title:"Acotada",text:"Hace visibles sus límites."},{title:"Referida a un resultado",text:"Permite reconocer éxito."},{title:"Oportuna",text:"Define el horizonte relevante."}],callout:{title:"Modelo práctico",text:"CLARO fue creado para esta guía; no es un estándar científico."}},
    {title:"El lienzo de definición",bullets:["Decisión y pregunta","Situación y resultado deseado","Métrica y horizonte","Incluido y excluido","Restricciones, actores y responsable","Evidencia, incógnitas, riesgos y respuesta suficiente"]},
    {title:"Alcance y restricciones",paragraphs:["Un alcance útil incluye soluciones plausibles sin volverse inabarcable. Puede delimitar geografía, clientes, producto, proceso, tiempo, finanzas u organización.","Distingue restricciones confirmadas, supuestas, negociables y autoimpuestas: presupuesto, tiempo, regulación, tecnología, capacidad, contratos, datos, seguridad o dependencias."]},
    {title:"Actores y preguntas potentes",questionGroups:[{title:"Decisión y éxito",items:["¿Qué debe decidirse y quién decide?","¿Qué resultado cambiaría?","¿Qué intercambio es aceptable?"]},{title:"Evidencia e implementación",items:["¿Qué sabemos y qué creemos?","¿Qué dato cambiaría la decisión?","¿Quién debe ejecutar y qué capacidad falta?"]}]},
    {title:"Reescribe problemas ambiguos",examples:ambiguousExercises,links:[{label:"Abrir el constructor de definición",href:"/herramientas/definir-problema"}]}
  ],relatedResources:["claro","problem-canvas","stakeholder-map"],relatedTools:["definir-problema"]},
  { slug:"hipotesis-y-estructura",title:"Formular hipótesis y estructurar",description:"Usa explicaciones provisionales y árboles lógicos para orientar la búsqueda de evidencia.",outcomes:["Formular hipótesis reemplazables","Elegir un tipo de árbol","Revisar cobertura y solapamiento"],sections:[
    {title:"Una hipótesis es una dirección provisional",paragraphs:["Una hipótesis ayuda a decidir qué evidencia buscar primero. No es un hecho, una conclusión ni un compromiso: debe poder probarse, contradecirse y reemplazarse."],examples:[{title:"Demora operativa",text:"La mayor fricción podría estar en la programación de capacidad, no en el transporte."},{title:"Adopción",text:"La falta de claridad sobre el valor podría pesar más que la dificultad técnica."}]},
    {title:"Mantén explicaciones en competencia",bullets:["Registra evidencia a favor y en contra","Define una prueba que pueda cambiar tu opinión","Usa confianza cualitativa: débil, plausible, fuerte, rechazada o no resuelta"]},
    {title:"Cinco árboles para cinco lógicas",framework:[{title:"Impulsores",text:"Descompone una métrica: ingresos = clientes × frecuencia × ticket medio."},{title:"Causas",text:"Separa áreas que podrían explicar un síntoma."},{title:"Decisión",text:"Organiza criterios para elegir."},{title:"Hipótesis",text:"Expone condiciones que deberían cumplirse."},{title:"Proceso",text:"Revisa etapas y transferencias."}]},
    {title:"Construye hasta llegar a una prueba",ordered:["Escribe la pregunta principal.","Elige una lógica.","Crea ramas de primer nivel.","Convierte ramas en preguntas investigables.","Detente cuando una prueba pueda responder la hoja.","Revisa cobertura, solapamiento y relevancia.","Prioriza y actualiza con evidencia."]},
    {title:"Cobertura sin obsesión formal",paragraphs:["Evita repetir la misma pregunta y cubre las categorías decisivas. La idea conocida como MECE puede ayudar, pero una estructura útil no necesita perfección geométrica: un solapamiento explícito puede ser manejable."],bullets:["No mezcles causas y soluciones en un nivel","No copies un marco familiar sin conectarlo a la decisión","Valida la primera capa antes de profundizar"]},
    {title:"Ocho prácticas de estructura",examples:treeExercises,links:[{label:"Construir un árbol accesible",href:"/herramientas/constructor-arbol-problemas"}]}
  ],relatedResources:["hypothesis-register","logic-tree"],relatedTools:["constructor-arbol-problemas"]},
  { slug:"priorizar",title:"Priorizar preguntas y análisis",description:"Concentra el esfuerzo en las pruebas con mayor valor para la decisión.",outcomes:["Aplicar VERA de forma cualitativa","Reconocer excepciones críticas","Definir reglas de parada"],sections:[
    {title:"Analizar más no siempre ayuda",paragraphs:["Tiempo, datos y atención son limitados. Priorizar permite investigar primero lo que podría cambiar la decisión, sin eliminar para siempre explicaciones plausibles de alto riesgo."]},
    {title:"El principio práctico detrás del 80/20",callout:{title:"No es una ley exacta",text:"Busca el conjunto mínimo de preguntas que podría cambiar la decisión; no supongas que una proporción fija se cumple en todos los contextos."}},
    {title:"VERA",framework:[{title:"Valor para la decisión",text:"¿La respuesta podría cambiar lo que haremos?"},{title:"Evidencia disponible",text:"¿Puede examinarse con credibilidad?"},{title:"Riesgo de ignorarlo",text:"¿Qué ocurre si omitimos esta explicación?"},{title:"Accesibilidad",text:"¿Cabe en el tiempo y recursos disponibles?"}],paragraphs:["Usa niveles bajo, medio y alto. La precisión numérica sin fundamento puede ocultar juicio débil."]},
    {title:"Matriz de decisión y esfuerzo",comparison:{leftTitle:"Mayor valor",leftItems:["Bajo esfuerzo: investigar primero","Alto esfuerzo: planificar y secuenciar"],rightTitle:"Menor valor",rightItems:["Bajo esfuerzo: verificación opcional","Alto esfuerzo: diferir o eliminar"]},paragraphs:["Seguridad, cumplimiento, ética, irreversibilidad y dependencias críticas pueden cambiar el orden."]},
    {title:"Decide cuándo detenerte",checklist:["Definí evidencia suficiente","Sé qué refutaría la hipótesis","Sé qué activaría más análisis","Aclaré cuándo basta una dirección","Mantendré visible la incertidumbre"]},
    {title:"Caso: renovaciones de NubeSur",caseStudy:{title:"Seis explicaciones",paragraphs:["Las renovaciones bajaron. El equipo considera puesta en marcha débil, confiabilidad, precio, mezcla de clientes, competencia y error de medición.","Una respuesta posible prioriza validar medición y concentración por cohorte; luego prueba experiencia inicial y confiabilidad. El orden cambia si ya existe evidencia sólida o un riesgo crítico."]},links:[{label:"Priorizar un análisis",href:"/herramientas/priorizar-analisis"}]}
  ],relatedResources:["vera","evidence"],relatedTools:["priorizar-analisis"]},
  { slug:"plan-y-analisis",title:"Diseñar un plan de trabajo y analizar",description:"Conecta preguntas prioritarias con evidencia, métodos, responsables y decisiones.",outcomes:["Elegir análisis proporcionales","Clasificar hechos y supuestos","Diseñar revisiones y reglas de parada"],sections:[
    {title:"Un plan conecta razonamiento y ejecución",bullets:["Pregunta prioritaria e hipótesis","Evidencia y método","Fuente, responsable y fecha","Dependencia y salida","Hito de decisión y regla de parada"]},
    {title:"Elige el método por la pregunta",questionGroups:[{title:"Cuantitativos",items:["Tendencias, segmentos, variaciones y embudos","Cohortes, capacidad, finanzas, escenarios y pronósticos","Experimentos cuando sean viables y éticos"]},{title:"Cualitativos",items:["Entrevistas y observación","Mapeo de procesos y documentos","Investigación de usuarios, consulta experta y talleres"]}],paragraphs:["Muchos problemas requieren combinar métodos. Ningún método compensa una pregunta mal definida."]},
    {title:"Exactitud antes que detalle aparente",example:{title:"Pronóstico frágil",text:"Informar 127.483 unidades parece preciso, pero no es necesariamente exacto si población y adopción son inciertas. Un rango con supuestos visibles puede ser más útil."}},
    {title:"Etiqueta cada afirmación",framework:[{title:"Hecho",text:"Cuenta con evidencia confiable."},{title:"Supuesto",text:"Se acepta temporalmente para avanzar."},{title:"Estimación",text:"Combina hechos y supuestos."},{title:"Interpretación",text:"Asigna significado a la evidencia."},{title:"Incógnita",text:"Aún no se conoce."}]},
    {title:"Calidad y puntos de control",bullets:["Confiabilidad, vigencia y relevancia de la fuente","Muestra, medición e incentivos","Evidencia contradictoria y datos ausentes","Diferencia entre asociación y causalidad"],checklist:["El análisis sigue respondiendo la pregunta","La hipótesis continúa abierta a revisión","Sé qué aprendimos y qué falta","Puedo detener o redirigir trabajo"]},
    {title:"Caso: entregas de Ruta Clara",caseStudy:{title:"Plan de dos semanas",paragraphs:["Una empresa logística regional debe explicar atrasos con datos de rutas, escaneos y capacidad, dos analistas y diez días hábiles.","Un plan posible valida primero la medición; luego segmenta retrasos por ruta y etapa, contrasta capacidad con volumen, entrevista a coordinación y sintetiza a mitad de período. Cada frente tiene responsable, salida y regla de parada."]},links:[{label:"Crear un plan de trabajo",href:"/herramientas/plan-trabajo-problema"}]}
  ],relatedResources:["work-plan","assumptions","evidence"],relatedTools:["plan-trabajo-problema"]},
  { slug:"sintesis-y-recomendaciones",title:"Sintetizar y recomendar",description:"Convierte hallazgos dispersos en una decisión, sus condiciones y un primer paso.",outcomes:["Escribir un HIA","Formular una recomendación DECIR","Integrar riesgo e implementación"],sections:[
    {title:"Resumen no es síntesis",comparison:{leftTitle:"Resumen",leftItems:["Repite hallazgos","Describe lo observado","Puede dejar la decisión abierta"],rightTitle:"Síntesis",rightItems:["Conecta hallazgos","Explica su significado","Orienta la decisión"]}},
    {title:"HIA: del dato a la acción",framework:[{title:"Hallazgo",text:"Qué muestra la evidencia."},{title:"Implicación",text:"Por qué importa para la decisión."},{title:"Acción",text:"Qué debería ocurrir por ese significado."}],callout:{title:"Estructura práctica",text:"HIA fue creada para esta guía y no convierte evidencia débil en certeza."}},
    {title:"Sintetiza durante el proyecto",checklist:["Qué cambió","Qué significa","Qué hipótesis ganó o perdió apoyo","Qué pregunta sigue","Qué parte del plan debe ajustarse"]},
    {title:"DECIR: una recomendación completa",framework:[{title:"Decisión",text:"Qué propones hacer."},{title:"Evidencia",text:"Qué hallazgos la sostienen."},{title:"Condiciones",text:"Cuándo sigue siendo válida."},{title:"Impacto",text:"Qué cambio razonable se espera."},{title:"Riesgos",text:"Qué puede fallar y cómo responder."}]},
    {title:"Errores que debilitan la conclusión",bullets:["Mostrar todo el análisis sin hacer un punto","Listar hallazgos sin implicación","Ignorar restricciones o incertidumbre","Proponer demasiadas acciones","Omitir responsable, secuencia o revisión"]},
    {title:"Implementar y practicar",paragraphs:["Define primera acción, responsable, secuencia, recursos, participación, piloto o despliegue, métrica y fecha para detener, continuar o modificar."],examples:["Retención de suscripciones","Asistencia a un programa","Paradas de fábrica","Error comercial","Incorporación de personal","Adopción de billetera digital","Finalización universitaria","Costo de despacho"].map((title)=>({title,text:"Escribe un HIA con evidencia contradictoria; luego una recomendación DECIR, un riesgo y el siguiente paso."})),links:[{label:"Construir una recomendación",href:"/herramientas/constructor-recomendaciones"}]}
  ],relatedResources:["hia","decir","decision-log"],relatedTools:["constructor-recomendaciones"]},
  { slug:"colaboracion-y-sesgos",title:"Resolver problemas en equipo",description:"Combina perspectivas sin confundir consenso, jerarquía o confianza con calidad del razonamiento.",outcomes:["Aclarar derechos de decisión","Reconocer riesgos de sesgo","Facilitar desacuerdo constructivo"],sections:[
    {title:"Más personas no garantizan mejor razonamiento",comparison:{leftTitle:"Puede aportar",leftItems:["Información diversa","Experiencia especializada","Riesgos de implementación","Mayor apropiación"],rightTitle:"También puede crear",rightItems:["Pensamiento grupal","Deferencia jerárquica","Responsabilidad difusa","Debate interminable"]}},
    {title:"Roles y derechos",bullets:["Responsable de decidir","Responsable del problema","Responsable de análisis","Especialista o representante de implementación","Facilitación, revisión crítica y registro"],paragraphs:["Aclara quién recomienda, decide, aporta, ejecuta y debe ser informado. Un problema pequeño no necesita una gobernanza grande."]},
    {title:"Sesgos como riesgos, no diagnósticos",bullets:["Confirmación y exceso de confianza","Anclaje y preferencia por el estado actual","Disponibilidad y pensamiento grupal","Autoridad y costo hundido"],paragraphs:["Estas etiquetas pueden orientar preguntas; no explican por sí solas cada error ni diagnostican a una persona."]},
    {title:"Contramedidas observables",framework:[{title:"Explicaciones rivales",text:"Exige dos hipótesis plausibles."},{title:"Evidencia en contra",text:"Pregunta qué refutaría la preferida."},{title:"Vista independiente",text:"Registra opiniones antes del debate."},{title:"Revisión del fracaso",text:"Imagina que la decisión falló y busca causas."},{title:"Registro",text:"Documenta decisión, evidencia, incertidumbre y revisión."}]},
    {title:"Desacuerdo seguro y útil",checklist:["Criticar ideas, no personas","Pedir evidencia y admitir incertidumbre","Invitar voces menos presentes","Permitir cambiar de opinión","Cerrar cuando existe evidencia suficiente"]},
    {title:"Caso: lanzamiento en Prisma",caseStudy:{title:"Una voz con mucha autoridad",paragraphs:["La dirección favorece lanzar una función nueva, pero uso piloto, soporte y clientes entregan señales mixtas.","El equipo registra su opinión individual, asigna una revisión crítica rotativa, contrasta hipótesis y acuerda qué evidencia permitiría decidir. La dirección conserva su derecho de decisión y deja visible el razonamiento."]},links:[{label:"Usar el registro de decisiones",href:`${base}#resource-decision-log`},{label:"Practicar feedback y reflexión",href:"/aprende/adaptabilidad-resiliencia/reflexion-y-feedback"}]}
  ],relatedResources:["assumptions","decision-log","meeting"],relatedTools:[]},
  { slug:"caso-integrador",title:"Aplicar el método completo",description:"Recorre una decisión ambigua desde la definición hasta la recomendación y su revisión.",outcomes:["Integrar las ocho etapas","Revisar una hipótesis con evidencia contradictoria","Proponer una implementación condicionada"],sections:[
    {title:"Caso ficticio: Aula Región",paragraphs:["Caso ficticio creado con fines educativos.","Una plataforma regional de formación profesional enfrenta menor finalización, más solicitudes de soporte y crecimiento lento. Tiene presupuesto limitado y debe decidir en seis semanas qué intervención priorizar."],bullets:["Actores: dirección, producto, docentes, soporte, clientes corporativos, participantes, finanzas y tecnología","Hipótesis: duración, tiempo disponible, incorporación, rendimiento técnico, mezcla de clientes, medición o incentivos"]},
    {title:"Exhibiciones",questionGroups:[{title:"Datos operativos",items:["La finalización cae sobre todo en cursos con más de ocho unidades.","Los tiempos de carga empeoran, pero no explican toda la variación.","Parte de las cuentas nuevas usa una definición distinta de finalización."]},{title:"Entrevistas",items:["Participantes mencionan falta de tiempo y una primera semana poco clara.","Docentes observan abandono antes de la primera actividad.","Clientes corporativos difieren en tiempo protegido e incentivos."]}]},
    {title:"Tu recorrido",ordered:["Clasifica el problema.","Define decisión, alcance y restricciones.","Escribe una pregunta CLARO.","Mapea actores.","Formula hipótesis rivales y un árbol.","Prioriza con VERA.","Diseña el plan y revisa evidencia.","Actualiza la hipótesis.","Escribe HIA y DECIR.","Registra riesgos, implementación y revisión."]},
    {title:"Giro de evidencia",callout:{title:"La explicación inicial no basta",text:"Una revisión muestra que la duración influye, pero el abandono se concentra donde no existe tiempo protegido y donde la primera actividad llega tarde. La recomendación debe combinar segmentación, prueba acotada y corrección de medición."}},
    {title:"Respuesta modelo",modelAnswers:[{title:"Una ruta defendible",text:"Definir la decisión como qué combinación de cambios probar primero; validar medición; segmentar por diseño e incentivos; pilotear una primera semana más clara con cuentas comparables; acordar tiempo protegido con clientes; revisar finalización, primera actividad y demanda de soporte antes de ampliar."},{title:"Ruta alternativa",text:"Si el desempeño técnico muestra daño crítico, estabilizar la plataforma puede preceder al piloto pedagógico. La prioridad depende de severidad, evidencia y reversibilidad."}]},
    {title:"Guía de facilitación",bullets:["Entrega las exhibiciones por etapas","Pide opiniones individuales antes del consenso","Solicita evidencia que cambiaría cada hipótesis","Acepta estructuras alternativas conectadas a la decisión","Cierra con registro y fecha de revisión"],links:[{label:"Explorar los doce problemas de práctica",href:"#biblioteca-casos"}]}
  ],relatedResources:["problem-canvas","hypothesis-register","vera","work-plan","decir","decision-log"],relatedTools:["definir-problema","constructor-arbol-problemas","priorizar-analisis","plan-trabajo-problema","constructor-recomendaciones"]},
];

export const problemSolvingLessons = lessons.map((item,index)=>({...item,order:index+1,href:`${base}/${item.slug}`,status:"published",level:index<2?"Introductorio":index===7?"Avanzado":"Intermedio",readingTime:`${9 + index} minutos`,updatedAt,contentType:"lesson"}));
export const problemSolvingPath = { title:"Resolución de problemas",description:"Aprende a definir problemas ambiguos, enfocar el análisis y convertir evidencia en decisiones y acciones concretas.",audience:"Estudiantes, profesionales, líderes, emprendedores y equipos",format:"Ruta práctica",readingTime:"Aproximadamente 100 minutos",level:"Progresivo",updatedAt,status:"published",outcomes:["Definir la decisión real","Estructurar hipótesis y preguntas","Priorizar evidencia y análisis","Sintetizar una recomendación accionable","Colaborar con disenso y revisión"] };
export const getProblemSolvingLesson = (slug)=>problemSolvingLessons.find((item)=>item.slug===slug);
export const getProblemSolvingResource = (id)=>problemSolvingResources.find((item)=>item.id===id);
