import { useEffect, useMemo, useState } from "react";
import { Printer, RotateCcw, Sparkles } from "lucide-react";
import { trackEvent } from "./analytics";
import { buildBiasReview, buildLogicTree, buildProblemDefinition, buildRecommendation, buildWorkPlan, diagnoseProblemType, prioritizeAnalysis } from "./problemSolvingTools";
import { Breadcrumbs, CopyToClipboard, PageShell } from "./LearningComponents";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const levels=["Bajo","Medio","Alto"];
const configs={
  diagnostic:{title:"Diagnóstico de profundidad del problema",description:"Evalúa señales de urgencia, incertidumbre y consecuencia para orientar la profundidad del proceso.",path:"/herramientas/diagnostico-tipo-problema",event:"problem_diagnostic_completed",build:diagnoseProblemType,fields:[["urgency","Urgencia *","select"],["consequence","Consecuencia de error *","select"],["data","Disponibilidad de datos *","select"],["stakeholders","Cantidad de actores *","select"],["reversibility","Reversibilidad *","reversibility"],["uncertainty","Incertidumbre *","select"],["creativity","Necesidad de exploración creativa *","select"],["duration","Duración esperada *","duration"]]},
  definition:{title:"Constructor de definición del problema",description:"Convierte una situación ambigua en una pregunta CLARO y un lienzo revisable.",path:"/herramientas/definir-problema",event:"problem_definition_generated",build:buildProblemDefinition,fields:[["situation","Situación actual *"],["decision","Decisión a tomar *"],["outcome","Resultado deseado *"],["metric","Métrica o señal de éxito"],["horizon","Horizonte temporal *"],["scope","Alcance incluido y excluido"],["constraints","Restricciones"],["stakeholders","Actores relevantes"],["facts","Hechos conocidos"],["unknowns","Incertidumbres clave"]]},
  tree:{title:"Constructor de árbol lógico",description:"Crea ramas y subpreguntas sin depender de arrastrar elementos.",path:"/herramientas/constructor-arbol-problemas",event:"logic_tree_created",build:buildLogicTree,fields:[["question","Pregunta principal *"],["type","Tipo de árbol *","tree"],["branches","Ramas, separadas por punto y coma o línea *"],["hypotheses","Hipótesis o notas"],["evidence","Evidencia necesaria"],["priority","Prioridad cualitativa"]]},
  priority:{title:"Priorizador de análisis",description:"Agrupa una pregunta mediante VERA, esfuerzo, urgencia y dependencias.",path:"/herramientas/priorizar-analisis",event:"analysis_prioritization_completed",build:prioritizeAnalysis,fields:[["question","Pregunta o análisis *"],["value","Valor para la decisión *","select"],["evidence","Evidencia disponible *","select"],["risk","Riesgo de ignorarlo *","select"],["effort","Esfuerzo *","select"],["urgency","Urgencia","select"],["dependency","Dependencia"]]},
  workplan:{title:"Constructor de plan de trabajo",description:"Conecta una pregunta con hipótesis, evidencia, responsable y regla de parada.",path:"/herramientas/plan-trabajo-problema",event:"problem_work_plan_generated",build:buildWorkPlan,fields:[["workstream","Frente de trabajo *"],["question","Pregunta *"],["hypothesis","Hipótesis *"],["analysis","Análisis *"],["data","Datos necesarios"],["source","Fuente"],["owner","Responsable *"],["collaborators","Colaboradores"],["due","Fecha objetivo *"],["dependency","Dependencia"],["output","Resultado esperado"],["review","Punto de revisión"],["stop","Regla de parada"]]},
  recommendation:{title:"Constructor de recomendaciones",description:"Organiza hallazgos con HIA y una recomendación DECIR ejecutable.",path:"/herramientas/constructor-recomendaciones",event:"problem_recommendation_generated",build:buildRecommendation,fields:[["question","Pregunta del problema *"],["decision","Decisión recomendada *"],["findings","Hallazgos principales *"],["evidence","Evidencia de apoyo *"],["conditions","Condiciones"],["impact","Impacto esperado"],["risks","Riesgos y respuesta"],["next","Siguiente paso *"],["owner","Responsable *"],["metric","Métrica y revisión"]]},
  bias:{title:"Revisión de sesgos y decisión",description:"Busca perspectivas y evidencia faltante antes de cerrar una decisión.",path:"/herramientas/revision-sesgos-decision",event:"decision_bias_review_completed",build:buildBiasReview,fields:[["decision","Decisión propuesta *"],["preferred","Explicación preferida *"],["alternatives","Alternativas consideradas *"],["supporting","Evidencia a favor *"],["contradicting","Evidencia en contra *"],["anchor","Primer número o explicación"],["stakeholders","Perspectivas consultadas"],["failure","Escenario de fracaso"],["assumptions","Supuestos *"],["review","Fecha de revisión *"]]},
};

const optionsFor=(type)=>type==="tree"?["Causas","Impulsores","Decisión","Hipótesis","Proceso"]:type==="reversibility"?["Alta","Media","Baja"]:type==="duration"?["Bajo","Medio","Alto"]:levels;

export default function ProblemSolvingToolsPage({kind}) {
  const config=configs[kind]; const initial=useMemo(()=>Object.fromEntries(config.fields.map(([name])=>[name,""])),[kind]); const [values,setValues]=useState(initial); const [result,setResult]=useState({errors:{},output:"",warnings:[]});
  const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Herramientas",href:"/herramientas"},{label:config.title,href:config.path}];
  const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[{"@type":"BreadcrumbList",itemListElement:breadcrumbSchema(breadcrumbs).itemListElement},{"@type":"WebApplication",name:config.title,description:config.description,applicationCategory:"EducationalApplication",operatingSystem:"Web",url:`https://masanes.cl${config.path}`,dateModified:"2026-07-15"}]}),[kind]);
  usePageMetadata({title:config.title,description:config.description,path:config.path,schema}); useEffect(()=>trackEvent("problem_solving_tool_opened",{tool:kind}),[kind]);
  const reset=()=>{setValues(initial);setResult({errors:{},output:"",warnings:[]});}; const submit=(event)=>{event.preventDefault();const next=config.build(values);setResult(next);if(next.output)trackEvent(config.event,{tool:kind});};
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero"><div><p className="eyebrow">Herramienta local</p><h1>{config.title}</h1><p className="page-hero__lead">{config.description}</p><p>Evita información sensible. Tus entradas no se guardan, no se envían y desaparecen al recargar.</p></div></header><section className="generator-layout"><form className="generator-form" noValidate onSubmit={submit}>{config.fields.map(([name,label,type])=><label className="field" key={name} htmlFor={`problem-${kind}-${name}`}><span>{label}</span>{type?<select id={`problem-${kind}-${name}`} value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name]?`problem-error-${kind}-${name}`:undefined} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}><option value="">Selecciona una opción</option>{optionsFor(type).map((option)=><option key={option}>{option}</option>)}</select>:<textarea id={`problem-${kind}-${name}`} rows={name==="branches"?5:3} value={values[name]} aria-invalid={Boolean(result.errors[name])} aria-describedby={result.errors[name]?`problem-error-${kind}-${name}`:undefined} onChange={(event)=>setValues((current)=>({...current,[name]:event.target.value}))}/>} {result.errors[name]&&<small className="field-error" id={`problem-error-${kind}-${name}`}>{result.errors[name]}</small>}</label>)}<div className="form-actions"><button className="button button--primary" type="submit"><Sparkles size={16}/>Generar resultado</button><button className="button button--secondary" type="button" onClick={reset}><RotateCcw size={16}/>Limpiar</button></div></form><aside className="generator-output" aria-live="polite"><h2>Resultado</h2>{result.output?<><pre className="template-preview">{result.output}</pre>{result.warnings?.length>0&&<div className="tool-warnings"><h3>Revisiones sugeridas</h3><ul>{result.warnings.map((warning)=><li key={warning}>{warning}</li>)}</ul></div>}<div className="form-actions"><CopyToClipboard text={result.output} label="Copiar resultado" onCopy={()=>trackEvent("problem_solving_resource_copied",{tool:kind})}/><button className="button button--secondary" type="button" onClick={()=>{trackEvent("problem_solving_resource_printed",{tool:kind});window.print();}}><Printer size={16}/>Imprimir</button></div></>:<p>Completa los campos obligatorios para crear una primera versión revisable.</p>}</aside></section></main></PageShell>;
}
