import { useEffect, useMemo } from "react";
import { ArrowRight, BookOpen, Clock, Gauge, Layers3, Target } from "lucide-react";
import { trackEvent } from "./analytics";
import { practiceProblems, problemSolvingLessons, problemSolvingPath, problemSolvingResources, getProblemSolvingLesson, getProblemSolvingResource } from "./problemSolvingContent";
import { Breadcrumbs, LessonContent, LessonMetadata, LessonNavigation, PageShell, RelatedContent, ResourceCard, StatusBadge } from "./LearningComponents";
import { NotFoundPage } from "./LearningPages";
import { breadcrumbSchema, usePageMetadata } from "./seo";

const base = "/aprende/resolucion-de-problemas";
const graphNode = ({ "@context": _context, ...node }) => node;

const toolLinks = {
  "diagnostico-tipo-problema": { title: "Diagnóstico de profundidad", href: "/herramientas/diagnostico-tipo-problema" },
  "definir-problema": { title: "Constructor de definición", href: "/herramientas/definir-problema" },
  "constructor-arbol-problemas": { title: "Constructor de árbol lógico", href: "/herramientas/constructor-arbol-problemas" },
  "priorizar-analisis": { title: "Priorizador de análisis", href: "/herramientas/priorizar-analisis" },
  "plan-trabajo-problema": { title: "Constructor de plan de trabajo", href: "/herramientas/plan-trabajo-problema" },
  "constructor-recomendaciones": { title: "Constructor de recomendaciones", href: "/herramientas/constructor-recomendaciones" },
  "revision-sesgos-decision": { title: "Revisión de decisión", href: "/herramientas/revision-sesgos-decision" },
};

export function ProblemSolvingHubPage() {
  const breadcrumbs = [{ label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"Resolución de problemas",href:base}];
  const schema = useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:problemSolvingPath.title,description:problemSolvingPath.description,url:`https://masanes.cl${base}`,learningResourceType:"Ruta de aprendizaje",educationalLevel:problemSolvingPath.level,dateModified:problemSolvingPath.updatedAt}]}),[]);
  usePageMetadata({title:"Resolución de problemas: guía práctica",description:problemSolvingPath.description,path:base,schema});
  useEffect(()=>{trackEvent("problem_solving_hub_viewed"); if(window.location.hash) requestAnimationFrame(()=>document.querySelector(window.location.hash)?.scrollIntoView());},[]);
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--networking"><div><p className="eyebrow">Ruta de aprendizaje</p><h1>Resolución de problemas</h1><p className="page-hero__lead">{problemSolvingPath.description}</p><p>Muchas soluciones débiles comienzan con una pregunta mal definida. Estructurar no significa analizarlo todo: significa aclarar la decisión, buscar evidencia suficiente y revisar el rumbo cuando cambian los hechos.</p><div className="hero-actions"><a className="button button--primary" href={problemSolvingLessons[0].href}>Comenzar la ruta <ArrowRight size={17}/></a><a className="button button--secondary" href="/herramientas/definir-problema">Definir un problema</a><a className="button button--secondary" href="/herramientas/diagnostico-tipo-problema">Evaluar mi enfoque</a></div></div><aside className="summary-panel"><StatusBadge status="published"/><dl><div><dt><Target size={18}/>Dirigido a</dt><dd>{problemSolvingPath.audience}</dd></div><div><dt><BookOpen size={18}/>Tipo</dt><dd>{problemSolvingPath.format}</dd></div><div><dt><Clock size={18}/>Tiempo</dt><dd>{problemSolvingPath.readingTime}</dd></div><div><dt><Gauge size={18}/>Nivel</dt><dd>{problemSolvingPath.level}</dd></div><div><dt><Layers3 size={18}/>Módulos</dt><dd>8 módulos</dd></div></dl></aside></header>
  <section className="guide-intro"><div><p className="eyebrow">Idea central</p><h2>Una estructura ligera, proporcional e iterativa</h2><p>La resolución estructurada de problemas aclara una decisión, divide la incertidumbre en preguntas manejables, busca evidencia relevante y convierte hallazgos en una acción razonada. Es una definición práctica, no científica.</p></div><ul>{problemSolvingPath.outcomes.map((item)=><li key={item}>{item}</li>)}</ul></section>
  <section className="content-section content-section--soft" aria-labelledby="problem-lessons"><div className="section-title"><p className="eyebrow">Ocho módulos</p><h2 id="problem-lessons">De la ambigüedad a una decisión revisable</h2></div><div className="case-chapter-grid">{problemSolvingLessons.map((item)=><a className="content-card content-card--link" href={item.href} key={item.slug}><span className="resource-type">Módulo {item.order}</span><h3>{item.title}</h3><p>{item.description}</p><span className="card-link">Abrir módulo <ArrowRight size={16}/></span></a>)}</div></section>
  <section className="content-section" aria-labelledby="problem-tools"><div className="section-title"><p className="eyebrow">Herramientas locales</p><h2 id="problem-tools">Aplica cada paso sin enviar tus datos</h2></div><div className="case-tool-links">{Object.values(toolLinks).map((tool)=><a href={tool.href} key={tool.href}>{tool.title}<ArrowRight size={16}/></a>)}</div></section>
  <section className="content-section content-section--soft" id="biblioteca-casos" aria-labelledby="practice-title"><div className="section-title"><p className="eyebrow">Biblioteca de práctica</p><h2 id="practice-title">Doce problemas ficticios para estructurar</h2><p>Cada ejercicio ofrece una ruta modelo, no una respuesta única.</p></div><div className="scenario-grid">{practiceProblems.map((item)=><article key={item.slug} id={`caso-${item.slug}`}><p className="resource-type">Caso ficticio · {item.difficulty}</p><h3>{item.title}</h3><p>{item.description}</p><p><strong>Decisión:</strong> {item.decision}</p><details><summary>Practicar y ver orientación</summary><p>{item.prompt}</p><p><strong>Contexto:</strong> {item.context.join(" ")}</p><p><strong>Actores:</strong> {item.stakeholders.join("; ")}</p><p><strong>Restricciones:</strong> {item.constraints.join("; ")}</p><p><strong>Hechos disponibles:</strong> {item.knownFacts.join("; ")}</p><p><strong>Incógnitas:</strong> {item.unknowns.join("; ")}</p><p><strong>Hipótesis:</strong> {item.possibleHypotheses.join("; ")}</p><p><strong>Estructura posible:</strong> {item.possibleStructures.join("; ")}</p><p><strong>Evidencia a revisar:</strong> {item.evidence.join("; ")}</p><p><strong>Priorización:</strong> {item.prioritizationExercise}</p><p><strong>Modelo:</strong> {item.modelInsights[0]}</p><p><strong>Síntesis:</strong> {item.synthesisPrompt}</p><p><strong>Recomendación:</strong> {item.recommendationPrompt}</p><p><strong>Habilidades:</strong> {item.skills.join("; ")}</p></details></article>)}</div></section>
  <section className="content-section" id="recursos" aria-labelledby="problem-resources"><div className="section-title"><p className="eyebrow">Recursos</p><h2 id="problem-resources">Plantillas y checklists para el trabajo real</h2><p>Los campos son efímeros. Copia lo que quieras conservar antes de cerrar.</p></div><div className="resource-grid">{problemSolvingResources.map((resource)=><ResourceCard key={resource.id} resource={resource}/>)}</div></section>
  <aside className="contextual-cta"><div><h2>¿Necesitas estructurar una decisión o desafío complejo?</h2><p>Puedo ayudarte a clarificar el problema, ordenar hipótesis y construir un plan de análisis y acción.</p></div><a className="button button--primary" href="/#services" onClick={()=>trackEvent("problem_solving_service_clicked",{destination:"consulting"})}>Conocer los servicios de consultoría</a></aside></main></PageShell>;
}

export function ProblemSolvingLessonPage({slug}) { const item=getProblemSolvingLesson(slug); return item?<ProblemSolvingLessonContent item={item}/>:<NotFoundPage/>; }

function ProblemSolvingLessonContent({item}) {
  const index=problemSolvingLessons.indexOf(item); const resources=item.relatedResources.map(getProblemSolvingResource).filter(Boolean); const tools=item.relatedTools.map((slug)=>toolLinks[slug]).filter(Boolean);
  if(item.slug==="colaboracion-y-sesgos") tools.push(toolLinks["revision-sesgos-decision"]);
  const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"Resolución de problemas",href:base},{label:item.title,href:item.href}];
  const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:item.title,description:item.description,url:`https://masanes.cl${item.href}`,learningResourceType:"Lección",educationalLevel:item.level,dateModified:item.updatedAt,isPartOf:{"@type":"LearningResource",name:problemSolvingPath.title,url:`https://masanes.cl${base}`}}]}),[item.slug]);
  usePageMetadata({title:item.title,description:item.description,path:item.href,schema}); useEffect(()=>trackEvent("problem_solving_lesson_opened",{module:item.slug}),[item.slug]);
  return <PageShell><main id="main-content" className="content-page lesson-page"><Breadcrumbs items={breadcrumbs}/><article><header className="lesson-header"><div><p className="eyebrow">Módulo {item.order} de 8</p><h1>{item.title}</h1><p>{item.description}</p></div><StatusBadge status="published"/></header><LessonMetadata module={item} total={8}/><aside className="lesson-outcomes"><h2>Al terminar podrás</h2><ul>{item.outcomes.map((outcome)=><li key={outcome}>{outcome}</li>)}</ul></aside><LessonContent content={item}/><RelatedContent resources={resources} tools={tools} basePath={base}/><div className="lesson-hub-link"><a className="button button--secondary" href={base}>Volver a Resolución de problemas</a></div><LessonNavigation previous={problemSolvingLessons[index-1]} next={problemSolvingLessons[index+1]}/></article></main></PageShell>;
}
