import { useEffect, useMemo, useState } from "react";
import { ArrowRight, BookOpen, Clock, Gauge, Layers3, Printer, RotateCcw, Sparkles, Target } from "lucide-react";
import { trackEvent } from "./analytics";
import { Breadcrumbs, CopyToClipboard, LessonContent, LessonMetadata, LessonNavigation, PageShell, RelatedContent, ResourceCard, StatusBadge, ToolCard } from "./LearningComponents";
import { NotFoundPage } from "./LearningPages";
import { breadcrumbSchema, usePageMetadata } from "./seo";
import { brandBase, brandCases, brandLastReviewed, brandLessons, brandPath, brandResources, brandToolLinks, getBrandLesson } from "./professionalBrandContent";
import { professionalBrandToolConfigs } from "./professionalBrandTools";

const graphNode = ({ "@context": _, ...node }) => node;
const tools = Object.values(brandToolLinks);
const crumbs = (last, href) => [{ label: "Inicio", href: "/" }, { label: "Aprende", href: "/aprende" }, { label: "Marca profesional", href: brandBase }, ...(last ? [{ label: last, href }] : [])];

function BoundaryNotice() {
  return <aside className="lesson-callout"><h2>Evidencia antes que promoción</h2><p>No inventes logros, cifras, cargos, recomendaciones ni experiencia. No necesitas publicar constantemente, mostrar una fotografía ni divulgar información privada para construir una narrativa profesional útil.</p></aside>;
}

export function ProfessionalBrandHubPage() {
  const breadcrumbs = crumbs();
  const schema = useMemo(() => ({ "@context": "https://schema.org", "@graph": [graphNode(breadcrumbSchema(breadcrumbs)), { "@type": "LearningResource", name: brandPath.title, description: brandPath.description, url: `https://masanes.cl${brandBase}`, learningResourceType: "Ruta de aprendizaje", educationalLevel: "Inicial a aplicado", dateModified: brandLastReviewed, inLanguage: "es" }] }), []);
  usePageMetadata({ title: "Marca profesional: evidencia, narrativa y coherencia", description: brandPath.description, path: brandBase, schema });
  useEffect(() => trackEvent("professional_brand_hub_viewed"), []);
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/>
    <header className="page-hero page-hero--networking"><div><p className="eyebrow">Carrera y habilidades profesionales</p><h1>Marca profesional</h1><p className="page-hero__lead">{brandPath.description}</p><p>Ya produces señales profesionales: en tus decisiones, proyectos, explicaciones, documentos y forma de trabajar. Esta ruta te ayuda a ordenarlas sin fabricar una personalidad comercial.</p><div className="hero-actions"><a className="button button--primary" href={brandLessons[0].href}>Comenzar aquí <ArrowRight size={17}/></a><a className="button button--secondary" href={brandToolLinks.signals.href}>Revisar mis señales</a><a className="button button--secondary" href={`${brandBase}/casos`}>Practicar con casos</a></div></div>
      <aside className="summary-panel"><StatusBadge status="published"/><dl><div><dt><Target size={18}/>Dirigido a</dt><dd>{brandPath.audience}</dd></div><div><dt><BookOpen size={18}/>Formato</dt><dd>{brandPath.format}</dd></div><div><dt><Clock size={18}/>Dedicación orientativa</dt><dd>{brandPath.effort}</dd></div><div><dt><Gauge size={18}/>Nivel</dt><dd>Inicial a aplicado</dd></div><div><dt><Layers3 size={18}/>Contenido</dt><dd>10 módulos · 10 herramientas</dd></div></dl></aside>
    </header><BoundaryNotice/>
    <section className="guide-intro"><div><p className="eyebrow">Definición y límite</p><h2>Expectativas razonables construidas con señales</h2><p><strong>{brandPath.definition}</strong></p><p>Puedes adaptar el énfasis a una audiencia sin cambiar hechos, apropiarte del trabajo colectivo ni exponer información que deba permanecer privada.</p></div><ul>{brandPath.outcomes.map((item)=><li key={item}>{item}</li>)}</ul></section>
    <section className="content-section content-section--soft"><div className="section-title"><p className="eyebrow">Sistema de señales profesionales</p><h2>Cinco decisiones conectadas</h2><p>Dirección, Evidencia, Narrativa, Coherencia y Evolución. Es un modelo práctico creado para esta ruta; no es un estándar, certificación ni garantía.</p></div><div className="skill-framework">{["Dirección", "Evidencia", "Narrativa", "Coherencia", "Evolución"].map((title,index)=><article key={title}><span>{String(index+1).padStart(2,"0")}</span><h3>{title}</h3><p>{["Qué quieres hacer comprensible", "Qué lo respalda", "Cómo lo explicas", "Cómo coincide entre canales", "Cuándo cambia"][index]}</p></article>)}</div></section>
    <section className="content-section"><div className="section-title"><p className="eyebrow">Ruta flexible</p><h2>Diez módulos para ordenar experiencia y mensajes</h2><p>Comienza por la definición si aún piensas en adjetivos. Si ya tienes documentos, ve al módulo de coherencia o a la práctica integrada.</p></div><div className="case-chapter-grid">{brandLessons.map((item)=><a className="content-card content-card--link" href={item.href} key={item.slug}><span className="resource-type">Módulo {item.order}</span><h3>{item.title}</h3><p>{item.description}</p><span className="card-link">Abrir módulo <ArrowRight size={16}/></span></a>)}</div></section>
    <section className="content-section content-section--soft"><div className="section-title"><p className="eyebrow">Práctica y materiales</p><h2>Decisiones con evidencia incompleta</h2><p>Los casos son ficticios y los recursos funcionan en HTML, móvil e impresión.</p></div><div className="card-grid"><a className="content-card content-card--link" href={`${brandBase}/casos`}><h3>26 casos ficticios</h3><p>Practica evidencia, transiciones, privacidad y coherencia.</p><span className="card-link">Abrir casos <ArrowRight size={16}/></span></a><a className="content-card content-card--link" href={`${brandBase}/recursos`}><h3>14 recursos editables</h3><p>Lienzos, fichas, listas y guías para imprimir.</p><span className="card-link">Abrir recursos <ArrowRight size={16}/></span></a><a className="content-card content-card--link" href={`${brandBase}/practica-integrada`}><h3>Proyecto Trama</h3><p>Resuelve un caso completo de transición y coherencia.</p><span className="card-link">Resolver caso <ArrowRight size={16}/></span></a></div></section>
    <section className="content-section"><div className="section-title"><p className="eyebrow">Herramientas locales</p><h2>Diez ayudas sin cuentas, IA externa ni almacenamiento</h2><p>Las entradas permanecen en la sesión y nunca se envían a analítica.</p></div><div className="card-grid">{tools.map((tool)=><ToolCard key={tool.href} tool={{...tool,status:"published"}}/>)}</div></section>
    <section className="content-section content-section--soft"><div className="section-title"><p className="eyebrow">Información temporal</p><h2>Fuentes primarias revisadas</h2><p>Última revisión editorial: 16 de julio de 2026. Las convenciones de CV y las funciones de plataformas dependen del contexto y pueden cambiar.</p></div><div className="lesson-links"><a href="https://www.w3.org/TR/WCAG22/" target="_blank" rel="noreferrer">W3C: WCAG 2.2 <ArrowRight size={16}/></a><a href="https://developers.google.com/search/docs/appearance/structured-data/sd-policies" target="_blank" rel="noreferrer">Google: datos estructurados <ArrowRight size={16}/></a><a href="https://schema.org/LearningResource" target="_blank" rel="noreferrer">Schema.org: LearningResource <ArrowRight size={16}/></a><a href="https://www.linkedin.com/help/linkedin/topic/a149001" target="_blank" rel="noreferrer">LinkedIn: configuración y privacidad <ArrowRight size={16}/></a></div></section>
    <section className="content-section"><div className="section-title"><p className="eyebrow">Rutas relacionadas</p><h2>Continúa según tu objetivo</h2></div><div className="lesson-links"><a href="/aprende/entrevistas-informativas">Entrevistas informativas <ArrowRight size={16}/></a><a href="/aprende/networking">Networking <ArrowRight size={16}/></a><a href="/aprende/comunicacion-profesional">Comunicación profesional <ArrowRight size={16}/></a><a href="/aprende/adaptabilidad-resiliencia">Adaptabilidad y transiciones <ArrowRight size={16}/></a><a href="/aprende/consultoria">Preparación para consultoría <ArrowRight size={16}/></a></div></section>
    <aside className="contextual-cta"><div><h2>¿Tu experiencia es sólida, pero cuesta explicarla?</h2><p>Un proceso de coaching puede ayudarte a ordenar evidencia, dirección y mensajes para una transición profesional concreta.</p></div><a className="button button--primary" href="/#services" onClick={()=>trackEvent("professional_brand_coaching_clicked",{destination:"services"})}>Conocer Coaching Profesional</a></aside>
  </main></PageShell>;
}

export function ProfessionalBrandLessonPage({ slug }) {
  const item=getBrandLesson(slug); if(!item) return <NotFoundPage/>;
  const breadcrumbs=crumbs(item.title,item.href); const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:item.title,description:item.description,url:`https://masanes.cl${item.href}`,learningResourceType:"Lección",educationalLevel:item.level,dateModified:item.lastReviewed,inLanguage:"es",isPartOf:{"@type":"LearningResource",name:brandPath.title,url:`https://masanes.cl${brandBase}`}}]}),[item.slug]);
  usePageMetadata({title:item.title,description:item.description,path:item.href,schema}); useEffect(()=>trackEvent("professional_brand_lesson_opened",{module:item.slug}),[item.slug]);
  const resources=brandResources.slice((item.order-1)%10,((item.order-1)%10)+2).map((resource)=>({...resource,href:`${brandBase}/recursos#resource-${resource.id}`})); const relatedTools=item.relatedTools.map((key)=>brandToolLinks[key]).filter(Boolean);
  return <PageShell><main id="main-content" className="content-page lesson-page"><Breadcrumbs items={breadcrumbs}/><article><header className="lesson-header"><div><p className="eyebrow">Módulo {item.order} de 10</p><h1>{item.title}</h1><p>{item.description}</p></div><StatusBadge status="published"/></header><LessonMetadata module={item} total={10}/><BoundaryNotice/><aside className="lesson-outcomes"><h2>Al terminar podrás</h2><ul>{item.outcomes.map((x)=><li key={x}>{x}</li>)}</ul></aside><LessonContent content={item}/><RelatedContent resources={resources} tools={relatedTools} basePath={brandBase}/><LessonNavigation lessons={brandLessons} currentSlug={slug}/></article></main></PageShell>;
}

export function ProfessionalBrandCasesPage(){
  const path=`${brandBase}/casos`; const breadcrumbs=crumbs("Casos",path); const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:"Casos de marca profesional",description:"Casos ficticios para practicar evidencia, narrativa y coherencia.",url:`https://masanes.cl${path}`,learningResourceType:"Biblioteca de práctica",dateModified:brandLastReviewed,inLanguage:"es"}]}),[]);
  usePageMetadata({title:"Casos para practicar marca profesional",description:"Veintiséis casos ficticios sobre evidencia, narrativa, privacidad y coherencia.",path,schema});
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--compact"><p className="eyebrow">Biblioteca de práctica</p><h1>Casos de marca profesional</h1><p className="page-hero__lead">Situaciones originales con información incompleta y más de una decisión defendible.</p></header><section className="content-section"><div className="scenario-grid">{brandCases.map((item)=><article key={item.id}><p className="resource-type">{item.label} · {item.difficulty}</p><h2>{item.title}</h2><p>{item.context}</p><details onToggle={(e)=>e.currentTarget.open&&trackEvent("professional_brand_case_opened",{category:item.difficulty})}><summary>Analizar el caso</summary><p><strong>Objetivo:</strong> {item.learningObjective}</p><p><strong>Evidencia:</strong> {item.evidence.join("; ")}.</p><p><strong>Ambigüedad:</strong> {item.ambiguity}</p><p><strong>Decisión:</strong> {item.decisionPoint}</p><ul>{item.actions.map((x)=><li key={x}>{x}</li>)}</ul><p><strong>Riesgos:</strong> {item.risks.join(", ")}.</p><p><strong>Retroalimentación:</strong> {item.feedback}</p><a href={`${brandBase}/${item.relatedLesson}`}>Abrir lección relacionada <ArrowRight size={15}/></a></details></article>)}</div></section></main></PageShell>;
}

export function ProfessionalBrandResourcesPage(){
  const path=`${brandBase}/recursos`; const breadcrumbs=crumbs("Recursos",path); const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:"Recursos de marca profesional",description:"Lienzos y guías editables para trabajar evidencia y coherencia.",url:`https://masanes.cl${path}`,learningResourceType:"Biblioteca de recursos",dateModified:brandLastReviewed,inLanguage:"es"}]}),[]);
  usePageMetadata({title:"Recursos para construir una marca profesional",description:"Catorce recursos editables e imprimibles para dirección, evidencia, narrativa y privacidad.",path,schema});
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--compact"><p className="eyebrow">Biblioteca editable</p><h1>Recursos para ordenar tus señales</h1><p className="page-hero__lead">Trabaja con descripciones anónimas. Nada se guarda ni se envía.</p></header><section className="content-section"><div className="resource-grid">{brandResources.map((resource)=><ResourceCard key={resource.id} resource={resource}/>)}</div></section></main></PageShell>;
}

export function ProfessionalBrandToolsPage({kind}){
  const config=professionalBrandToolConfigs[kind]||professionalBrandToolConfigs.signals; const initial=useMemo(()=>Object.fromEntries(config.fields.map(([name])=>[name,""])),[kind]);
  const [values,setValues]=useState(initial); const [generated,setGenerated]=useState({errors:{},output:"",warnings:[]}); const [resetStatus,setResetStatus]=useState("");
  const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Herramientas",href:"/herramientas"},{label:config.title,href:config.path}]; const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"WebApplication",name:config.title,description:`Herramienta local para ${config.title.toLowerCase()}.`,applicationCategory:"EducationalApplication",operatingSystem:"Web",url:`https://masanes.cl${config.path}`,dateModified:brandLastReviewed,inLanguage:"es"}]}),[kind]);
  usePageMetadata({title:config.title,description:`Herramienta local y privada para ${config.title.toLowerCase()}.`,path:config.path,schema}); useEffect(()=>trackEvent("professional_brand_tool_opened",{tool:kind}),[kind]);
  const submit=(event)=>{event.preventDefault();const next=config.build(values);setGenerated(next);setResetStatus("");if(!Object.keys(next.errors||{}).length)trackEvent(config.event,{tool:kind});};
  const reset=()=>{setValues(initial);setGenerated({errors:{},output:"",warnings:[]});setResetStatus("Formulario y resultado reiniciados");};
  return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--compact"><p className="eyebrow">Herramienta local y determinista</p><h1>{config.title}</h1><p className="page-hero__lead">Organiza evidencia y mensajes sin cuentas, almacenamiento ni servicios externos.</p><p>No pegues CV completos ni ingreses nombres, empleadores, contactos, clientes, datos sensibles o información confidencial. Las entradas permanecen en esta sesión.</p></header><section className="generator-layout"><form className="generator-form" onSubmit={submit} noValidate>{config.fields.map(([name,label,type="textarea",options])=><label className="field" htmlFor={`brand-${kind}-${name}`} key={name}><span>{label}</span>{type==="select"?<select id={`brand-${kind}-${name}`} value={values[name]} aria-invalid={Boolean(generated.errors?.[name])} aria-describedby={generated.errors?.[name]?`brand-error-${kind}-${name}`:undefined} onChange={(e)=>setValues((v)=>({...v,[name]:e.target.value}))}><option value="">Selecciona una opción</option>{options.map((x)=><option key={x}>{x}</option>)}</select>:<textarea id={`brand-${kind}-${name}`} rows="3" maxLength="2000" value={values[name]} aria-invalid={Boolean(generated.errors?.[name])} aria-describedby={generated.errors?.[name]?`brand-error-${kind}-${name}`:undefined} onChange={(e)=>setValues((v)=>({...v,[name]:e.target.value}))}/>} {generated.errors?.[name]&&<small className="field-error" id={`brand-error-${kind}-${name}`}>{generated.errors[name]}</small>}</label>)}<div className="form-actions"><button className="button button--primary" type="submit"><Sparkles size={16}/>Crear ayuda</button><button className="button button--secondary" type="button" onClick={reset}><RotateCcw size={16}/>Limpiar</button><span className="sr-only" role="status" aria-live="polite">{resetStatus}</span></div></form><aside className="generator-output" aria-live="polite"><h2>Resultado</h2>{Object.keys(generated.errors||{}).length>0&&<div role="alert"><p>Revisa los campos señalados.</p></div>}{generated.output?<><pre className="template-preview">{generated.output}</pre>{generated.warnings?.length>0&&<div className="tool-warnings"><h3>Límites</h3><ul>{generated.warnings.map((x)=><li key={x}>{x}</li>)}</ul></div>}<div className="form-actions"><CopyToClipboard text={generated.output} label="Copiar resultado" onCopy={()=>trackEvent("professional_brand_resource_copied",{tool:kind})}/><button className="button button--secondary" type="button" onClick={()=>{trackEvent("professional_brand_resource_printed",{tool:kind});window.print();}}><Printer size={16}/>Imprimir</button></div></>:<p>Completa los campos obligatorios. La salida organiza información declarada; no evalúa reputación, empleabilidad ni rendimiento en plataformas.</p>}</aside></section></main></PageShell>;
}
