export const brandBase = "/aprende/marca-profesional";
export const brandLastReviewed = "2026-07-16";

const framework = (...items) => items.map(([title, text]) => ({ title, text }));
const exercise = (title, prompt, help) => ({ title, prompt, help });
const lesson = (order, slug, title, description, outcomes, sections, relatedTools = []) => ({
  order, slug, title, description, outcomes, sections, relatedTools,
  href: `${brandBase}/${slug}`,
  level: order < 4 ? "Inicial" : order < 9 ? "Intermedio" : "Aplicado",
  readingTime: `${11 + (order % 4)}–${17 + (order % 4)} minutos`,
  updatedAt: brandLastReviewed, lastReviewed: brandLastReviewed, status: "published",
});

export const brandToolLinks = {
  signals: { title: "Diagnóstico de señales profesionales", href: "/herramientas/diagnostico-senales-profesionales", description: "Ordena dirección, evidencia, narrativa, coherencia y evolución." },
  evidence: { title: "Inventario de evidencia", href: "/herramientas/inventario-evidencia-profesional", description: "Convierte experiencias anónimas en fichas verificables." },
  contribution: { title: "Constructor de contribuciones", href: "/herramientas/constructor-contribuciones-profesionales", description: "Distingue responsabilidad, aporte, contexto y efecto." },
  narrative: { title: "Constructor de narrativa profesional", href: "/herramientas/constructor-narrativa-marca-profesional", description: "Prepara versiones breve, media y extendida sin inventar contenido." },
  language: { title: "Revisor de lenguaje genérico", href: "/herramientas/revisor-lenguaje-profesional", description: "Señala adjetivos, jerga y afirmaciones que necesitan pruebas." },
  coherence: { title: "Mapa de coherencia", href: "/herramientas/mapa-coherencia-profesional", description: "Compara afirmaciones, fechas y evidencia entre canales." },
  profile: { title: "Revisor de perfil público", href: "/herramientas/revisor-perfil-profesional", description: "Revisa propósito, claridad, evidencia y privacidad sin puntuación algorítmica." },
  peers: { title: "Preparador de revisión por pares", href: "/herramientas/preparar-revision-marca-profesional", description: "Crea un encargo de revisión centrado en comprensión y evidencia." },
  update: { title: "Plan de actualización", href: "/herramientas/plan-actualizacion-marca-profesional", description: "Organiza mantenimiento a partir de cambios reales." },
  compare: { title: "Comparador CV–perfil–presentación", href: "/herramientas/comparar-canales-profesionales", description: "Detecta coincidencias, diferencias y contradicciones justificables." },
};

export const brandPath = {
  title: "Marca profesional",
  description: "Convierte tu experiencia, criterio y forma de trabajar en una narrativa clara, creíble y coherente.",
  definition: "Tu marca profesional es el patrón de expectativas razonables que otras personas forman a partir de señales repetidas: trabajo realizado, decisiones, evidencia, explicaciones y conducta. No es un logotipo, una personalidad fabricada ni una promesa de empleabilidad.",
  audience: "Estudiantes, profesionales, personas en transición, perfiles híbridos e independientes",
  format: "Ruta práctica con casos, recursos y herramientas locales",
  effort: "Entre 3 y 5 horas de lectura y práctica, según la profundidad elegida",
  outcomes: ["Distinguir identidad, reputación y posicionamiento", "Sustentar afirmaciones con evidencia", "Adaptar una narrativa sin contradecir hechos", "Mantener coherencia y privacidad entre canales"],
};

const signalsSystem = framework(
  ["Dirección", "Trabajo, contribución o transición que necesitas hacer comprensible."],
  ["Evidencia", "Proyectos, decisiones, resultados y conductas que respaldan esa dirección."],
  ["Narrativa", "Selección honesta de señales explicada con claridad y contexto."],
  ["Coherencia", "Correspondencia razonable entre CV, perfil, conversación y pruebas."],
  ["Evolución", "Revisión cuando cambian experiencia, objetivos, contexto o privacidad."],
);
const claimChain = framework(
  ["Afirmación", "Qué dices que puedes aportar, expresado de manera concreta."],
  ["Prueba", "Qué experiencia observable y verificable respalda la afirmación."],
  ["Contexto", "En qué condiciones, alcance y límites ocurrió esa contribución."],
);

const signalScenarios = ["Foto cuidada sin evidencia", "Proyecto con decisión documentada", "Adjetivo sin ejemplo", "Recomendación específica", "Publicación frecuente irrelevante", "Cambio de rol verificable", "Presentación coherente con el CV", "Aspiración declarada como dominio", "Aprendizaje de un error", "Título inflado", "Límite de confidencialidad", "Actualización tras una transición"].map((title, index) => ({
  id: `senal-${index + 1}`, title, situation: `Se observa la señal ficticia: “${title}”.`, question: "¿Es identidad, evidencia, narrativa, reputación, visibilidad o ruido?", action: "Clasifica y explica qué puede inferirse razonablemente.", constraint: "No confundas exposición con credibilidad ni aspiración con experiencia.",
}));

export const brandLessons = [
  lesson(1, "entender-marca-profesional", "Entender qué es una marca profesional", "Sustituye la promoción vaga por una lectura de señales, evidencia y expectativas.", ["Distinguir conceptos cercanos", "Reconocer señales observables", "Evitar una identidad fabricada"], [
    { title: "Identidad, reputación y posicionamiento", paragraphs: ["La identidad incluye cómo te entiendes; la reputación reúne expectativas que otras personas forman; el posicionamiento selecciona qué contribución quieres hacer comprensible para un contexto. La narrativa organiza esa selección, la evidencia la sustenta y la visibilidad solo determina dónde puede encontrarse.", "Autenticidad no significa divulgar toda tu vida. Puedes comunicar hechos verdaderos y relevantes conservando límites personales."] },
    { title: "Sistema de señales profesionales", framework: signalsSystem, callout: { title: "Modelo práctico", text: "Este es un modelo práctico creado para organizar esta ruta. No es un estándar, una certificación ni una garantía de resultados." } },
    { title: "Lo que una marca profesional no es", bullets: ["Un logo o una paleta de colores", "Una fotografía perfecta", "Una personalidad fija", "Publicar constantemente", "Adjetivos sin pruebas", "Valores separados de la conducta", "Un sustituto de competencia", "Una garantía de empleo"], comparison: { leftTitle: "Visibilidad sin fundamento", leftItems: ["Frecuencia", "Apariencia", "Frases memorables"], rightTitle: "Credibilidad contextual", rightItems: ["Evidencia", "Límites", "Coherencia entre señales"] } },
    { title: "Taller de doce señales", scenarios: signalScenarios, exercise: exercise("Clasificar sin puntuar", "Clasifica las señales y escribe qué información adicional necesitarías.", "Puede haber más de una interpretación; justifica el límite."), links: [{ label: "Explorar comunicación profesional", href: "/aprende/comunicacion-profesional" }] },
  ], ["signals"]),

  lesson(2, "definir-direccion-audiencias", "Definir dirección y audiencias", "Aclara qué necesitas hacer comprensible y para qué interlocutores resulta relevante.", ["Definir una dirección provisional", "Diferenciar audiencias de estereotipos", "Comunicar exploración con honestidad"], [
    { title: "Dirección no equivale a cargo", paragraphs: ["Una dirección combina problemas, contribuciones y movimiento deseado. Un título laboral puede orientar una búsqueda, pero no explica qué sabes resolver ni qué evidencia llevas contigo.", "Explorar es legítimo: expresa qué estás contrastando sin presentar interés inicial como experiencia consolidada."] },
    { title: "Lienzo de dirección", questionGroups: [{ title: "Movimiento", items: ["Situación actual", "Movimiento deseado", "Problemas que puedes ayudar a resolver", "Evidencia disponible y faltante"] }, { title: "Audiencias y límites", items: ["Interlocutores relevantes", "Interpretaciones que quieres evitar", "Información que no divulgarás", "Incertidumbre que declararás"] }] },
    { title: "Una experiencia, tres lecturas", example: { title: "Caso ficticio", text: "Nadia combina docencia, análisis y coordinación comunitaria. Para un equipo de investigación enfatiza método; para operaciones, coordinación; para una organización educativa, traducción entre evidencia y práctica. Los hechos no cambian." }, exercise: exercise("Adaptar sin fingir", "Crea tres interpretaciones para Nadia conservando las mismas pruebas.", "Cambia énfasis y vocabulario, no el nivel de experiencia.") },
    { title: "Riesgos de orientación", bullets: ["Intentar agradar a todos", "Usar un cargo como dirección completa", "Copiar requisitos sin evidencia", "Ocultar toda ambigüedad", "Confundir audiencia con una caricatura demográfica"], links: [{ label: "Preparar una transición", href: "/aprende/adaptabilidad-resiliencia" }] },
  ], ["signals"]),

  lesson(3, "reunir-evidencia", "Reunir evidencia de contribución", "Convierte tareas dispersas en pruebas honestas de decisiones, aportes y efectos.", ["Separar responsabilidad y contribución", "Usar evidencia cualitativa o cuantitativa", "Proteger información confidencial"], [
    { title: "De actividad a contribución", comparison: { leftTitle: "Responsabilidad", leftItems: ["Coordinaba reuniones", "Preparaba reportes", "Atendía clientes"], rightTitle: "Contribución", rightItems: ["Qué problema abordó", "Qué decisión o acción realizó", "Qué efecto pudo observarse"] }, paragraphs: ["El esfuerzo importa, pero no equivale automáticamente a impacto. Tampoco corresponde adjudicarse el resultado completo de un equipo."] },
    { title: "Cadena afirmación–prueba–contexto", framework: claimChain, callout: { title: "Evidencia sin falsa precisión", text: "La evidencia puede ser cualitativa: una decisión documentada, un riesgo prevenido, una mejora observable o una retroalimentación específica. No inventes cifras para parecer convincente." } },
    { title: "Inventario de evidencia", questionGroups: [{ title: "Hecho profesional", items: ["Situación", "Problema", "Contribución", "Resultado observable", "Personas involucradas"] }, { title: "Credibilidad", items: ["Restricciones", "Capacidades demostradas", "Prueba disponible", "Límite de confidencialidad", "Relevancia futura"] }], exercise: exercise("Reescribir quince tareas", "Convierte responsabilidades ficticias en contribuciones con alcance claro.", "Si falta evidencia, escribe la pregunta pendiente en vez de rellenarla.") },
    { title: "Ejemplo con límites", example: { title: "Caso ficticio", text: "Damián no puede revelar datos de clientes. Describe el tipo de decisión, su contribución y el cambio de proceso, pero omite nombres, montos y detalles que permitirían identificar el proyecto." }, bullets: ["No atribuyas al individuo todo el trabajo colectivo", "No uses superlativos sin comparación válida", "No listes herramientas sin explicar su uso", "No publiques evidencia que no estás autorizado a compartir"] },
  ], ["evidence", "contribution"]),

  lesson(4, "construir-narrativa", "Construir una narrativa profesional", "Conecta experiencia pasada, contribución actual y dirección futura sin convertirla en ficción.", ["Encontrar patrones legítimos", "Explicar transiciones no lineales", "Crear versiones para distintos contextos"], [
    { title: "Narrar es seleccionar, no inventar", paragraphs: ["Una narrativa profesional no cuenta toda la cronología: elige hechos pertinentes, muestra un patrón y reconoce discontinuidades. Una pausa, un cambio de sector o un proyecto fallido no necesitan transformarse en una historia heroica."] },
    { title: "Origen, patrón, aporte y dirección", framework: framework(["Origen", "Contexto inicial relevante para la conversación."], ["Patrón", "Problemas, decisiones o intereses que reaparecen."], ["Aporte", "Contribución actual respaldada por evidencia."], ["Dirección", "Lo que quieres explorar, profundizar o aportar después."]), callout: { title: "Guía opcional", text: "Esta estructura ayuda a seleccionar información; no es un guion obligatorio ni una fórmula de éxito." } },
    { title: "Variantes útiles", bullets: ["Resumen de CV", "Perfil público", "Presentación en entrevista", "Conversación informativa", "Presentación en evento", "Biografía independiente", "Promoción interna", "Transición profesional"], exercise: exercise("Tres versiones, mismos hechos", "Escribe una versión breve, media y extendida de un caso ficticio.", "Cada versión debe conservar afirmación, prueba y contexto.") },
    { title: "Ejemplo no lineal", example: { title: "Caso ficticio", text: "Sol trabajó en producción cultural, compras y coordinación. Su patrón no es la industria: es organizar recursos bajo restricciones y traducir necesidades entre equipos. Declara que está explorando operaciones, no que ya domina todas sus funciones." }, bullets: ["Evita recitar la vida completa", "No escribas solo aspiraciones", "No fabriques una transformación dramática", "No ocultes evidencia que contradice el mensaje"] },
  ], ["narrative", "language"]),

  lesson(5, "narrativa-en-cv", "Traducir la narrativa al CV", "Trata el CV como un documento selectivo de evidencia, no como una biografía exhaustiva.", ["Priorizar relevancia y legibilidad", "Revisar afirmaciones y fechas", "Adaptar convenciones al contexto"], [
    { title: "Propósito antes que plantilla", paragraphs: ["La extensión, el orden y las secciones útiles dependen del país, sector, experiencia y proceso. No existe una regla universal de una página. Investiga las convenciones del contexto antes de enviar."] },
    { title: "Revisión en seis lentes", framework: framework(["Relevancia", "¿Ayuda a comprender la dirección actual?"], ["Evidencia", "¿Las afirmaciones tienen hechos que las sostienen?"], ["Claridad", "¿Se entiende alcance y contribución?"], ["Consistencia", "¿Fechas, cargos y nombres coinciden?"], ["Verificabilidad", "¿Podrías explicar el dato con honestidad?"], ["Accesibilidad", "¿El documento conserva lectura, contraste y orden?"]), callout: { title: "Convenciones variables", text: "Los sistemas y prácticas de selección cambian. Evita mitos sobre filtros automáticos y verifica requisitos concretos del proceso." } },
    { title: "Qué puede incluirse", bullets: ["Experiencia", "Educación", "Capacidades demostradas", "Proyectos", "Publicaciones", "Idiomas", "Voluntariado", "Portafolio"], exercise: exercise("Auditar fragmentos", "Detecta afirmaciones sin prueba, redundancia, contexto faltante, fechas inconsistentes y riesgos de privacidad.", "No añadas una sección solo porque otra persona la usa.") },
    { title: "Caso de resultado cualitativo", example: { title: "Caso ficticio", text: "Ariel facilitó la adopción de un procedimiento, pero no dispone de una métrica fiable. Describe el problema, el material creado, las áreas participantes y la decisión habilitada, sin inventar un porcentaje." }, links: [{ label: "Ver preparación para consultoría", href: "/aprende/consultoria" }] },
  ], ["contribution", "coherence"]),

  lesson(6, "narrativa-en-perfil-publico", "Traducir la narrativa al perfil público", "Decide qué mostrar, cómo hacerlo comprensible y qué mantener fuera de internet.", ["Priorizar conceptos neutrales de plataforma", "Revisar descriptor, resumen y experiencia", "Tomar decisiones conscientes de privacidad"], [
    { title: "Un perfil es un canal, no tu identidad completa", bullets: ["Descubribilidad", "Contexto profesional", "Descriptor", "Resumen", "Experiencia y proyectos", "Capacidades", "Pruebas destacadas", "Límites de contacto", "Visibilidad y mantenimiento"], paragraphs: ["No necesitas publicar contenido, mostrar una fotografía ni completar todos los campos para construir una narrativa creíble. Cada elección depende del objetivo, exposición y riesgo."] },
    { title: "Descriptor y resumen", comparison: { leftTitle: "Lenguaje débil", leftItems: ["Superlativos vacíos", "Lista de palabras clave", "Aspiración como experiencia", "Propósito impreciso"], rightTitle: "Lenguaje verificable", rightItems: ["Contribución actual", "Problema relevante", "Patrón con evidencia", "Dirección y límites"] } },
    { title: "Nota actual sobre LinkedIn", paragraphs: ["Última revisión editorial: 16 de julio de 2026. LinkedIn mantiene controles para editar la visibilidad del perfil público y las secciones elegibles para mostrarse fuera de la sesión. También permite gestionar una URL pública personalizada, sujeta a disponibilidad. Revisa la ayuda oficial antes de cambiar información sensible.", "Esta ruta no afirma que completar campos, publicar o repetir palabras clave mejore el alcance de un algoritmo."], links: [{ label: "Ayuda oficial sobre configuración y privacidad", href: "https://www.linkedin.com/help/linkedin/topic/a149001" }] },
    { title: "Diagnóstico de coherencia", example: { title: "Caso ficticio", text: "El descriptor de Paula promete liderazgo estratégico; el resumen habla de exploración y la experiencia solo enumera soporte administrativo. Paula conserva la aspiración como dirección futura y vuelve a describir sus contribuciones demostradas." }, exercise: exercise("Revisar un perfil ficticio", "Identifica contradicciones entre descriptor, resumen, experiencia y capacidades.", "Incluye una decisión sobre qué no publicar.") },
  ], ["profile", "language"]),

  lesson(7, "coherencia-entre-canales", "Crear coherencia entre canales", "Mantén hechos compatibles mientras adaptas extensión, tono y énfasis a cada situación.", ["Separar núcleo y adaptación", "Detectar contradicciones", "Gestionar versiones y traducciones"], [
    { title: "Coherencia no significa copiar", paragraphs: ["El CV necesita síntesis; una entrevista permite razonamiento; un portafolio muestra pruebas. La redacción puede cambiar siempre que fechas, cargos, alcance y nivel de dominio no se contradigan."] },
    { title: "Mapa de coherencia", questionGroups: [{ title: "Núcleo", items: ["Afirmación central", "Evidencia", "Fechas y cargos", "Límite de divulgación"] }, { title: "Expresiones", items: ["CV", "Perfil público", "Presentación oral", "Portafolio", "Riesgo y actualización"] }], callout: { title: "Modelo práctico", text: "El mapa facilita una comparación; no puntúa autenticidad, reputación ni empleabilidad y no exige texto idéntico." } },
    { title: "Cinco canales ficticios", example: { title: "Caso ficticio", text: "El CV de Mei dice analista, su perfil dice líder de datos y su presentación dice consultora. Al revisar alcance descubre que lideró un proyecto, no un equipo permanente. Ajusta el perfil y explica la responsabilidad temporal." }, exercise: exercise("Encontrar contradicciones", "Compara cinco expresiones ficticias y separa adaptación válida de contradicción factual.", "Revisa también versiones bilingües y fechas.") },
    { title: "Errores de versión", bullets: ["Copiar el mismo párrafo en todos los canales", "Usar fechas diferentes", "Inflar seniority en un solo canal", "Dejar visible una dirección antigua", "Traducir cargos como si fueran equivalentes exactos"], links: [{ label: "Mejorar mensajes profesionales", href: "/aprende/comunicacion-profesional" }] },
  ], ["coherence", "compare"]),

  lesson(8, "revision-por-pares", "Revisar con otras personas", "Solicita retroalimentación sobre comprensión y evidencia sin convertirla en votación de popularidad.", ["Elegir revisores pertinentes", "Separar observación y recomendación", "Resolver comentarios incompatibles"], [
    { title: "Una pregunta específica produce mejor revisión", paragraphs: ["“¿Te gusta?” mezcla preferencia y claridad. Pide que la persona describa qué entiende que haces, qué evidencia notó, qué resulta ambiguo y dónde percibe una contradicción."] },
    { title: "Proceso de lectura independiente", ordered: ["La persona revisora lee sin explicación previa.", "Escribe qué cree que haces.", "Identifica la evidencia que observó.", "Marca ambigüedad y contradicción.", "Separa observación de consejo.", "Tú comparas interpretación e intención.", "Decides qué cambios se justifican."] },
    { title: "Tres miradas distintas", example: { title: "Caso ficticio", text: "Una colega entiende que Bruno investiga, un cliente que facilita y una persona de selección que coordina. Bruno no promedia opiniones: identifica qué señales produjeron cada lectura y decide cuál corresponde a su dirección." }, exercise: exercise("Simular revisión", "Compara comentarios de tres revisores ficticios con sesgos y contextos diferentes.", "Conserva tu juicio y registra qué evidencia resolvería la diferencia.") },
    { title: "Privacidad y sesgos", bullets: ["No compartas documentos privados sin permiso", "No elijas solo amistades cercanas", "No trates una opinión de selección como universal", "No copies el estilo de quien revisa", "Considera sesgos culturales y sectoriales"], links: [{ label: "Practicar escucha y retroalimentación", href: "/aprende/comunicacion-profesional" }] },
  ], ["peers"]),

  lesson(9, "mantener-corregir", "Mantener y corregir la marca profesional", "Actualiza señales cuando cambian hechos, dirección, contexto o límites de privacidad.", ["Usar desencadenantes reales", "Retirar afirmaciones desactualizadas", "Corregir incoherencias con transparencia"], [
    { title: "Mantener no significa publicar constantemente", paragraphs: ["Actualiza cuando existe una razón: nuevo rol o proyecto, cambio de dirección, aprendizaje relevante, publicación, pausa, modificación de privacidad o señal que dejó de ser cierta. Si nada cambió, una revisión puede concluir sin editar."] },
    { title: "Ciclo de mantenimiento", framework: framework(["Capturar", "Registrar evidencia y cambios sin publicarlos todavía."], ["Verificar", "Confirmar hechos, autoría, permisos y vigencia."], ["Seleccionar", "Elegir qué sirve a la dirección actual."], ["Actualizar", "Modificar los canales pertinentes."], ["Comparar", "Revisar coherencia factual y contextual."], ["Retirar", "Eliminar afirmaciones, pruebas o accesos que ya no corresponden."]), callout: { title: "Modelo práctico", text: "El ciclo se activa por cambios relevantes; no impone frecuencia ni garantiza reputación." } },
    { title: "Corregir sin dramatizar", example: { title: "Caso ficticio", text: "Irene descubre que un perfil antiguo exagera su dominio de una tecnología. Corrige el nivel, conserva un proyecto verificable y prepara una explicación breve si alguien pregunta; no intenta ocultar la fecha del cambio." }, exercise: exercise("Plan anual por eventos", "Define desencadenantes, canales afectados, evidencia necesaria y elementos que retirarías.", "No programes cambios mensuales si no hay hechos nuevos.") },
    { title: "Situaciones que requieren cautela", bullets: ["Cambio reputacional", "Proyecto confidencial", "Pausa profesional", "Nueva jurisdicción", "Perfil bilingüe", "Información personal más expuesta", "Cambio de plataforma"], links: [{ label: "Gestionar cambios profesionales", href: "/aprende/adaptabilidad-resiliencia" }] },
  ], ["update"]),

  lesson(10, "practica-integrada", "Práctica integrada y herramientas", "Integra dirección, evidencia, narrativa, canales, revisión y mantenimiento en un caso con decisiones abiertas.", ["Resolver un caso completo", "Justificar decisiones de divulgación", "Elegir herramientas según el bloqueo"], [
    { title: "Caso ficticio creado con fines educativos", caseStudy: { title: "Proyecto Trama: de operaciones a transformación", paragraphs: ["Camila combina operaciones, gestión de clientes y análisis. Quiere explorar transformación estratégica, pero su CV enumera tareas, su perfil habla de liderazgo sin pruebas y su presentación se aferra a un cargo anterior.", "Parte de la evidencia pertenece a un proyecto confidencial, algunas métricas describen al equipo completo y tres revisores interpretan su trayectoria de manera distinta. El objetivo no es producir una versión perfecta, sino decidir qué puede afirmar, demostrar, adaptar y reservar."] } },
    { title: "Quince decisiones del caso", ordered: ["Aclara el objetivo profesional provisional.", "Compara las tres descripciones incompatibles.", "Construye un inventario de evidencia.", "Marca afirmaciones sin respaldo.", "Define límites de confidencialidad.", "Elige audiencias primarias y secundarias.", "Redacta dos narrativas plausibles.", "Revisa contribuciones y fechas del CV.", "Adapta el perfil público sin inflar liderazgo.", "Prepara una presentación oral breve.", "Recibe observaciones de tres revisores.", "Separa comentarios incompatibles y sesgos.", "Completa un mapa de coherencia.", "Define desencadenantes de mantenimiento.", "Decide qué evidencia no se publicará."] },
    { title: "Alternativas razonadas", modelAnswers: [{ title: "Dirección", text: "Puede enfatizar coordinación de transformación o análisis para decisiones. Elegirá según evidencia disponible y tipo de rol, sin declararse experta en ambas." }, { title: "Métrica", text: "Usará solo la parte verificable y atribuible; si el efecto fue colectivo, nombrará al equipo y su contribución específica." }, { title: "Privacidad", text: "Describirá el tipo de problema y decisión, pero omitirá cliente, montos, datos y detalles que permitan reconstruir el proyecto." }, { title: "Revisión", text: "No aceptará por mayoría. Rastreará cada interpretación hasta la señal que la produjo." }] },
    { title: "Rúbrica y facilitación", rubric: ["Dirección comprensible", "Afirmaciones con prueba y contexto", "Crédito colectivo correcto", "Narrativa honesta", "Coherencia factual", "Adaptación contextual", "Privacidad", "Plan de evolución"], callout: { title: "Para facilitar", text: "Pide dos soluciones defendibles, la evidencia que falta y qué cambio de contexto alteraría la decisión. No existe una narrativa única correcta." }, exercise: exercise("Resolver Proyecto Trama", "Entrega narrativa breve, contribución revisada, mapa de coherencia y decisión de privacidad.", "Explica también qué no puedes concluir con la información disponible.") },
  ], ["signals", "evidence", "coherence", "compare"]),
];

const caseSeeds = [
  ["Primera experiencia", "Estudiante con proyectos académicos y voluntariado"], ["Giro de sector", "Profesional que traslada capacidades a una industria nueva"], ["Perfil ejecutivo antiguo", "Directiva con diez años de información sin revisar"], ["Consultoría independiente", "Persona con varios clientes y límites de confidencialidad"], ["De técnica a gestión", "Especialista que coordinó proyectos sin dirigir personas"], ["Regreso al trabajo técnico", "Gerente que busca volver a contribuir como especialista"], ["Pausa profesional", "Persona que retorna después de cuidar a un familiar"], ["Nuevo mercado", "Profesional migrante que traduce títulos y contexto"], ["Proyecto reservado", "Trabajo valioso que no puede mostrarse"], ["De investigación a industria", "Investigadora que necesita traducir método en contribución"], ["Servicio público", "Profesional con resultados colectivos y restricciones"], ["Portafolio creativo", "Diseñadora con piezas atractivas pero poco contexto"], ["Operaciones sin métricas", "Coordinador con mejoras cualitativas"], ["Identidad múltiple", "Persona con empleo, docencia y práctica independiente"], ["Proyecto fallido", "Equipo que aprendió de una implementación detenida"], ["Fechas incompatibles", "CV y perfil muestran periodos diferentes"], ["Dominio exagerado", "Perfil declara experiencia que apenas comienza"], ["Aporte oculto", "CV enumera tareas y omite decisiones"], ["Jerga acumulada", "Resumen lleno de expresiones genéricas"], ["Dos idiomas", "Versiones que atribuyen seniority diferente"], ["Dirección sin evidencia", "Rol deseado todavía no respaldado"], ["Después del giro", "La audiencia sigue asociando a la persona con su carrera anterior"], ["Sin fotografía", "Profesional que decide no mostrar su imagen"], ["Sin publicaciones", "Especialista que no desea crear contenido"], ["Consejos incompatibles", "Tres revisores proponen direcciones distintas"], ["Exposición excesiva", "Perfil revela clientes y detalles sensibles"],
];

export const brandCases = caseSeeds.map(([title, context], index) => ({
  id: `marca-caso-${String(index + 1).padStart(2, "0")}`, title, label: "Caso ficticio creado con fines educativos.",
  difficulty: index < 9 ? "inicial" : index < 18 ? "intermedia" : "avanzada",
  learningObjective: `Practicar una decisión de evidencia y coherencia en “${title}”.`, context,
  evidence: ["Existe al menos una experiencia verificable", "La atribución y el contexto aún necesitan aclaración"],
  ambiguity: "La misma señal puede interpretarse de modo distinto según audiencia y contexto.",
  decisionPoint: "¿Qué conviene afirmar, adaptar, verificar o mantener privado?",
  actions: ["Pedir evidencia adicional", "Reescribir con alcance y contexto", "Retirar o reservar la señal"],
  risks: ["Sobreafirmar", "Contradecir otro canal", "Exponer información innecesaria"],
  feedback: "Compara dirección, prueba, contexto, audiencia y privacidad. Más visibilidad no siempre es la mejor decisión.",
  relatedLesson: brandLessons[index % brandLessons.length].slug,
  relatedTool: Object.keys(brandToolLinks)[index % 10], fictional: true,
}));

const resourceSeeds = [
  ["lienzo-direccion", "Lienzo de dirección profesional", "Define situación, movimiento, problemas, evidencia y límites."], ["mapa-audiencias-marca", "Mapa de audiencias", "Compara qué necesita comprender cada interlocutor."], ["inventario-evidencia", "Inventario de evidencia", "Registra situación, contribución, efecto, prueba y confidencialidad."], ["ficha-contribucion", "Ficha de contribución", "Transforma una responsabilidad en una afirmación contextual."], ["constructor-narrativa", "Constructor de narrativa", "Ordena origen, patrón, aporte y dirección."], ["revision-cv", "Lista de revisión de CV", "Revisa relevancia, evidencia, claridad, consistencia y accesibilidad."], ["revision-perfil", "Lista de revisión de perfil público", "Evalúa propósito, secciones, coherencia y privacidad."], ["mapa-coherencia", "Mapa de coherencia entre canales", "Compara afirmaciones, fechas, cargos y pruebas."], ["guia-feedback", "Guía de retroalimentación", "Separa comprensión, observación, ambigüedad y recomendación."], ["privacidad-divulgacion", "Lista de privacidad y divulgación", "Decide qué publicar, limitar, anonimizar o excluir."], ["disparadores-actualizacion", "Plan de desencadenantes", "Activa revisiones cuando cambian hechos o dirección."], ["rubrica-marca", "Rúbrica de autoevaluación", "Revisa dirección, evidencia, narrativa, coherencia y evolución."], ["guia-facilitacion-marca", "Guía para facilitar prácticas", "Incluye preguntas, alternativas y límites éticos."], ["coherencia-bilingue", "Ficha de coherencia bilingüe", "Compara significado, cargos, fechas y nivel de dominio entre idiomas."],
];

export const brandResources = resourceSeeds.map(([id, title, description], index) => ({
  id, title, description, contentType: "worksheet", format: "HTML · editable · imprimible", status: "published",
  reminder: "Trabaja con descripciones anónimas. No incluyas nombres, contactos, clientes ni información confidencial.",
  fields: ["Propósito", "Hechos observables", "Evidencia y contexto", "Dudas o contradicciones", "Límite de privacidad", "Próxima decisión"],
}));

export const getBrandLesson = (slug) => brandLessons.find((item) => item.slug === slug);
