export const prospectingBase = "/aprende/prospeccion-b2b";
export const prospectingLastReviewed = "2026-07-16";

const framework = (...items) => items.map(([title, text]) => ({ title, text }));
const exercise = (title, prompt, help) => ({ title, prompt, help });
const lesson = (order, slug, title, description, outcomes, sections, relatedTools = []) => ({
  order, slug, title, description, outcomes, sections, relatedTools,
  href: `${prospectingBase}/${slug}`, level: order < 5 ? "Introductorio" : "Intermedio",
  readingTime: `${11 + (order % 5)} minutos`, updatedAt: prospectingLastReviewed,
  lastReviewed: prospectingLastReviewed, timeSensitive: [6, 7, 8, 13].includes(order), status: "published",
});

export const prospectingToolLinks = {
  diagnostic: { title: "Diagnóstico de prospección B2B", href: "/herramientas/diagnostico-prospeccion-b2b", description: "Detecta fundamentos ausentes y decide por dónde comenzar." },
  icp: { title: "Constructor de cliente ideal B2B", href: "/herramientas/definir-cliente-ideal-b2b", description: "Define encaje, exclusiones, roles y vacíos de evidencia." },
  value: { title: "Constructor de propuesta de valor B2B", href: "/herramientas/crear-propuesta-valor-b2b", description: "Convierte capacidades en una hipótesis de cambio verificable." },
  message: { title: "Constructor de mensaje de prospección", href: "/herramientas/crear-mensaje-prospeccion-b2b", description: "Prepara un primer contacto breve, relevante y respetuoso." },
  sequence: { title: "Constructor de secuencia de prospección", href: "/herramientas/crear-secuencia-prospeccion", description: "Asigna una función a cada contacto y una regla de salida." },
  objection: { title: "Preparador de respuestas a objeciones", href: "/herramientas/preparar-respuestas-objeciones", description: "Decide si aclarar, aportar, pausar, derivar o cerrar." },
  calculator: { title: "Calculadora de prospección B2B", href: "/herramientas/calculadora-prospeccion-b2b", description: "Estima actividad con supuestos y rangos de sensibilidad." },
  dashboard: { title: "Tablero de prospección B2B", href: "/herramientas/tablero-prospeccion-b2b", description: "Interpreta un embudo con denominadores explícitos." },
};

export const prospectingPath = {
  title: "Prospección B2B",
  description: "Aprende a identificar prospectos relevantes, comunicar valor y convertir contactos iniciales en conversaciones comerciales útiles.",
  definition: "La prospección B2B es el proceso sistemático de identificar organizaciones relevantes, formular una hipótesis de valor y abrir conversaciones comerciales mediante contactos oportunos, claros y respetuosos.",
  audience: "Consultores, fundadores, profesionales independientes y equipos comerciales B2B",
  format: "Ruta práctica con casos, recursos y herramientas",
  readingTime: "14 módulos · avance flexible",
  level: "Introductorio a intermedio",
  outcomes: ["Elegir cuentas y roles con evidencia", "Diseñar contactos y secuencias respetuosas", "Medir conversaciones y oportunidades con denominadores claros", "Construir un plan comercial que incluya pausas y cierres"],
};

const reunion = framework(
  ["Relevancia", "Razón verificable por la que la organización pertenece al mercado objetivo."],
  ["Evidencia", "Hechos observables que sostienen la hipótesis sin convertirla en certeza."],
  ["Usuario y roles", "Personas que viven el problema, influyen, evalúan y responden por el resultado."],
  ["Necesidad", "Problema, prioridad, riesgo u oportunidad que conviene validar."],
  ["Impacto", "Cambio significativo al que la oferta podría contribuir."],
  ["Oportunidad de conversación", "Siguiente paso pequeño y razonable que se propone."],
  ["Navegación", "Canales, tiempos, seguimiento y reglas de parada."],
);

const readinessScenarios = [
  ["Oferta todavía inestable", "Una firma pequeña aún cambia su servicio cada semana y no puede explicar el resultado.", "¿Contactar, preparar o descartar?", "Preparar primero una oferta comprensible y una capacidad real de entrega."],
  ["Lista de origen dudoso", "Un proveedor ofrece miles de correos sin explicar su procedencia.", "¿Puede usarse para comenzar?", "No comprar ni usar; revisar obtención legítima y criterios de relevancia."],
  ["Cliente anterior con exclusión", "Una persona pidió expresamente no recibir nuevos mensajes comerciales.", "¿Una nueva oferta justifica escribir?", "No contactar y conservar la preferencia en el registro apropiado."],
  ["Señal pública parcial", "Una organización anunció una expansión, pero no existe evidencia de un problema concreto.", "¿La señal basta para afirmar necesidad?", "Solo permite una hipótesis cauta; investigar un rol y una pregunta pertinente."],
  ["Evidencia confidencial", "El único caso comparable contiene cifras que el cliente no autorizó a divulgar.", "¿Cómo demostrar credibilidad?", "Usar método o evidencia autorizada; no revelar las cifras."],
  ["Encaje fuerte y paso pequeño", "Una cuenta coincide con el ICP, existe una prioridad pública y un contacto profesional legítimo.", "¿Qué resultado inicial conviene buscar?", "Validar relevancia o identificar al rol apropiado antes de presentar toda la solución."],
].map(([title, situation, question, action], index) => ({ id: `preparacion-${index + 1}`, title, situation, question, action, constraint: "Caso ficticio; no añadir datos personales ni asumir una necesidad." }));

const messageRevisionScenarios = [
  ["Presentación demasiado larga", "El borrador dedica tres párrafos a la historia del proveedor.", "Reduce el texto a contexto, hipótesis y paso pequeño."],
  ["Asunto con falsa respuesta", "El asunto comienza con Re: aunque nunca hubo intercambio.", "Escribe un asunto exacto y breve."],
  ["Halago automático", "La apertura elogia una publicación que no fue leída.", "Sustituye el halago por una razón verificable."],
  ["Necesidad presentada como hecho", "El mensaje afirma que la planta tiene retrasos sin evidencia.", "Convierte la afirmación en una pregunta cauta."],
  ["Resultado garantizado", "La propuesta promete eliminar todos los errores.", "Expresa contribución, condición e incertidumbre."],
  ["Credenciales sin relación", "El correo enumera premios que no respaldan el problema tratado.", "Conserva solo evidencia pertinente."],
  ["CTA desproporcionado", "El primer contacto pide una demostración de una hora con todo el comité.", "Propón una confirmación o conversación acotada."],
  ["Sin opción de salida", "La secuencia asume que el silencio permite continuar.", "Añade un cierre respetuoso y una regla de parada."],
  ["Referencia exagerada", "El texto dice que una colega recomienda el servicio cuando solo autorizó compartir un nombre.", "Describe exactamente el alcance de la presentación."],
  ["Detalle personal innecesario", "El mensaje usa información familiar tomada de una red social.", "Elimina el dato y vuelve al contexto profesional."],
  ["Apertura de evento", "Ambas personas asistieron a un encuentro, pero no conversaron.", "Usa el evento sin fingir una relación previa."],
  ["Derivación", "El contacto no dirige el proceso, pero podría orientar.", "Pide una indicación fácil de rechazar sin presionar."],
].map(([title, situation, question], index) => ({ id: `mensaje-${index + 1}`, title, situation, question, action: "Aplicar CLAVE, conservar solo hechos verificables y ofrecer una elección sencilla.", constraint: "Caso ficticio. No inventar familiaridad, urgencia, evidencia ni permiso." }));

const objectionScenarios = ["No es prioridad este trimestre", "Ya existe un proveedor", "Lo resolvemos internamente", "No tenemos presupuesto", "Escríbeme el próximo año", "Envíame información", "No soy la persona adecuada", "No conozco tu trabajo", "No veo relación con nuestro negocio", "No quiero recibir más mensajes", "Estamos en proceso de compra", "La iniciativa quedó suspendida", "Comunícate con compras", "Solo revisamos proveedores inscritos", "No puedo hablar ahora", "La evidencia no es comparable"].map((title, index) => ({
  id: `objecion-${index + 1}`, title,
  situation: `Un rol de una organización ficticia responde: “${title}”.`,
  question: "¿Conviene aclarar, aportar, derivar, pausar o cerrar?",
  action: index === 9 ? "Aceptar el rechazo, registrar la preferencia y terminar." : index % 4 === 0 ? "Reconocer, preguntar solo si aporta y ofrecer una pausa definida." : "Aplicar ESCUCHA y elegir la salida menos invasiva coherente con la señal.",
  constraint: "No discutir, manipular ni convertir cada objeción en algo que deba superarse.",
}));

export const prospectingLessons = [
  lesson(1, "fundamentos", "Qué es la prospección y qué resultado debe producir", "Separa la apertura de una conversación de la venta y define cuándo no corresponde contactar.", ["Distinguir prospección, venta y oportunidad", "Definir una primera conversación útil", "Aplicar REUNIÓN y decidir no contactar"], [
    { title: "Prospectar no es cerrar", paragraphs: ["Prospectar crea condiciones para una conversación futura. Vender, presentar, negociar y cerrar ocurren después y requieren información que el primer contacto todavía no tiene.", "Un prospecto es una organización con encaje posible; un contacto es una persona alcanzable; una conversación valida relevancia; una reunión permite explorar; una oportunidad calificada tiene problema, actores y siguiente decisión; una propuesta formaliza una alternativa; un cliente ha acordado comprar."], comparison: { leftTitle: "Primer contacto", leftItems: ["Pedir permiso", "Validar una hipótesis", "Encontrar a la persona adecuada", "Acordar un paso pequeño"], rightTitle: "Proceso de venta", rightItems: ["Diagnosticar con profundidad", "Construir una solución", "Evaluar condiciones", "Decidir y formalizar"] } },
    { title: "REUNIÓN: siete decisiones antes de insistir", framework: reunion, callout: { title: "Modelo práctico de esta ruta", text: "REUNIÓN organiza preguntas; no es un estándar comercial ni garantiza obtener reuniones. Tampoco exige incluir sus siete partes en cada mensaje." } },
    { title: "Una primera conversación útil", bullets: ["Tiene una razón comprensible para ambas partes.", "Permite confirmar o descartar relevancia.", "Aclara quién vive o dirige el problema.", "Termina con un siguiente paso, una derivación, una pausa o un cierre explícito.", "No presupone una reunión de duración fija."], exercise: exercise("Definir el resultado mínimo", "Escribe qué necesitas aprender y qué paso sería proporcionado para el contacto.", "Una respuesta negativa o una derivación también puede evitar trabajo improductivo.") },
    { title: "Cuándo no prospectar", bullets: ["No existe una razón creíble para el contacto.", "Los datos se obtuvieron de forma inapropiada.", "La persona rechazó nuevos contactos o sus preferencias los impiden.", "La oferta no está lista o no puede explicarse.", "La evidencia exigiría exagerar o revelar información confidencial.", "Una restricción de compra, proveedor o canal debe respetarse."], callout: { title: "No contactar también es una decisión comercial", text: "La relevancia importa más que el volumen. Una salida responsable puede recomendar no contactar, pausar o cerrar." } },
    { title: "Seis decisiones de preparación", paragraphs: ["Revisa los casos y decide si corresponde contactar, preparar mejor, investigar, pausar o descartar."], scenarios: readinessScenarios },
  ], ["diagnostic"]),

  lesson(2, "cliente-ideal", "Cómo definir a quién vale la pena contactar", "Construye un perfil de organización, criterios de exclusión y un mapa de roles de compra.", ["Separar ICP y persona", "Aplicar FOCO sin falsa precisión", "Mapear roles de compra"], [
    { title: "El cliente ideal describe organizaciones", paragraphs: ["Un perfil de cliente ideal, o ICP, combina rasgos organizacionales y evidencia de encaje. No es un personaje inventado ni una lista de deseos.", "Revisa industria, modelo, tamaño, geografía, etapa, complejidad, proceso afectado, entorno tecnológico, intensidad del problema, señales, capacidad de compra y exclusiones."], exercise: exercise("Escribir una exclusión útil", "Define una condición que indique falta de encaje aunque la organización pueda pagar.", "Una exclusión protege tiempo, reputación y capacidad de entrega.") },
    { title: "FOCO para priorizar sin puntajes mágicos", framework: framework(["Fit", "Encaje con el perfil y sus exclusiones."], ["Oportunidad", "Problema, señal o prioridad observable en este momento."], ["Contactabilidad", "Posibilidad de llegar respetuosamente a un rol apropiado."], ["Oferta creíble", "Evidencia pertinente para este contexto."]), callout: { title: "Etiquetas cualitativas", text: "Usa fuerte, parcial, débil o desconocido. Lo desconocido pide investigación; no debe transformarse en un número preciso." } },
    { title: "El grupo de compra", bullets: ["Comprador económico: responde por la inversión.", "Responsable del problema: debe producir el resultado.", "Usuario: vive el proceso cotidiano.", "Evaluador técnico: revisa viabilidad e integración.", "Compras: coordina condiciones y proveedores.", "Riesgo o legal: evalúa consecuencias y obligaciones.", "Influyente: aporta criterio sin decidir por sí solo.", "Promotor interno: moviliza el proceso desde dentro.", "Bloqueador: puede detener o rediseñar la decisión."], paragraphs: ["Una persona puede ocupar varios roles. La autoridad jerárquica más alta no siempre es el mejor inicio: conviene buscar a quien comprende el problema y puede orientar el siguiente paso."] },
    { title: "Hipótesis, no etiqueta", paragraphs: ["El rol se infiere de responsabilidades observables y debe confirmarse. Evita suponer intereses por edad, género, origen u otros atributos personales."], links: [{ label: "Relacionar roles con networking", href: "/aprende/networking" }] },
  ], ["icp"]),

  lesson(3, "investigacion", "Cómo investigar antes de contactar sin convertirlo en una tarea infinita", "Reúne evidencia pública suficiente para una hipótesis y detente cuando ya permite decidir.", ["Responder por qué esta cuenta, ahora y persona", "Distinguir señal de necesidad", "Aplicar PISTA"], [
    { title: "Investigar para reducir incertidumbre", paragraphs: ["La investigación debe mejorar una decisión: contactar, investigar una pieza más, buscar otro rol o descartar. No busca simular cercanía.", "Responde por qué esta cuenta, por qué ahora, por qué esta persona, qué podría importar, qué evidencia existe y qué no se puede afirmar."], callout: { title: "Regla de parada", text: "Detén la búsqueda cuando puedas formular una hipótesis cauta y un siguiente paso, o cuando la evidencia indique que no corresponde contactar." } },
    { title: "Fuentes y límites", bullets: ["Sitio y anuncios oficiales de la organización.", "Informes públicos, presentaciones y entrevistas autorizadas.", "Vacantes, eventos, productos y prioridades públicas.", "Perfiles profesionales y relación previa legítima.", "Información sectorial y cambios regulatorios públicos."], paragraphs: ["No extraigas perfiles de forma automatizada ni uses datos sensibles. Registra fuente, fecha, hecho e incertidumbre para no confundir inferencia con evidencia."] },
    { title: "PISTA: convertir una señal en pregunta", framework: framework(["Prioridad observable", "Hecho público que podría importar."], ["Impacto posible", "Efecto empresarial que merece validación."], ["Stakeholder", "Rol que podría vivir o dirigir el asunto."], ["Tesis", "Hipótesis expresada con cautela."], ["Acción", "Pregunta o paso que permite aprender."]) },
    { title: "Los detonantes no prueban una necesidad", bullets: ["Expansión o nuevo mercado", "Cambio de liderazgo", "Lanzamiento o contratación", "Fusión o adquisición", "Cambio regulatorio", "Migración tecnológica", "Interrupción operativa pública"], exercise: exercise("Auditar una señal", "Separa el hecho publicado, tu interpretación y la pregunta que la validaría.", "Una vacante o anuncio puede tener muchas explicaciones.") },
  ], ["diagnostic"]),

  lesson(4, "propuesta-de-valor", "Cómo explicar valor sin enumerar servicios", "Formula un cambio significativo, muestra su base de credibilidad y conserva la incertidumbre.", ["Distinguir atributo, beneficio, resultado y prueba", "Aplicar CAMBIO", "Reducir el riesgo de afirmaciones"], [
    { title: "De la capacidad al resultado", bullets: ["Característica: componente de la oferta.", "Capacidad: trabajo que permite realizar.", "Beneficio funcional: mejora inmediata para quien la usa.", "Resultado de negocio: cambio medible en una operación.", "Impacto estratégico: consecuencia más amplia y dependiente del contexto.", "Prueba: evidencia que respalda una afirmación.", "Afirmación: declaración que aún debe sostenerse.", "Garantía: compromiso de resultado que rara vez corresponde en prospección."], callout: { title: "No saltes de atributo a impacto", text: "Una capacidad puede contribuir a un resultado, pero no demuestra por sí sola causalidad ni garantiza el efecto." } },
    { title: "CAMBIO para formular valor", framework: framework(["Contexto del cliente", "Situación que puede reconocerse sin inventar."], ["Afectación", "Costo, riesgo, fricción u oportunidad."], ["Mejora esperada", "Resultado que podría avanzar."], ["Base de credibilidad", "Evidencia pertinente y autorizada."], ["Incertidumbre", "Dependencias y preguntas abiertas."], ["Gancho de conversación", "Pregunta que permite validar."]), callout: { title: "Alcance del modelo", text: "CAMBIO es el marco práctico de valor de esta ruta. No sustituye diagnóstico, prueba ni revisión de afirmaciones." } },
    { title: "Construir evidencia sin inventar precisión", bullets: ["Resultado medido y contexto de medición.", "Comparación antes/después con cautelas.", "Caso autorizado y comparable.", "Piloto o demostración de capacidad.", "Testimonio con permiso.", "Método, experiencia de dominio o validación externa."], paragraphs: ["Si faltan cifras, entrevista clientes, revisa entregables y describe efectos operativos verificables. Nunca publiques nombres, resultados o citas sin permiso."] },
    { title: "Prueba de afirmaciones", exercise: exercise("Marcar nivel de evidencia", "Para cada frase comercial, anota hecho, inferencia, condición y pregunta pendiente.", "Reemplaza certeza por una hipótesis cuando la evidencia no alcance."), links: [{ label: "Profundizar en problemas e hipótesis", href: "/aprende/resolucion-de-problemas" }] },
  ], ["value"]),

  lesson(5, "mensajes", "Cómo diseñar un primer contacto claro y relevante", "Crea mensajes que ganen un siguiente paso razonable sin explicar toda la oferta.", ["Aplicar CLAVE", "Elegir un nivel legítimo de personalización", "Revisar relevancia, evidencia y CTA"], [
    { title: "Un mensaje abre; no resuelve", paragraphs: ["Un primer contacto necesita una razón creíble, una prioridad posible, un resultado conciso, evidencia cuando aporta y una elección sencilla. No existe una cantidad universal de palabras.", "La situación de la otra parte merece más espacio que las credenciales del remitente. La personalización sirve para aumentar relevancia, no para aparentar una relación inexistente."] },
    { title: "CLAVE: un marco distinto para esta ruta", framework: framework(["Contexto legítimo", "Hecho o relación que justifica contactar."], ["Lectura cauta", "Problema o prioridad expresado como hipótesis."], ["Aporte posible", "Cambio que valdría la pena explorar."], ["Verificación", "Evidencia breve o pregunta para comprobar."], ["Elección sencilla", "Paso proporcionado, incluida la opción de no continuar."]), callout: { title: "No es una plantilla rígida", text: "CLAVE organiza la revisión del mensaje. El orden y la presencia de cada elemento dependen del canal y del contexto." } },
    { title: "Cuatro niveles de personalización", bullets: ["Básica: sector, rol o proceso.", "De cuenta: iniciativa o contexto público de la organización.", "De persona: responsabilidad o contribución profesional pública.", "De relación: contacto compartido, evento o conversación real."], callout: { title: "Evita familiaridad artificial", text: "No uses halagos automáticos, detalles personales excesivos ni afirmes haber revisado algo que no revisaste." } },
    { title: "Revisión de mensajes", exercise: exercise("Reescribir con CLAVE", "Reduce una presentación extensa a razón, hipótesis, aporte y paso pequeño. Escribe una alternativa que solo pida confirmar relevancia.", "Comprueba exactitud, claridad, credibilidad, respeto y riesgo de exageración."), links: [{ label: "Practicar claridad en comunicación profesional", href: "/aprende/comunicacion-profesional" }] },
    { title: "Doce ejercicios de revisión", paragraphs: ["Cada borrador admite más de una redacción válida; el objetivo es corregir el riesgo sin perder claridad."], scenarios: messageRevisionScenarios },
  ], ["message"]),

  lesson(6, "email", "Cómo escribir correos de prospección que merezcan una respuesta", "Planifica asuntos precisos, un cuerpo legible y una salida respetuosa según la norma aplicable.", ["Construir un correo breve y exacto", "Evaluar ética y riesgo", "Adaptar consentimiento y salida a la jurisdicción"], [
    { title: "Anatomía de un correo responsable", ordered: ["Asunto fiel al contenido.", "Apertura con razón legítima.", "Hipótesis de problema o prioridad.", "Resultado que podría explorarse.", "Evidencia pertinente y autorizada.", "Siguiente paso pequeño.", "Firma e identificación claras.", "Vía de cierre o exclusión cuando corresponda."], paragraphs: ["Usa párrafos cortos y continuidad de hilo para facilitar la lectura móvil. No escondas la naturaleza comercial ni uses asuntos engañosos como “Re:” o “Fwd:” cuando no existe conversación previa."] },
    { title: "El CTA puede pedir menos que una reunión", bullets: ["Confirmar si el tema es relevante.", "Identificar a la persona adecuada.", "Responder una pregunta acotada.", "Revisar un recurso breve.", "Considerar una llamada corta.", "Elegir una ventana posible.", "Solicitar que no haya más contacto."], callout: { title: "La regla depende del lugar y destinatario", text: "Las obligaciones sobre identificación, consentimiento, base de tratamiento y exclusión varían. Revisa la autoridad y la legislación aplicables; esta guía no es asesoría legal." } },
    { title: "Rúbrica antes de enviar", rubric: ["Relevancia", "Claridad", "Credibilidad", "Brevedad", "Evidencia", "Respeto", "Siguiente paso", "Riesgo de exageración"] },
    { title: "Ética del correo", bullets: ["No compres listas no verificadas ni ocultes identidad.", "No uses información obtenida de manera impropia.", "Respeta rechazo, exclusión y preferencias registradas.", "No trates una dirección pública como permiso universal.", "Revisa la normativa de cada jurisdicción y tipo de destinatario."], paragraphs: ["Última revisión editorial: 16 de julio de 2026."] },
  ], ["message"]),

  lesson(7, "telefono", "Cómo abrir una conversación comercial por teléfono", "Prepara una llamada breve que identifica al remitente, pide espacio y acepta el cierre.", ["Preparar una apertura conversacional", "Tratar asistentes con respeto", "Definir cierre y registro"], [
    { title: "Secuencia conversacional", ordered: ["Identifícate con claridad.", "Confirma si la persona puede hablar brevemente.", "Explica una razón pertinente para llamar.", "Presenta la hipótesis de problema o resultado.", "Haz una pregunta útil.", "Acuerda el paso, la derivación o el cierre.", "Termina con respeto."], callout: { title: "No es un libreto para forzar", text: "La persona puede no tener tiempo, no ser la indicada o no querer continuar. Una negativa clara termina el contacto." } },
    { title: "Preparación mínima", bullets: ["Contexto de la cuenta y fuente.", "Rol probable y lo que falta confirmar.", "Una hipótesis de apertura.", "Una pregunta principal.", "Evidencia disponible.", "Paso deseado y alternativa.", "Notas sin datos innecesarios."], exercise: exercise("Ensayar sin grabar", "Lee la apertura, elimina jerga y prepara una respuesta de cierre.", "No necesitas grabar la voz; practica por escrito o con otra persona.") },
    { title: "Asistentes, central y buzón", paragraphs: ["Trata a asistentes y recepcionistas como participantes informados, no como obstáculos. Explica el motivo y pide orientación sin fingir una relación previa.", "Un mensaje de voz identifica quién llama, por qué podría ser relevante, cómo responder y no crea urgencia falsa."] },
    { title: "Privacidad y reglas telefónicas", paragraphs: ["Registros de no llamar, horarios, identificación y grabación dependen de la jurisdicción. Consulta a la autoridad competente antes de operar y documenta las preferencias expresadas."], bullets: ["No grabes sin revisar requisitos y obtener autorizaciones aplicables.", "No vuelvas a llamar después de un rechazo claro.", "No uses números privados sin una razón legítima."], callout: { title: "Revisión temporal", text: "Última revisión editorial: 16 de julio de 2026. Esta lección no constituye asesoría legal." } },
  ], ["diagnostic"]),

  lesson(8, "linkedin", "Cómo utilizar LinkedIn para investigar, aportar valor y abrir conversaciones", "Usa la red profesional para credibilidad, aprendizaje y relaciones, sin extracción ni automatización masiva.", ["Usar LinkedIn más allá de mensajes", "Mejorar perfil y contenido", "Evitar spam y automatización no autorizada"], [
    { title: "Nueve funciones posibles", bullets: ["Credibilidad profesional", "Investigación pública", "Observación de cuentas", "Activación de red", "Distribución de contenido", "Conversación", "Mantenimiento de relaciones", "Seguimiento de eventos", "Aprendizaje comercial"], paragraphs: ["LinkedIn no es solo una bandeja de mensajes. Un perfil útil explica a quién ayudas, qué problemas comprendes, qué resultados apoyas, qué evidencia tienes y cómo contactarte sin convertirse en una página agresiva."] },
    { title: "Contenido que aporta contexto", bullets: ["Explicar un problema o método.", "Interpretar una tendencia con fuente.", "Presentar evidencia con límites.", "Compartir aprendizaje profesional.", "Comentar material ajeno con atribución y aporte original.", "Plantear una pregunta útil."], paragraphs: ["Antes del contacto puedes seguir organizaciones, observar prioridades públicas y comentar con sustancia. Evita rituales de interacción artificial."] },
    { title: "Conversaciones distintas", bullets: ["Invitación de conexión", "Conversación tras conectar", "Mensaje directo", "Referencia", "Seguimiento de interacción pública", "Seguimiento de evento"], callout: { title: "Política actual de la plataforma", text: "LinkedIn prohíbe software no autorizado que extraiga datos o automatice actividad, y sus políticas rechazan mensajes no dirigidos, irrelevantes o repetitivos. Revisa siempre las condiciones vigentes." } },
    { title: "Límites operativos", bullets: ["No automatices invitaciones o mensajes masivos.", "No extraigas perfiles ni compres datos extraídos.", "No inventes afinidad a partir de una publicación.", "No publiques información de clientes sin permiso.", "Respeta identidad, relevancia y preferencias."], paragraphs: ["Última revisión editorial: 16 de julio de 2026."], links: [{ label: "Aprender estrategia de contenido y canales", href: "/aprende/marketing-digital" }] },
  ], ["sequence"]),

  lesson(9, "secuencias", "Cómo diseñar una secuencia multicanal coherente", "Coordina funciones, canales y tiempos sin adoptar un número universal de contactos.", ["Aplicar RITMO", "Asignar función a cada canal", "Definir regla de salida"], [
    { title: "Una secuencia es una hipótesis", paragraphs: ["Define objetivo, segmento, señal, canales, función de cada mensaje, intervalo, aporte nuevo, tratamiento de respuesta, responsable y medición. Su longitud depende del contexto, la relación, el canal y el riesgo reputacional.", "No existe un número universal de contactos ni una cadencia que sirva para todos los mercados."] },
    { title: "RITMO", framework: framework(["Razón", "Motivo por el que el contacto es pertinente."], ["Interacción", "Trabajo distinto que realiza cada paso."], ["Tiempo", "Espacio apropiado según contexto y disponibilidad."], ["Medio", "Canal adecuado para el contenido."], ["Opción de salida", "Condición para pausar o terminar."]), callout: { title: "Modelo de planificación", text: "RITMO fue creado para esta ruta. No prescribe frecuencia ni garantiza respuesta." } },
    { title: "Los canales cumplen trabajos diferentes", bullets: ["Correo: relevancia estructurada.", "Teléfono: aclaración rápida y humana.", "LinkedIn: contexto, credibilidad y relación.", "Referencia: transferencia limitada de confianza.", "Contenido: educación y evidencia.", "Evento: contexto compartido."], exercise: exercise("Diseñar tres pasos", "Asigna a cada contacto una información nueva y una condición de salida.", "Si el segundo paso solo repite el primero, rediseña su función.") },
    { title: "Secuencias según situación", bullets: ["Introducción cálida", "Cuenta objetivo nombrada", "Seguimiento de evento", "Señal entrante", "Referencia", "Relación inactiva", "Dueño de pequeña empresa", "Grupo de compra empresarial"], paragraphs: ["Una secuencia puede terminar antes de lo previsto por respuesta, falta de encaje, preferencia o pérdida de relevancia."] },
  ], ["sequence"]),

  lesson(10, "seguimiento", "Cómo hacer seguimiento sin repetir ni presionar", "Añade contexto o utilidad, interpreta señales distintas y sabe cuándo detenerte.", ["Añadir valor en cada contacto", "Distinguir silencio, demora y rechazo", "Definir pausa y reactivación"], [
    { title: "Cada seguimiento necesita un trabajo", bullets: ["Aclarar una idea relevante.", "Hacer una pregunta útil.", "Aportar evidencia nueva.", "Compartir un caso breve autorizado.", "Ofrecer un recurso pertinente.", "Incorporar una señal reciente.", "Sugerir otro rol.", "Reducir el siguiente paso.", "Cerrar respetuosamente."], paragraphs: ["Repetir la misma solicitud con palabras distintas no añade valor."] },
    { title: "Señales que no significan lo mismo", bullets: ["Sin respuesta: no permite inferir interés ni rechazo.", "Respuesta demorada: acuerda un momento realista.", "Derivación: confirma permiso y contexto.", "Rechazo suave: aclara solo si existe ambigüedad útil.", "Rechazo claro: cierra.", "Problema de momento: define condición de reactivación.", "Falta de encaje: descarta.", "Exclusión: registra y no vuelvas a contactar por ese canal." ] },
    { title: "Reglas de parada", bullets: ["La persona declina claramente.", "El contacto dejó de ser relevante.", "Las preferencias impiden continuar.", "La secuencia llegó a su final planificado.", "La señal perdió vigencia.", "Continuar podría dañar la relación.", "Los canales disponibles resultan inapropiados."], callout: { title: "Silencio no es consentimiento", text: "La consistencia no justifica presión indefinida. Define la salida antes de comenzar." } },
    { title: "Pausa con condiciones", exercise: exercise("Escribir una regla completa", "Define cuándo pausar, qué hecho permitiría reactivar y cuándo cerrar definitivamente.", "Evita fechas arbitrarias si no existe un cambio esperado.") },
  ], ["sequence"]),

  lesson(11, "objeciones", "Cómo responder objeciones sin convertir la conversación en una discusión", "Interpreta lo que la persona comunica y elige avanzar, pausar, derivar o terminar.", ["Clasificar objeciones", "Aplicar ESCUCHA", "Aceptar un no"], [
    { title: "La objeción contiene información", bullets: ["No es prioridad", "No hay interés", "Existe solución interna", "Existe proveedor", "No hay presupuesto", "No es el momento", "Envíame información", "No soy la persona", "Falta confianza", "La relevancia es débil", "Rechazo claro"], paragraphs: ["No toda objeción es una barrera que deba superarse. Puede señalar falta de encaje, momento, autoridad o deseo de terminar."] },
    { title: "ESCUCHA", framework: framework(["Entender", "Interpretar qué está comunicando la persona."], ["Señalar acuerdo", "Reconocer honestamente la parte válida."], ["Clarificar", "Preguntar solo si reduce una ambigüedad útil."], ["Utilidad", "Añadir información pertinente y comprobable."], ["Cerrar o avanzar", "Elegir continuar, pausar, redirigir o terminar."], ["Aceptar el no", "Respetar la negativa sin otra maniobra."]), callout: { title: "Marco conversacional", text: "ESCUCHA no es una técnica para vencer todas las objeciones. Un rechazo claro se acepta." } },
    { title: "Cuando piden información", bullets: ["Qué información ayudaría.", "Qué decisión busca apoyar.", "Quién la revisará.", "Qué paso tendría sentido después.", "Cuándo, si corresponde, retomar."], paragraphs: ["Si la persona no desea precisar, envía solo lo acordado o cierra. El recurso no autoriza una nueva secuencia indefinida."] },
    { title: "Preparar opciones", exercise: exercise("Tres salidas válidas", "Para una objeción, escribe una respuesta para aclarar, otra para pausar y otra para cerrar.", "Elige la menos invasiva que sea coherente con la señal.") },
    { title: "Dieciséis escenarios de objeciones", paragraphs: ["Practica interpretar antes de responder. El rechazo explícito no requiere una pregunta adicional."], scenarios: objectionScenarios },
  ], ["objection"]),

  lesson(12, "referencias", "Cómo activar referencias sin desgastar la confianza", "Solicita introducciones específicas, fáciles de rechazar y responsables con la confianza transferida.", ["Aplicar PUERTA", "Preparar texto reenviable", "Cuidar a quien presenta"], [
    { title: "Una referencia no transfiere permiso ilimitado", paragraphs: ["Pide después de haber creado valor, explica por qué la conexión podría ser útil y facilita que la persona decline. No solicites acceso a toda su agenda ni atribuyas un respaldo que no dio."], bullets: ["Cliente", "Excolega", "Socio profesional", "Proveedor", "Comunidad", "Red de egresados", "Evento", "Alianza", "Referencia interna"] },
    { title: "PUERTA", framework: framework(["Por qué ahora", "Razón que hace apropiada la solicitud."], ["Utilidad mutua", "Posible valor para ambas partes."], ["Especificidad", "Tipo de organización o rol relevante."], ["Respeto", "Forma cómoda de declinar."], ["Texto fácil", "Explicación breve que puede reenviarse."], ["Acompañamiento", "Manejo responsable después de presentar."]) },
    { title: "Después de la introducción", ordered: ["Responde con prontitud.", "Reconoce el alcance exacto de la presentación.", "Permite que la nueva persona decida.", "No agregues a una secuencia sin contexto.", "Informa al introductor solo lo apropiado.", "Agradece sin revelar detalles de la conversación." ] },
    { title: "Solicitud fácil de rechazar", exercise: exercise("Redactar una referencia", "Explica a quién buscas, por qué podría ser útil y añade una frase explícita que permita decir que no.", "Incluye un texto reenviable de dos o tres ideas, no una recomendación inventada."), links: [{ label: "Profundizar en desarrollo de relaciones", href: "/aprende/networking" }] },
  ], ["diagnostic"]),

  lesson(13, "operacion-y-metricas", "Cómo convertir la prospección en un sistema medible", "Protege tiempo, define etapas, calcula con supuestos y aprende mediante experimentos pequeños.", ["Definir un embudo operativo", "Calcular tasas con denominadores", "Diseñar rutinas y experimentos"], [
    { title: "Rutina protegida, no horario universal", bullets: ["Bloque de preparación", "Bloque de contacto", "Bloque de seguimiento", "Actualización del registro", "Revisión semanal", "Revisión de experimentos"], paragraphs: ["Elige periodos según energía, disponibilidad del mercado, función y geografía. No toda persona debe prospectar por la mañana."] },
    { title: "Embudo con definiciones", ordered: ["Cuentas objetivo: cumplen criterios mínimos.", "Cuentas investigadas: tienen fuente, hecho e hipótesis.", "Contactos intentados: envíos o llamadas entregados o realizados.", "Conversaciones: hubo intercambio sustantivo.", "Reuniones: conversación acordada y realizada o agendada según la métrica.", "Oportunidades calificadas: problema, actores y siguiente decisión definidos.", "Propuestas: alternativa formal compartida.", "Ganadas: acuerdo comercial confirmado."], callout: { title: "No mezcles etapas", text: "Una reunión agendada no es una reunión realizada; una respuesta no es necesariamente positiva; una propuesta no es una oportunidad ganada." } },
    { title: "Métricas y denominadores", formulas: [
      { label: "Tasa de respuesta", formula: "Respuestas ÷ contactos entregados" },
      { label: "Respuesta positiva", formula: "Respuestas positivas ÷ contactos entregados" },
      { label: "Reunión agendada", formula: "Reuniones agendadas ÷ contactos entregados" },
      { label: "Reunión realizada", formula: "Reuniones realizadas ÷ reuniones agendadas" },
      { label: "Oportunidad", formula: "Oportunidades calificadas ÷ reuniones realizadas" },
      { label: "Ganancia", formula: "Acuerdos ganados ÷ oportunidades calificadas o propuestas, indicando cuál" },
    ], paragraphs: ["También observa contactos, conversaciones, tiempos, finalización, exclusiones, segmentos, canales y fuentes. Una tasa sin periodo, segmento y denominador puede inducir decisiones erróneas."] },
    { title: "Planificación con incertidumbre", paragraphs: ["Puedes estimar contactos desde metas, valor medio y tasas históricas, pero los resultados cambian por segmento, canal, mensaje, temporada y mercado. Usa rangos y revisa supuestos.", "En experimentos, cambia una variable principal cuando sea posible; define línea base, audiencia, métrica de decisión, periodo, limitación de muestra y métrica de riesgo. Una muestra pequeña produce resultados inestables."], callout: { title: "IA responsable con DATOS", text: "Datos autorizados, Acción, Tono, Objetivo y Salvaguardas: usa solo información verificada, no confidencial ni sensible; pide un borrador acotado; prohíbe inventar hechos, familiaridad y resultados; revisa siempre antes de usar." }, links: [{ label: "Revisar uso responsable de IA", href: "/aprende/ia-responsable-y-gobernanza" }] },
    { title: "Revisión temporal", paragraphs: ["Última revisión editorial: 16 de julio de 2026. No se publican benchmarks universales: construye una línea base propia y comparable."] },
  ], ["calculator", "dashboard"]),

  lesson(14, "caso-integrador", "Caso práctico: construir un sistema de prospección B2B desde cero", "Integra foco, investigación, valor, contactos, secuencia, métricas, privacidad e IA responsable.", ["Construir un plan ejecutivo", "Defender pausas y exclusiones", "Relacionar actividad con aprendizaje"], [
    { title: "Caso ficticio creado con fines educativos", caseStudy: { title: "Taller Norte: de referencias a un sistema pequeño y disciplinado", paragraphs: ["Taller Norte es una consultora ficticia que ayuda a fabricantes regionales a coordinar planificación y reducir demoras operativas. Sus proyectos llegan por referencias; tiene cuatro experiencias, evidencia incompleta y no puede publicar nombres sin permiso.", "La fundadora dispone de ocho horas semanales. Suele escribir a gerentes generales, aunque operaciones vive el problema; sus correos describen servicios, el seguimiento es irregular y el registro comercial casi no se actualiza. Quiere explorar diez primeras conversaciones relevantes en el próximo trimestre sin exponer datos de clientes."] } },
    { title: "Diagnóstico y foco", ordered: ["Define qué resultado debe producir la prospección.", "Aplica REUNIÓN y enumera razones para no contactar.", "Crea un ICP con fabricantes de complejidad observable y exclusiones.", "Mapea operaciones, usuarios, finanzas, tecnología, compras y dirección.", "Prioriza con FOCO sin asignar puntajes inventados.", "Usa PISTA para separar señales, hipótesis y preguntas."], modelAnswers: [{ title: "Foco", text: "Comenzaría con organizaciones donde la coordinación operacional sea visible y la consultora tenga experiencia comparable. Excluiría cuentas que requieren credenciales o escala de entrega que aún no posee." }, { title: "Roles", text: "Operaciones puede ser un mejor inicio que gerencia general porque vive el proceso y puede validar la hipótesis; dirección y finanzas seguirían siendo actores posibles." }] },
    { title: "Valor y contacto", ordered: ["Entrevista a clientes anteriores con permiso para reconstruir resultados.", "Formula CAMBIO distinguiendo contribución y causalidad.", "Escribe dos mensajes CLAVE y dos asuntos precisos.", "Prepara una apertura telefónica y un cierre.", "Redefine LinkedIn como perfil, investigación, contenido y relación.", "Diseña una secuencia RITMO donde cada paso aporte algo nuevo."], modelAnswers: [{ title: "Propuesta", text: "Ayudamos a equipos de operaciones con planificación fragmentada a hacer visibles dependencias y reducir retrasos evitables mediante un diagnóstico y rediseño práctico; el alcance y el efecto deben validarse en cada planta." }, { title: "Contacto", text: "Usaría una señal pública de expansión como contexto, aclararía que no demuestra un problema y preguntaría si coordinar capacidad entre áreas es hoy una prioridad." }] },
    { title: "Operación, rechazo e IA", ordered: ["Prepara ESCUCHA para proveedor actual, momento y rechazo.", "Crea una solicitud PUERTA para contactos con valor previo.", "Distribuye ocho horas entre preparación, contacto, seguimiento y revisión.", "Define embudo, denominadores y un rango de actividad.", "Prueba por separado señal y CTA con muestras limitadas.", "Aplica DATOS: solo notas autorizadas, sin nombres ni resultados confidenciales.", "Entrega una recomendación ejecutiva con pausas y criterios de salida."], modelAnswers: [{ title: "Rutina", text: "Reservaría dos bloques de preparación, dos de contacto, uno de seguimiento y una revisión corta; ajustaría al observar disponibilidad real del mercado." }, { title: "Decisión", text: "No intentaría alcanzar la meta a cualquier costo. Priorizaría aprendizaje de cuentas relevantes, registraría exclusiones y revisaría capacidad antes de ampliar." }] },
    { title: "Entregables", bullets: ["ICP y mapa de compra", "Brief de investigación", "Propuesta de valor", "Mensajes y apertura telefónica", "Secuencia y reglas de parada", "Plan de objeciones y referencias", "Rutina semanal", "Embudo y tablero", "Dos experimentos", "Salvaguardas de privacidad e IA", "Recomendación ejecutiva"], callout: { title: "Alternativas válidas", text: "La fundadora puede comenzar solo con referencias y contenido, pausar el teléfono o reducir el segmento. La mejor combinación depende de evidencia, capacidad y preferencias del mercado." } },
  ], ["diagnostic", "calculator", "dashboard"]),
];

const scenarioCategories = ["objetivo", "mercado objetivo", "cliente ideal", "exclusión", "rol de compra", "responsable del problema", "priorización", "señal", "investigación", "personalización", "atributo y resultado", "evidencia", "afirmación", "propuesta de valor", "asunto de correo", "apertura de correo", "siguiente paso", "apertura telefónica", "asistente", "perfil profesional", "contenido", "invitación", "secuencia", "seguimiento", "rechazo claro", "momento", "solución interna", "solicitud de información", "referencia", "métrica", "cálculo de embudo", "bloque de tiempo", "experimento", "borrador con IA", "privacidad"];

export const prospectingScenarios = scenarioCategories.map((category, index) => ({
  slug: `escenario-${String(index + 1).padStart(2, "0")}`,
  title: ["¿Conversar o presentar?", "Una cuenta que parece atractiva", "Encaje con límites", "Capacidad insuficiente", "¿A quién contactar?", "La prioridad vive en operaciones", "Dos cuentas, distinta evidencia", "Una expansión anunciada", "El dato que falta", "Un elogio automático", "De función a cambio", "Un resultado sin permiso", "Una promesa demasiado amplia", "Valor para logística", "Asunto que finge respuesta", "Apertura centrada en el remitente", "Pedir un paso menor", "Una llamada sin contexto", "Orientación de recepción", "Un perfil lleno de consignas", "Comentar con aporte", "Conectar después de un evento", "Canales que repiten", "El segundo correo", "La negativa inequívoca", "Reactivar con condición", "Ya lo hacemos internamente", "Envíame antecedentes", "Presentación cómoda de rechazar", "¿Qué cuenta como respuesta?", "Del objetivo a la actividad", "Ocho horas disponibles", "Probar una sola variable", "IA que inventa una señal", "Un dato personal innecesario"][index],
  category,
  difficulty: index < 10 ? "introductorio" : index < 25 ? "intermedio" : "avanzado",
  account: `Organización ficticia ${String.fromCharCode(65 + (index % 26))}`,
  contactRole: ["Operaciones", "Finanzas", "Tecnología", "Gerencia", "Compras"][index % 5],
  evidence: `Hecho público ficticio ${index + 1}, con fuente y fecha por validar`,
  hypothesis: `Hipótesis comercial cauta sobre ${category}`,
  constraint: index % 6 === 0 ? "La evidencia es parcial y no autoriza afirmar una necesidad." : "No usar nombres, datos de contacto ni información confidencial.",
  learnerTask: `Decide el siguiente paso más respetuoso para el caso de ${category}.`,
  modelReasoning: index === 24 ? "El rechazo es claro: registra la preferencia y termina sin otro intento." : index === 33 ? "El borrador debe eliminar el hecho inventado, volver a la información autorizada y pasar por revisión humana." : "Separa hecho, inferencia y pregunta; compara contactar, investigar, pausar o descartar.",
  recommendedNextStep: index % 7 === 0 ? "Pausar hasta contar con evidencia suficiente." : index % 11 === 0 ? "No contactar y registrar el motivo." : "Proponer un paso pequeño que permita validar relevancia.",
  skills: ["criterio comercial", "evidencia", "respeto"], fictional: true,
}));

const resourceTitles = ["Lienzo REUNIÓN", "Tarjeta de límites de prospección", "Hoja FOCO", "Perfil de cliente ideal", "Mapa de roles de compra", "Brief PISTA", "Checklist de señales", "Lienzo CAMBIO", "Inventario de evidencia", "Hoja de mensaje CLAVE", "Checklist de correo", "Preparación de llamada", "Plan de LinkedIn", "Plan de contenido comercial", "Lienzo RITMO", "Checklist de seguimiento útil", "Tarjeta de reglas de parada", "Hoja ESCUCHA", "Guía PUERTA", "Plan semanal", "Guía de etapas del embudo", "Ficha de fórmulas", "Brief de experimento", "Plantilla DATOS", "Checklist de privacidad y ética", "Campos mínimos del registro comercial", "Tablero de prospección", "Plan ejecutivo de prospección"];
export const prospectingResources = resourceTitles.map((title, index) => ({
  id: `prospeccion-${index + 1}`, title,
  description: `Recurso práctico para estructurar ${title.toLowerCase()} sin almacenar información de prospectos.`,
  contentType: index % 3 === 0 ? "template" : index % 3 === 1 ? "checklist" : "worksheet",
  status: "published",
  fields: index % 3 === 2 ? ["Evidencia disponible", "Hipótesis", "Decisión", "Regla de parada"] : undefined,
  groups: index % 3 === 1 ? [{ title: "Antes de usar", items: ["Uso información autorizada", "Distingo hechos e inferencias", "Incluyo una salida respetuosa", "Evito datos sensibles"] }] : undefined,
  template: index % 3 === 0 ? `${title.toUpperCase()}\n\nCONTEXTO\n\nEVIDENCIA\n\nHIPÓTESIS\n\nSIGUIENTE PASO\n\nPAUSA O CIERRE` : undefined,
  reminder: "Usa descripciones generales o ficticias. No ingreses nombres, contactos ni información confidencial.",
}));

export const getProspectingLesson = (slug) => prospectingLessons.find((item) => item.slug === slug);
