const updatedAt="2026-07-16";const base="/aprende/sistemas-ia-confiables";
export const reliableAIPath={title:"Sistemas de IA confiables",description:"Comprende cómo instrucciones, fuentes, RAG, datos, seguridad y monitoreo se combinan en una solución de inteligencia artificial.",audience:"Líderes, producto, analítica, consultoría, tecnología, datos, riesgo y operaciones",level:"Intermedio",format:"Ruta técnica para decisiones de negocio",readingTime:"Aproximadamente 2 horas y 15 minutos",updatedAt,outcomes:["Mapear una solución completa y sus puntos de falla","Diseñar instrucciones reutilizables y fuentes gobernadas","Distinguir grounding, RAG, generación, predicción y reglas","Preparar datos, permisos, evaluación y seguridad","Definir monitoreo, incidentes, cambios y retiro"]};
const frameworks={
 FUENTE:[["Finalidad","Tarea o decisión que debe apoyar el sistema."],["Usuarios y permisos","Quién pregunta, recupera, revisa, aprueba o actúa."],["Evidencia","Fuentes, datos y etiquetas que respaldan el resultado."],["Núcleo técnico","Modelo, recuperación, reglas o método predictivo."],["Trazabilidad","Reconstrucción de fuentes, versiones, decisiones y acciones."],["Evaluación","Calidad, valor, riesgo y cambio que se observarán."]],
 NORMA:[["Necesidad","Tarea y resultado esperado."],["Origen de información","Entradas y fuentes autorizadas."],["Reglas","Restricciones, políticas y prohibiciones."],["Modelo de entrega","Formato, campos o esquema requerido."],["Aseguramiento","Verificación, incertidumbre, negativa y escalación."]],
 VIGENTE:[["Verificable","La fuente puede inspeccionarse."],["Idónea","Corresponde a la pregunta y su consecuencia."],["Gobernada","Tiene dueño, permisos y reglas."],["En fecha","Está suficientemente actualizada para la tarea."],["Nítida","Define alcance, términos y excepciones."],["Trazable","Su origen y cambios pueden seguirse."],["Equilibrada","Incluye perspectivas y excepciones relevantes."]],
 PREPARA:[["Propósito","Uso autorizado que apoyarán los datos."],["Responsabilidad","Dueño y mantenimiento."],["Exactitud","Calidad, completitud y limitaciones conocidas."],["Permisos","Acceso y uso permitido."],["Actualización","Cómo y cuándo cambia."],["Representación","Casos, grupos, idiomas o situaciones ausentes."],["Archivo y eliminación","Retención, corrección y borrado."]],
 ELIGE:[["Evidencia disponible","Datos, ejemplos, reglas y resultados observables."],["Labor requerida","Generar, predecir, clasificar, buscar, optimizar o ejecutar."],["Impacto del error","Consecuencia, reversibilidad y necesidad de revisión."],["Gobierno","Permisos, trazabilidad y propiedad."],["Evaluación","Prueba capaz de comparar alternativas."]],
 RESPONDE:[["Responsabilidad","Dueño del resultado y autoridad para detener."],["Estándares","Criterios internos y requisitos aplicables."],["Seguridad","Acceso, secretos, segmentación y respuesta."],["Pruebas","Casos, umbrales y aprobación de cambios."],["Operación","Monitoreo, soporte, costo y capacidad."],["Notificación","Alertas, incidentes y comunicación."],["Decisión","Cambiar, limitar, revertir o retirar."],["Evidencia","Versiones, registros y justificación."]]
};
const fw=(name)=>frameworks[name].map(([title,text])=>({title,text}));
const lesson=(order,slug,title,description,readingTime,outcomes,sections,relatedTools=[],relatedResources=[])=>({order,slug,title,description,readingTime,outcomes,sections,relatedTools,relatedResources,href:`${base}/${slug}`,level:"Intermedio",status:"published",updatedAt,lastReviewed:updatedAt,timeSensitive:true});
export const reliableAILessons=[
lesson(1,"confiabilidad-como-sistema","Por qué la confiabilidad depende de todo el sistema","Observa la cadena completa, no solo el desempeño del modelo.","11 minutos",["Separar modelo y sistema","Ubicar capas de falla","Aplicar FUENTE"],[
 {title:"El modelo es un componente",paragraphs:["Una solución puede reunir interfaz, instrucciones, solicitud, modelo, recuperación, documentos, datos, APIs, permisos, reglas, revisión humana, registros, monitoreo, incidentes y propiedad. Un modelo capaz puede formar parte de un sistema deficiente si recibe la fuente equivocada, ignora permisos o activa una acción incorrecta."],bullets:["Fuente desactualizada o no autorizada","Instrucción ambigua","Pregunta inadecuada para el sistema","Revisión ausente","Métrica que recompensa el comportamiento equivocado"]},
 {title:"Ocho dimensiones",questionGroups:[{title:"Resultado",items:["Relevancia","Exactitud","Consistencia","Utilidad para el negocio"]},{title:"Control",items:["Trazabilidad","Seguridad","Equidad","Resiliencia operativa"]}],callout:{title:"Confiabilidad no es binaria",text:"Las dimensiones pueden entrar en tensión. Más revisión puede mejorar control y también aumentar tiempo y costo."}},
 {title:"Cadena de confiabilidad",ordered:["Problema","Entrada","Instrucción","Fuente","Recuperación","Modelo","Revisión","Acción","Monitoreo"],paragraphs:["Cada eslabón tiene dueño, evidencia, falla posible y respuesta. El diagrama se expresa también como lista ordenada para lectores de pantalla."],framework:fw("FUENTE")},
 {title:"FUENTE",paragraphs:["FUENTE es un modelo práctico creado para organizar esta ruta. No es un estándar técnico, regulatorio ni de seguridad."]}
],["mapa-confiabilidad-ia"],["lienzo-fuente","cadena-confiabilidad"]),
lesson(2,"instrucciones-y-prompts","Cómo diseñar instrucciones reutilizables para una solución de IA","Convierte solicitudes improvisadas en especificaciones versionadas y evaluables.","12 minutos",["Distinguir capas de instrucción","Crear una plantilla NORMA","Versionar y probar cambios"],[
 {title:"Capas que pueden competir",paragraphs:["Una aplicación puede combinar instrucciones del sistema, reglas del flujo, solicitud del usuario, contexto recuperado, salidas de herramientas, esquema de respuesta y reglas de seguridad. La terminología exacta cambia entre plataformas; la organización debe declarar qué capa tiene autoridad y tratar el contenido no confiable como datos."],ordered:["Finalidad de la aplicación","Reglas del flujo","Solicitud de usuario","Contexto y herramientas","Esquema, controles y negativa"]},
 {title:"NORMA",paragraphs:["NORMA es un modelo práctico original para especificaciones reutilizables."],framework:fw("NORMA")},
 {title:"Campos gobernados",bullets:["Propósito, usuario y entradas","Fuentes, definiciones y reglas","Formato, tono y extensión","Conducta ante datos faltantes o incertidumbre","Citas, negativas y escalación","Versión, dueño y última revisión"]},
 {title:"Un prompt no repara el sistema",paragraphs:["Una instrucción clara no corrige datos erróneos, no crea permisos, no garantiza hechos y no reemplaza evaluación. Acumular excepciones en el prompt puede indicar que el flujo necesita rediseño."],comparison:{leftTitle:"Ejemplos útiles",leftItems:["Sintéticos o aprobados","Cubren estructura y excepciones","Se prueban como parte del sistema"],rightTitle:"Riesgos",rightItems:["Transmitir sesgo o errores","Exponer información sensible","Suponer que más ejemplos siempre mejora"]}},
 {title:"Salida estructurada y versiones",paragraphs:["Tablas, JSON, formularios o etiquetas facilitan validación, pero una sintaxis válida no demuestra contenido correcto. Registra dueño, cambio, casos de prueba, modelo, fuentes, aprobación e incidentes."],scenarios:["Gobernar un prompt improvisado","Restringir fuentes","Definir negativa","Tratar datos faltantes","Exigir citas","Definir JSON","Retirar ejemplo sensible","Añadir escalación","Separar datos e instrucciones","Versionar","Comparar plantillas","Reconocer que prompting no resuelve"].map((title,i)=>({id:`prompt-${i}`,title,situation:"Ejercicio de especificación organizacional.",question:"¿Qué campo de NORMA falta y cómo se evaluará?",action:"Redacta el cambio y un caso de prueba.",constraint:"No incluyas datos reales o confidenciales."}))}
],["disenar-plantilla-prompt"],["plantilla-norma"]),
lesson(3,"grounding","Cómo conectar una respuesta con información confiable","Revisa contexto, autoridad, vigencia, permisos y conflicto entre fuentes.","11 minutos",["Definir grounding sin reducirlo a RAG","Aplicar VIGENTE","Diseñar conducta ante evidencia insuficiente"],[
 {title:"Grounding es aportar contexto relevante",paragraphs:["Grounding conecta la generación con evidencia o contexto para la tarea. Puede provenir de un documento aportado por el usuario, base interna, consulta estructurada, API, regla, registro, fuente externa actual o hechos ingresados por una persona. RAG es una forma de recuperar contexto; no agota el concepto."]},
 {title:"Tener contexto no garantiza corrección",bullets:["La fuente puede ser incorrecta o antigua","La recuperación puede elegir un pasaje parecido pero inadecuado","Puede faltar una excepción","El modelo puede interpretar mal o exceder la evidencia","Puede haber conflicto, falta de permiso o instrucciones maliciosas"]},
 {title:"VIGENTE",paragraphs:["VIGENTE es un marco original de revisión de fuentes; no define una jerarquía universal. La autoridad depende de la tarea."],framework:fw("VIGENTE")},
 {title:"Citas y límites",bullets:["Citar fuentes inspeccionables","Separar evidencia e interpretación","Mostrar conflicto y fecha relevante","Decir cuando la evidencia es insuficiente","No inventar referencias ni responder fuera del contexto permitido"]},
 {title:"Ocho casos",scenarios:["Política para empleados","Especificación de producto","Actualización normativa","Término contractual","Manual de formación","Solución técnica","Síntesis de investigación","Información de servicio público"].map((title,i)=>({id:`fuente-${i}`,title,situation:"Caso ficticio con más de una fuente posible.",question:"¿Cuál tiene autoridad, quién la mantiene, quién accede y qué vigencia necesita?",action:"Define comportamiento ante conflicto o ausencia.",constraint:"La herramienta no emite una conclusión legal o regulatoria."}))}
],["evaluar-fuentes-ia"],["checklist-vigente"]),
lesson(4,"rag","Cómo funciona un sistema RAG","Mapea ingestión, permisos, recuperación, contexto, generación y evaluación separada.","14 minutos",["Explicar RAG sin confundirlo con entrenamiento","Mapear un flujo completo","Evaluar recuperación y generación por separado"],[
 {title:"Definición práctica",paragraphs:["Un flujo de generación aumentada por recuperación busca información relevante y la entrega a un modelo generativo como contexto para producir una respuesta. Recuperar no entrena ni actualiza permanentemente el modelo por defecto; cambia el contexto disponible en esa interacción."]},
 {title:"Flujo accesible",ordered:["Recibir la solicitud","Interpretar o reformular","Verificar identidad y permisos","Buscar fuentes aprobadas","Seleccionar y ordenar pasajes","Armar el contexto","Enviar instrucciones y contexto al modelo","Generar","Verificar, citar o restringir","Registrar y mostrar","Usar feedback e incidentes para mejorar"]},
 {title:"Preparar antes de buscar",bullets:["Recolectar y analizar documentos","Extraer texto y dividir según estructura y preguntas","Asignar metadata, versiones y permisos","Crear representaciones de búsqueda e índice","Actualizar y eliminar contenido"],callout:{title:"No existe un tamaño universal de fragmento",text:"Depende de estructura, pregunta, ventana de contexto, método de búsqueda y precisión de cita."}},
 {title:"Métodos y fallas",questionGroups:[{title:"Recuperación",items:["Palabras clave","Semántica","Híbrida","Filtros de metadata","Reordenamiento","Consultas estructuradas o por etapas"]},{title:"Fallas",items:["Contenido ausente o antiguo","Permisos perdidos","Pasaje parecido pero incorrecto","Fragmento sin contexto","Metadata ausente","Instrucción maliciosa en documento","Contexto excesivo o evidencia insuficiente"]}]},
 {title:"Tres evaluaciones",comparison:{leftTitle:"Componente",leftItems:["Fuente necesaria recuperada","Pasaje bien posicionado","Irrelevantes excluidos","Respuesta respaldada y citas correctas"],rightTitle:"Extremo a extremo",rightItems:["Tarea completada","Acceso apropiado","Tiempo aceptable","Trabajo reducido, no desplazado"]},paragraphs:["Evalúa recuperación y generación por separado: una respuesta mala puede venir de búsqueda, contexto o generación. Después mide utilidad, permisos, costo y carga operacional."]}
],["disenar-flujo-rag"],["lienzo-rag","fallas-rag"]),
lesson(5,"preparacion-de-datos","Cómo preparar datos y conocimiento para una solución de IA","Evalúa propósito, propiedad, calidad, permisos, representación y ciclo de vida.","12 minutos",["Distinguir datos estructurados e información","Aplicar PREPARA","Diseñar feedback sin recolectar de más"],[
 {title:"Datos e información no son equivalentes",comparison:{leftTitle:"Estructurados",leftItems:["Transacciones","Inventario","Mediciones","Eventos y campos"],rightTitle:"No estructurados y conocimiento",rightItems:["Políticas, informes, contratos y medios","Definiciones y excepciones","Práctica que no está documentada","Contexto de propietarios y usuarios"]}},
 {title:"PREPARA",paragraphs:["PREPARA es un marco práctico original. Preparación depende del uso; no produce una puntuación universal."],framework:fw("PREPARA")},
 {title:"Inventario y metadata",bullets:["Fuente, dueño, formato, ubicación y sensibilidad","Población, fechas, frecuencia y calidad","Acceso, retención, uso y restricciones","Título, autor, versión, idioma, geografía, audiencia, acceso y vencimiento"],callout:{title:"Metadata requiere mantenimiento",text:"Añadir campos no mejora la búsqueda si están vacíos, son ambiguos o no se actualizan."}},
 {title:"Representación, linaje y feedback",questionGroups:[{title:"Cobertura",items:["Idiomas y grupos","Casos raros y resultados negativos","Abandonos ausentes","Historia discriminatoria o proceso cambiado"]},{title:"Linaje",items:["Origen y transformaciones","Aprobación y usos","Corrección y borrado"]},{title:"Feedback categorizado",items:["Respuesta, fuente, recuperación, instrucción, acceso, daño o proceso"]}]}
],["evaluar-preparacion-datos-ia"],["hoja-prepara","inventario-datos"]),
lesson(6,"seguridad","Cómo proteger una solución de inteligencia artificial","Aplica identidad, permisos, secretos, registros y respuesta a incidentes en toda la cadena.","13 minutos",["Distinguir autenticación y autorización","Reconocer prompt injection","Definir controles defensivos"],[
 {title:"La seguridad atraviesa el flujo",bullets:["Identidad y aplicación","Endpoint del modelo","Fuentes, índice y bases","Integraciones y herramientas","Registros, monitoreo y administración","Respuesta a incidentes"]},
 {title:"Conceptos esenciales",examples:[{title:"Autenticación",text:"Verifica quién es una persona o servicio."},{title:"Autorización",text:"Determina qué puede consultar o ejecutar esa identidad."},{title:"Cifrado",text:"Protege datos en tránsito o reposo, pero no impide por sí solo accesos autorizados incorrectos, fugas en salidas o abuso."},{title:"Mínimo privilegio y segmentación",text:"Reducen acceso y alcance potencial de una falla."},{title:"Registros, auditoría y secretos",text:"Permiten observar actividad y proteger credenciales fuera del código."}]},
 {title:"Riesgos específicos",bullets:["Prompt injection directa o indirecta","Fuga de datos y recuperación no autorizada","Permisos excesivos de herramientas","Código o salida tratados de forma insegura","Documentos maliciosos o envenenamiento","Dependencias y cadena de suministro","Exposición entre usuarios y registros sensibles"]},
 {title:"Prompt injection: enfoque defensivo",paragraphs:["Contenido no confiable puede incluir instrucciones que intenten alterar el comportamiento. Trátalo como datos, separa instrucciones de confianza, autoriza herramientas fuera del modelo, aplica privilegios mínimos, valida salidas y prepara interrupción. Filtrar y delimitar reduce riesgo, pero no demuestra protección total."],checklist:["Qué datos entran y salen","Quién accede y a qué fuentes","Qué herramientas usa el modelo","Qué acción exige aprobación","Qué se registra sin exponer secretos","Cómo detectar, contener, recuperar y comunicar"]}
],["revision-seguridad-ia"],["revision-seguridad","defensa-inyeccion"]),
lesson(7,"ia-generativa-vs-machine-learning","Cómo elegir entre IA generativa, machine learning y reglas","Selecciona una capacidad por la tarea y evidencia, no por novedad.","11 minutos",["Distinguir generación y predicción","Conservar reglas como alternativa","Diseñar sistemas híbridos"],[
 {title:"Capacidades distintas",comparison:{leftTitle:"Generación",leftItems:["Produce contenido o estructura","Admite variación","Necesita revisión de respaldo y formato"],rightTitle:"Predicción y software",rightItems:["Clasifica, estima, detecta o optimiza","Reglas ejecutan lógica explícita","Requiere datos, métricas o condiciones definidas"]}},
 {title:"ELIGE",paragraphs:["ELIGE es un marco original para comparar métodos; no sustituye validación técnica."],framework:fw("ELIGE")},
 {title:"Sistemas híbridos",paragraphs:["Una solución puede usar reglas para permisos, un modelo predictivo para priorizar, recuperación para aportar evidencia y generación para explicar. Mantén métricas y responsabilidades separadas por componente."],scenarios:["Predecir abandono","Redactar explicación","Clasificar solicitudes","Detectar anomalías","Optimizar inventario","Aplicar criterio de elegibilidad","Buscar políticas","Resumir comentarios"].map((title,i)=>({id:`metodo-${i}`,title,situation:"Caso ficticio con una tarea y consecuencias distintas.",question:"¿Convienen reglas, búsqueda, predicción, generación o una combinación?",action:"Define evidencia y comparación.",constraint:"No elijas generación solo porque acepta lenguaje natural."}))}
],["elegir-metodo-ia"],["guia-elige"]),
lesson(8,"ciclo-de-vida-ml","Cómo gestionar el ciclo de vida de un modelo","Conecta problema, datos, prueba, despliegue, monitoreo, cambio y retiro.","11 minutos",["Mapear responsabilidades del ciclo","Distinguir tipos de cambio","Preparar retiro"],[
 {title:"Etapas revisables",ordered:["Definir problema y alternativa","Preparar datos y permisos","Desarrollar o seleccionar método","Evaluar con casos relevantes","Aprobar y desplegar gradualmente","Monitorear resultado, riesgo y operación","Cambiar, revertir o retirar"]},
 {title:"Responsabilidad de negocio",bullets:["Validar objetivo y métrica","Autorizar datos y usos","Aprobar umbrales y excepciones","Definir intervención humana","Financiar operación y soporte","Aceptar, limitar o retirar"]},
 {title:"Cambios que pueden degradar el sistema",examples:[{title:"Datos",text:"Cambian las características de las entradas."},{title:"Concepto",text:"Cambia la relación entre entradas y resultado."},{title:"Etiqueta o resultado",text:"Cambia cómo se observa o define el resultado."},{title:"Proceso o política",text:"Cambia el flujo o la regla de negocio."},{title:"Usuarios",text:"Cambian población, conducta o forma de uso."}],paragraphs:["La palabra drift agrupa fenómenos distintos. Cada señal necesita diagnóstico y respuesta; no todo cambio exige reentrenar."]},
 {title:"Reproducir y retirar",bullets:["Versionar código, datos, modelo, instrucciones, fuentes y configuración","Conservar pruebas y aprobaciones","Definir exportación, revocación, archivo y comunicación","Mantener alternativa segura cuando sea necesaria"]}
],["plan-ciclo-vida-modelo"],["lienzo-ciclo-vida","checklist-drift"]),
lesson(9,"evaluacion-y-monitoreo","Cómo evaluar y monitorear un sistema de IA","Diseña conjuntos de prueba, métricas, revisión humana y alertas vinculadas con decisiones.","13 minutos",["Separar capas de evaluación","Diseñar un conjunto representativo","Convertir señales en acciones"],[
 {title:"Cuatro capas",framework:[{title:"Componentes",text:"Instrucción, recuperación, modelo, regla o herramienta."},{title:"Extremo a extremo",text:"Resultado del flujo completo."},{title:"Negocio",text:"Valor frente a línea base y alternativas."},{title:"Riesgo",text:"Daño, acceso, diferencias, incidentes y posibilidad de recurso."}]},
 {title:"Conjunto de prueba",bullets:["Casos típicos, raros y adversos","Idiomas, grupos y permisos relevantes","Evidencia suficiente, insuficiente y contradictoria","Resultados esperados, aceptables y prohibidos","Versiones congeladas para comparar cambios"]},
 {title:"Métricas y revisión humana",paragraphs:["Combina medidas automáticas con revisión de personas autorizadas. Define rúbrica, muestra, capacitación, desacuerdo, autoridad y escalación; una etiqueta de revisión humana no aclara por sí sola responsabilidad."],questionGroups:[{title:"RAG",items:["Cobertura y posición de recuperación","Respaldo y exactitud de citas","Afirmaciones sin soporte"]},{title:"Operación",items:["Latencia, costo, disponibilidad","Anulaciones, escalaciones e incidentes"]}]},
 {title:"Monitorear para decidir",bullets:["Definir señal, umbral, dueño y cadencia","Investigar cambios de datos, modelo, fuente, política y usuarios","Separar feedback de respuesta, fuente, acceso o proceso","Limitar, revertir o retirar cuando corresponde"]}
],["plan-evaluacion-ia"],["plan-evaluacion","registro-feedback-incidentes"]),
lesson(10,"gobierno-y-operacion","Cómo diseñar una arquitectura de responsabilidad","Asigna propiedad, pruebas, cambios, incidentes y decisiones de operación.","12 minutos",["Aplicar RESPONDE","Explicar operaciones de modelos con cautela","Comparar construir, comprar y diferir"],[
 {title:"RESPONDE",paragraphs:["RESPONDE es un marco operativo original. No certifica seguridad ni cumplimiento."],framework:fw("RESPONDE")},
 {title:"MLOps, LLMOps y GenAIOps",paragraphs:["Estas etiquetas suelen agrupar prácticas para desarrollar, desplegar, evaluar, observar y cambiar sistemas con modelos. El alcance varía entre organizaciones. La práctica concreta importa más que el nombre: versiones, pruebas, permisos, telemetría, incidentes, costos y retiro."]},
 {title:"Control de cambio e incidentes",ordered:["Detectar y registrar la señal","Contener alcance y preservar evidencia","Asignar dueño y evaluar impacto","Comunicar a quienes corresponda","Corregir, probar y aprobar","Restaurar o retirar","Aprender y actualizar controles"]},
 {title:"Decisión de aprovisionamiento",comparison:{leftTitle:"Configurar o comprar",leftItems:["Menor carga inicial posible","Controles y cambios dependen del servicio","Revisar salida, datos, portabilidad y soporte"],rightTitle:"Integrar, construir o diferir",rightItems:["Mayor control y responsabilidad","Exige capacidades de operación","Diferir es válido si faltan evidencia o controles"]},links:[{label:"Revisar gobierno y escala de negocio",href:"/aprende/ia-generativa-para-negocios/escalar-y-operar"},{label:"Preparar comunicación de incidentes",href:"/aprende/comunicacion-profesional"}]}
],["disenar-operacion-ia"],["lienzo-responde","matriz-aprovisionamiento"]),
lesson(11,"caso-integrador","Caso integrador: una respuesta confiable requiere un sistema","Aplica los seis marcos a una solución ficticia de conocimiento y predicción.","16 minutos",["Integrar arquitectura, datos y seguridad","Diseñar evaluación y operación","Recomendar límites o retiro"],[
 {title:"Caso ficticio: Faro Servicios Urbanos",caseStudy:{title:"Asistente para incidencias y mantenimiento",paragraphs:["Faro recibe reportes ciudadanos y mantiene infraestructura. El equipo propone un sistema que clasifique incidencias, recupere procedimientos, redacte respuestas y prediga prioridad de mantenimiento.","Los manuales tienen versiones contradictorias, algunos registros contienen datos personales y los permisos actuales dependen del área. No existe conjunto de prueba ni dueño único. La demostración usa ejemplos seleccionados y no registra fuentes."]}},
 {title:"Encargo",ordered:["Mapea la cadena y FUENTE","Especifica NORMA y comportamiento sin evidencia","Evalúa fuentes con VIGENTE","Diseña RAG con permisos y citas","Revisa datos con PREPARA","Separa reglas, predicción y generación con ELIGE","Define seguridad, evaluación, monitoreo y RESPONDE","Recomienda qué no implementar todavía"]},
 {title:"Razonamiento modelo",modelAnswers:[{title:"Alcance",text:"Separaría clasificación, recuperación, redacción y predicción. Empezaría con consulta interna sin acciones externas y una sola fuente gobernada."},{title:"Datos y fuentes",text:"Resolvería versiones, dueño, permisos, retención y cobertura antes de indexar. Una cita no compensa una fuente incorrecta."},{title:"Seguridad",text:"Verificaría identidad antes de recuperar, aplicaría permisos por fuente, trataría documentos como no confiables y mantendría herramientas sin autoridad externa."},{title:"Evaluación",text:"Mediría recuperación y generación por separado, además de utilidad, diferencias entre grupos, accesos, latencia, costo e incidentes."},{title:"Decisión",text:"Diferiría predicción de prioridad hasta contar con resultados observables y evaluación de representación. Detendría ante exposición de datos o fuente crítica no trazable."}]},
 {title:"Memo final",exercise:{title:"Recomienda construir, configurar, integrar o diferir",prompt:"Resume arquitectura, evidencia, control, responsables, métricas y condiciones de retiro.",help:"Incluye una alternativa sin IA y una limitación explícita."}}
],["mapa-confiabilidad-ia","plan-evaluacion-ia"],["checklist-piloto-confiable"])
];

const caseRows=[
["politicas-lago","Asistente de políticas de Lago Norte","Conocimiento"],["soporte-cedro","Copiloto de soporte de Cedro","Servicio"],["finanzas-aurora","Resumen financiero de Aurora","Finanzas"],["feedback-nimbo","Clasificador de feedback de Nimbo","Producto"],["mantenimiento-sur","Predicción de mantenimiento de Surco","Operaciones"],["crm-via","Agente de CRM de Vía Clara","Comercial"],["contratos-puente","Consulta contractual de Puente","Legal interno"],["manuales-orbita","Buscador de manuales de Órbita","Técnica"],["becas-rio","Orientador de becas de Río Alto","Servicio público"],["calidad-lumen","Detección de calidad de Lumen","Manufactura"],["inventario-pino","Optimización de inventario de Pino","Operaciones"],["reportes-atlas","Narrativa de reportes de Atlas","Analítica"],["codigo-brisa","Ayuda de código de Brisa","Tecnología"],["formacion-marea","Ejercicios de Marea","Aprendizaje"],["traduccion-norte","Localización de Norte","Contenido"],["incidentes-cauce","Clasificación de incidentes de Cauce","Seguridad"],["proveedores-olmo","Síntesis de proveedores de Olmo","Compras"],["turnos-delta","Predicción de demanda de Delta","Planificación"],["reclamos-faro","Respuestas a reclamos de Faro","Servicio"],["investigacion-senda","Síntesis de investigación de Senda","Investigación"]];
export const reliableAICases=caseRows.map(([slug,title,category],i)=>({slug,title,category,difficulty:i%3===0?"avanzado":"intermedio",businessTask:"Apoyar una tarea definida sin automatizar la decisión final.",users:["persona usuaria autorizada","dueño del proceso"],inputs:["solicitud de prueba"],sources:["fuente ficticia gobernada","excepción deliberadamente incompleta"],permissions:["mínimo privilegio","revisión antes de actuar"],modelType:i%4===0?"predictivo o híbrido":"generativo o híbrido",humanOversight:["revisor con autoridad para rechazar"],risks:["fuente incorrecta","acceso indebido","resultado no respaldado"],evaluation:["componente","extremo a extremo","negocio","riesgo"],monitoring:["calidad","cambio","incidentes"],stopConditions:["exposición de datos","falla crítica no contenida"],fictional:true}));

export const reliableAIResources=[
["lienzo-fuente","Lienzo FUENTE"],["cadena-confiabilidad","Cadena de confiabilidad"],["plantilla-norma","Plantilla NORMA"],["checklist-vigente","Checklist VIGENTE"],["lienzo-rag","Lienzo de arquitectura RAG"],["fallas-rag","Checklist de fallas RAG"],["hoja-prepara","Hoja PREPARA"],["inventario-datos","Inventario de datos"],["revision-seguridad","Revisión de seguridad"],["defensa-inyeccion","Tarjeta defensiva ante prompt injection"],["guia-elige","Guía ELIGE"],["lienzo-ciclo-vida","Lienzo de ciclo de vida"],["checklist-drift","Checklist de cambios y drift"],["plan-evaluacion","Plan de evaluación"],["registro-feedback-incidentes","Registro de feedback e incidentes"],["lienzo-responde","Lienzo RESPONDE"],["matriz-aprovisionamiento","Matriz de aprovisionamiento"],["checklist-piloto-confiable","Checklist de piloto confiable"]
].map(([id,title])=>({id,title,type:"Plantilla",description:"Recurso imprimible para estructurar decisiones sin almacenar información.",fields:["Propósito","Evidencia","Responsable","Riesgo","Control","Prueba","Condición de cambio"]}));
export const getReliableAILesson=(slug)=>reliableAILessons.find((item)=>item.slug===slug);export const getReliableAIResource=(id)=>reliableAIResources.find((item)=>item.id===id);
