export const teamworkBase="/aprende/trabajo-en-equipo";
export const teamworkLastReviewed="2026-07-16";
export const personalityNotice="Esta herramienta no evalúa ni clasifica la personalidad. Ayuda a describir preferencias y necesidades en una situación concreta, que pueden cambiar según el contexto.";
const modelNotice="Este es un modelo práctico creado para organizar esta ruta. No es un estándar, una certificación ni una garantía de resultados.";
const exercise=(title,prompt,help)=>({title,prompt,help});
const section=(title,paragraphs,bullets=[],extra={})=>({title,paragraphs,bullets,...extra});
const lesson=(order,slug,title,description,outcomes,sections,relatedTools)=>({order,slug,title,description,outcomes,sections,relatedTools,href:`${teamworkBase}/${slug}`,level:order<4?"Inicial":order<8?"Intermedio":"Aplicado",readingTime:`${12+(order%4)}–${18+(order%4)} minutos`,updatedAt:teamworkLastReviewed,lastReviewed:teamworkLastReviewed,status:"published"});

export const teamworkToolLinks={
 purpose:{title:"Clarificador de propósito colectivo",href:"/herramientas/clarificar-proposito-equipo",description:"Ordena resultado, beneficiario, entregables, límites y evidencia de éxito."},
 dependencies:{title:"Mapa de dependencias",href:"/herramientas/mapear-dependencias-equipo",description:"Detecta entregables sin dueño, ciclos y puntos únicos de fallo."},
 rights:{title:"Diseñador de derechos de decisión",href:"/herramientas/disenar-decision-equipo",description:"Aclara autoridad, consulta, evidencia, urgencia y reversibilidad."},
 agreements:{title:"Constructor de acuerdos de trabajo",href:"/herramientas/crear-acuerdos-equipo",description:"Convierte preferencias, necesidades y restricciones en conductas revisables."},
 disagreement:{title:"Preparador de desacuerdo",href:"/herramientas/preparar-desacuerdo-equipo",description:"Separa tema, evidencia, tensión, alternativas, poder y canal."},
 decision:{title:"Registro de decisiones",href:"/herramientas/registrar-decision-equipo",description:"Documenta pregunta, opciones, razón, objeciones y reapertura."},
 commitments:{title:"Revisor de compromisos",href:"/herramientas/revisar-compromisos-equipo",description:"Revisa dueño, capacidad, dependencias, fecha y evidencia de cierre."},
 review:{title:"Facilitador de revisión de ciclo",href:"/herramientas/revisar-ciclo-equipo",description:"Distingue resultados, interpretaciones, condiciones y experimentos."},
 dynamics:{title:"Detector de dinámica situacional",href:"/herramientas/observar-dinamica-equipo",description:"Orienta entre conversar, cambiar proceso, documentar, escalar o salir."},
 experiment:{title:"Plan de experimento de equipo",href:"/herramientas/crear-experimento-equipo",description:"Diseña un cambio acotado, señal, revisión y condición de interrupción."},
};

export const teamworkLessons=[
lesson(1,"entender-interdependencia","Entender qué hace que un grupo sea un equipo","Distingue interdependencia real de presencia conjunta, comunidad o coordinación puntual.",[
"Reconocer cuándo existe un resultado colectivo","Distinguir equipo, grupo, red y coordinación puntual","Definir fronteras, beneficiario y autoridad"],[
section("No toda colaboración necesita ser equipo",["Un equipo existe cuando producir el resultado requiere integrar contribuciones y decisiones. Un grupo puede compartir información sin asumir un resultado común; una red conecta recursos sin una frontera estable."],["Resultado que nadie produce solo","Dependencias recíprocas","Responsabilidad individual y compartida","Cliente o beneficiario","Autoridad formal e informal"]),
section("Fronteras útiles",["Aclara quién integra el trabajo, quién patrocina, quién recibe el resultado y qué colaboración queda fuera. Una identidad colectiva sin interdependencia puede añadir reuniones sin mejorar el trabajo."],["Permanente o temporal","Proyecto o función continua","Comité, comunidad o red","Qué ocurre cuando una contribución falla"]),
section("Caso ficticio: Red Faro",["Doce personas intercambian prácticas cada mes. Solo cuatro deben integrar un entregable para un municipio ficticio. El conjunto es una comunidad; el subgrupo del entregable sí opera como equipo."],["La buena relación no define el sistema","Reunirse no crea interdependencia","La frontera puede cambiar según el resultado"]),
section("Práctica",["Clasifica doce situaciones ficticias como grupo, equipo, red o coordinación puntual y justifica la dependencia real."],[],{exercise:exercise("Clasifica por trabajo, no por etiqueta","Para cada situación identifica resultado, beneficiario, dependencia, decisión y frontera.","No conviertas toda colaboración en equipo.")})
],["purpose","dependencies"]),
lesson(2,"alinear-resultado","Alinear propósito, entregables y criterios","Convierte objetivos vagos en resultados observables con evidencia y límites.",[
"Separar actividad, entregable y resultado","Definir evidencia de aceptación","Hacer visibles restricciones, riesgos y asuntos fuera de alcance"],[
section("Resultado, evidencia y límite",[modelNotice,"Resultado describe el cambio o producto; evidencia indica cómo reconocerlo; límite protege alcance, restricciones y aquello que no puede sacrificarse."],[],{framework:[{title:"Resultado",text:"Qué debe producirse o cambiar y para quién."},{title:"Evidencia",text:"Qué observación permitiría reconocer calidad suficiente."},{title:"Límite",text:"Qué queda fuera y qué restricción no puede ignorarse."}]}),
section("Alineación verificable",["Un indicador ayuda solo si representa el resultado y no incentiva atajos. Declara supuestos, prioridad, fecha, interesados y criterio de aceptación; revisa los cambios de alcance explícitamente."],["Verbos observables","Calidad suficiente","Riesgo y supuesto","Prioridad y capacidad","Cambio reconocido"]),
section("Caso ficticio: Portal Claro",["El encargo ‘mejorar la experiencia’ produce tres trabajos incompatibles. El equipo redefine el resultado, evidencia de uso y límites de accesibilidad y privacidad."],["Actividad no equivale a resultado","Una fecha no resuelve el alcance","Una métrica puede ocultar daño"]),
section("Práctica",["Reescribe ocho objetivos ambiguos como acuerdos verificables."],[],{exercise:exercise("Del verbo vago al acuerdo","Añade beneficiario, entregable, evidencia, límite, supuesto y señal de revisión.","No prometas certeza ni sacrifiques seguridad por velocidad.")})
],["purpose","commitments"]),
lesson(3,"roles-dependencias-decisiones","Acordar roles, dependencias y decisiones","Reduce duplicación, vacíos, esperas y concentración de autoridad.",[
"Distinguir responsabilidad, contribución y autoridad","Mapear entradas y puntos de integración","Prever sustitución y escalamiento"],[
section("Mapa de contribución y autoridad",["Para cada entregable o decisión registra quién prepara, quién aporta evidencia, quién decide, quién necesita información, qué depende de qué y qué riesgo aparece si no ocurre."],["Preparación","Evidencia","Autoridad final","Información","Condición o fecha","Dependencias y sustitución"]),
section("Responsable no significa aislado",["Asignar a todo el grupo diluye responsabilidad; asignar todo a una persona crea fragilidad. Participar no equivale a decidir y consultar no implica veto."],["Puntos únicos de fallo","Cuellos de botella","Ausencias previsibles","Aprobaciones proporcionales","Escalamiento claro"]),
section("Caso ficticio: Vértice",["Tres personas creen dirigir la validación y nadie prepara los datos. Un mapa revela autoridad duplicada, entrada sin dueño y ausencia de reemplazo."],["Nombrar el entregable primero","Separar preparación de decisión","Registrar integración y contingencia"]),
section("Práctica",["Diagnostica el proyecto ficticio y rediseña responsabilidades sin copiar una matriz externa."],[],{exercise:exercise("Mapa de trabajo real","Registra decisión o entregable, preparación, evidencia, autoridad, información, dependencia y riesgo.","Revisa quién concentra aprobación y quién absorbe trabajo invisible.")})
],["dependencies","rights"]),
lesson(4,"diferencias-sin-etiquetas","Trabajar con diferencias sin encasillar","Sustituye etiquetas por preferencias declaradas, necesidades del contexto y acuerdos observables.",[
"Describir diferencias sin inferir rasgos","Separar comodidad, necesidad y acuerdo","Diseñar alternativas accesibles y revisables"],[
section("Preferencia, necesidad y acuerdo",[personalityNotice,"Una preferencia expresa comodidad; una necesidad surge de la tarea, el contexto o la accesibilidad; un acuerdo define una conducta concreta y revisable."],[],{framework:[{title:"Preferencia",text:"Cómo alguien declara que procesa o colabora mejor en esta situación."},{title:"Necesidad",text:"Qué condición requiere la tarea, la accesibilidad o el contexto."},{title:"Acuerdo",text:"Qué hará el equipo, durante cuánto y cuándo lo revisará."}]}),
section("Diferencias observables",["Preparación, síntesis, detalle, canal escrito u oral, ritmo, autonomía, contexto, documentación y disponibilidad pueden variar. Una conducta puntual no demuestra personalidad ni competencia."],["No usar para selección, promoción o exclusión","No exigir revelación personal ni participación verbal inmediata","No interpretar silencio o contacto visual","Ofrecer participación escrita y asincrónica","Revisar el acuerdo"]),
section("Caso ficticio: Marea Técnica",["Una persona pide documentos antes; otra necesita una conversación breve. La tarea además requiere revisión financiera. El equipo diseña preparación escrita y una sesión con agenda, sin atribuir identidades."],["La necesidad de la tarea puede prevalecer","Adaptar no significa manipular","El acuerdo puede cambiar"]),
section("Práctica",["Transforma estereotipos en preguntas de trabajo y acuerdos observables."],[],{exercise:exercise("De etiqueta a conversación","Escribe conducta observada, contexto, pregunta, necesidad y experimento.",personalityNotice)})
],["agreements","dynamics"]),
lesson(5,"desacuerdo-y-participacion","Crear conversaciones donde pueda aparecer el desacuerdo","Diseña discusiones donde objeciones, evidencia y poder puedan hacerse visibles.",[
"Distinguir conflicto de tarea, proceso y relación","Separar objeción de ataque","Elegir formatos que reduzcan barreras de participación"],[
section("Tema, evidencia, tensión y opción",[modelNotice,"Tema acota la decisión; evidencia sostiene posiciones; tensión nombra valores, riesgos o restricciones en competencia; opción abre alternativas o pruebas."],[],{framework:[{title:"Tema",text:"Qué se decide y qué queda fuera."},{title:"Evidencia",text:"Qué información sostiene o contradice cada posición."},{title:"Tensión",text:"Qué riesgos, valores o restricciones compiten."},{title:"Opción",text:"Qué alternativa, prueba o pausa es posible."}]}),
section("Participación no es velocidad",["Silencio no equivale a acuerdo y rapidez no equivale a competencia. Una agenda previa, turnos explícitos, escritura, pausas y objeciones asincrónicas pueden ampliar la evidencia disponible."],["Criterios antes de soluciones","Preguntas de clarificación","Protección frente a represalias","Registro de opciones","Canal adecuado al poder y riesgo"]),
section("Caso ficticio: Reunión Alba",["Dos voces dominan y el aparente consenso se desarma en mensajes privados. La facilitación recoge objeciones por escrito y aclara quién decide y cómo se protegerán desacuerdos."],["Franqueza sin protección puede dañar","No todo conflicto pertenece al grupo","Una objeción ética no se silencia por compromiso"]),
section("Práctica",["Analiza la reunión y diseña una segunda discusión con opciones reales."],[],{exercise:exercise("Diseña la conversación","Define tema, evidencia, tensión, opciones, turnos, formato alternativo, autoridad y registro.","Si existe amenaza o represalia, prioriza seguridad y canales apropiados.")})
],["disagreement","agreements"]),
lesson(6,"decidir-y-comprometerse","Tomar decisiones y construir compromiso","Aclara método, autoridad, razones, objeciones y condiciones de reapertura.",[
"Elegir un método proporcional","Distinguir compromiso de unanimidad","Registrar una decisión comprensible"],[
section("La decisión necesita dueño y método",["Consulta, consentimiento, consenso, delegación, jerarquía y experimento tienen costos distintos. Elige según reversibilidad, urgencia, consecuencia, conocimiento y autoridad legítima."],["Pregunta","Autoridad","Personas consultadas","Criterios y opciones","Evidencia y riesgos","Fecha y revisión"]),
section("Compromiso sin obediencia ciega",["Una persona puede ejecutar una decisión que no prefería si comprende qué se decidió, qué se espera y cómo plantear riesgos. Ninguna idea de compromiso debe silenciar objeciones éticas o de seguridad."],["Razón visible","Objeciones pendientes","Condición de reapertura","Responsabilidad de implementación","Límite de autoridad"]),
section("Caso ficticio: Decisión Bruma",["El equipo confunde consulta con consenso y reabre cada conversación. La autoridad registra decisión, razón y condición de revisión; una objeción de seguridad queda abierta y escalada."],["Consultar no promete adoptar","Reabrir requiere condición","Registrar protege memoria, no impide corregir"]),
section("Práctica",["Elige métodos para diez situaciones ficticias y explica el costo de cada opción."],[],{exercise:exercise("Tarjeta de decisión","Completa pregunta, autoridad, consulta, criterios, opciones, decisión, razón, objeciones y reapertura.","No uses consenso para transferir responsabilidad formal al grupo.")})
],["rights","decision"]),
lesson(7,"seguimiento-compartido","Convertir compromisos en responsabilidad compartida","Hace visibles bloqueos, capacidad, renegociación y cierre sin convertir seguimiento en vigilancia.",[
"Formular compromisos verificables","Pedir ayuda antes del vencimiento","Distinguir responsabilidad, apoyo, culpa y disciplina formal"],[
section("Ciclo de compromiso",["Acordar, registrar, hacer visible, revisar, renegociar y cerrar. Cada movimiento necesita una conducta observable, no una etiqueta sobre motivación."],[],{ordered:["Acordar acción, dueño y evidencia de cierre","Registrar capacidad, fecha y dependencias","Hacer visible avance y bloqueo","Revisar sin esperar al vencimiento","Renegociar alcance o apoyo","Cerrar o escalar con claridad"]}),
section("Seguimiento proporcional",["Una actualización no demuestra avance. Revisa evidencia, dependencias y capacidad. No controles con más intensidad a quien tiene menos poder ni conviertas un tablero en evaluación oculta."],["Bloqueo y ayuda requerida","Cambio de capacidad","Riesgo y consecuencia","Proceso formal separado","Cierre verificable"]),
section("Caso ficticio: Tablero Ámbar",["El tablero tiene tareas sin dueño, fechas impuestas y estados vagos. La persona que coordina absorbe los bloqueos. El equipo renegocia capacidad y distribuye seguimiento."],["Fecha validada","Ayuda antes del retraso","No rescatar todo","Escalar lo estructural"]),
section("Práctica",["Rediseña el tablero y explica qué campos eliminarías para evitar vigilancia."],[],{exercise:exercise("Compromisos con salida","Define acción, dueño, evidencia, dependencia, capacidad, riesgo, ayuda, revisión y cierre.","Los procesos disciplinarios no se sustituyen por una herramienta informal.")})
],["commitments","dependencies"]),
lesson(8,"revisar-y-aprender","Revisar resultados y aprender","Convierte experiencia en cambios concretos del sistema sin imponer una narrativa de culpa.",[
"Preparar un ciclo con supuestos y señales","Separar resultado, interpretación y condiciones","Diseñar pocos experimentos revisables"],[
section("Preparación de ciclo",["Antes de ejecutar, define resultado, supuestos, experiencias comparables, fallos posibles de coordinación, señales para cambiar y evidencia que registrarás."],["Resultado relevante","Supuestos explícitos","Riesgos de coordinación","Señal de adaptación","Registro mínimo"]),
section("Revisión de ciclo",["Después, compara resultado observado con lo esperado; identifica decisiones y condiciones; decide qué detener, conservar o probar y quién actualizará el sistema."],["Hecho frente a interpretación","Factores estructurales y conductas","Qué es repetible","Experimento pequeño","Responsable de actualización"],{callout:{title:"Límite",text:"Una revisión no sustituye una investigación formal ni debe usarse para imponer una versión o castigar a quien aporta información negativa."}}),
section("Caso ficticio: Lanzamiento Nube",["El lanzamiento cumple fecha, pero genera retrabajo y agotamiento. La revisión evita celebrar solo el plazo y examina decisiones de alcance, carga y señales ignoradas."],["Resultado multidimensional","Costo no visible","Condiciones, no culpable único","Cambio concreto"]),
section("Práctica",["Facilita la revisión y produce dos experimentos, no una lista interminable."],[],{exercise:exercise("Aprendizaje que cambia el sistema","Separa observado, esperado, decisión, condición, aprendizaje, experimento y dueño.","Documenta riesgos de seguridad o conducta formal por el canal correspondiente.")})
],["review","experiment"]),
lesson(9,"dinamicas-dificiles","Intervenir en dinámicas difíciles","Elige una intervención proporcional según patrón, efecto, poder, intentos y riesgo.",[
"Nombrar patrones sin diagnosticar personas","Distinguir cambio de proceso, conversación y escalamiento","Reconocer límites del equipo"],[
section("Secuencia de intervención",["Observa, nombra el patrón, comprueba perspectivas, identifica efecto, propone un experimento, registra, revisa y escala cuando corresponda."],[],{ordered:["Observar conducta y contexto","Nombrar el patrón sin atribuir intención","Comprobar perspectivas y poder","Identificar efecto en trabajo o dignidad","Proponer cambio o experimento","Registrar lo necesario","Revisar evidencia","Escalar, pedir apoyo o salir"]}),
section("Proporción y seguridad",["Dominar turnos, ocultar bloqueos, reabrir decisiones o distribuir carga de modo desigual pueden admitir cambios de proceso. Acoso, discriminación, represalias, amenazas, apropiación deliberada o riesgos de seguridad pueden requerir documentación y canales formales."],["Intervenir ahora","Conversar en privado","Cambiar el proceso","Documentar","Escalar o pedir apoyo","Salir cuando corresponda"]),
section("Caso ficticio: Crédito Partido",["Una persona presenta como propio el trabajo de otra y existe diferencia jerárquica. Una conversación directa podría no ser segura ni suficiente; se conservan registros y se evalúa un canal formal."],["No inferir intención no impide documentar hechos","Reparación y proceso formal pueden coexistir","La persona afectada no debe cargar sola con la solución"]),
section("Práctica",["Compara intervenciones para patrones de baja presión y situaciones de alto riesgo."],[],{exercise:exercise("Intervención proporcional","Registra patrón, frecuencia, efecto, poder, intentos, riesgo, acción y condición de escalamiento.","No diagnostiques al equipo ni reemplaces apoyo profesional.")})
],["dynamics","disagreement"]),
lesson(10,"practica-integrada","Práctica integrada y herramientas","Integra propósito, dependencia, decisión, diferencias, desacuerdo, seguimiento, aprendizaje y seguridad.",[
"Aplicar el sistema completo a un caso ambiguo","Justificar alternativas según contexto y poder","Diseñar una mejora que pueda interrumpirse"],[
section("Sistema de coordinación del equipo",[modelNotice,"El sistema conecta seis elementos sin suponer una secuencia causal rígida."],[],{framework:[{title:"Propósito",text:"Resultado colectivo y beneficiario."},{title:"Trabajo",text:"Entregables, actividades, dependencias y restricciones."},{title:"Decisión",text:"Participación y autoridad final."},{title:"Interacción",text:"Información, desacuerdo, ayuda y acceso."},{title:"Seguimiento",text:"Compromisos, riesgos, cambios y avances."},{title:"Aprendizaje",text:"Revisión y modificación del sistema."}]}),
section("Caso integrado: Proyecto Umbral",["Un equipo multidisciplinario remoto debe lanzar una herramienta interna; la fecha se anunció antes del alcance. En 16 etapas aparecen interpretaciones distintas, roles superpuestos, dependencias invisibles, voces dominantes, objeciones privadas, decisión no registrada, capacidad incompatible, retraso, culpa, revisión del sistema, nuevo mapa, experimento, segundo ciclo, revisión final y límites que exigen apoyo fuera del equipo."],["Poder desigual y presión temporal","Necesidades de accesibilidad","Información incompleta","Riesgos y alternativas","Varias decisiones defendibles","Notas de facilitación y rúbrica cualitativa"]),
section("Modalidades de práctica",["La práctica puede ser individual, en pareja, con equipo o facilitación; escrita, remota o asincrónica. La observación se centra en claridad, evidencia, participación, poder, seguimiento y aprendizaje."],["Caso de baja presión","Caso con riesgo","Guía de observación","Razonamiento modelo","Sin respuesta única ni puntuación global"]),
section("Práctica",["Recorre diez decisiones desde definir el resultado hasta elegir una intervención."],[],{exercise:exercise("Plan integrado","Produce propósito, mapa, decisión, acuerdo, discusión, compromiso, revisión e intervención.","Detén el ejercicio si expone información confidencial o crea riesgo para una persona.")})
],["purpose","experiment"])
];

export const teamworkPath={title:"Trabajo en equipo",description:"Cómo coordinar objetivos, diferencias, decisiones y aprendizaje para trabajar mejor con otras personas.",definition:"El trabajo en equipo es un sistema observable de interdependencia, decisión, seguimiento y aprendizaje; no una suma de perfiles ni una ausencia de conflicto.",audience:"Personas que colaboran, coordinan o lideran equipos permanentes, temporales, remotos o híbridos",format:"10 módulos, 28 casos, 16 recursos y 10 herramientas",effort:"Ruta flexible, sin tiempo obligatorio",outcomes:["Definir resultados y evidencia","Aclarar roles, dependencias y autoridad","Convertir diferencias en acuerdos","Facilitar desacuerdos con opciones","Registrar decisiones y compromisos","Revisar resultados sin culpa automática","Elegir cuándo reparar, escalar o salir"]};
export const getTeamworkLesson=(slug)=>teamworkLessons.find((item)=>item.slug===slug);

const caseSeeds=[
["equipo-nuevo","Un equipo nuevo sin resultado común","inicial"],["temporal","Proyecto temporal con fronteras móviles","intermedia"],["remoto","Equipo remoto con información desigual","intermedia"],["hibrido","Participación desigual en formato híbrido","intermedia"],["multicultural","Supuestos culturales no comprobados","avanzada"],["sin-autoridad","Liderazgo sin autoridad formal","avanzada"],["objetivo-ambiguo","Objetivo que admite tres interpretaciones","inicial"],["roles-duplicados","Dos personas preparan el mismo entregable","intermedia"],["sin-responsable","Entrada crítica sin responsable","inicial"],["centralizada","Toda decisión espera una aprobación","intermedia"],["autoridad-incierta","Nadie sabe quién puede decidir","intermedia"],["falso-consenso","Silencio interpretado como acuerdo","avanzada"],["voz-dominante","Una voz ocupa casi todo el espacio","intermedia"],["interrupcion","Una persona es interrumpida sistemáticamente","avanzada"],["objeciones-privadas","Las objeciones aparecen fuera de la reunión","avanzada"],["plazo-irreal","Fecha anunciada antes de validar capacidad","intermedia"],["sobrecarga","Una persona absorbe todos los bloqueos","avanzada"],["trabajo-invisible","Documentación y coordinación no reconocidas","intermedia"],["bloqueo-tardio","El bloqueo se comunica al vencer","inicial"],["reapertura","Decisiones reabiertas sin condición","intermedia"],["sin-documentacion","Acuerdos que cambian según quien recuerda","inicial"],["revision-culpa","La revisión busca un culpable","avanzada"],["credito","Apropiación de crédito con poder desigual","avanzada"],["favoritismo","Acceso y carga distribuidos por favoritismo","avanzada"],["etiquetas","Una etiqueta sustituye una conversación","intermedia"],["accesibilidad","Procesamiento y acceso no contemplados","intermedia"],["escalamiento","Una amenaza requiere apoyo formal","avanzada"],["cerrar-equipo","El equipo ya no tiene interdependencia","avanzada"]
];
export const teamworkCases=caseSeeds.map(([id,title,difficulty],index)=>({id,title,difficulty,label:"Caso ficticio creado con fines educativos.",learningObjective:"Elegir una intervención basada en conducta, sistema, poder y evidencia.",context:`Situación ficticia sobre ${title.toLowerCase()} en un proyecto con información incompleta.`,observations:["Existe una conducta observable y acotada","El efecto alcanza coordinación o dignidad","La autoridad no está completamente aclarada"],interpretations:["Puede existir un problema de proceso","También puede faltar contexto","No corresponde inferir un rasgo o intención"],missingInformation:["Perspectivas afectadas","Restricciones y poder","Intentos previos y riesgo"],decisionPoint:"¿Conviene conversar, cambiar el proceso, documentar, escalar, pedir apoyo o salir?",actions:["Aclarar el resultado o decisión","Comprobar perspectivas con un formato accesible","Proponer un cambio revisable","Usar un canal formal si el riesgo lo exige"],risks:["Etiquetar personas","Exponer a quien tiene menos poder","Confundir seguimiento con vigilancia"],feedback:"Una respuesta sólida separa hechos e interpretación, considera poder y explica por qué la intervención es proporcional.",relatedLesson:teamworkLessons[index%10].slug,relatedTool:Object.keys(teamworkToolLinks)[index%10]}));

const resourceSeeds=[
["purpose","Lienzo de propósito del equipo",["Resultado","Beneficiario","Entregables","Evidencia","Límites"]],
["dependencies","Mapa de entregables y dependencias",["Entregable","Preparación","Entrada","Integración","Riesgo"]],
["decisions","Mapa de decisiones",["Pregunta","Autoridad","Evidencia","Consulta","Condición"]],
["working","Acuerdo de trabajo",["Tema","Necesidad","Acuerdo","Alternativa asincrónica","Revisión"]],
["preferences","Preferencias, necesidades y acuerdos",["Situación","Preferencia declarada","Necesidad contextual","Acuerdo","Revisión"]],
["disagreement","Preparador de desacuerdo",["Tema","Evidencia","Tensión","Opciones","Poder"]],
["decision-card","Tarjeta de decisión",["Pregunta","Opciones","Criterios","Decisión","Reapertura"]],
["commitments","Registro de compromisos",["Acción","Dueño","Capacidad","Evidencia de cierre","Revisión"]],
["blockers","Registro de bloqueos",["Bloqueo","Efecto","Dependencia","Ayuda","Escalamiento"]],
["cycle-prep","Preparación de ciclo",["Resultado","Supuestos","Riesgo de coordinación","Señal","Registro"]],
["cycle-review","Revisión de ciclo",["Observado","Esperado","Condiciones","Aprendizaje","Experimento"]],
["intervention","Guía de intervención",["Patrón","Efecto","Poder","Acción","Límite"]],
["power","Checklist de poder y participación",["Decisión","Voces ausentes","Riesgo","Alternativa","Protección"]],
["remote","Guía para equipos remotos",["Canales","Asincronía","Documentación","Accesibilidad","Revisión"]],
["facilitation","Guía de facilitación",["Propósito","Turnos","Opciones","Registro","Cierre"]],
["self-review","Rúbrica de autoevaluación",["Claridad","Evidencia","Participación","Poder","Aprendizaje"]]
];
export const teamworkResources=resourceSeeds.map(([id,title,fields])=>({id,title,type:"Ficha HTML editable e imprimible",description:`Apoya ${title.toLowerCase()} con conductas y acuerdos observables.`,fields:[...fields,"Alternativa escrita o asincrónica","Fecha de revisión"],reminder:`Evita nombres, información sensible y diagnósticos. ${personalityNotice}`}));
