import { useEffect,useMemo } from "react";
import { ArrowRight,BookOpen,Clock,Gauge,Layers3,ShieldAlert,Target } from "lucide-react";
import { trackEvent } from "./analytics";
import { harmfulConditionsNotice,wellbeingLessons,wellbeingPath,wellbeingResources,wellbeingSafetyNotice,wellbeingScenarios,getWellbeingLesson,getWellbeingResource } from "./wellbeingContent";
import { Breadcrumbs,LessonContent,LessonMetadata,LessonNavigation,PageShell,RelatedContent,ResourceCard,StatusBadge } from "./LearningComponents";
import { NotFoundPage } from "./LearningPages";
import { breadcrumbSchema,usePageMetadata } from "./seo";
const base="/aprende/relaciones-y-bienestar";const graphNode=({"@context":_context,...node})=>node;
const toolLinks={"mapa-bienestar-contexto":{title:"Mapa de contexto",href:"/herramientas/mapa-bienestar-contexto"},"mapa-energia-recuperacion":{title:"Mapa de energía",href:"/herramientas/mapa-energia-recuperacion"},"plan-practica-sostenible":{title:"Plan PASO",href:"/herramientas/plan-practica-sostenible"},"preparar-limite-profesional":{title:"Preparar un límite",href:"/herramientas/preparar-limite-profesional"},"preparar-conversacion-relacion":{title:"Conversación CERCA",href:"/herramientas/preparar-conversacion-relacion"},"preparar-conversacion-dificil":{title:"Plan HABLAR",href:"/herramientas/preparar-conversacion-dificil"},"reflexion-seguridad-equipo":{title:"Reflexión VOCES",href:"/herramientas/reflexion-seguridad-equipo"},"disenar-practicas-equipo":{title:"Plan EQUIPO",href:"/herramientas/disenar-practicas-equipo"},"plan-relaciones-bienestar":{title:"Plan CUIDA",href:"/herramientas/plan-relaciones-bienestar"}};

function SafetyNotice(){return <aside className="lesson-callout safety-notice"><h2><ShieldAlert size={20}/> Alcance y seguridad</h2><p>{wellbeingSafetyNotice}</p><p>{harmfulConditionsNotice}</p></aside>;}
export function WellbeingHubPage(){const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"Relaciones y bienestar",href:base}];const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:wellbeingPath.title,description:wellbeingPath.description,url:`https://masanes.cl${base}`,learningResourceType:"Ruta de aprendizaje",educationalLevel:wellbeingPath.level,dateModified:wellbeingPath.updatedAt}]}),[]);usePageMetadata({title:"Relaciones y bienestar profesional",description:wellbeingPath.description,path:base,schema});useEffect(()=>{trackEvent("wellbeing_hub_viewed");if(window.location.hash)requestAnimationFrame(()=>document.querySelector(window.location.hash)?.scrollIntoView());},[]);
 return <PageShell><main id="main-content" className="content-page"><Breadcrumbs items={breadcrumbs}/><header className="page-hero page-hero--networking"><div><p className="eyebrow">Ruta de aprendizaje</p><h1>Relaciones y bienestar</h1><p className="page-hero__lead">{wellbeingPath.description}</p><p>El bienestar cambia con la carga, la salud, las relaciones y las condiciones de trabajo. Las prácticas personales pueden ayudar, pero no sustituyen límites, acuerdos ni responsabilidad organizacional.</p><div className="hero-actions"><a className="button button--primary" href={wellbeingLessons[0].href}>Comenzar la ruta <ArrowRight size={17}/></a><a className="button button--secondary" href="/herramientas/mapa-bienestar-contexto">Revisar mi situación</a><a className="button button--secondary" href="/herramientas/plan-relaciones-bienestar">Crear un plan personal</a></div></div><aside className="summary-panel"><StatusBadge status="published"/><dl><div><dt><Target size={18}/>Dirigido a</dt><dd>{wellbeingPath.audience}</dd></div><div><dt><BookOpen size={18}/>Tipo</dt><dd>{wellbeingPath.format}</dd></div><div><dt><Clock size={18}/>Tiempo</dt><dd>{wellbeingPath.readingTime}</dd></div><div><dt><Gauge size={18}/>Nivel</dt><dd>{wellbeingPath.level}</dd></div><div><dt><Layers3 size={18}/>Módulos</dt><dd>9 módulos</dd></div></dl></aside></header><SafetyNotice/>
 <section className="guide-intro"><div><p className="eyebrow">CUIDA</p><h2>Una guía flexible para elegir el nivel adecuado</h2><p>Contexto, Ubicar, Intervenir, Dialogar y Ajustar. CUIDA organiza este recurso; no es una herramienta clínica ni una evaluación científica.</p></div><ul>{wellbeingPath.outcomes.map((item)=><li key={item}>{item}</li>)}</ul></section>
 <section className="content-section content-section--soft" aria-labelledby="wellbeing-lessons"><div className="section-title"><p className="eyebrow">Nueve módulos</p><h2 id="wellbeing-lessons">De observar el contexto a diseñar condiciones</h2></div><div className="case-chapter-grid">{wellbeingLessons.map((item)=><a className="content-card content-card--link" href={item.href} key={item.slug}><span className="resource-type">Módulo {item.order}</span><h3>{item.title}</h3><p>{item.description}</p><span className="card-link">Abrir módulo <ArrowRight size={16}/></span></a>)}</div></section>
 <section className="content-section" aria-labelledby="wellbeing-tools"><div className="section-title"><p className="eyebrow">Herramientas privadas y locales</p><h2 id="wellbeing-tools">Reflexiona sin crear un diagnóstico</h2><p>No escribas nombres, diagnósticos, empleadores ni información de salud.</p></div><div className="case-tool-links">{Object.values(toolLinks).map((tool)=><a href={tool.href} key={tool.href}>{tool.title}<ArrowRight size={16}/></a>)}</div></section>
 <section className="content-section content-section--soft" id="biblioteca-bienestar" aria-labelledby="wellbeing-practice"><div className="section-title"><p className="eyebrow">Biblioteca de práctica</p><h2 id="wellbeing-practice">Quince escenarios ficticios</h2><p>Cada respuesta depende de poder, seguridad y quién controla la condición.</p></div><div className="scenario-grid">{wellbeingScenarios.map((item)=><article id={`escenario-${item.slug}`} key={item.slug}><p className="resource-type">Caso ficticio · {item.difficulty}</p><h3>{item.title}</h3><p>{item.context}</p><details><summary>Abrir práctica y razonamiento</summary><p><strong>Hechos:</strong> {item.observableFacts.join("; ")}</p><p><strong>Incógnitas:</strong> {item.unknowns.join("; ")}</p><p><strong>Actores:</strong> {item.stakeholders.join("; ")}</p><p><strong>Poder:</strong> {item.powerConsiderations.join("; ")}</p><p><strong>Tarea:</strong> {item.learnerTasks.join("; ")}</p><p><strong>Respuestas posibles:</strong> {item.possibleResponses.join("; ")}</p><p><strong>Razonamiento:</strong> {item.modelReasoning.join(" ")}</p><p><strong>Seguridad:</strong> {item.safetyConsiderations.join(" ")}</p><p><strong>Habilidades:</strong> {item.skills.join("; ")}</p></details></article>)}</div></section>
 <section className="content-section" id="recursos" aria-labelledby="wellbeing-resources"><div className="section-title"><p className="eyebrow">Recursos</p><h2 id="wellbeing-resources">Quince hojas y guías no clínicas</h2><p>Todo lo escrito desaparece al recargar. Copia solo lo que quieras conservar de forma segura.</p></div><div className="resource-grid">{wellbeingResources.map((resource)=><ResourceCard key={resource.id} resource={resource}/>)}</div></section>
 <aside className="contextual-cta"><div><h2>¿Necesitas ordenar una situación profesional que está afectando tu trabajo o tus relaciones?</h2><p>Puedo ayudarte a clarificar el problema, preparar una conversación y construir un plan acorde con tus objetivos y límites. Este servicio no ofrece atención clínica.</p></div><a className="button button--primary" href="/#services" onClick={()=>trackEvent("wellbeing_service_clicked",{destination:"coaching"})}>Conocer el servicio de coaching</a></aside></main></PageShell>;
}
export function WellbeingLessonPage({slug}){const item=getWellbeingLesson(slug);return item?<WellbeingLessonContent item={item}/>:<NotFoundPage/>;}
function WellbeingLessonContent({item}){const index=wellbeingLessons.indexOf(item);const resources=item.relatedResources.map(getWellbeingResource).filter(Boolean);const tools=item.relatedTools.map((slug)=>toolLinks[slug]).filter(Boolean);const breadcrumbs=[{label:"Inicio",href:"/"},{label:"Aprende",href:"/aprende"},{label:"Relaciones y bienestar",href:base},{label:item.title,href:item.href}];const schema=useMemo(()=>({"@context":"https://schema.org","@graph":[graphNode(breadcrumbSchema(breadcrumbs)),{"@type":"LearningResource",name:item.title,description:item.description,url:`https://masanes.cl${item.href}`,learningResourceType:"Lección",educationalLevel:item.level,dateModified:item.updatedAt,isPartOf:{"@type":"LearningResource",name:wellbeingPath.title,url:`https://masanes.cl${base}`}}]}),[item.slug]);usePageMetadata({title:item.title,description:item.description,path:item.href,schema});useEffect(()=>trackEvent("wellbeing_lesson_opened",{module:item.slug}),[item.slug]);return <PageShell><main id="main-content" className="content-page lesson-page"><Breadcrumbs items={breadcrumbs}/><article><header className="lesson-header"><div><p className="eyebrow">Módulo {item.order} de 9</p><h1>{item.title}</h1><p>{item.description}</p></div><StatusBadge status="published"/></header><SafetyNotice/><LessonMetadata module={item} total={9}/><aside className="lesson-outcomes"><h2>Al terminar podrás</h2><ul>{item.outcomes.map((outcome)=><li key={outcome}>{outcome}</li>)}</ul></aside><LessonContent content={item}/><RelatedContent resources={resources} tools={tools} basePath={base}/><div className="lesson-hub-link"><a className="button button--secondary" href={base}>Volver a Relaciones y bienestar</a></div><LessonNavigation previous={wellbeingLessons[index-1]} next={wellbeingLessons[index+1]}/></article></main></PageShell>;}
