const clean=(value)=>String(value||"").trim().replace(/\s+/g," ");
const validate=(values,required)=>Object.fromEntries(required.filter((key)=>!clean(values[key])).map((key)=>[key,"Completa este campo para continuar."]));
const line=(label,value,fallback="Por definir")=>`${label}: ${clean(value)||fallback}`;
const safety="Este recurso ofrece reflexión y organización general. No reemplaza apoyo médico, psicológico, legal, laboral ni de emergencia.";
const pack=(errors,output,warnings=[])=>({errors,output,warnings});

export function buildWellbeingContext(values){
 const errors=validate(values,["context","load","recovery","conditions","support"]);if(Object.keys(errors).length)return pack(errors,"");
 const warnings=[!clean(values.negotiation)&&"Identifica qué necesita conversación o acuerdo.",!clean(values.organization)&&"Revisa si una condición requiere acción del equipo o de la organización.",/amenaza|acoso|discrimin|represalia|insegur/i.test(clean(values.context)+" "+clean(values.conditions))&&"La situación descrita puede requerir canales formales o apoyo especializado; no dependas solo de una conversación directa."].filter(Boolean);
 return pack({},`MAPA DE CONTEXTO\n${line("Situación",values.context)}\n${line("Fuente principal de carga",values.load)}\n${line("Recuperación disponible",values.recovery)}\n${line("Factores relacionales",values.relationships)}\n${line("Condiciones de trabajo",values.conditions)}\n${line("Apoyo actual",values.support)}\n\nNIVELES DE ACCIÓN\nPersonal: ${clean(values.control)||"identificar una acción pequeña y segura"}\nRelacional: ${clean(values.negotiation)||"preparar una conversación sobre expectativas o apoyo"}\nOrganizacional: ${clean(values.organization)||"documentar la condición y definir quién puede cambiarla"}\n\nSIGUIENTES PREGUNTAS\n¿Qué es un patrón y qué fue un momento aislado?\n¿Qué condición no puede resolverse con una rutina personal?\n¿Qué apoyo o canal sería adecuado?\n\n${safety}\nCuidar el bienestar no significa aceptar condiciones dañinas.`,warnings);
}

export function buildEnergyMap(values){
 const errors=validate(values,["activities","effect","timing","duration","recovery","control","adjustment"]);if(Object.keys(errors).length)return pack(errors,"");
 const warnings=[values.effect==="Desborda"&&"Una condición que supera repetidamente la capacidad puede requerir ajuste de carga, apoyo organizacional o un canal formal.",!clean(values.people)&&"Observa si las personas o dinámicas cambian el efecto de la actividad."].filter(Boolean);
 return pack({},`MAPA DE ENERGÍA Y RECUPERACIÓN\n${line("Actividad recurrente",values.activities)}\n${line("Efecto temporal",values.effect)}\n${line("Momento",values.timing)}\n${line("Duración",values.duration)}\n${line("Personas o contexto",values.people)}\n${line("Recuperación necesaria",values.recovery)}\n${line("Grado de control",values.control)}\n${line("Ajuste posible",values.adjustment)}\n\nVENTANAS A PROBAR\nAntes: reducir una fricción o aclarar la expectativa.\nDurante: usar una pausa o límite compatible con la tarea.\nDespués: reservar la recuperación que indicaste.\n\nPREGUNTA DE CARGA\n¿Te estás recuperando repetidamente de una condición que debería cambiar?\n\nEsta clasificación describe un contexto, no un rasgo ni un estado de salud. ${safety}`,warnings);
}

export function buildSustainablePractice(values){
 const errors=validate(values,["area","obstacle","action","trigger","frequency","minimum","restart","review"]);if(Object.keys(errors).length)return pack(errors,"");
 const warnings=[!clean(values.support)&&"Aclara si la práctica necesita apoyo o un acuerdo con otra persona."].filter(Boolean);
 return pack({},`PLAN PASO\nPequeña: ${clean(values.minimum)}\nAsociada: cuando ocurra ${clean(values.trigger)}, realizaré ${clean(values.action)}.\nSostenible: ${clean(values.frequency)}, considerando ${clean(values.obstacle)}.\nObservable: registraré si la acción ocurrió, sin puntuar mi bienestar.\n\nÁREA\n${clean(values.area)}\n\nINTERRUPCIÓN Y REINICIO\n${clean(values.restart)}\n\nAPOYO O LÍMITE\n${clean(values.support)||"Por definir"}\n\nREVISIÓN\n${clean(values.review)}\n\nUna interrupción no convierte el plan en fracaso. Rediseña la práctica si deja de caber en el contexto. ${safety}`,warnings);
}

export function buildBoundary(values){
 const errors=validate(values,["situation","behavior","impact","boundary","alternative","review"]);if(Object.keys(errors).length)return pack(errors,"");
 const formal=/sí|amenaza|acoso|discrimin|represalia|seguridad/i.test(clean(values.safety)+" "+clean(values.escalation));
 const warnings=[formal&&"Considera apoyo institucional, representación o canales formales antes de una conversación directa. Esta herramienta no determina una vía legal.",!clean(values.flexibility)&&"Aclara qué margen de negociación existe."].filter(Boolean);
 return pack({},`PLAN LÍMITE\nLugar o situación: ${clean(values.situation)}\nImpacto: ${clean(values.impact)}\nNecesidad: ${clean(values.boundary)}\nMargen: ${clean(values.flexibility)||"Por acordar"}\nIntercambio: ${clean(values.alternative)}\nTérmino o revisión: ${clean(values.review)}\nEscalamiento: ${clean(values.escalation)||"Por definir"}\n\nBORRADOR\n“Cuando ${clean(values.behavior)}, ocurre ${clean(values.impact)}. Necesito ${clean(values.boundary)}. Puedo ofrecer ${clean(values.alternative)} y propongo revisarlo ${clean(values.review)}.”\n\nPREPARACIÓN\n□ Elegí un canal seguro\n□ Describí una condición observable\n□ Evité atribuir intención\n□ Definí alternativa y revisión\n□ Consideré poder, seguridad y apoyo\n\n${safety}`,warnings);
}

export function buildRelationshipConversation(values){
 const errors=validate(values,["context","issue","interpretation","impact","perspective","request","followUp"]);if(Object.keys(errors).length)return pack(errors,"");
 const warnings=[!clean(values.boundary)&&"Aclara el límite que no quieres perder durante la reparación.",!clean(values.contribution)&&"Considera si existe una contribución propia que puedas reconocer sin aceptar culpa inapropiada."].filter(Boolean);
 return pack({},`CONVERSACIÓN CERCA\nClaridad: ${clean(values.context)}; el hecho observable es ${clean(values.issue)}.\nEscucha: quiero explorar ${clean(values.perspective)}.\nReciprocidad: mi impacto fue ${clean(values.impact)} y preguntaré por el de la otra persona.\nConfianza gradual: compartiré solo la información necesaria.\nAjuste y reparación: solicitaré ${clean(values.request)} y revisaré ${clean(values.followUp)}.\n\nHECHO E INTERPRETACIÓN\nHecho: ${clean(values.issue)}\nInterpretación personal: ${clean(values.interpretation)}\nContribución propia: ${clean(values.contribution)||"Por considerar"}\nLímite: ${clean(values.boundary)||"Por definir"}\n\nPREGUNTAS\n¿Cómo viste tú la situación?\n¿Qué expectativa no estaba clara?\n¿Qué cambio sería realista para ambas partes?\n\nLa empatía implica preguntar y comprobar; no exige acuerdo, intimidad ni responsabilizarte de emociones ajenas.`,warnings);
}

export function buildDifficultConversation(values){
 const errors=validate(values,["situation","facts","interpretation","impact","shared","request","followUp"]);if(Object.keys(errors).length)return pack(errors,"");
 const formal=/sí|amenaza|acoso|discrimin|represalia|seguridad|abuso/i.test(clean(values.safety));
 const warnings=[formal&&"Puede no ser seguro conversar directamente. Considera representación, apoyo especializado o un canal formal adecuado.",!clean(values.unknowns)&&"Prepara al menos una explicación alternativa que debas explorar.",!clean(values.boundary)&&"Define qué límite o condición debe protegerse."].filter(Boolean);
 return pack({},`PLAN HABLAR\nHechos: ${clean(values.facts)}\nAfectación: ${clean(values.impact)}\nBase compartida: ${clean(values.shared)}\nLectura alternativa: ${clean(values.unknowns)||"Por explorar"}\nAcuerdo solicitado: ${clean(values.request)}\nRevisión: ${clean(values.followUp)}\n\nSEPARACIÓN\nInterpretación: ${clean(values.interpretation)}\nNecesidad o límite: ${clean(values.boundary)||"Por definir"}\n\nAPERTURA\n“Quiero conversar sobre ${clean(values.situation)} para proteger ${clean(values.shared)}. Observé ${clean(values.facts)} y el impacto fue ${clean(values.impact)}. Quiero entender tu perspectiva y proponer ${clean(values.request)}.”\n\nPREGUNTAS\n¿Qué contexto me falta?\n¿Qué parte ves de otra manera?\n¿Qué acuerdo podemos observar y revisar?\n\nSi aparece amenaza o represalia, termina la interacción y busca apoyo adecuado. ${safety}`,warnings);
}

export function buildTeamPractices(values){
 const errors=validate(values,["size","context","friction","meetings","communication","workload","participation","decision","priority"]);if(Object.keys(errors).length)return pack(errors,"");
 const warnings=[/acoso|discrimin|represalia|amenaza|seguridad/i.test(clean(values.friction))&&"Esta fricción puede requerir intervención formal; un experimento de equipo no sustituye un proceso de seguridad.",!clean(values.norms)&&"Registra la norma actual, incluso si es implícita."].filter(Boolean);
 return pack({},`PLAN EQUIPO\nContexto: ${clean(values.size)} personas; ${clean(values.context)}\nFricción: ${clean(values.friction)}\nExpectativas: ${clean(values.norms)||"Por aclarar"}\nQuestions welcomed: reservar una pregunta independiente antes de cerrar.\nUso sostenible del tiempo: revisar ${clean(values.meetings)} y ${clean(values.workload)}.\nInclusión práctica: ajustar ${clean(values.participation)}.\nEvidencia y aprendizaje: observar qué cambia durante el experimento.\nOwnership: hacer visible quién decide en ${clean(values.decision)}.\n\nPRIORIDAD\n${clean(values.priority)}\n\nNORMA SUGERIDA\n“Las decisiones relevantes incluirán propósito, responsable, evidencia y una vía para plantear riesgos antes del cierre.”\n\nEXPERIMENTO\nDurante dos ciclos de trabajo, probar una reflexión individual breve antes de decisiones y un cierre con acción, responsable y revisión.\nResponsable: por asignar\nFecha de revisión: por acordar\n\n${safety}`,warnings);
}

export function buildTeamSafetyReflection(values){
 const errors=validate(values,["context","questions","mistakes","participation","decisions","help","disagreement","accountability","power","example"]);if(Object.keys(errors).length)return pack(errors,"");
 const formal=/represalia|amenaza|acoso|discrimin|humill/i.test(Object.values(values).map(clean).join(" "));
 const warnings=[formal&&"La situación puede requerir un canal formal o apoyo institucional. Una reflexión de equipo no sustituye una investigación o medida de seguridad."].filter(Boolean);
 return pack({},`REFLEXIÓN VOCES\nContexto: ${clean(values.context)}\nValorar preguntas: ${clean(values.questions)}\nOfrecer contexto: ${clean(values.decisions)}\nConvertir errores en aprendizaje: ${clean(values.mistakes)}\nEscuchar desacuerdo: ${clean(values.disagreement)}\nSostener responsabilidad: ${clean(values.accountability)}\n\nPATRONES A OBSERVAR\nParticipación: ${clean(values.participation)}\nSolicitud de ayuda: ${clean(values.help)}\nDiferencias de poder: ${clean(values.power)}\nEjemplo reciente: ${clean(values.example)}\n\nEXPERIMENTOS POSIBLES\n• Recoger una perspectiva independiente antes de discutir.\n• Explicar cómo una pregunta o desacuerdo influyó en la decisión.\n• Revisar un error separando proceso, capacidad y responsabilidad.\n\nEsta reflexión no genera una puntuación ni declara que el equipo sea seguro o inseguro. La experiencia puede variar entre personas y situaciones.`,warnings);
}

export function buildWellbeingActionPlan(values){
 const errors=validate(values,["context","personal","relationship","team","structural","action","boundary","conversation","experiment","support","review"]);if(Object.keys(errors).length)return pack(errors,"");
 const warnings=[/acoso|discrimin|represalia|amenaza|seguridad|salud/i.test(clean(values.structural))&&"La situación estructural descrita puede requerir apoyo profesional, institucional o formal además del plan."] .filter(Boolean);
 return pack({},`PLAN CUIDA · CUATRO SEMANAS\nContexto: ${clean(values.context)}\n\nSEMANA 1 · OBSERVAR\nMapear carga, recuperación y niveles. Prioridad personal: ${clean(values.personal)}. Problema estructural: ${clean(values.structural)}.\n\nSEMANA 2 · AJUSTAR\nAcción pequeña: ${clean(values.action)}.\nLímite: ${clean(values.boundary)}.\n\nSEMANA 3 · DIALOGAR\nPrioridad relacional: ${clean(values.relationship)}.\nConversación: ${clean(values.conversation)}.\nApoyo: ${clean(values.support)}.\n\nSEMANA 4 · DISEÑAR\nPrioridad de equipo: ${clean(values.team)}.\nExperimento: ${clean(values.experiment)}.\nRevisión: ${clean(values.review)}.\n\nNIVELES\nPersonal: acción pequeña y reinicio.\nRelacional: petición y acuerdo.\nEquipo: norma y responsable.\nOrganización: documentar, solicitar o escalar la condición.\n\n${safety}\nSi una situación afecta seguridad o salud, busca apoyo profesional o institucional adecuado.`,warnings);
}
