const updatedAt="2026-07-15";
const base="/aprende/relaciones-y-bienestar";
export const wellbeingSafetyNotice="Este recurso ofrece herramientas generales de reflexión y organización. No reemplaza apoyo médico, psicológico, legal, laboral ni de emergencia. Si una situación afecta tu seguridad o salud, busca apoyo profesional o institucional adecuado.";
export const harmfulConditionsNotice="Cuidar el bienestar no significa aceptar condiciones dañinas. Puede implicar pedir ayuda, renegociar expectativas, documentar un problema, utilizar canales formales o salir de una situación que no es sostenible.";

const contextCases=["Analista con expectativas ambiguas","Jefatura sin tiempo de concentración","Estudiante que trabaja","Profesional remoto con poco contacto","Equipo estable sin claridad de contribución"].map((title)=>({title,text:`Caso ficticio: ${title}. Separa factores personales, relacionales y organizacionales; anota hechos, supuestos, una acción segura y el apoyo que podría hacer falta.`}));
const energyCases=["Actividad física tras un día exigente","Trabajo desde casa","Almuerzo con colegas","Notificaciones desactivadas","Curso en línea","Tiempo a solas","Voluntariado","Extender una fecha"].map((title)=>({title,text:`${title} puede restaurar, sostener, consumir o convertirse en evitación según duración, control, salud, obligaciones y lo que ocurre después. Explica el contexto; no elijas una respuesta universal.`}));
const practiceCases=["Persona cuidadora con horario rígido","Desarrollador remoto con muchas reuniones","Docente con trabajo emocionalmente exigente","Consultora que viaja","Estudiante con turnos nocturnos","Jefatura en varios husos horarios"].map((title)=>({title,text:`Caso ficticio: ${title}. Diseña una práctica PASO compatible con sus restricciones, apoyo disponible y un plan de reinicio.`}));
const boundaryCases=["Mensajes nocturnos","Solicitudes urgentes repetidas","Preguntas personales","Instrucciones de dos jefaturas","Carga desigual","Interrupción de permiso","Rol ambiguo","Expectativa de apoyo emocional","Exceso de reuniones","Práctica insegura"].map((title)=>({title,text:`${title}: redacta observación, impacto, límite, petición, alternativa, revisión y condición de escalamiento. Considera poder y seguridad.`}));
const relationshipCases=["Interrupciones repetidas","Crédito poco claro","Instrucciones inconsistentes","Distancia tras feedback","Desconfianza entre áreas","Exclusión de una persona remota","Apoyo emocional que excede capacidad","Persona nueva que no sabe pedir ayuda"].map((title)=>({title,text:`Caso ficticio: ${title}. Propón más de una respuesta CERCA, distingue hecho e interpretación y conserva límites de privacidad.`}));
const difficultCases=["Fecha incumplida","Interrupción recurrente","Reconocimiento desigual","Feedback ambiguo","Sobrecarga","Crítica pública","Exclusión de decisiones","Error de calidad","Límite vulnerado","Prioridades en conflicto"].map((title)=>({title,text:`${title}: prepara HABLAR con hechos, impacto, base compartida, lectura alternativa, acuerdo, revisión y una vía segura si conversar directamente no corresponde.`}));
const teamCases=["La jerarquía decide primero","Se ocultan problemas de calidad","Personas remotas quedan fuera","Lo urgente llega cada viernes","Solo se reconoce a quien presenta","La amabilidad evita feedback","Pedir ayuda se interpreta como incapacidad","La retrospectiva no produce cambios"].map((title)=>({title,text:`Caso ficticio: ${title}. Identifica señales observables, explicaciones posibles, preguntas, acción inmediata, norma, cambio estructural y evidencia de revisión.`}));

export const wellbeingScenarios=[
 ["capacidad","Entregables acumulados","Carga y capacidad","intermedio"],["disponibilidad","Mensajes fuera de horario","Límites de disponibilidad","introductorio"],["recuperacion","Semana sin transiciones","Recuperación y agenda","introductorio"],["apoyo","Solicitud de apoyo temporal","Pedir apoyo","intermedio"],["reparacion","Coordinación dañada","Reparación relacional","intermedio"],["feedback","Feedback bajo tensión","Conversación difícil","avanzado"],["participacion","Dos voces dominan","Participación desigual","intermedio"],["errores","Falla descubierta tarde","Errores ocultos","avanzado"],["reconocimiento","Trabajo invisible","Reconocimiento","introductorio"],["rol","Decisión sin responsable","Ambigüedad de rol","intermedio"],["remoto","Acuerdos informales","Exclusión remota","intermedio"],["conflicto","Criterios incompatibles","Conflicto y desacuerdo","avanzado"],["vulnerabilidad","Jefatura reconoce incertidumbre","Vulnerabilidad responsable","intermedio"],["normas","Urgencia permanente","Normas de equipo","avanzado"],["escalamiento","Riesgo reiterado","Escalamiento organizacional","avanzado"],
].map(([slug,title,category,difficulty],index)=>({slug,title,category,difficulty,fictional:true,context:`Escenario ficticio ${index+1} en un entorno profesional o educativo.`,observableFacts:["Existe una conducta observable y repetida.","La responsabilidad o expectativa no está completamente clara."],unknowns:["Perspectiva de otras personas","Restricción estructural"],stakeholders:["Persona afectada","Responsable del trabajo","Quien puede cambiar la condición"],powerConsiderations:[index>11?"Existe diferencia de autoridad o riesgo de consecuencia.":"La autoridad para decidir debe confirmarse."],learnerTasks:["Separar niveles","Elegir una acción segura","Preparar conversación o escalamiento"],possibleResponses:["Acción personal limitada y revisión","Petición o acuerdo relacional","Intervención de equipo u organización"],modelReasoning:["La respuesta depende del poder, la seguridad y quién controla la condición.","Una práctica personal no sustituye un cambio estructural."],safetyConsiderations:["No exigir información de salud.","Usar apoyo formal si existe riesgo o represalia."],skills:["Contexto","Límites","Diálogo","Responsabilidad"]}));

export const wellbeingResources=[
 {id:"context",title:"Mapa de contexto",description:"Separa factores personales, relacionales, de equipo, organizacionales y formales.",contentType:"worksheet",status:"published",fields:["Personal","Relacional","Equipo","Organización","Apoyo formal"],reminder:wellbeingSafetyNotice},
 {id:"energy",title:"Energía y recuperación",description:"Observa efectos temporales sin diagnosticar.",contentType:"worksheet",status:"published",fields:["Actividad","Efecto típico","Momento","Recuperación necesaria","Ajuste posible"],reminder:"Describe el contexto; no conviertas una categoría en identidad."},
 {id:"paso",title:"Tarjeta PASO",description:"Diseña una práctica pequeña y reiniciable.",contentType:"worksheet",status:"published",fields:["Pequeña","Asociada","Sostenible","Observable","Plan de reinicio"],reminder:"La práctica debe ajustarse si cambia el contexto."},
 {id:"boundary",title:"Hoja de límites",description:"Prepara condición, margen, alternativa y escalamiento.",contentType:"worksheet",status:"published",fields:["Situación","Impacto","Necesidad","Margen","Alternativa","Revisión","Escalamiento"],reminder:"Considera seguridad y poder antes de conversar."},
 {id:"help",title:"Solicitud de apoyo",description:"Formula una petición específica y realista.",contentType:"template",status:"published",template:"SITUACIÓN\n\nIMPACTO OBSERVABLE\n\nQUÉ YA INTENTÉ\n\nAPOYO SOLICITADO\n\nMOMENTO O FECHA\n\nALTERNATIVA SI NO ES POSIBLE",reminder:"No necesitas revelar información privada para pedir un ajuste."},
 {id:"cerca",title:"Guía CERCA",description:"Fortalece claridad, escucha, reciprocidad, confianza gradual y reparación.",contentType:"checklist",status:"published",groups:[{title:"Relación profesional",items:["Claridad de expectativas","Escucha y verificación","Reciprocidad realista","Confianza gradual","Ajuste o reparación"]}],reminder:"Una relación profesional saludable no exige amistad ni intimidad."},
 {id:"facts",title:"Hechos e interpretaciones",description:"Separa lo observado de significado, emoción, necesidad y petición.",contentType:"worksheet",status:"published",fields:["Hecho","Interpretación","Emoción","Necesidad","Petición"],reminder:"No presentes una interpretación como hecho compartido."},
 {id:"hablar",title:"Plan HABLAR",description:"Prepara una conversación y su revisión.",contentType:"worksheet",status:"published",fields:["Hechos","Afectación","Base compartida","Lectura alternativa","Acuerdo solicitado","Revisión"],reminder:"Una conversación directa no siempre es la vía segura."},
 {id:"myths",title:"Mitos sobre seguridad psicológica",description:"Contrasta comodidad, acuerdo, confidencialidad y responsabilidad.",contentType:"checklist",status:"published",groups:[{title:"Revisar ideas",items:["No elimina conflicto","No exige aceptar toda idea","No elimina consecuencias legítimas","Puede variar por persona","La confidencialidad sigue importando"]}],reminder:"Una señal aislada no diagnostica al equipo."},
 {id:"voces",title:"Tarjeta VOCES",description:"Combina preguntas, contexto, aprendizaje, desacuerdo y responsabilidad.",contentType:"worksheet",status:"published",fields:["Valorar preguntas","Ofrecer contexto","Convertir errores en aprendizaje","Escuchar desacuerdo","Sostener responsabilidad"],reminder:"No todos los errores son equivalentes ni deben celebrarse."},
 {id:"equipo",title:"Normas EQUIPO",description:"Diseña condiciones observables de trabajo.",contentType:"worksheet",status:"published",fields:["Expectativas","Preguntas","Uso sostenible del tiempo","Inclusión","Evidencia","Ownership"],reminder:"No pidas datos privados de bienestar."},
 {id:"retro",title:"Guía de retrospectiva",description:"Convierte reflexión en un experimento revisable.",contentType:"worksheet",status:"published",fields:["Keep","Change","Clarify","Support","Experiment","Responsable","Fecha","Evidencia"],reminder:"Evita una retrospectiva centrada en culpar personas."},
 {id:"recognition",title:"Reconocimiento específico",description:"Hace visible una contribución y su impacto.",contentType:"template",status:"published",template:"CONTRIBUCIÓN OBSERVADA\n\nIMPACTO\n\nPOR QUÉ IMPORTA\n\nQUÉ CONVIENE MANTENER",reminder:"Reconoce preguntas, alertas, apoyo y seguimiento, no solo visibilidad."},
 {id:"concern-log",title:"Registro de decisiones e inquietudes",description:"Documenta evidencia, información y seguimiento.",contentType:"worksheet",status:"published",fields:["Inquietud","Fecha","Evidencia","Persona informada","Decisión","Responsable","Seguimiento"],reminder:"Protege confidencialidad y usa canales apropiados."},
 {id:"four-week",title:"Plan de cuatro semanas",description:"Integra acciones personales, relacionales, de equipo y organizacionales.",contentType:"worksheet",status:"published",fields:["Semana 1: observar","Semana 2: ajustar","Semana 3: dialogar","Semana 4: diseñar","Apoyo o escalamiento"],reminder:wellbeingSafetyNotice},
];

const lessons=[
 {slug:"comprender-bienestar",title:"Comprender el bienestar en contexto",description:"Distingue prácticas personales, acuerdos relacionales y condiciones que requieren acción organizacional.",outcomes:["Mapear niveles de acción","Observar patrones sin diagnosticar","Elegir un siguiente paso seguro"],sections:[
  {title:"El bienestar no depende solo de ti",paragraphs:["La capacidad puede verse afectada por carga, claridad de rol, autonomía, salud, responsabilidades de cuidado, relaciones, seguridad laboral, discriminación, liderazgo, entorno físico, sobrecarga digital y acceso a apoyo. Reducirlo a hábitos individuales oculta quién puede cambiar cada condición."]},
  {title:"Tres niveles de acción",framework:[{title:"Personal",text:"Pausa, notificaciones, recuperación o solicitud de claridad que una persona puede iniciar."},{title:"Relacional",text:"Expectativas, disponibilidad, feedback o reparación que deben acordarse."},{title:"Organizacional",text:"Dotación, acoso, discriminación, riesgo, decisiones o plazos que requieren intervención institucional."}],callout:{title:"Límite importante",text:"Una rutina personal no compensa indefinidamente un problema estructural."}},
  {title:"Una condición cambiante",bullets:["La capacidad varía entre días y etapas","Una práctica afecta distinto a cada persona","Energía alta no prueba sostenibilidad","Energía baja no diagnostica un trastorno","Los patrones importan más que un momento aislado"]},
  {title:"Diez dimensiones descriptivas",questionGroups:[{title:"Persona",items:["Capacidad física","Foco mental","Carga emocional","Sentido","Límites","Recuperación"]},{title:"Contexto",items:["Apoyo social","Carga de trabajo","Claridad de rol","Capacidad de influencia"]}],paragraphs:["Describe cada dimensión como requiere atención, inestable, suficiente por ahora o fuente de apoyo. No agregues un puntaje."]},
  {title:"Cinco contextos ficticios",examples:contextCases},
  {title:"Mapea antes de actuar",links:[{label:"Abrir mapa de contexto",href:"/herramientas/mapa-bienestar-contexto"}],callout:{title:"Seguridad y apoyo",text:wellbeingSafetyNotice}}
 ],relatedResources:["context"],relatedTools:["mapa-bienestar-contexto"]},
 {slug:"energia-y-recuperacion",title:"Reconocer carga, energía y recuperación",description:"Observa qué restaura, sostiene, consume o desborda en un contexto concreto.",outcomes:["Clasificar efectos temporales","Distinguir recuperación y evitación","Diseñar ventanas de recuperación"],sections:[
  {title:"La energía es contextual",paragraphs:["El efecto de una actividad depende de duración, momento, control, dificultad, sentido, conflicto, entorno, recuperación previa, salud y preferencia. Evita convertir introversión o extroversión en una explicación rígida."]},
  {title:"Cuatro descripciones temporales",framework:[{title:"Restaura",text:"Tiende a recuperar capacidad."},{title:"Sostiene",text:"Exige, pero resulta manejable."},{title:"Consume",text:"Suele requerir recuperación posterior."},{title:"Desborda",text:"Supera repetidamente la capacidad o crea una preocupación de seguridad."}]},
  {title:"Áreas para observar",bullets:["Descanso y comodidad física","Foco, reuniones e interrupciones","Interacción y tiempo a solas","Traslado, cuidados e incertidumbre","Actividad significativa e intereses personales","Alimentación, hidratación o movimiento sin prescripciones"]},
  {title:"Recuperarse no es evitar",checklist:["La actividad me permite volver al problema","No retrasa una decisión necesaria","No crea daño adicional","Distingo control, apoyo y conversación","No intento recuperarme eternamente de una condición que debe cambiar"]},
  {title:"Cuatro escalas",framework:[{title:"Micro",text:"Pausa, cambio de foco o cierre de una tarea."},{title:"Diaria",text:"Comida protegida, transición o menor intrusión digital."},{title:"Semanal",text:"Descanso más largo y revisión de compromisos."},{title:"Estructural",text:"Carga, rol, horario, dotación, permiso o apoyo formal."}]},
  {title:"Ocho ejercicios contextuales",examples:energyCases,links:[{label:"Crear mapa de energía",href:"/herramientas/mapa-energia-recuperacion"}]}
 ],relatedResources:["energy"],relatedTools:["mapa-energia-recuperacion"]},
 {slug:"practicas-sostenibles",title:"Construir prácticas sostenibles",description:"Elige un cambio pequeño que sobreviva a días imperfectos y se rediseñe cuando haga falta.",outcomes:["Aplicar PASO","Preparar interrupciones","Distinguir práctica personal y norma de equipo"],sections:[
  {title:"Empieza con un cambio útil",paragraphs:["Los planes ambiciosos suelen ignorar carga, depender de motivación constante o acumular cambios. Elige un contexto, conducta, disparador, frecuencia realista y forma de reiniciar."]},
  {title:"PASO",framework:[{title:"Pequeña",text:"Lo bastante acotada para comenzar."},{title:"Asociada",text:"Unida a un momento existente."},{title:"Sostenible",text:"Compatible con carga y capacidad reales."},{title:"Observable",text:"Sabes si ocurrió sin puntuar tu salud."}],callout:{title:"Modelo práctico",text:"PASO orienta diseño; no garantiza un hábito ni un resultado de salud."}},
  {title:"Áreas posibles",questionGroups:[{title:"Trabajo",items:["Transiciones y cierre","Bloque de foco","Comodidad física","Revisión semanal"]},{title:"Relación y sentido",items:["Conversación significativa","Pedir apoyo","Reconocer una contribución","Detener trabajo sin valor"]}]},
  {title:"Interrumpir y volver",bullets:["Fallar una rutina es esperable","Reiniciar importa más que una racha","El contexto puede exigir rediseño","Una práctica puede dejar de servir","El castigo personal no mejora el plan"]},
  {title:"Prácticas de equipo sin exposición",bullets:["Expectativas de respuesta","Ventanas de foco y descanso","Revisión de carga","Rotación de tareas exigentes","Vías de escalamiento","Respeto por ausencias"],paragraphs:["No exijas revelar salud, sueño, familia o metas personales."]},
  {title:"Seis planes distintos",examples:practiceCases,links:[{label:"Diseñar una práctica PASO",href:"/herramientas/plan-practica-sostenible"},{label:"Revisar hábitos de aprendizaje",href:"/aprende/adaptabilidad-resiliencia/habitos-de-aprendizaje"}]}
 ],relatedResources:["paso"],relatedTools:["plan-practica-sostenible"]},
 {slug:"limites-y-apoyo",title:"Establecer límites y pedir apoyo",description:"Comunica capacidad, necesidad, margen y escalamiento sin intentar controlar a otras personas.",outcomes:["Aplicar LÍMITE","Pedir apoyo específico","Reconocer cuándo no conversar directamente"],sections:[
  {title:"Qué protege un límite",paragraphs:["Un límite profesional es una condición comunicada para proteger capacidad, responsabilidad, seguridad o disponibilidad. Puede referirse a tiempo, carga, canal, alcance, confidencialidad, espacio, trabajo emocional, rol, seguridad o información personal."]},
  {title:"Un límite no controla unilateralmente",paragraphs:["Aclara qué puedes hacer, qué no, qué necesita negociación y qué ocurrirá si la condición no se cumple. No intenta controlar sentimientos o toda conducta ajena."]},
  {title:"LÍMITE",framework:[{title:"Lugar o situación",text:"Dónde ocurre."},{title:"Impacto",text:"Qué efecto observable tiene."},{title:"Necesidad",text:"Qué condición hace falta."},{title:"Margen",text:"Qué flexibilidad existe."},{title:"Intercambio",text:"Qué alternativa ofreces."},{title:"Término o revisión",text:"Cuándo se revisa."},{title:"Escalamiento",text:"Qué ocurre si sigue sin resolverse."}]},
  {title:"Ejemplos claros",examples:[{title:"Carga",text:"Con la capacidad actual puedo terminar A o B, pero no ambos con el estándar esperado. Necesito priorización."},{title:"Disponibilidad",text:"Fuera del horario acordado responderé al siguiente día hábil; las urgencias usarán el canal definido."},{title:"Divulgación",text:"Prefiero no compartir ese aspecto personal. Sí puedo explicar qué ajuste laboral necesito."}]},
  {title:"Pedir apoyo",bullets:["Describe situación e impacto","Explica qué intentaste","Solicita apoyo específico","Define momento o fecha","Ofrece una alternativa si no es posible"],callout:{title:"Cuando la conversación directa no corresponde",text:"Acoso, discriminación, amenaza, represalia, abuso de poder, riesgo de seguridad o una obligación formal pueden requerir representación o canales institucionales."}},
  {title:"Diez prácticas de límites",examples:boundaryCases,links:[{label:"Preparar un límite",href:"/herramientas/preparar-limite-profesional"}]}
 ],relatedResources:["boundary","help"],relatedTools:["preparar-limite-profesional"]},
 {slug:"relaciones-profesionales",title:"Fortalecer relaciones profesionales",description:"Desarrolla claridad, reciprocidad y reparación sin exigir amistad o divulgación personal.",outcomes:["Aplicar CERCA","Usar empatía con límites","Preparar una reparación"],sections:[
  {title:"Una relación fuerte admite desacuerdo",paragraphs:["Puede incluir confianza, confiabilidad, curiosidad, respeto, claridad, reparación, límites, apoyo y reconocimiento. No exige amistad, intimidad, disponibilidad permanente, acuerdo constante ni cuidado emocional sin límites."]},
  {title:"CERCA",framework:[{title:"Claridad",text:"Roles, expectativas y límites."},{title:"Escucha",text:"Atención y verificación."},{title:"Reciprocidad",text:"El apoyo no fluye siempre en una dirección."},{title:"Confianza gradual",text:"Surge de conducta consistente, no de divulgación forzada."},{title:"Ajuste y reparación",text:"Los problemas se nombran y los acuerdos cambian."}]},
  {title:"Atención y accesibilidad",bullets:["Reduce distracciones cuando importa","Pregunta si es buen momento","Escucha antes de solucionar","Comprueba entendimiento","Adapta a cultura y accesibilidad","No exige contacto visual"]},
  {title:"Vulnerabilidad responsable",paragraphs:["Puede ser admitir un error, incertidumbre o necesidad de ayuda. No obliga a revelar trauma, salud o familia; debe considerar poder, privacidad de terceros y cualquier deber de reporte."]},
  {title:"Empatía, apoyo y reparación",ordered:["Describe una situación observable.","Explica impacto.","Invita otra perspectiva.","Reconoce tu contribución si corresponde.","Aclara una necesidad compartida.","Acuerda una conducta.","Revisa más adelante."],paragraphs:["Pregunta qué ayuda sería útil y no prometas una confidencialidad que quizá no puedas sostener."]},
  {title:"Ocho relaciones ficticias",examples:relationshipCases,links:[{label:"Preparar una conversación CERCA",href:"/herramientas/preparar-conversacion-relacion"},{label:"Explorar relaciones de networking",href:"/aprende/networking"}]}
 ],relatedResources:["cerca","facts"],relatedTools:["preparar-conversacion-relacion"]},
 {slug:"conversaciones-dificiles",title:"Abordar conversaciones difíciles",description:"Prepara hechos, impacto, petición y seguridad antes de elegir si conversar directamente.",outcomes:["Aplicar HABLAR","Separar cinco elementos","Responder sin improvisar certeza"],sections:[
  {title:"No todo conflicto es una oportunidad",paragraphs:["Una conversación puede mejorar claridad, pero peligro, represalia, acoso, abuso, investigación, procesos formales o falta de autoridad pueden volverla inadecuada. Buscar apoyo también es una acción válida."]},
  {title:"HABLAR",framework:[{title:"Hechos",text:"Qué observaste."},{title:"Afectación",text:"Qué impacto tuvo."},{title:"Base compartida",text:"Qué responsabilidad o resultado comparten."},{title:"Lectura alternativa",text:"Qué podrías no saber."},{title:"Acuerdo solicitado",text:"Qué cambio necesitas."},{title:"Revisión",text:"Cómo y cuándo comprobarlo."}]},
  {title:"Cinco elementos separados",examples:[{title:"Hecho",text:"Tres entregables llegaron después de la fecha acordada."},{title:"Interpretación",text:"El proyecto no es una prioridad."},{title:"Emoción",text:"Estoy frustrado y preocupado."},{title:"Necesidad",text:"Necesito previsibilidad."},{title:"Petición",text:"Acordemos fechas realistas y alertas tempranas."}]},
  {title:"Preparar y conversar",checklist:["Propósito claro","Canal seguro","Observación específica","Explicaciones alternativas","Petición y privacidad","Poder y represalia considerados","Apoyo disponible","Progreso observable"]},
  {title:"Respuestas posibles",bullets:["Negación: vuelve a hechos","Defensa: separa problema y persona","Contraacusación: decide si es otro tema","Emoción: pausa sin forzar","Silencio: permite tiempo","Acuerdo sin acción: define responsable y fecha","Amenaza: termina y busca apoyo formal"]},
  {title:"Diez planes HABLAR",examples:difficultCases,links:[{label:"Preparar una conversación difícil",href:"/herramientas/preparar-conversacion-dificil"},{label:"Practicar escucha activa",href:"/aprende/comunicacion-profesional/escucha-activa"}]}
 ],relatedResources:["facts","hablar"],relatedTools:["preparar-conversacion-dificil"]},
 {slug:"seguridad-psicologica",title:"Comprender la seguridad psicológica",description:"Distingue apertura interpersonal, confidencialidad, estándares y responsabilidad.",outcomes:["Reconocer riesgos interpersonales","Aplicar VOCES","Revisar errores con responsabilidad"],sections:[
  {title:"Una condición de equipo",paragraphs:["Se refiere a la percepción de que es posible preguntar, admitir un error, disentir, pedir ayuda, alertar o proponer una idea incompleta sin humillación o represalia interpersonal innecesaria. La experiencia puede variar entre personas y momentos."]},
  {title:"Lo que no significa",bullets:["Comodidad permanente o acuerdo","Ausencia de conflicto o jerarquía","Aceptar todas las ideas","Rendimiento sin consecuencias","Compartir todo sin confidencialidad","Amistad o liderazgo competente por sí solos"]},
  {title:"Apertura y responsabilidad",comparison:{leftTitle:"Menor apertura",leftItems:["Con baja responsabilidad: desconexión","Con alta responsabilidad: ocultamiento y obediencia"],rightTitle:"Mayor apertura",rightItems:["Con baja responsabilidad: conversación sin ejecución","Con alta responsabilidad: aprendizaje y cumplimiento"]}},
  {title:"Señales que requieren investigar",bullets:["Preguntas o malas noticias tardías","Acuerdo aparente y resistencia posterior","Jerarquía habla primero","Errores o ayuda se ocultan","Decisiones no se explican","El desacuerdo se castiga o ridiculiza"],paragraphs:["Una señal aislada no prueba una condición general."]},
  {title:"VOCES",framework:[{title:"Valorar preguntas",text:"Trátalas como información."},{title:"Ofrecer contexto",text:"Explica objetivos, límites y decisiones."},{title:"Convertir errores en aprendizaje",text:"Revisa proceso y responsabilidad sin humillación."},{title:"Escuchar desacuerdo",text:"Examina perspectivas distintas."},{title:"Sostener responsabilidad",text:"Mantén estándares y seguimiento."}]},
  {title:"Errores, disenso y reconocimiento",paragraphs:["Distingue experimento responsable, error prevenible, brecha de habilidad, falta de capacidad, rol confuso, negligencia, conducta deliberada y falla del sistema. No todos los errores se celebran."],bullets:["Pide una visión independiente","Haz hablar a la jerarquía después","Explica cómo influyó el disenso","Reconoce preguntas, alertas, ayuda y seguimiento"],links:[{label:"Reflexionar sobre VOCES",href:"/herramientas/reflexion-seguridad-equipo"},{label:"Revisar colaboración y sesgos",href:"/aprende/resolucion-de-problemas/colaboracion-y-sesgos"}]}
 ],relatedResources:["myths","voces","recognition"],relatedTools:["reflexion-seguridad-equipo"]},
 {slug:"practicas-de-equipo",title:"Crear condiciones de equipo más saludables",description:"Diseña expectativas, participación, tiempo, aprendizaje y responsabilidad observables.",outcomes:["Aplicar EQUIPO","Crear normas útiles","Diseñar una retrospectiva con seguimiento"],sections:[
  {title:"El bienestar del equipo se diseña",paragraphs:["Distribución de trabajo, plazos, roles, reuniones, expectativas de respuesta, decisiones, liderazgo, apoyo, inclusión, dotación, recuperación y seguridad influyen. Las actividades de bienestar no sustituyen estas condiciones."]},
  {title:"EQUIPO",framework:[{title:"Expectativas claras",text:"Roles, prioridades, respuesta y decisión."},{title:"Questions welcomed",text:"Preguntas y alertas tienen una vía."},{title:"Uso sostenible del tiempo",text:"Reuniones, foco, permisos y recuperación se respetan."},{title:"Inclusión práctica",text:"Participación considera poder y acceso."},{title:"Evidencia y aprendizaje",text:"Errores y decisiones se revisan."},{title:"Ownership",text:"Responsabilidad y seguimiento son visibles."}]},
  {title:"Normas observables",bullets:["Canal urgente definido","Sin respuesta inmediata implícita","Permisos y foco respetados","Agenda y decisor visibles","Carga revisada","Asignaciones extra consultadas","Decisiones resumidas","Riesgos de seguridad escalados"]},
  {title:"Check-ins sin divulgación privada",paragraphs:["Pregunta por capacidad de trabajo, riesgo, ayuda, conflicto de prioridades, trabajo que debe detenerse, decisión, dependencia o disponibilidad. Evita puntajes emocionales obligatorios."]},
  {title:"Retrospectiva y conducta",framework:[{title:"Keep",text:"Qué continuar."},{title:"Change",text:"Qué fricción reducir."},{title:"Clarify",text:"Qué expectativa aclarar."},{title:"Support",text:"Dónde se necesita ayuda."},{title:"Experiment",text:"Qué cambio probar con responsable, fecha y evidencia."}],paragraphs:["Líderes y miembros comparten responsabilidad: explicar, preguntar, intervenir ante irrespeto, elevar riesgos, respetar límites y cumplir compromisos; nadie debe actuar como terapeuta."]},
  {title:"Ocho equipos ficticios",examples:teamCases,links:[{label:"Diseñar prácticas EQUIPO",href:"/herramientas/disenar-practicas-equipo"}]}
 ],relatedResources:["equipo","retro","concern-log"],relatedTools:["disenar-practicas-equipo"]},
 {slug:"plan-de-accion",title:"Diseñar un plan personal y de equipo",description:"Elige el nivel correcto, prueba ajustes pequeños y escala lo que no puede resolverse localmente.",outcomes:["Crear un ciclo de cuatro semanas","Integrar límites y normas","Definir apoyo y escalamiento"],sections:[
  {title:"Elige el nivel correcto",bullets:["Práctica personal","Conversación relacional","Norma de equipo","Petición organizacional","Escalamiento formal","Apoyo externo calificado"],paragraphs:["Actuar en el nivel equivocado genera frustración y puede transferir responsabilidad estructural a una persona."]},
  {title:"Semana 1 · Observar",bullets:["Mapea carga y recuperación","Separa niveles","Elige prioridad","Identifica seguridad"]},
  {title:"Semana 2 · Ajustar",bullets:["Prueba una práctica pequeña","Protege un límite","Quita una fricción","Registra qué ocurrió"]},
  {title:"Semana 3 · Dialogar",bullets:["Prepara una conversación","Haz una petición","Formula una pregunta","Acuerda revisión"]},
  {title:"Semana 4 · Diseñar",bullets:["Propón una práctica de equipo","Define responsable y evidencia","Revisa el problema estructural","Continúa, cambia o escala"]},
  {title:"Caso integrado ficticio",caseStudy:{title:"Equipo Faro",paragraphs:["Caso ficticio creado con fines educativos. Un equipo de seis personas prepara un lanzamiento; cambian plazos, dos personas cubren varios proyectos, las reuniones ocupan el día, decisiones informales excluyen a una persona junior y nadie sabe quién responde por la entrega final.","Una respuesta posible protege el riesgo de calidad, aclara responsabilidad, limita mensajes fuera de horario, recupera tiempo de foco, revisa la alerta ignorada y escala dotación o plazos. Una alternativa válida puede priorizar representación o un canal formal si existe riesgo de represalia."]},links:[{label:"Crear plan CUIDA",href:"/herramientas/plan-relaciones-bienestar"},{label:"Explorar escenarios",href:"#biblioteca-bienestar"}]}
 ],relatedResources:["four-week","concern-log"],relatedTools:["plan-relaciones-bienestar"]},
];

export const wellbeingLessons=lessons.map((item,index)=>({...item,order:index+1,href:`${base}/${item.slug}`,status:"published",level:index<3?"Introductorio":index===8?"Avanzado":"Intermedio",readingTime:`${10+index} minutos`,updatedAt,contentType:"lesson"}));
export const wellbeingPath={title:"Relaciones y bienestar",description:"Aprende a cuidar tu capacidad, fortalecer relaciones profesionales y contribuir a equipos donde sea posible hablar, aprender y trabajar con responsabilidad.",audience:"Estudiantes, profesionales, líderes, docentes, emprendedores y equipos",format:"Ruta práctica no clínica",readingTime:"Aproximadamente 125 minutos",level:"Progresivo",updatedAt,status:"published",outcomes:["Comprender el contexto","Diseñar recuperación y prácticas sostenibles","Comunicar límites y reparar relaciones","Combinar apertura y responsabilidad","Crear un plan personal, relacional y de equipo"]};
export const getWellbeingLesson=(slug)=>wellbeingLessons.find((item)=>item.slug===slug);
export const getWellbeingResource=(id)=>wellbeingResources.find((item)=>item.id===id);
