name: Deploy Vite React app to GitHub Pages

on:
  push:
    branches: [ "main" ]   # 👈 se ejecuta cada vez que hagas push a la rama main
  workflow_dispatch:        # 👈 también puedes ejecutarlo manualmente desde GitHub

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18   # 👈 versión recomendada para Vite

      - name: Instalar dependencias
        run: npm install

      - name: Construir el proyecto
        run: npm run build

      - name: Copiar index.html como 404.html (para SPA con React Router)
        run: cp dist/index.html dist/404.html

      - name: Subir artefacto
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist       # 👈 carpeta generada por Vite al hacer build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Desplegar a GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
